# Microsoft Azure Build Pipeline
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema

# https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops
pr: none
trigger:
  batch: true
  branches:
    include:
    - master

jobs:
- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: ci-template.yml

- job: Ubuntu
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    display: ':99' # This will also set the environment variable 'DISPLAY=:99' required for apps to connect to the X-Server
  steps:
  # Running electron on Ubuntu requires an X-server:
  # https://github.com/Microsoft/azure-pipelines-image-generation/issues/239
  # It is also possible to use X-Server for just a single command:
  # https://manpages.ubuntu.com/manpages/trusty/man1/xvfb-run.1.html
  # This snippet was partially stolen from VSCode to support running electron on Ubuntu
  - script: |
      #sudo apt-get update
      #sudo apt-get install -y libxkbfile-dev pkg-config libsecret-1-dev libxss1 dbus xvfb libgtk-3-0 libgconf-2-4
      sudo /usr/bin/Xvfb $(display) -ac -screen 0 1920x1080x24 &> /tmp/Xvfb.out &
      disown -ar # remove all running jobs (e.g. xvfb) from the job table of this bash process
    displayName: 'Starting X Virtual Frame Buffer (Port 99)'
  - template: ci-template.yml

- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - template: ci-template.yml