name: ❗ Website not working
description: Report a broken website that stopped working
title: "[%WEBSITE-NAME%] is no longer working"
labels: ["Website Change"]
body:
  - type: checkboxes
    attributes:
      label: Disclaimer
      description: >
        By truthfully answering this questionnaire you are supporting the developers to save precious time.
        You also agree that this ticket may be closed without any further investigation in case it was answered hasty or untruthfully.
      options:
        - label: I searched and confirm that the same or a similar issue could not be found in the list of [existing tickets](https://github.com/manga-download/hakuneko/issues?q=)
          required: true
        - label: I read and confirm that the issue could not be addressed by following the topics listed in the [troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)
          required: true
        - label: I tested and confirm that the issue is also reproducible with the latest [Nightly Build](https://github.com/manga-download/hakuneko/releases/tag/nightly-20200705.1)
          required: true
        - label: I confirm that the placeholder `%WEBSITE-NAME%` in this ticket's title was correctly replaced with the name of the broken website
          required: true
  - type: dropdown
    attributes:
      label: What kind of issue are you encountering?
      options:
        - Please Select ...
        - Manga list isn't refreshing
        - Chapter list isn't refreshing
        - Downloads aren't working
        - Images are missing in the embeded viewer
        - Other
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: |
        A clear and concise description of the issue.
        Copy any relevant error message that appears in a popup or (advanced) within the console (press `F12`)
    validations:
      required: true
  - type: textarea
    attributes:
      label: How can this be reproduced?
      description: |
        Provide a simplified list of instructions which caused the issue and can be replayed by a developer.
        Make sure to include correct names and links to the referenced website, manga(s) and chapter(s).
      value: |
        1. Start HakuNeko
        2. Select the website [MangaDex](https://mangadex.org)
        3. Press the button to refresh the manga list
        4. Select manga [One Piece](https://mangadex.org/title/a1c7c817-4e59-43b7-9365-09675a149a6f/one-piece)
        5. Press the button to refresh the chapter list
        6. Click the download button on chapter [Ch. 1 - Romance Dawn](https://mangaplus.shueisha.co.jp/viewer/1000486)
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        **Screenshots**
        If complex to describe, add screenshots to help explain your problem.
