/**
@license @nocompile
Copyright (c) 2018 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
'use strict';var n,ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},q="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function da(){da=function(){};q.Symbol||(q.Symbol=ea)}var ea=function(){var a=0;return function(b){return"jscomp_symbol_"+(b||"")+a++}}();
function fa(){da();var a=q.Symbol.iterator;a||(a=q.Symbol.iterator=q.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&ba(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ha(this)}});fa=function(){}}function ha(a){var b=0;return ia(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function ia(a){fa();a={next:a};a[q.Symbol.iterator]=function(){return this};return a}function ja(a){fa();var b=a[Symbol.iterator];return b?b.call(a):ha(a)}
function ka(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c}
(function(){if(!function(){var a=document.createEvent("Event");a.initEvent("foo",!0,!0);a.preventDefault();return a.defaultPrevented}()){var a=Event.prototype.preventDefault;Event.prototype.preventDefault=function(){this.cancelable&&(a.call(this),Object.defineProperty(this,"defaultPrevented",{get:function(){return!0},configurable:!0}))}}var b=/Trident/.test(navigator.userAgent);if(!window.CustomEvent||b&&"function"!==typeof window.CustomEvent)window.CustomEvent=function(a,b){b=b||{};var c=document.createEvent("CustomEvent");
c.initCustomEvent(a,!!b.bubbles,!!b.cancelable,b.detail);return c},window.CustomEvent.prototype=window.Event.prototype;if(!window.Event||b&&"function"!==typeof window.Event){var c=window.Event;window.Event=function(a,b){b=b||{};var c=document.createEvent("Event");c.initEvent(a,!!b.bubbles,!!b.cancelable);return c};if(c)for(var d in c)window.Event[d]=c[d];window.Event.prototype=c.prototype}if(!window.MouseEvent||b&&"function"!==typeof window.MouseEvent){b=window.MouseEvent;window.MouseEvent=function(a,
b){b=b||{};var c=document.createEvent("MouseEvent");c.initMouseEvent(a,!!b.bubbles,!!b.cancelable,b.view||window,b.detail,b.screenX,b.screenY,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,b.button,b.relatedTarget);return c};if(b)for(d in b)window.MouseEvent[d]=b[d];window.MouseEvent.prototype=b.prototype}Array.from||(Array.from=function(a){return[].slice.call(a)});Object.assign||(Object.assign=function(a,b){for(var c=[].slice.call(arguments,1),d=0,e;d<c.length;d++)if(e=c[d])for(var f=
a,m=e,p=Object.getOwnPropertyNames(m),x=0;x<p.length;x++)e=p[x],f[e]=m[e];return a})})(window.WebComponents);(function(){function a(){}function b(a,b){if(!a.childNodes.length)return[];switch(a.nodeType){case Node.DOCUMENT_NODE:return va.call(a,b);case Node.DOCUMENT_FRAGMENT_NODE:return nb.call(a,b);default:return Y.call(a,b)}}var c="undefined"===typeof HTMLTemplateElement,d=!(document.createDocumentFragment().cloneNode()instanceof DocumentFragment),e=!1;/Trident/.test(navigator.userAgent)&&function(){function a(a,b){if(a instanceof DocumentFragment)for(var d;d=a.firstChild;)c.call(this,d,b);else c.call(this,
a,b);return a}e=!0;var b=Node.prototype.cloneNode;Node.prototype.cloneNode=function(a){a=b.call(this,a);this instanceof DocumentFragment&&(a.__proto__=DocumentFragment.prototype);return a};DocumentFragment.prototype.querySelectorAll=HTMLElement.prototype.querySelectorAll;DocumentFragment.prototype.querySelector=HTMLElement.prototype.querySelector;Object.defineProperties(DocumentFragment.prototype,{nodeType:{get:function(){return Node.DOCUMENT_FRAGMENT_NODE},configurable:!0},localName:{get:function(){},
configurable:!0},nodeName:{get:function(){return"#document-fragment"},configurable:!0}});var c=Node.prototype.insertBefore;Node.prototype.insertBefore=a;var d=Node.prototype.appendChild;Node.prototype.appendChild=function(b){b instanceof DocumentFragment?a.call(this,b,null):d.call(this,b);return b};var f=Node.prototype.removeChild,h=Node.prototype.replaceChild;Node.prototype.replaceChild=function(b,c){b instanceof DocumentFragment?(a.call(this,b,c),f.call(this,c)):h.call(this,b,c);return c};Document.prototype.createDocumentFragment=
function(){var a=this.createElement("df");a.__proto__=DocumentFragment.prototype;return a};var g=Document.prototype.importNode;Document.prototype.importNode=function(a,b){b=g.call(this,a,b||!1);a instanceof DocumentFragment&&(b.__proto__=DocumentFragment.prototype);return b}}();var f=Node.prototype.cloneNode,h=Document.prototype.createElement,g=Document.prototype.importNode,k=Node.prototype.removeChild,l=Node.prototype.appendChild,m=Node.prototype.replaceChild,p=DOMParser.prototype.parseFromString,
x=Object.getOwnPropertyDescriptor(window.HTMLElement.prototype,"innerHTML")||{get:function(){return this.innerHTML},set:function(a){this.innerHTML=a}},N=Object.getOwnPropertyDescriptor(window.Node.prototype,"childNodes")||{get:function(){return this.childNodes}},Y=Element.prototype.querySelectorAll,va=Document.prototype.querySelectorAll,nb=DocumentFragment.prototype.querySelectorAll,ob=function(){if(!c){var a=document.createElement("template"),b=document.createElement("template");b.content.appendChild(document.createElement("div"));
a.content.appendChild(b);a=a.cloneNode(!0);return 0===a.content.childNodes.length||0===a.content.firstChild.content.childNodes.length||d}}();if(c){var T=document.implementation.createHTMLDocument("template"),C=!0,Z=document.createElement("style");Z.textContent="template{display:none;}";var na=document.head;na.insertBefore(Z,na.firstElementChild);a.prototype=Object.create(HTMLElement.prototype);var wa=!document.createElement("div").hasOwnProperty("innerHTML");a.H=function(b){if(!b.content&&b.namespaceURI===
document.documentElement.namespaceURI){b.content=T.createDocumentFragment();for(var c;c=b.firstChild;)l.call(b.content,c);if(wa)b.__proto__=a.prototype;else if(b.cloneNode=function(b){return a.a(this,b)},C)try{Q(b),aa(b)}catch(ph){C=!1}a.C(b.content)}};var ca={option:["select"],thead:["table"],col:["colgroup","table"],tr:["tbody","table"],th:["tr","tbody","table"],td:["tr","tbody","table"]},Q=function(b){Object.defineProperty(b,"innerHTML",{get:function(){return pb(this)},set:function(b){var c=ca[(/<([a-z][^/\0>\x20\t\r\n\f]+)/i.exec(b)||
["",""])[1].toLowerCase()];if(c)for(var d=0;d<c.length;d++)b="<"+c[d]+">"+b+"</"+c[d]+">";T.body.innerHTML=b;for(a.C(T);this.content.firstChild;)k.call(this.content,this.content.firstChild);b=T.body;if(c)for(d=0;d<c.length;d++)b=b.lastChild;for(;b.firstChild;)l.call(this.content,b.firstChild)},configurable:!0})},aa=function(a){Object.defineProperty(a,"outerHTML",{get:function(){return"<template>"+this.innerHTML+"</template>"},set:function(a){if(this.parentNode){T.body.innerHTML=a;for(a=this.ownerDocument.createDocumentFragment();T.body.firstChild;)l.call(a,
T.body.firstChild);m.call(this.parentNode,a,this)}else throw Error("Failed to set the 'outerHTML' property on 'Element': This element has no parent node.");},configurable:!0})};Q(a.prototype);aa(a.prototype);a.C=function(c){c=b(c,"template");for(var d=0,e=c.length,f;d<e&&(f=c[d]);d++)a.H(f)};document.addEventListener("DOMContentLoaded",function(){a.C(document)});Document.prototype.createElement=function(){var b=h.apply(this,arguments);"template"===b.localName&&a.H(b);return b};DOMParser.prototype.parseFromString=
function(){var b=p.apply(this,arguments);a.C(b);return b};Object.defineProperty(HTMLElement.prototype,"innerHTML",{get:function(){return pb(this)},set:function(b){x.set.call(this,b);a.C(this)},configurable:!0,enumerable:!0});var cf=/[&\u00A0"]/g,Ec=/[&\u00A0<>]/g,Fc=function(a){switch(a){case "&":return"&amp;";case "<":return"&lt;";case ">":return"&gt;";case '"':return"&quot;";case "\u00a0":return"&nbsp;"}};Z=function(a){for(var b={},c=0;c<a.length;c++)b[a[c]]=!0;return b};var df=Z("area base br col command embed hr img input keygen link meta param source track wbr".split(" ")),
ef=Z("style script xmp iframe noembed noframes plaintext noscript".split(" ")),pb=function(a,b){"template"===a.localName&&(a=a.content);for(var c="",d=b?b(a):N.get.call(a),e=0,f=d.length,h;e<f&&(h=d[e]);e++){a:{var g=h;var k=a;var l=b;switch(g.nodeType){case Node.ELEMENT_NODE:for(var Q=g.localName,m="<"+Q,aa=g.attributes,p=0;k=aa[p];p++)m+=" "+k.name+'="'+k.value.replace(cf,Fc)+'"';m+=">";g=df[Q]?m:m+pb(g,l)+"</"+Q+">";break a;case Node.TEXT_NODE:g=g.data;g=k&&ef[k.localName]?g:g.replace(Ec,Fc);break a;
case Node.COMMENT_NODE:g="\x3c!--"+g.data+"--\x3e";break a;default:throw window.console.error(g),Error("not implemented");}}c+=g}return c}}if(c||ob){a.a=function(a,b){var c=f.call(a,!1);this.H&&this.H(c);b&&(l.call(c.content,f.call(a.content,!0)),qb(c.content,a.content));return c};var qb=function(c,d){if(d.querySelectorAll&&(d=b(d,"template"),0!==d.length)){c=b(c,"template");for(var e=0,f=c.length,h,g;e<f;e++)g=d[e],h=c[e],a&&a.H&&a.H(g),m.call(h.parentNode,ff.call(g,!0),h)}},ff=Node.prototype.cloneNode=
function(b){if(!e&&d&&this instanceof DocumentFragment)if(b)var c=gf.call(this.ownerDocument,this,!0);else return this.ownerDocument.createDocumentFragment();else this.nodeType===Node.ELEMENT_NODE&&"template"===this.localName&&this.namespaceURI==document.documentElement.namespaceURI?c=a.a(this,b):c=f.call(this,b);b&&qb(c,this);return c},gf=Document.prototype.importNode=function(c,d){d=d||!1;if("template"===c.localName)return a.a(c,d);var e=g.call(this,c,d);if(d){qb(e,c);c=b(e,'script:not([type]),script[type="application/javascript"],script[type="text/javascript"]');
for(var f,k=0;k<c.length;k++){f=c[k];d=h.call(document,"script");d.textContent=f.textContent;for(var l=f.attributes,Q=0,aa;Q<l.length;Q++)aa=l[Q],d.setAttribute(aa.name,aa.value);m.call(f.parentNode,d,f)}}return e}}c&&(window.HTMLTemplateElement=a)})();var la=setTimeout;function ma(){}function oa(a,b){return function(){a.apply(b,arguments)}}function r(a){if(!(this instanceof r))throw new TypeError("Promises must be constructed via new");if("function"!==typeof a)throw new TypeError("not a function");this.v=0;this.na=!1;this.j=void 0;this.K=[];pa(a,this)}
function qa(a,b){for(;3===a.v;)a=a.j;0===a.v?a.K.push(b):(a.na=!0,ra(function(){var c=1===a.v?b.Ra:b.Sa;if(null===c)(1===a.v?sa:ta)(b.ga,a.j);else{try{var d=c(a.j)}catch(e){ta(b.ga,e);return}sa(b.ga,d)}}))}function sa(a,b){try{if(b===a)throw new TypeError("A promise cannot be resolved with itself.");if(b&&("object"===typeof b||"function"===typeof b)){var c=b.then;if(b instanceof r){a.v=3;a.j=b;ua(a);return}if("function"===typeof c){pa(oa(c,b),a);return}}a.v=1;a.j=b;ua(a)}catch(d){ta(a,d)}}
function ta(a,b){a.v=2;a.j=b;ua(a)}function ua(a){2===a.v&&0===a.K.length&&ra(function(){a.na||"undefined"!==typeof console&&console&&console.warn("Possible Unhandled Promise Rejection:",a.j)});for(var b=0,c=a.K.length;b<c;b++)qa(a,a.K[b]);a.K=null}function xa(a,b,c){this.Ra="function"===typeof a?a:null;this.Sa="function"===typeof b?b:null;this.ga=c}function pa(a,b){var c=!1;try{a(function(a){c||(c=!0,sa(b,a))},function(a){c||(c=!0,ta(b,a))})}catch(d){c||(c=!0,ta(b,d))}}
r.prototype["catch"]=function(a){return this.then(null,a)};r.prototype.then=function(a,b){var c=new this.constructor(ma);qa(this,new xa(a,b,c));return c};r.prototype["finally"]=function(a){var b=this.constructor;return this.then(function(c){return b.resolve(a()).then(function(){return c})},function(c){return b.resolve(a()).then(function(){return b.reject(c)})})};
function ya(a){return new r(function(b,c){function d(a,h){try{if(h&&("object"===typeof h||"function"===typeof h)){var g=h.then;if("function"===typeof g){g.call(h,function(b){d(a,b)},c);return}}e[a]=h;0===--f&&b(e)}catch(m){c(m)}}if(!a||"undefined"===typeof a.length)throw new TypeError("Promise.all accepts an array");var e=Array.prototype.slice.call(a);if(0===e.length)return b([]);for(var f=e.length,h=0;h<e.length;h++)d(h,e[h])})}
function za(a){return a&&"object"===typeof a&&a.constructor===r?a:new r(function(b){b(a)})}function Aa(a){return new r(function(b,c){c(a)})}function Ba(a){return new r(function(b,c){for(var d=0,e=a.length;d<e;d++)a[d].then(b,c)})}var ra="function"===typeof setImmediate&&function(a){setImmediate(a)}||function(a){la(a,0)};/*

Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
if(!window.Promise){window.Promise=r;r.prototype.then=r.prototype.then;r.all=ya;r.race=Ba;r.resolve=za;r.reject=Aa;var Ca=document.createTextNode(""),Da=[];(new MutationObserver(function(){for(var a=Da.length,b=0;b<a;b++)Da[b]();Da.splice(0,a)})).observe(Ca,{characterData:!0});ra=function(a){Da.push(a);Ca.textContent=0<Ca.textContent.length?"":"a"}};(function(a){function b(a,b){if("function"===typeof window.CustomEvent)return new CustomEvent(a,b);var c=document.createEvent("CustomEvent");c.initCustomEvent(a,!!b.bubbles,!!b.cancelable,b.detail);return c}function c(a){if(N)return a.ownerDocument!==document?a.ownerDocument:null;var b=a.__importDoc;if(!b&&a.parentNode){b=a.parentNode;if("function"===typeof b.closest)b=b.closest("link[rel=import]");else for(;!g(b)&&(b=b.parentNode););a.__importDoc=b}return b}function d(a){var b=m(document,"link[rel=import]:not([import-dependency])"),
c=b.length;c?p(b,function(b){return h(b,function(){0===--c&&a()})}):a()}function e(a){function b(){"loading"!==document.readyState&&document.body&&(document.removeEventListener("readystatechange",b),a())}document.addEventListener("readystatechange",b);b()}function f(a){e(function(){return d(function(){return a&&a()})})}function h(a,b){if(a.__loaded)b&&b();else if("script"===a.localName&&!a.src||"style"===a.localName&&!a.firstChild)a.__loaded=!0,b&&b();else{var c=function(d){a.removeEventListener(d.type,
c);a.__loaded=!0;b&&b()};a.addEventListener("load",c);na&&"style"===a.localName||a.addEventListener("error",c)}}function g(a){return a.nodeType===Node.ELEMENT_NODE&&"link"===a.localName&&"import"===a.rel}function k(){var a=this;this.a={};this.b=0;this.c=new MutationObserver(function(b){return a.Na(b)});this.c.observe(document.head,{childList:!0,subtree:!0});this.loadImports(document)}function l(a){p(m(a,"template"),function(a){p(m(a.content,'script:not([type]),script[type="application/javascript"],script[type="text/javascript"],script[type="module"]'),
function(a){var b=document.createElement("script");p(a.attributes,function(a){return b.setAttribute(a.name,a.value)});b.textContent=a.textContent;a.parentNode.replaceChild(b,a)});l(a.content)})}function m(a,b){return a.childNodes.length?a.querySelectorAll(b):Y}function p(a,b,c){var d=a?a.length:0,e=c?-1:1;for(c=c?d-1:0;c<d&&0<=c;c+=e)b(a[c],c)}var x=document.createElement("link"),N="import"in x,Y=x.querySelectorAll("*"),va=null;!1==="currentScript"in document&&Object.defineProperty(document,"currentScript",
{get:function(){return va||("complete"!==document.readyState?document.scripts[document.scripts.length-1]:null)},configurable:!0});var nb=/(url\()([^)]*)(\))/g,ob=/(@import[\s]+(?!url\())([^;]*)(;)/g,T=/(<link[^>]*)(rel=['|"]?stylesheet['|"]?[^>]*>)/g,C={Ia:function(a,b){a.href&&a.setAttribute("href",C.Y(a.getAttribute("href"),b));a.src&&a.setAttribute("src",C.Y(a.getAttribute("src"),b));if("style"===a.localName){var c=C.ra(a.textContent,b,nb);a.textContent=C.ra(c,b,ob)}},ra:function(a,b,c){return a.replace(c,
function(a,c,d,e){a=d.replace(/["']/g,"");b&&(a=C.Y(a,b));return c+"'"+a+"'"+e})},Y:function(a,b){if(void 0===C.ca){C.ca=!1;try{var c=new URL("b","http://a");c.pathname="c%20d";C.ca="http://a/c%20d"===c.href}catch(Ec){}}if(C.ca)return(new URL(a,b)).href;c=C.Ba;c||(c=document.implementation.createHTMLDocument("temp"),C.Ba=c,c.ja=c.createElement("base"),c.head.appendChild(c.ja),c.ia=c.createElement("a"));c.ja.href=b;c.ia.href=a;return c.ia.href||a}},Z={async:!0,load:function(a,b,c){if(a)if(a.match(/^data:/)){a=
a.split(",");var d=a[1];d=-1<a[0].indexOf(";base64")?atob(d):decodeURIComponent(d);b(d)}else{var e=new XMLHttpRequest;e.open("GET",a,Z.async);e.onload=function(){var a=e.responseURL||e.getResponseHeader("Location");a&&0===a.indexOf("/")&&(a=(location.origin||location.protocol+"//"+location.host)+a);var d=e.response||e.responseText;304===e.status||0===e.status||200<=e.status&&300>e.status?b(d,a):c(d)};e.send()}else c("error: href must be specified")}},na=/Trident/.test(navigator.userAgent)||/Edge\/\d./i.test(navigator.userAgent);
k.prototype.loadImports=function(a){var b=this;a=m(a,"link[rel=import]");p(a,function(a){return b.i(a)})};k.prototype.i=function(a){var b=this,c=a.href;if(void 0!==this.a[c]){var d=this.a[c];d&&d.__loaded&&(a.__import=d,this.f(a))}else this.b++,this.a[c]="pending",Z.load(c,function(a,d){a=b.Oa(a,d||c);b.a[c]=a;b.b--;b.loadImports(a);b.o()},function(){b.a[c]=null;b.b--;b.o()})};k.prototype.Oa=function(a,b){if(!a)return document.createDocumentFragment();na&&(a=a.replace(T,function(a,b,c){return-1===
a.indexOf("type=")?b+" type=import-disable "+c:a}));var c=document.createElement("template");c.innerHTML=a;if(c.content)a=c.content,l(a);else for(a=document.createDocumentFragment();c.firstChild;)a.appendChild(c.firstChild);if(c=a.querySelector("base"))b=C.Y(c.getAttribute("href"),b),c.removeAttribute("href");c=m(a,'link[rel=import],link[rel=stylesheet][href][type=import-disable],style:not([type]),link[rel=stylesheet][href]:not([type]),script:not([type]),script[type="application/javascript"],script[type="text/javascript"],script[type="module"]');
var d=0;p(c,function(a){h(a);C.Ia(a,b);a.setAttribute("import-dependency","");if("script"===a.localName&&!a.src&&a.textContent){if("module"===a.type)throw Error("Inline module scripts are not supported in HTML Imports.");a.setAttribute("src","data:text/javascript;charset=utf-8,"+encodeURIComponent(a.textContent+("\n//# sourceURL="+b+(d?"-"+d:"")+".js\n")));a.textContent="";d++}});return a};k.prototype.o=function(){var a=this;if(!this.b){this.c.disconnect();this.flatten(document);var b=!1,c=!1,d=function(){c&&
b&&(a.loadImports(document),a.b||(a.c.observe(document.head,{childList:!0,subtree:!0}),a.ea()))};this.Qa(function(){c=!0;d()});this.Pa(function(){b=!0;d()})}};k.prototype.flatten=function(a){var b=this;a=m(a,"link[rel=import]");p(a,function(a){var c=b.a[a.href];(a.__import=c)&&c.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&(b.a[a.href]=a,a.readyState="loading",a.__import=a,b.flatten(c),a.appendChild(c))})};k.prototype.Pa=function(a){function b(e){if(e<d){var f=c[e],g=document.createElement("script");f.removeAttribute("import-dependency");
p(f.attributes,function(a){return g.setAttribute(a.name,a.value)});va=g;f.parentNode.replaceChild(g,f);h(g,function(){va=null;b(e+1)})}else a()}var c=m(document,"script[import-dependency]"),d=c.length;b(0)};k.prototype.Qa=function(a){var b=m(document,"style[import-dependency],link[rel=stylesheet][import-dependency]"),d=b.length;if(d){var e=na&&!!document.querySelector("link[rel=stylesheet][href][type=import-disable]");p(b,function(b){h(b,function(){b.removeAttribute("import-dependency");0===--d&&
a()});if(e&&b.parentNode!==document.head){var f=document.createElement(b.localName);f.__appliedElement=b;f.setAttribute("type","import-placeholder");b.parentNode.insertBefore(f,b.nextSibling);for(f=c(b);f&&c(f);)f=c(f);f.parentNode!==document.head&&(f=null);document.head.insertBefore(b,f);b.removeAttribute("type")}})}else a()};k.prototype.ea=function(){var a=this,b=m(document,"link[rel=import]");p(b,function(b){return a.f(b)},!0)};k.prototype.f=function(a){a.__loaded||(a.__loaded=!0,a.import&&(a.import.readyState=
"complete"),a.dispatchEvent(b(a.import?"load":"error",{bubbles:!1,cancelable:!1,detail:void 0})))};k.prototype.Na=function(a){var b=this;p(a,function(a){return p(a.addedNodes,function(a){a&&a.nodeType===Node.ELEMENT_NODE&&(g(a)?b.i(a):b.loadImports(a))})})};var wa=null;if(N)x=m(document,"link[rel=import]"),p(x,function(a){a.import&&"loading"===a.import.readyState||(a.__loaded=!0)}),x=function(a){a=a.target;g(a)&&(a.__loaded=!0)},document.addEventListener("load",x,!0),document.addEventListener("error",
x,!0);else{var ca=Object.getOwnPropertyDescriptor(Node.prototype,"baseURI");Object.defineProperty((!ca||ca.configurable?Node:Element).prototype,"baseURI",{get:function(){var a=g(this)?this:c(this);return a?a.href:ca&&ca.get?ca.get.call(this):(document.querySelector("base")||window.location).href},configurable:!0,enumerable:!0});Object.defineProperty(HTMLLinkElement.prototype,"import",{get:function(){return this.__import||null},configurable:!0,enumerable:!0});e(function(){wa=new k})}f(function(){return document.dispatchEvent(b("HTMLImportsLoaded",
{cancelable:!0,bubbles:!0,detail:void 0}))});a.useNative=N;a.whenReady=f;a.importForElement=c;a.loadImports=function(a){wa&&wa.loadImports(a)}})(window.HTMLImports=window.HTMLImports||{});/*

 Copyright (c) 2014 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
window.WebComponents=window.WebComponents||{flags:{}};var Ea=document.querySelector('script[src*="webcomponents-lite.js"]'),Fa=/wc-(.+)/,t={};if(!t.noOpts){location.search.slice(1).split("&").forEach(function(a){a=a.split("=");var b;a[0]&&(b=a[0].match(Fa))&&(t[b[1]]=a[1]||!0)});if(Ea)for(var Ga=0,Ha=void 0;Ha=Ea.attributes[Ga];Ga++)"src"!==Ha.name&&(t[Ha.name]=Ha.value||!0);if(t.log&&t.log.split){var Ia=t.log.split(",");t.log={};Ia.forEach(function(a){t.log[a]=!0})}else t.log={}}
window.WebComponents.flags=t;var Ja=t.shadydom;Ja&&(window.ShadyDOM=window.ShadyDOM||{},window.ShadyDOM.force=Ja);var Ka=t.register||t.ce;Ka&&window.customElements&&(window.customElements.forcePolyfill=Ka);/*

Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
function La(){this.qa=this.root=null;this.V=!1;this.D=this.S=this.da=this.assignedSlot=this.assignedNodes=this.I=null;this.childNodes=this.nextSibling=this.previousSibling=this.lastChild=this.firstChild=this.parentNode=this.M=void 0;this.xa=this.la=!1;this.R={}}La.prototype.toJSON=function(){return{}};function u(a){a.__shady||(a.__shady=new La);return a.__shady}function v(a){return a&&a.__shady};var w=window.ShadyDOM||{};w.Ka=!(!Element.prototype.attachShadow||!Node.prototype.getRootNode);var Ma=Object.getOwnPropertyDescriptor(Node.prototype,"firstChild");w.w=!!(Ma&&Ma.configurable&&Ma.get);w.fa=w.force||!w.Ka;var Na=navigator.userAgent.match("Trident"),Oa=navigator.userAgent.match("Edge");void 0===w.ta&&(w.ta=w.w&&(Na||Oa));function Pa(a){return(a=v(a))&&void 0!==a.firstChild}function y(a){return"ShadyRoot"===a.Da}function Qa(a){a=a.getRootNode();if(y(a))return a}
var Ra=Element.prototype,Sa=Ra.matches||Ra.matchesSelector||Ra.mozMatchesSelector||Ra.msMatchesSelector||Ra.oMatchesSelector||Ra.webkitMatchesSelector;function Ta(a,b){if(a&&b)for(var c=Object.getOwnPropertyNames(b),d=0,e=void 0;d<c.length&&(e=c[d]);d++){var f=e,h=a,g=Object.getOwnPropertyDescriptor(b,f);g&&Object.defineProperty(h,f,g)}}function Ua(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];for(d=0;d<c.length;d++)Ta(a,c[d]);return a}
function Va(a,b){for(var c in b)a[c]=b[c]}var Wa=document.createTextNode(""),Xa=0,Ya=[];(new MutationObserver(function(){for(;Ya.length;)try{Ya.shift()()}catch(a){throw Wa.textContent=Xa++,a;}})).observe(Wa,{characterData:!0});function Za(a){Ya.push(a);Wa.textContent=Xa++}var $a=!!document.contains;function ab(a,b){for(;b;){if(b==a)return!0;b=b.parentNode}return!1}
function bb(a){for(var b=a.length-1;0<=b;b--){var c=a[b],d=c.getAttribute("id")||c.getAttribute("name");d&&"length"!==d&&isNaN(d)&&(a[d]=c)}a.item=function(b){return a[b]};a.namedItem=function(b){if("length"!==b&&isNaN(b)&&a[b])return a[b];for(var c=ja(a),d=c.next();!d.done;d=c.next())if(d=d.value,(d.getAttribute("id")||d.getAttribute("name"))==b)return d;return null};return a};var cb=[],db;function eb(a){db||(db=!0,Za(fb));cb.push(a)}function fb(){db=!1;for(var a=!!cb.length;cb.length;)cb.shift()();return a}fb.list=cb;function gb(){this.a=!1;this.addedNodes=[];this.removedNodes=[];this.U=new Set}function hb(a){a.a||(a.a=!0,Za(function(){a.flush()}))}gb.prototype.flush=function(){if(this.a){this.a=!1;var a=this.takeRecords();a.length&&this.U.forEach(function(b){b(a)})}};gb.prototype.takeRecords=function(){if(this.addedNodes.length||this.removedNodes.length){var a=[{addedNodes:this.addedNodes,removedNodes:this.removedNodes}];this.addedNodes=[];this.removedNodes=[];return a}return[]};
function ib(a,b){var c=u(a);c.I||(c.I=new gb);c.I.U.add(b);var d=c.I;return{Ca:b,G:d,Ea:a,takeRecords:function(){return d.takeRecords()}}}function jb(a){var b=a&&a.G;b&&(b.U.delete(a.Ca),b.U.size||(u(a.Ea).I=null))}
function kb(a,b){var c=b.getRootNode();return a.map(function(a){var b=c===a.target.getRootNode();if(b&&a.addedNodes){if(b=Array.from(a.addedNodes).filter(function(a){return c===a.getRootNode()}),b.length)return a=Object.create(a),Object.defineProperty(a,"addedNodes",{value:b,configurable:!0}),a}else if(b)return a}).filter(function(a){return a})};var lb=Element.prototype.insertBefore,mb=Element.prototype.replaceChild,rb=Element.prototype.removeChild,sb=Element.prototype.setAttribute,tb=Element.prototype.removeAttribute,ub=Element.prototype.cloneNode,vb=Document.prototype.importNode,wb=Element.prototype.addEventListener,xb=Element.prototype.removeEventListener,yb=Window.prototype.addEventListener,zb=Window.prototype.removeEventListener,Ab=Element.prototype.dispatchEvent,Bb=Node.prototype.contains||HTMLElement.prototype.contains,Cb=Document.prototype.getElementById,
Db=Element.prototype.querySelector,Eb=DocumentFragment.prototype.querySelector,Fb=Document.prototype.querySelector,Gb=Element.prototype.querySelectorAll,Hb=DocumentFragment.prototype.querySelectorAll,Ib=Document.prototype.querySelectorAll,z={};z.appendChild=Element.prototype.appendChild;z.insertBefore=lb;z.replaceChild=mb;z.removeChild=rb;z.setAttribute=sb;z.removeAttribute=tb;z.cloneNode=ub;z.importNode=vb;z.addEventListener=wb;z.removeEventListener=xb;z.ab=yb;z.bb=zb;z.dispatchEvent=Ab;
z.contains=Bb;z.getElementById=Cb;z.ib=Db;z.lb=Eb;z.gb=Fb;z.querySelector=function(a){switch(this.nodeType){case Node.ELEMENT_NODE:return Db.call(this,a);case Node.DOCUMENT_NODE:return Fb.call(this,a);default:return Eb.call(this,a)}};z.jb=Gb;z.mb=Hb;z.hb=Ib;z.querySelectorAll=function(a){switch(this.nodeType){case Node.ELEMENT_NODE:return Gb.call(this,a);case Node.DOCUMENT_NODE:return Ib.call(this,a);default:return Hb.call(this,a)}};var Jb=/[&\u00A0"]/g,Kb=/[&\u00A0<>]/g;function Lb(a){switch(a){case "&":return"&amp;";case "<":return"&lt;";case ">":return"&gt;";case '"':return"&quot;";case "\u00a0":return"&nbsp;"}}function Mb(a){for(var b={},c=0;c<a.length;c++)b[a[c]]=!0;return b}var Nb=Mb("area base br col command embed hr img input keygen link meta param source track wbr".split(" ")),Ob=Mb("style script xmp iframe noembed noframes plaintext noscript".split(" "));
function Pb(a,b){"template"===a.localName&&(a=a.content);for(var c="",d=b?b(a):a.childNodes,e=0,f=d.length,h=void 0;e<f&&(h=d[e]);e++){a:{var g=h;var k=a,l=b;switch(g.nodeType){case Node.ELEMENT_NODE:k=g.localName;for(var m="<"+k,p=g.attributes,x=0,N;N=p[x];x++)m+=" "+N.name+'="'+N.value.replace(Jb,Lb)+'"';m+=">";g=Nb[k]?m:m+Pb(g,l)+"</"+k+">";break a;case Node.TEXT_NODE:g=g.data;g=k&&Ob[k.localName]?g:g.replace(Kb,Lb);break a;case Node.COMMENT_NODE:g="\x3c!--"+g.data+"--\x3e";break a;default:throw window.console.error(g),
Error("not implemented");}}c+=g}return c};var A=document.createTreeWalker(document,NodeFilter.SHOW_ALL,null,!1),B=document.createTreeWalker(document,NodeFilter.SHOW_ELEMENT,null,!1);function Qb(a){var b=[];A.currentNode=a;for(a=A.firstChild();a;)b.push(a),a=A.nextSibling();return b}
var D={parentNode:function(a){A.currentNode=a;return A.parentNode()},firstChild:function(a){A.currentNode=a;return A.firstChild()},lastChild:function(a){A.currentNode=a;return A.lastChild()},previousSibling:function(a){A.currentNode=a;return A.previousSibling()},nextSibling:function(a){A.currentNode=a;return A.nextSibling()}};D.childNodes=Qb;D.parentElement=function(a){B.currentNode=a;return B.parentNode()};D.firstElementChild=function(a){B.currentNode=a;return B.firstChild()};
D.lastElementChild=function(a){B.currentNode=a;return B.lastChild()};D.previousElementSibling=function(a){B.currentNode=a;return B.previousSibling()};D.nextElementSibling=function(a){B.currentNode=a;return B.nextSibling()};D.children=function(a){var b=[];B.currentNode=a;for(a=B.firstChild();a;)b.push(a),a=B.nextSibling();return bb(b)};D.innerHTML=function(a){return Pb(a,function(a){return Qb(a)})};
D.textContent=function(a){switch(a.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:a=document.createTreeWalker(a,NodeFilter.SHOW_TEXT,null,!1);for(var b="",c;c=a.nextNode();)b+=c.nodeValue;return b;default:return a.nodeValue}};var Rb=w.w,Sb=[Node.prototype,Element.prototype,HTMLElement.prototype];function E(a){var b;a:{for(b=0;b<Sb.length;b++){var c=Sb[b];if(c.hasOwnProperty(a)){b=c;break a}}b=void 0}if(!b)throw Error("Could not find descriptor for "+a);return Object.getOwnPropertyDescriptor(b,a)}
var F=Rb?{parentNode:E("parentNode"),firstChild:E("firstChild"),lastChild:E("lastChild"),previousSibling:E("previousSibling"),nextSibling:E("nextSibling"),childNodes:E("childNodes"),parentElement:E("parentElement"),previousElementSibling:E("previousElementSibling"),nextElementSibling:E("nextElementSibling"),innerHTML:E("innerHTML"),textContent:E("textContent"),firstElementChild:E("firstElementChild"),lastElementChild:E("lastElementChild"),children:E("children")}:{},Tb=Rb?{firstElementChild:Object.getOwnPropertyDescriptor(DocumentFragment.prototype,
"firstElementChild"),lastElementChild:Object.getOwnPropertyDescriptor(DocumentFragment.prototype,"lastElementChild"),children:Object.getOwnPropertyDescriptor(DocumentFragment.prototype,"children")}:{},Ub=Rb?{firstElementChild:Object.getOwnPropertyDescriptor(Document.prototype,"firstElementChild"),lastElementChild:Object.getOwnPropertyDescriptor(Document.prototype,"lastElementChild"),children:Object.getOwnPropertyDescriptor(Document.prototype,"children")}:{},Vb={pa:F,kb:Tb,fb:Ub,parentNode:function(a){return F.parentNode.get.call(a)},
firstChild:function(a){return F.firstChild.get.call(a)},lastChild:function(a){return F.lastChild.get.call(a)},previousSibling:function(a){return F.previousSibling.get.call(a)},nextSibling:function(a){return F.nextSibling.get.call(a)},childNodes:function(a){return Array.prototype.slice.call(F.childNodes.get.call(a))},parentElement:function(a){return F.parentElement.get.call(a)},previousElementSibling:function(a){return F.previousElementSibling.get.call(a)},nextElementSibling:function(a){return F.nextElementSibling.get.call(a)},
innerHTML:function(a){return F.innerHTML.get.call(a)},textContent:function(a){return F.textContent.get.call(a)},children:function(a){switch(a.nodeType){case Node.DOCUMENT_FRAGMENT_NODE:return Tb.children.get.call(a);case Node.DOCUMENT_NODE:return Ub.children.get.call(a);default:return F.children.get.call(a)}},firstElementChild:function(a){switch(a.nodeType){case Node.DOCUMENT_FRAGMENT_NODE:return Tb.firstElementChild.get.call(a);case Node.DOCUMENT_NODE:return Ub.firstElementChild.get.call(a);default:return F.firstElementChild.get.call(a)}},
lastElementChild:function(a){switch(a.nodeType){case Node.DOCUMENT_FRAGMENT_NODE:return Tb.lastElementChild.get.call(a);case Node.DOCUMENT_NODE:return Ub.lastElementChild.get.call(a);default:return F.lastElementChild.get.call(a)}}};var G=w.ta?Vb:D;function Wb(a){for(;a.firstChild;)a.removeChild(a.firstChild)}
var Xb=w.w,Yb=document.implementation.createHTMLDocument("inert"),Zb=Object.getOwnPropertyDescriptor(Node.prototype,"isConnected"),$b=Zb&&Zb.get,ac=Object.getOwnPropertyDescriptor(Document.prototype,"activeElement"),bc={parentElement:{get:function(){var a=v(this);(a=a&&a.parentNode)&&a.nodeType!==Node.ELEMENT_NODE&&(a=null);return void 0!==a?a:G.parentElement(this)},configurable:!0},parentNode:{get:function(){var a=v(this);a=a&&a.parentNode;return void 0!==a?a:G.parentNode(this)},configurable:!0},
nextSibling:{get:function(){var a=v(this);a=a&&a.nextSibling;return void 0!==a?a:G.nextSibling(this)},configurable:!0},previousSibling:{get:function(){var a=v(this);a=a&&a.previousSibling;return void 0!==a?a:G.previousSibling(this)},configurable:!0},nextElementSibling:{get:function(){var a=v(this);if(a&&void 0!==a.nextSibling){for(a=this.nextSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.nextSibling;return a}return G.nextElementSibling(this)},configurable:!0},previousElementSibling:{get:function(){var a=
v(this);if(a&&void 0!==a.previousSibling){for(a=this.previousSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.previousSibling;return a}return G.previousElementSibling(this)},configurable:!0}},cc={className:{get:function(){return this.getAttribute("class")||""},set:function(a){this.setAttribute("class",a)},configurable:!0}},dc={childNodes:{get:function(){if(Pa(this)){var a=v(this);if(!a.childNodes){a.childNodes=[];for(var b=this.firstChild;b;b=b.nextSibling)a.childNodes.push(b)}var c=a.childNodes}else c=
G.childNodes(this);c.item=function(a){return c[a]};return c},configurable:!0},childElementCount:{get:function(){return this.children.length},configurable:!0},firstChild:{get:function(){var a=v(this);a=a&&a.firstChild;return void 0!==a?a:G.firstChild(this)},configurable:!0},lastChild:{get:function(){var a=v(this);a=a&&a.lastChild;return void 0!==a?a:G.lastChild(this)},configurable:!0},textContent:{get:function(){if(Pa(this)){for(var a=[],b=0,c=this.childNodes,d;d=c[b];b++)d.nodeType!==Node.COMMENT_NODE&&
a.push(d.textContent);return a.join("")}return G.textContent(this)},set:function(a){if("undefined"===typeof a||null===a)a="";switch(this.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:if(!Pa(this)&&Xb){var b=this.firstChild;(b!=this.lastChild||b&&b.nodeType!=Node.TEXT_NODE)&&Wb(this);Vb.pa.textContent.set.call(this,a)}else Wb(this),(0<a.length||this.nodeType===Node.ELEMENT_NODE)&&this.appendChild(document.createTextNode(a));break;default:this.nodeValue=a}},configurable:!0},firstElementChild:{get:function(){var a=
v(this);if(a&&void 0!==a.firstChild){for(a=this.firstChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.nextSibling;return a}return G.firstElementChild(this)},configurable:!0},lastElementChild:{get:function(){var a=v(this);if(a&&void 0!==a.lastChild){for(a=this.lastChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.previousSibling;return a}return G.lastElementChild(this)},configurable:!0},children:{get:function(){return Pa(this)?bb(Array.prototype.filter.call(this.childNodes,function(a){return a.nodeType===Node.ELEMENT_NODE})):
G.children(this)},configurable:!0},innerHTML:{get:function(){return Pa(this)?Pb("template"===this.localName?this.content:this):G.innerHTML(this)},set:function(a){var b="template"===this.localName?this.content:this;Wb(b);var c=this.localName||"div";c=this.namespaceURI&&this.namespaceURI!==Yb.namespaceURI?Yb.createElementNS(this.namespaceURI,c):Yb.createElement(c);Xb?Vb.pa.innerHTML.set.call(c,a):c.innerHTML=a;for(a="template"===this.localName?c.content:c;a.firstChild;)b.appendChild(a.firstChild)},
configurable:!0}},ec={shadowRoot:{get:function(){var a=v(this);return a&&a.qa||null},configurable:!0}},fc={activeElement:{get:function(){var a=ac&&ac.get?ac.get.call(document):w.w?void 0:document.activeElement;if(a&&a.nodeType){var b=!!y(this);if(this===document||b&&this.host!==a&&z.contains.call(this.host,a)){for(b=Qa(a);b&&b!==this;)a=b.host,b=Qa(a);a=this===document?b?null:a:b===this?a:null}else a=null}else a=null;return a},set:function(){},configurable:!0}};
function H(a,b,c){for(var d in b){var e=Object.getOwnPropertyDescriptor(a,d);e&&e.configurable||!e&&c?Object.defineProperty(a,d,b[d]):c&&console.warn("Could not define",d,"on",a)}}function gc(a){H(a,bc);H(a,cc);H(a,dc);H(a,fc)}
function hc(){var a=ic.prototype;a.__proto__=DocumentFragment.prototype;H(a,bc,!0);H(a,dc,!0);H(a,fc,!0);Object.defineProperties(a,{nodeType:{value:Node.DOCUMENT_FRAGMENT_NODE,configurable:!0},nodeName:{value:"#document-fragment",configurable:!0},nodeValue:{value:null,configurable:!0}});["localName","namespaceURI","prefix"].forEach(function(b){Object.defineProperty(a,b,{value:void 0,configurable:!0})});["ownerDocument","baseURI","isConnected"].forEach(function(b){Object.defineProperty(a,b,{get:function(){return this.host[b]},
configurable:!0})})}var jc=w.w?function(){}:function(a){var b=u(a);b.la||(b.la=!0,H(a,bc,!0),H(a,cc,!0))},kc=w.w?function(){}:function(a){u(a).xa||(H(a,dc,!0),H(a,ec,!0))};var lc=G.childNodes;function mc(a,b,c){kc(b);var d=u(b);void 0!==d.firstChild&&(d.childNodes=null);if(a.nodeType===Node.DOCUMENT_FRAGMENT_NODE){d=a.childNodes;for(var e=0;e<d.length;e++)nc(d[e],b,c);a=u(a);b=void 0!==a.firstChild?null:void 0;a.firstChild=a.lastChild=b;a.childNodes=b}else nc(a,b,c)}
function nc(a,b,c){jc(a);c=c||null;var d=u(a),e=u(b),f=c?u(c):null;d.previousSibling=c?f.previousSibling:b.lastChild;if(f=v(d.previousSibling))f.nextSibling=a;if(f=v(d.nextSibling=c))f.previousSibling=a;d.parentNode=b;c?c===e.firstChild&&(e.firstChild=a):(e.lastChild=a,e.firstChild||(e.firstChild=a));e.childNodes=null}
function oc(a,b){var c=u(a);b=u(b);a===b.firstChild&&(b.firstChild=c.nextSibling);a===b.lastChild&&(b.lastChild=c.previousSibling);a=c.previousSibling;var d=c.nextSibling;a&&(u(a).nextSibling=d);d&&(u(d).previousSibling=a);c.parentNode=c.previousSibling=c.nextSibling=void 0;void 0!==b.childNodes&&(b.childNodes=null)}
function pc(a,b){var c=u(a);if(void 0===c.firstChild)for(c.childNodes=null,b=b||lc(a),c.firstChild=b[0]||null,c.lastChild=b[b.length-1]||null,kc(a),c=0;c<b.length;c++){var d=b[c],e=u(d);e.parentNode=a;e.nextSibling=b[c+1]||null;e.previousSibling=b[c-1]||null;jc(d)}};var qc=G.parentNode,rc=window.document,sc=w.ob;
function tc(a,b,c){if(a.ownerDocument!==rc&&b.ownerDocument!==rc)return z.insertBefore.call(a,b,c);if(b===a)throw Error("Failed to execute 'appendChild' on 'Node': The new child element contains the parent.");if(c){var d=v(c);d=d&&d.parentNode;if(void 0!==d&&d!==a||void 0===d&&qc(c)!==a)throw Error("Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.");}if(c===b)return b;var e=[],f=uc,h=Qa(a),g;h?g=h.host.localName:g=vc(a);
if(b.parentNode){var k=vc(b);wc(b.parentNode,b,!!h||!(b.getRootNode()instanceof ShadowRoot));f=function(a,b){xc()&&(yc(a,k),uc(a,b))}}d=!0;var l=(!sc||void 0===b.__noInsertionPoint)&&!zc(b,g);if(h)b.__noInsertionPoint&&!l||Ac(b,function(a){"slot"===a.localName&&e.push(a);l&&f(a,g)});else if(l){var m=vc(b);Ac(b,function(a){var b=g;xc()&&(yc(a,m),uc(a,b))})}e.length&&Bc(h,e);("slot"===a.localName||e.length)&&h&&Cc(h);Pa(a)&&(mc(b,a,c),h=v(a),Dc(a)?(Cc(h.root),d=!1):h.root&&(d=!1));d?(d=y(a)?a.host:
a,c?(c=Gc(c),z.insertBefore.call(d,b,c)):z.appendChild.call(d,b)):b.ownerDocument!==a.ownerDocument&&a.ownerDocument.adoptNode(b);Hc(a,b);return b}
function wc(a,b,c){c=void 0===c?!1:c;if(a.ownerDocument!==rc)return z.removeChild.call(a,b);if(b.parentNode!==a)throw Error("The node to be removed is not a child of this node: "+b);var d=Qa(b),e=v(a);if(Pa(a)&&(oc(b,a),Dc(a))){Cc(e.root);var f=!0}if(xc()&&!c&&d){var h=vc(b);Ac(b,function(a){yc(a,h)})}Ic(b);if(d){var g=a&&"slot"===a.localName;g&&(f=!0);((c=Jc(d,b))||g)&&Cc(d)}f||(f=y(a)?a.host:a,(!e.root&&"slot"!==b.localName||f===qc(b))&&z.removeChild.call(f,b));Hc(a,null,b);return b}
function Ic(a){var b=v(a);if(b&&void 0!==b.M){b=a.childNodes;for(var c=0,d=b.length,e=void 0;c<d&&(e=b[c]);c++)Ic(e)}if(a=v(a))a.M=void 0}function Gc(a){var b=a;a&&"slot"===a.localName&&(b=(b=(b=v(a))&&b.D)&&b.length?b[0]:Gc(a.nextSibling));return b}function Dc(a){return(a=(a=v(a))&&a.root)&&Kc(a)}
function Lc(a,b){if("slot"===b)a=a.parentNode,Dc(a)&&Cc(v(a).root);else if("slot"===a.localName&&"name"===b&&(b=Qa(a))){if(b.g){Mc(b);var c=a.Aa,d=Nc(a);if(d!==c){c=b.h[c];var e=c.indexOf(a);0<=e&&c.splice(e,1);c=b.h[d]||(b.h[d]=[]);c.push(a);1<c.length&&(b.h[d]=Oc(c))}}Cc(b)}}function Hc(a,b,c){if(a=(a=v(a))&&a.I)b&&a.addedNodes.push(b),c&&a.removedNodes.push(c),hb(a)}
function Pc(a){if(a&&a.nodeType){var b=u(a),c=b.M;void 0===c&&(y(a)?(c=a,b.M=c):(c=(c=a.parentNode)?Pc(c):a,z.contains.call(document.documentElement,a)&&(b.M=c)));return c}}function Qc(a,b,c){var d=[];Rc(a.childNodes,b,c,d);return d}function Rc(a,b,c,d){for(var e=0,f=a.length,h=void 0;e<f&&(h=a[e]);e++){var g;if(g=h.nodeType===Node.ELEMENT_NODE){g=h;var k=b,l=c,m=d,p=k(g);p&&m.push(g);l&&l(p)?g=p:(Rc(g.childNodes,k,l,m),g=void 0)}if(g)break}}var Sc=null;
function xc(){Sc||(Sc=window.ShadyCSS&&window.ShadyCSS.ScopingShim);return Sc||null}function Tc(a,b,c){if(a.ownerDocument!==rc)z.setAttribute.call(a,b,c);else{var d=xc();d&&"class"===b?d.setElementClass(a,c):(z.setAttribute.call(a,b,c),Lc(a,b))}}function Uc(a,b){if(a.ownerDocument!==document||"template"===a.localName)return z.importNode.call(document,a,b);var c=z.importNode.call(document,a,!1);if(b){a=a.childNodes;b=0;for(var d;b<a.length;b++)d=Uc(a[b],!0),c.appendChild(d)}return c}
function uc(a,b){var c=xc();c&&c.scopeNode(a,b)}function yc(a,b){var c=xc();c&&c.unscopeNode(a,b)}function zc(a,b){var c=xc();if(!c)return!0;if(a.nodeType===Node.DOCUMENT_FRAGMENT_NODE){c=!0;for(var d=0;c&&d<a.childNodes.length;d++)c=c&&zc(a.childNodes[d],b);return c}return a.nodeType!==Node.ELEMENT_NODE?!0:c.currentScopeForNode(a)===b}function vc(a){if(a.nodeType!==Node.ELEMENT_NODE)return"";var b=xc();return b?b.currentScopeForNode(a):""}
function Ac(a,b){if(a){a.nodeType===Node.ELEMENT_NODE&&b(a);for(var c=0,d;c<a.childNodes.length;c++)d=a.childNodes[c],d.nodeType===Node.ELEMENT_NODE&&Ac(d,b)}};var Vc="__eventWrappers"+Date.now(),Wc=function(){var a=Object.getOwnPropertyDescriptor(Event.prototype,"composed");return a?function(b){return a.get.call(b)}:null}(),Xc={blur:!0,focus:!0,focusin:!0,focusout:!0,click:!0,dblclick:!0,mousedown:!0,mouseenter:!0,mouseleave:!0,mousemove:!0,mouseout:!0,mouseover:!0,mouseup:!0,wheel:!0,beforeinput:!0,input:!0,keydown:!0,keyup:!0,compositionstart:!0,compositionupdate:!0,compositionend:!0,touchstart:!0,touchend:!0,touchmove:!0,touchcancel:!0,pointerover:!0,
pointerenter:!0,pointerdown:!0,pointermove:!0,pointerup:!0,pointercancel:!0,pointerout:!0,pointerleave:!0,gotpointercapture:!0,lostpointercapture:!0,dragstart:!0,drag:!0,dragenter:!0,dragleave:!0,dragover:!0,drop:!0,dragend:!0,DOMActivate:!0,DOMFocusIn:!0,DOMFocusOut:!0,keypress:!0},Yc={DOMAttrModified:!0,DOMAttributeNameChanged:!0,DOMCharacterDataModified:!0,DOMElementNameChanged:!0,DOMNodeInserted:!0,DOMNodeInsertedIntoDocument:!0,DOMNodeRemoved:!0,DOMNodeRemovedFromDocument:!0,DOMSubtreeModified:!0};
function Zc(a,b){var c=[],d=a;for(a=a===window?window:a.getRootNode();d;)c.push(d),d=d.assignedSlot?d.assignedSlot:d.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&d.host&&(b||d!==a)?d.host:d.parentNode;c[c.length-1]===document&&c.push(window);return c}function $c(a,b){if(!y)return a;a=Zc(a,!0);for(var c=0,d,e=void 0,f,h=void 0;c<b.length;c++)if(d=b[c],f=d===window?window:d.getRootNode(),f!==e&&(h=a.indexOf(f),e=f),!y(f)||-1<h)return d}
var ad={get composed(){void 0===this.P&&(Wc?this.P="focusin"===this.type||"focusout"===this.type||Wc(this):!1!==this.isTrusted&&(this.P=Xc[this.type]));return this.P||!1},composedPath:function(){this.ka||(this.ka=Zc(this.__target,this.composed));return this.ka},get target(){return $c(this.currentTarget||this.__previousCurrentTarget,this.composedPath())},get relatedTarget(){if(!this.aa)return null;this.ma||(this.ma=Zc(this.aa,!0));return $c(this.currentTarget||this.__previousCurrentTarget,this.ma)},
stopPropagation:function(){Event.prototype.stopPropagation.call(this);this.$=!0},stopImmediatePropagation:function(){Event.prototype.stopImmediatePropagation.call(this);this.$=this.wa=!0}};function bd(a){function b(b,d){b=new a(b,d);b.P=d&&!!d.composed;return b}Va(b,a);b.prototype=a.prototype;return b}var cd={focus:!0,blur:!0};function dd(a){return a.__target!==a.target||a.aa!==a.relatedTarget}
function ed(a,b,c){if(c=b.__handlers&&b.__handlers[a.type]&&b.__handlers[a.type][c])for(var d=0,e;(e=c[d])&&(!dd(a)||a.target!==a.relatedTarget)&&(e.call(b,a),!a.wa);d++);}
function fd(a){var b=a.composedPath();Object.defineProperty(a,"currentTarget",{get:function(){return d},configurable:!0});for(var c=b.length-1;0<=c;c--){var d=b[c];ed(a,d,"capture");if(a.$)return}Object.defineProperty(a,"eventPhase",{get:function(){return Event.AT_TARGET}});var e;for(c=0;c<b.length;c++){d=b[c];var f=v(d);f=f&&f.root;if(0===c||f&&f===e)if(ed(a,d,"bubble"),d!==window&&(e=d.getRootNode()),a.$)break}}
function gd(a,b,c,d,e,f){for(var h=0;h<a.length;h++){var g=a[h],k=g.type,l=g.capture,m=g.once,p=g.passive;if(b===g.node&&c===k&&d===l&&e===m&&f===p)return h}return-1}
function hd(a,b,c){if(b){var d=typeof b;if("function"===d||"object"===d)if("object"!==d||b.handleEvent&&"function"===typeof b.handleEvent){var e=this instanceof Window?z.ab:z.addEventListener;if(Yc[a])return e.call(this,a,b,c);if(c&&"object"===typeof c){var f=!!c.capture;var h=!!c.once;var g=!!c.passive}else f=!!c,g=h=!1;var k=c&&c.ba||this,l=b[Vc];if(l){if(-1<gd(l,k,a,f,h,g))return}else b[Vc]=[];l=function(e){h&&this.removeEventListener(a,b,c);e.__target||id(e);if(k!==this){var f=Object.getOwnPropertyDescriptor(e,
"currentTarget");Object.defineProperty(e,"currentTarget",{get:function(){return k},configurable:!0})}e.__previousCurrentTarget=e.currentTarget;if(!y(k)||-1!=e.composedPath().indexOf(k))if(e.composed||-1<e.composedPath().indexOf(k))if(dd(e)&&e.target===e.relatedTarget)e.eventPhase===Event.BUBBLING_PHASE&&e.stopImmediatePropagation();else if(e.eventPhase===Event.CAPTURING_PHASE||e.bubbles||e.target===k||k instanceof Window){var g="function"===d?b.call(k,e):b.handleEvent&&b.handleEvent(e);k!==this&&
(f?(Object.defineProperty(e,"currentTarget",f),f=null):delete e.currentTarget);return g}};b[Vc].push({node:k,type:a,capture:f,once:h,passive:g,cb:l});cd[a]?(this.__handlers=this.__handlers||{},this.__handlers[a]=this.__handlers[a]||{capture:[],bubble:[]},this.__handlers[a][f?"capture":"bubble"].push(l)):e.call(this,a,l,c)}}}
function jd(a,b,c){if(b){var d=this instanceof Window?z.bb:z.removeEventListener;if(Yc[a])return d.call(this,a,b,c);if(c&&"object"===typeof c){var e=!!c.capture;var f=!!c.once;var h=!!c.passive}else e=!!c,h=f=!1;var g=c&&c.ba||this,k=void 0;var l=null;try{l=b[Vc]}catch(m){}l&&(f=gd(l,g,a,e,f,h),-1<f&&(k=l.splice(f,1)[0].cb,l.length||(b[Vc]=void 0)));d.call(this,a,k||b,c);k&&cd[a]&&this.__handlers&&this.__handlers[a]&&(a=this.__handlers[a][e?"capture":"bubble"],k=a.indexOf(k),-1<k&&a.splice(k,1))}}
function kd(){for(var a in cd)window.addEventListener(a,function(a){a.__target||(id(a),fd(a))},!0)}function id(a){a.__target=a.target;a.aa=a.relatedTarget;if(w.w){var b=Object.getPrototypeOf(a);if(!b.hasOwnProperty("__patchProto")){var c=Object.create(b);c.eb=b;Ta(c,ad);b.__patchProto=c}a.__proto__=b.__patchProto}else Ta(a,ad)}var ld=bd(window.Event),md=bd(window.CustomEvent),nd=bd(window.MouseEvent);
function od(){window.Event=ld;window.CustomEvent=md;window.MouseEvent=nd;kd();if(!Wc&&Object.getOwnPropertyDescriptor(Event.prototype,"isTrusted")){var a=function(){var a=new MouseEvent("click",{bubbles:!0,cancelable:!0,composed:!0});this.dispatchEvent(a)};Element.prototype.click?Element.prototype.click=a:HTMLElement.prototype.click&&(HTMLElement.prototype.click=a)}};function pd(a,b){return{index:a,N:[],T:b}}
function qd(a,b,c,d){var e=0,f=0,h=0,g=0,k=Math.min(b-e,d-f);if(0==e&&0==f)a:{for(h=0;h<k;h++)if(a[h]!==c[h])break a;h=k}if(b==a.length&&d==c.length){g=a.length;for(var l=c.length,m=0;m<k-h&&rd(a[--g],c[--l]);)m++;g=m}e+=h;f+=h;b-=g;d-=g;if(0==b-e&&0==d-f)return[];if(e==b){for(b=pd(e,0);f<d;)b.N.push(c[f++]);return[b]}if(f==d)return[pd(e,b-e)];k=e;h=f;d=d-h+1;g=b-k+1;b=Array(d);for(l=0;l<d;l++)b[l]=Array(g),b[l][0]=l;for(l=0;l<g;l++)b[0][l]=l;for(l=1;l<d;l++)for(m=1;m<g;m++)if(a[k+m-1]===c[h+l-1])b[l][m]=
b[l-1][m-1];else{var p=b[l-1][m]+1,x=b[l][m-1]+1;b[l][m]=p<x?p:x}k=b.length-1;h=b[0].length-1;d=b[k][h];for(a=[];0<k||0<h;)0==k?(a.push(2),h--):0==h?(a.push(3),k--):(g=b[k-1][h-1],l=b[k-1][h],m=b[k][h-1],p=l<m?l<g?l:g:m<g?m:g,p==g?(g==d?a.push(0):(a.push(1),d=g),k--,h--):p==l?(a.push(3),k--,d=l):(a.push(2),h--,d=m));a.reverse();b=void 0;k=[];for(h=0;h<a.length;h++)switch(a[h]){case 0:b&&(k.push(b),b=void 0);e++;f++;break;case 1:b||(b=pd(e,0));b.T++;e++;b.N.push(c[f]);f++;break;case 2:b||(b=pd(e,0));
b.T++;e++;break;case 3:b||(b=pd(e,0)),b.N.push(c[f]),f++}b&&k.push(b);return k}function rd(a,b){return a===b};var sd=G.parentNode,td=G.childNodes,ud={},vd=w.deferConnectionCallbacks&&"loading"===document.readyState,wd;function xd(a){var b=[];do b.unshift(a);while(a=a.parentNode);return b}
function ic(a,b,c){if(a!==ud)throw new TypeError("Illegal constructor");this.Da="ShadyRoot";this.host=b;this.c=c&&c.mode;a=td(b);pc(b,a);c=u(b);c.root=this;c.qa="closed"!==this.c?this:null;c=u(this);c.firstChild=c.lastChild=c.parentNode=c.nextSibling=c.previousSibling=null;c.childNodes=[];this.b=this.L=!1;this.a=this.h=this.g=null;if(w.preferPerformance){c=0;for(var d=a.length;c<d;c++)z.removeChild.call(b,a[c])}else Cc(this)}function Cc(a){a.L||(a.L=!0,eb(function(){return yd(a)}))}
function yd(a){for(var b;a;){a.L&&(b=a);a:{var c=a;a=c.host.getRootNode();if(y(a))for(var d=c.host.childNodes,e=0;e<d.length;e++)if(c=d[e],"slot"==c.localName)break a;a=void 0}}b&&b._renderRoot()}
ic.prototype._renderRoot=function(){var a=vd;vd=!0;this.L=!1;if(this.g){Mc(this);for(var b=0,c;b<this.g.length;b++){c=this.g[b];var d=v(c),e=d.assignedNodes;d.assignedNodes=[];d.D=[];if(d.da=e)for(d=0;d<e.length;d++){var f=v(e[d]);f.S=f.assignedSlot;f.assignedSlot===c&&(f.assignedSlot=null)}}for(b=this.host.firstChild;b;b=b.nextSibling)zd(this,b);for(b=0;b<this.g.length;b++){c=this.g[b];e=v(c);if(!e.assignedNodes.length)for(d=c.firstChild;d;d=d.nextSibling)zd(this,d,c);(d=(d=v(c.parentNode))&&d.root)&&
(Kc(d)||d.L)&&d._renderRoot();Ad(this,e.D,e.assignedNodes);if(d=e.da){for(f=0;f<d.length;f++)v(d[f]).S=null;e.da=null;d.length>e.assignedNodes.length&&(e.V=!0)}e.V&&(e.V=!1,Bd(this,c))}c=this.g;b=[];for(e=0;e<c.length;e++)d=c[e].parentNode,(f=v(d))&&f.root||!(0>b.indexOf(d))||b.push(d);for(c=0;c<b.length;c++){f=b[c];e=f===this?this.host:f;d=[];f=f.childNodes;for(var h=0;h<f.length;h++){var g=f[h];if("slot"==g.localName){g=v(g).D;for(var k=0;k<g.length;k++)d.push(g[k])}else d.push(g)}f=td(e);h=qd(d,
d.length,f,f.length);k=g=0;for(var l=void 0;g<h.length&&(l=h[g]);g++){for(var m=0,p=void 0;m<l.N.length&&(p=l.N[m]);m++)sd(p)===e&&z.removeChild.call(e,p),f.splice(l.index+k,1);k-=l.T}k=0;for(l=void 0;k<h.length&&(l=h[k]);k++)for(g=f[l.index],m=l.index;m<l.index+l.T;m++)p=d[m],z.insertBefore.call(e,p,g),f.splice(m,0,p)}}if(!w.preferPerformance&&!this.b)for(b=this.host.childNodes,c=0,e=b.length;c<e;c++)d=b[c],f=v(d),sd(d)!==this.host||"slot"!==d.localName&&f.assignedSlot||z.removeChild.call(this.host,
d);this.b=!0;vd=a;wd&&wd()};function zd(a,b,c){var d=u(b),e=d.S;d.S=null;c||(c=(a=a.h[b.slot||"__catchall"])&&a[0]);c?(u(c).assignedNodes.push(b),d.assignedSlot=c):d.assignedSlot=void 0;e!==d.assignedSlot&&d.assignedSlot&&(u(d.assignedSlot).V=!0)}function Ad(a,b,c){for(var d=0,e=void 0;d<c.length&&(e=c[d]);d++)if("slot"==e.localName){var f=v(e).assignedNodes;f&&f.length&&Ad(a,b,f)}else b.push(c[d])}
function Bd(a,b){z.dispatchEvent.call(b,new Event("slotchange"));b=v(b);b.assignedSlot&&Bd(a,b.assignedSlot)}function Bc(a,b){a.a=a.a||[];a.g=a.g||[];a.h=a.h||{};a.a.push.apply(a.a,b instanceof Array?b:ka(ja(b)))}function Mc(a){if(a.a&&a.a.length){for(var b=a.a,c,d=0;d<b.length;d++){var e=b[d];pc(e);pc(e.parentNode);var f=Nc(e);a.h[f]?(c=c||{},c[f]=!0,a.h[f].push(e)):a.h[f]=[e];a.g.push(e)}if(c)for(var h in c)a.h[h]=Oc(a.h[h]);a.a=[]}}
function Nc(a){var b=a.name||a.getAttribute("name")||"__catchall";return a.Aa=b}function Oc(a){return a.sort(function(a,c){a=xd(a);for(var b=xd(c),e=0;e<a.length;e++){c=a[e];var f=b[e];if(c!==f)return a=Array.from(c.parentNode.childNodes),a.indexOf(c)-a.indexOf(f)}})}
function Jc(a,b){if(a.g){Mc(a);var c=a.h,d;for(d in c)for(var e=c[d],f=0;f<e.length;f++){var h=e[f];if(ab(b,h)){e.splice(f,1);var g=a.g.indexOf(h);0<=g&&a.g.splice(g,1);f--;h=v(h);if(g=h.D)for(var k=0;k<g.length;k++){var l=g[k],m=sd(l);m&&z.removeChild.call(m,l)}h.D=[];h.assignedNodes=[];g=!0}}return g}}function Kc(a){Mc(a);return!(!a.g||!a.g.length)}
if(window.customElements&&w.fa&&!w.preferPerformance){var Cd=new Map;wd=function(){var a=Array.from(Cd);Cd.clear();a=ja(a);for(var b=a.next();!b.done;b=a.next()){b=ja(b.value);var c=b.next().value;b.next().value?c.ya():c.za()}};vd&&document.addEventListener("readystatechange",function(){vd=!1;wd()},{once:!0});var Dd=function(a,b,c){var d=0,e="__isConnected"+d++;if(b||c)a.prototype.connectedCallback=a.prototype.ya=function(){vd?Cd.set(this,!0):this[e]||(this[e]=!0,b&&b.call(this))},a.prototype.disconnectedCallback=
a.prototype.za=function(){vd?this.isConnected||Cd.set(this,!1):this[e]&&(this[e]=!1,c&&c.call(this))};return a},Ed=window.customElements.define;Object.defineProperty(window.CustomElementRegistry.prototype,"define",{value:function(a,b){var c=b.prototype.connectedCallback,d=b.prototype.disconnectedCallback;Ed.call(window.customElements,a,Dd(b,c,d));b.prototype.connectedCallback=c;b.prototype.disconnectedCallback=d}})};function Fd(a){var b=a.getRootNode();y(b)&&yd(b);return(a=v(a))&&a.assignedSlot||null}
var Gd={addEventListener:hd.bind(window),removeEventListener:jd.bind(window)},Hd={addEventListener:hd,removeEventListener:jd,appendChild:function(a){return tc(this,a)},insertBefore:function(a,b){return tc(this,a,b)},removeChild:function(a){return wc(this,a)},replaceChild:function(a,b){tc(this,a,b);wc(this,b);return a},cloneNode:function(a){if("template"==this.localName)var b=z.cloneNode.call(this,a);else if(b=z.cloneNode.call(this,!1),a&&b.nodeType!==Node.ATTRIBUTE_NODE){a=this.childNodes;for(var c=
0,d;c<a.length;c++)d=a[c].cloneNode(!0),b.appendChild(d)}return b},getRootNode:function(){return Pc(this)},contains:function(a){return ab(this,a)},dispatchEvent:function(a){fb();return z.dispatchEvent.call(this,a)}};
Object.defineProperties(Hd,{isConnected:{get:function(){if($b&&$b.call(this))return!0;if(this.nodeType==Node.DOCUMENT_FRAGMENT_NODE)return!1;var a=this.ownerDocument;if($a){if(z.contains.call(a,this))return!0}else if(a.documentElement&&z.contains.call(a.documentElement,this))return!0;for(a=this;a&&!(a instanceof Document);)a=a.parentNode||(y(a)?a.host:void 0);return!!(a&&a instanceof Document)},configurable:!0}});
var Id={get assignedSlot(){return Fd(this)}},Jd={querySelector:function(a){return Qc(this,function(b){return Sa.call(b,a)},function(a){return!!a})[0]||null},querySelectorAll:function(a,b){if(b){b=Array.prototype.slice.call(z.querySelectorAll.call(this,a));var c=this.getRootNode();return b.filter(function(a){return a.getRootNode()==c})}return Qc(this,function(b){return Sa.call(b,a)})}},Kd={},Ld={assignedNodes:function(a){if("slot"===this.localName){var b=this.getRootNode();y(b)&&yd(b);return(b=v(this))?
(a&&a.flatten?b.D:b.assignedNodes)||[]:[]}}},Md=Ua({setAttribute:function(a,b){Tc(this,a,b)},removeAttribute:function(a){z.removeAttribute.call(this,a);Lc(this,a)},attachShadow:function(a){if(!this)throw"Must provide a host.";if(!a)throw"Not enough arguments.";return new ic(ud,this,a)},get slot(){return this.getAttribute("slot")},set slot(a){Tc(this,"slot",a)},get assignedSlot(){return Fd(this)}},Jd,Ld);Object.defineProperties(Md,ec);
var Nd={importNode:function(a,b){return Uc(a,b)},getElementById:function(a){return Qc(this,function(b){return b.id==a},function(a){return!!a})[0]||null}};Object.defineProperties(Nd,{_activeElement:fc.activeElement});
for(var Od=HTMLElement.prototype.blur,Pd={blur:function(){var a=v(this);(a=(a=a&&a.root)&&a.activeElement)?a.blur():Od.call(this)}},Qd={},Rd=ja(Object.getOwnPropertyNames(Document.prototype)),Sd=Rd.next();!Sd.done;Qd={s:Qd.s},Sd=Rd.next())Qd.s=Sd.value,"on"===Qd.s.substring(0,2)&&Object.defineProperty(Pd,Qd.s,{set:function(a){return function(b){var c=u(this),d=a.s.substring(2);c.R[a.s]&&this.removeEventListener(d,c.R[a.s]);this.addEventListener(d,b,{});c.R[a.s]=b}}(Qd),get:function(a){return function(){var b=
v(this);return b&&b.R[a.s]}}(Qd),configurable:!0});var Td=Ua({addEventListener:function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.ba=this;this.host.addEventListener(a,b,c)},removeEventListener:function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.ba=this;this.host.removeEventListener(a,b,c)},getElementById:function(a){return Qc(this,function(b){return b.id==a},function(a){return!!a})[0]||null}},Jd);w.preferPerformance||(Ua(Nd,Jd),Ua(Kd,Jd));
function I(a,b){for(var c=Object.getOwnPropertyNames(b),d=0;d<c.length;d++){var e=c[d],f=Object.getOwnPropertyDescriptor(b,e);f.value?a[e]=f.value:Object.defineProperty(a,e,f)}};if(w.fa){var ShadyDOM={inUse:w.fa,patch:function(a){kc(a);jc(a);return a},isShadyRoot:y,enqueue:eb,flush:fb,settings:w,filterMutations:kb,observeChildren:ib,unobserveChildren:jb,nativeMethods:z,nativeTree:G,deferConnectionCallbacks:w.deferConnectionCallbacks,preferPerformance:w.preferPerformance,handlesDynamicScoping:!0};window.ShadyDOM=ShadyDOM;od();var Ud=window.customElements&&window.customElements.nativeHTMLElement||HTMLElement;I(ic.prototype,Td);I(window.Node.prototype,Hd);I(window.Window.prototype,
Gd);I(window.Text.prototype,Id);I(window.Element.prototype,Md);I(window.DocumentFragment.prototype,Kd);I(window.Document.prototype,Nd);window.HTMLSlotElement&&I(window.HTMLSlotElement.prototype,Ld);I(Ud.prototype,Pd);w.w&&(gc(window.Node.prototype),gc(window.Text.prototype),gc(window.DocumentFragment.prototype),gc(window.Element.prototype),gc(Ud.prototype),gc(window.Document.prototype),window.HTMLSlotElement&&gc(window.HTMLSlotElement.prototype));hc();window.ShadowRoot=ic};var Vd=new Set("annotation-xml color-profile font-face font-face-src font-face-uri font-face-format font-face-name missing-glyph".split(" "));function Wd(a){var b=Vd.has(a);a=/^[a-z][.0-9_a-z]*-[\-.0-9_a-z]*$/.test(a);return!b&&a}function J(a){var b=a.isConnected;if(void 0!==b)return b;for(;a&&!(a.__CE_isImportDocument||a instanceof Document);)a=a.parentNode||(window.ShadowRoot&&a instanceof ShadowRoot?a.host:void 0);return!(!a||!(a.__CE_isImportDocument||a instanceof Document))}
function Xd(a,b){for(;b&&b!==a&&!b.nextSibling;)b=b.parentNode;return b&&b!==a?b.nextSibling:null}
function Yd(a,b,c){c=void 0===c?new Set:c;for(var d=a;d;){if(d.nodeType===Node.ELEMENT_NODE){var e=d;b(e);var f=e.localName;if("link"===f&&"import"===e.getAttribute("rel")){d=e.import;if(d instanceof Node&&!c.has(d))for(c.add(d),d=d.firstChild;d;d=d.nextSibling)Yd(d,b,c);d=Xd(a,e);continue}else if("template"===f){d=Xd(a,e);continue}if(e=e.__CE_shadowRoot)for(e=e.firstChild;e;e=e.nextSibling)Yd(e,b,c)}d=d.firstChild?d.firstChild:Xd(a,d)}}function K(a,b,c){a[b]=c};function Zd(){this.a=new Map;this.i=new Map;this.f=[];this.c=!1}function $d(a,b,c){a.a.set(b,c);a.i.set(c.constructorFunction,c)}function ae(a,b){a.c=!0;a.f.push(b)}function be(a,b){a.c&&Yd(b,function(b){return a.b(b)})}Zd.prototype.b=function(a){if(this.c&&!a.__CE_patched){a.__CE_patched=!0;for(var b=0;b<this.f.length;b++)this.f[b](a)}};function L(a,b){var c=[];Yd(b,function(a){return c.push(a)});for(b=0;b<c.length;b++){var d=c[b];1===d.__CE_state?a.connectedCallback(d):ce(a,d)}}
function M(a,b){var c=[];Yd(b,function(a){return c.push(a)});for(b=0;b<c.length;b++){var d=c[b];1===d.__CE_state&&a.disconnectedCallback(d)}}
function O(a,b,c){c=void 0===c?{}:c;var d=c.$a||new Set,e=c.Z||function(b){return ce(a,b)},f=[];Yd(b,function(b){if("link"===b.localName&&"import"===b.getAttribute("rel")){var c=b.import;c instanceof Node&&(c.__CE_isImportDocument=!0,c.__CE_hasRegistry=!0);c&&"complete"===c.readyState?c.__CE_documentLoadHandled=!0:b.addEventListener("load",function(){var c=b.import;if(!c.__CE_documentLoadHandled){c.__CE_documentLoadHandled=!0;var f=new Set(d);f.delete(c);O(a,c,{$a:f,Z:e})}})}else f.push(b)},d);if(a.c)for(b=
0;b<f.length;b++)a.b(f[b]);for(b=0;b<f.length;b++)e(f[b])}
function ce(a,b){if(void 0===b.__CE_state){var c=b.ownerDocument;if(c.defaultView||c.__CE_isImportDocument&&c.__CE_hasRegistry)if(c=a.a.get(b.localName)){c.constructionStack.push(b);var d=c.constructorFunction;try{try{if(new d!==b)throw Error("The custom element constructor did not produce the element being upgraded.");}finally{c.constructionStack.pop()}}catch(h){throw b.__CE_state=2,h;}b.__CE_state=1;b.__CE_definition=c;if(c.attributeChangedCallback)for(c=c.observedAttributes,d=0;d<c.length;d++){var e=
c[d],f=b.getAttribute(e);null!==f&&a.attributeChangedCallback(b,e,null,f,null)}J(b)&&a.connectedCallback(b)}}}Zd.prototype.connectedCallback=function(a){var b=a.__CE_definition;b.connectedCallback&&b.connectedCallback.call(a)};Zd.prototype.disconnectedCallback=function(a){var b=a.__CE_definition;b.disconnectedCallback&&b.disconnectedCallback.call(a)};
Zd.prototype.attributeChangedCallback=function(a,b,c,d,e){var f=a.__CE_definition;f.attributeChangedCallback&&-1<f.observedAttributes.indexOf(b)&&f.attributeChangedCallback.call(a,b,c,d,e)};function de(a){var b=document;this.b=a;this.a=b;this.G=void 0;O(this.b,this.a);"loading"===this.a.readyState&&(this.G=new MutationObserver(this.c.bind(this)),this.G.observe(this.a,{childList:!0,subtree:!0}))}function ee(a){a.G&&a.G.disconnect()}de.prototype.c=function(a){var b=this.a.readyState;"interactive"!==b&&"complete"!==b||ee(this);for(b=0;b<a.length;b++)for(var c=a[b].addedNodes,d=0;d<c.length;d++)O(this.b,c[d])};function fe(){var a=this;this.a=this.j=void 0;this.b=new Promise(function(b){a.a=b;a.j&&b(a.j)})}fe.prototype.resolve=function(a){if(this.j)throw Error("Already resolved.");this.j=a;this.a&&this.a(a)};function P(a){this.c=!1;this.a=a;this.o=new Map;this.f=function(a){return a()};this.b=!1;this.i=[];this.ea=new de(a)}n=P.prototype;
n.ua=function(a,b){var c=this;if(!(b instanceof Function))throw new TypeError("Custom element constructors must be functions.");if(!Wd(a))throw new SyntaxError("The element name '"+a+"' is not valid.");if(this.a.a.get(a))throw Error("A custom element with name '"+a+"' has already been defined.");if(this.c)throw Error("A custom element is already being defined.");this.c=!0;try{var d=function(a){var b=e[a];if(void 0!==b&&!(b instanceof Function))throw Error("The '"+a+"' callback must be a function.");
return b},e=b.prototype;if(!(e instanceof Object))throw new TypeError("The custom element constructor's prototype is not an object.");var f=d("connectedCallback");var h=d("disconnectedCallback");var g=d("adoptedCallback");var k=d("attributeChangedCallback");var l=b.observedAttributes||[]}catch(m){return}finally{this.c=!1}b={localName:a,constructorFunction:b,connectedCallback:f,disconnectedCallback:h,adoptedCallback:g,attributeChangedCallback:k,observedAttributes:l,constructionStack:[]};$d(this.a,
a,b);this.i.push(b);this.b||(this.b=!0,this.f(function(){return ge(c)}))};n.Z=function(a){O(this.a,a)};
function ge(a){if(!1!==a.b){a.b=!1;for(var b=a.i,c=[],d=new Map,e=0;e<b.length;e++)d.set(b[e].localName,[]);O(a.a,document,{Z:function(b){if(void 0===b.__CE_state){var e=b.localName,f=d.get(e);f?f.push(b):a.a.a.get(e)&&c.push(b)}}});for(e=0;e<c.length;e++)ce(a.a,c[e]);for(;0<b.length;){var f=b.shift();e=f.localName;f=d.get(f.localName);for(var h=0;h<f.length;h++)ce(a.a,f[h]);(e=a.o.get(e))&&e.resolve(void 0)}}}n.get=function(a){if(a=this.a.a.get(a))return a.constructorFunction};
n.va=function(a){if(!Wd(a))return Promise.reject(new SyntaxError("'"+a+"' is not a valid custom element name."));var b=this.o.get(a);if(b)return b.b;b=new fe;this.o.set(a,b);this.a.a.get(a)&&!this.i.some(function(b){return b.localName===a})&&b.resolve(void 0);return b.b};n.Ta=function(a){ee(this.ea);var b=this.f;this.f=function(c){return a(function(){return b(c)})}};window.CustomElementRegistry=P;P.prototype.define=P.prototype.ua;P.prototype.upgrade=P.prototype.Z;P.prototype.get=P.prototype.get;
P.prototype.whenDefined=P.prototype.va;P.prototype.polyfillWrapFlushCallback=P.prototype.Ta;var he=window.Document.prototype.createElement,ie=window.Document.prototype.createElementNS,je=window.Document.prototype.importNode,ke=window.Document.prototype.prepend,le=window.Document.prototype.append,me=window.DocumentFragment.prototype.prepend,ne=window.DocumentFragment.prototype.append,oe=window.Node.prototype.cloneNode,pe=window.Node.prototype.appendChild,qe=window.Node.prototype.insertBefore,re=window.Node.prototype.removeChild,se=window.Node.prototype.replaceChild,te=Object.getOwnPropertyDescriptor(window.Node.prototype,
"textContent"),ue=window.Element.prototype.attachShadow,ve=Object.getOwnPropertyDescriptor(window.Element.prototype,"innerHTML"),we=window.Element.prototype.getAttribute,xe=window.Element.prototype.setAttribute,ye=window.Element.prototype.removeAttribute,ze=window.Element.prototype.getAttributeNS,Ae=window.Element.prototype.setAttributeNS,Be=window.Element.prototype.removeAttributeNS,Ce=window.Element.prototype.insertAdjacentElement,De=window.Element.prototype.insertAdjacentHTML,Ee=window.Element.prototype.prepend,
Fe=window.Element.prototype.append,Ge=window.Element.prototype.before,He=window.Element.prototype.after,Ie=window.Element.prototype.replaceWith,Je=window.Element.prototype.remove,Ke=window.HTMLElement,Le=Object.getOwnPropertyDescriptor(window.HTMLElement.prototype,"innerHTML"),Me=window.HTMLElement.prototype.insertAdjacentElement,Ne=window.HTMLElement.prototype.insertAdjacentHTML;var Oe=new function(){};function Pe(){var a=Qe;window.HTMLElement=function(){function b(){var b=this.constructor,d=a.i.get(b);if(!d)throw Error("The custom element being constructed was not registered with `customElements`.");var e=d.constructionStack;if(0===e.length)return e=he.call(document,d.localName),Object.setPrototypeOf(e,b.prototype),e.__CE_state=1,e.__CE_definition=d,a.b(e),e;d=e.length-1;var f=e[d];if(f===Oe)throw Error("The HTMLElement constructor was either called reentrantly for this constructor or called multiple times.");
e[d]=Oe;Object.setPrototypeOf(f,b.prototype);a.b(f);return f}b.prototype=Ke.prototype;Object.defineProperty(b.prototype,"constructor",{writable:!0,configurable:!0,enumerable:!1,value:b});return b}()};function Re(a,b,c){function d(b){return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e]=arguments[e];e=[];for(var f=[],l=0;l<d.length;l++){var m=d[l];m instanceof Element&&J(m)&&f.push(m);if(m instanceof DocumentFragment)for(m=m.firstChild;m;m=m.nextSibling)e.push(m);else e.push(m)}b.apply(this,d);for(d=0;d<f.length;d++)M(a,f[d]);if(J(this))for(d=0;d<e.length;d++)f=e[d],f instanceof Element&&L(a,f)}}void 0!==c.X&&(b.prepend=d(c.X));void 0!==c.append&&(b.append=d(c.append))};function Se(){var a=Qe;K(Document.prototype,"createElement",function(b){if(this.__CE_hasRegistry){var c=a.a.get(b);if(c)return new c.constructorFunction}b=he.call(this,b);a.b(b);return b});K(Document.prototype,"importNode",function(b,c){b=je.call(this,b,!!c);this.__CE_hasRegistry?O(a,b):be(a,b);return b});K(Document.prototype,"createElementNS",function(b,c){if(this.__CE_hasRegistry&&(null===b||"http://www.w3.org/1999/xhtml"===b)){var d=a.a.get(c);if(d)return new d.constructorFunction}b=ie.call(this,
b,c);a.b(b);return b});Re(a,Document.prototype,{X:ke,append:le})};function Te(){function a(a,d){Object.defineProperty(a,"textContent",{enumerable:d.enumerable,configurable:!0,get:d.get,set:function(a){if(this.nodeType===Node.TEXT_NODE)d.set.call(this,a);else{var c=void 0;if(this.firstChild){var e=this.childNodes,g=e.length;if(0<g&&J(this)){c=Array(g);for(var k=0;k<g;k++)c[k]=e[k]}}d.set.call(this,a);if(c)for(a=0;a<c.length;a++)M(b,c[a])}}})}var b=Qe;K(Node.prototype,"insertBefore",function(a,d){if(a instanceof DocumentFragment){var c=Array.prototype.slice.apply(a.childNodes);
a=qe.call(this,a,d);if(J(this))for(d=0;d<c.length;d++)L(b,c[d]);return a}c=J(a);d=qe.call(this,a,d);c&&M(b,a);J(this)&&L(b,a);return d});K(Node.prototype,"appendChild",function(a){if(a instanceof DocumentFragment){var c=Array.prototype.slice.apply(a.childNodes);a=pe.call(this,a);if(J(this))for(var e=0;e<c.length;e++)L(b,c[e]);return a}c=J(a);e=pe.call(this,a);c&&M(b,a);J(this)&&L(b,a);return e});K(Node.prototype,"cloneNode",function(a){a=oe.call(this,!!a);this.ownerDocument.__CE_hasRegistry?O(b,a):
be(b,a);return a});K(Node.prototype,"removeChild",function(a){var c=J(a),e=re.call(this,a);c&&M(b,a);return e});K(Node.prototype,"replaceChild",function(a,d){if(a instanceof DocumentFragment){var c=Array.prototype.slice.apply(a.childNodes);a=se.call(this,a,d);if(J(this))for(M(b,d),d=0;d<c.length;d++)L(b,c[d]);return a}c=J(a);var f=se.call(this,a,d),h=J(this);h&&M(b,d);c&&M(b,a);h&&L(b,a);return f});te&&te.get?a(Node.prototype,te):ae(b,function(b){a(b,{enumerable:!0,configurable:!0,get:function(){for(var a=
[],b=0;b<this.childNodes.length;b++)a.push(this.childNodes[b].textContent);return a.join("")},set:function(a){for(;this.firstChild;)re.call(this,this.firstChild);pe.call(this,document.createTextNode(a))}})})};function Ue(a){function b(b){return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e]=arguments[e];e=[];for(var g=[],k=0;k<d.length;k++){var l=d[k];l instanceof Element&&J(l)&&g.push(l);if(l instanceof DocumentFragment)for(l=l.firstChild;l;l=l.nextSibling)e.push(l);else e.push(l)}b.apply(this,d);for(d=0;d<g.length;d++)M(a,g[d]);if(J(this))for(d=0;d<e.length;d++)g=e[d],g instanceof Element&&L(a,g)}}var c=Element.prototype;void 0!==Ge&&(c.before=b(Ge));void 0!==Ge&&(c.after=b(He));void 0!==Ie&&
K(c,"replaceWith",function(b){for(var c=[],d=0;d<arguments.length;++d)c[d]=arguments[d];d=[];for(var h=[],g=0;g<c.length;g++){var k=c[g];k instanceof Element&&J(k)&&h.push(k);if(k instanceof DocumentFragment)for(k=k.firstChild;k;k=k.nextSibling)d.push(k);else d.push(k)}g=J(this);Ie.apply(this,c);for(c=0;c<h.length;c++)M(a,h[c]);if(g)for(M(a,this),c=0;c<d.length;c++)h=d[c],h instanceof Element&&L(a,h)});void 0!==Je&&K(c,"remove",function(){var b=J(this);Je.call(this);b&&M(a,this)})};function Ve(){function a(a,b){Object.defineProperty(a,"innerHTML",{enumerable:b.enumerable,configurable:!0,get:b.get,set:function(a){var c=this,e=void 0;J(this)&&(e=[],Yd(this,function(a){a!==c&&e.push(a)}));b.set.call(this,a);if(e)for(var f=0;f<e.length;f++){var h=e[f];1===h.__CE_state&&d.disconnectedCallback(h)}this.ownerDocument.__CE_hasRegistry?O(d,this):be(d,this);return a}})}function b(a,b){K(a,"insertAdjacentElement",function(a,c){var e=J(c);a=b.call(this,a,c);e&&M(d,c);J(a)&&L(d,c);return a})}
function c(a,b){function c(a,b){for(var c=[];a!==b;a=a.nextSibling)c.push(a);for(b=0;b<c.length;b++)O(d,c[b])}K(a,"insertAdjacentHTML",function(a,d){a=a.toLowerCase();if("beforebegin"===a){var e=this.previousSibling;b.call(this,a,d);c(e||this.parentNode.firstChild,this)}else if("afterbegin"===a)e=this.firstChild,b.call(this,a,d),c(this.firstChild,e);else if("beforeend"===a)e=this.lastChild,b.call(this,a,d),c(e||this.firstChild,null);else if("afterend"===a)e=this.nextSibling,b.call(this,a,d),c(this.nextSibling,
e);else throw new SyntaxError("The value provided ("+String(a)+") is not one of 'beforebegin', 'afterbegin', 'beforeend', or 'afterend'.");})}var d=Qe;ue&&K(Element.prototype,"attachShadow",function(a){return this.__CE_shadowRoot=a=ue.call(this,a)});ve&&ve.get?a(Element.prototype,ve):Le&&Le.get?a(HTMLElement.prototype,Le):ae(d,function(b){a(b,{enumerable:!0,configurable:!0,get:function(){return oe.call(this,!0).innerHTML},set:function(a){var b="template"===this.localName,c=b?this.content:this,d=ie.call(document,
this.namespaceURI,this.localName);for(d.innerHTML=a;0<c.childNodes.length;)re.call(c,c.childNodes[0]);for(a=b?d.content:d;0<a.childNodes.length;)pe.call(c,a.childNodes[0])}})});K(Element.prototype,"setAttribute",function(a,b){if(1!==this.__CE_state)return xe.call(this,a,b);var c=we.call(this,a);xe.call(this,a,b);b=we.call(this,a);d.attributeChangedCallback(this,a,c,b,null)});K(Element.prototype,"setAttributeNS",function(a,b,c){if(1!==this.__CE_state)return Ae.call(this,a,b,c);var e=ze.call(this,a,
b);Ae.call(this,a,b,c);c=ze.call(this,a,b);d.attributeChangedCallback(this,b,e,c,a)});K(Element.prototype,"removeAttribute",function(a){if(1!==this.__CE_state)return ye.call(this,a);var b=we.call(this,a);ye.call(this,a);null!==b&&d.attributeChangedCallback(this,a,b,null,null)});K(Element.prototype,"removeAttributeNS",function(a,b){if(1!==this.__CE_state)return Be.call(this,a,b);var c=ze.call(this,a,b);Be.call(this,a,b);var e=ze.call(this,a,b);c!==e&&d.attributeChangedCallback(this,b,c,e,a)});Me?b(HTMLElement.prototype,
Me):Ce?b(Element.prototype,Ce):console.warn("Custom Elements: `Element#insertAdjacentElement` was not patched.");Ne?c(HTMLElement.prototype,Ne):De?c(Element.prototype,De):console.warn("Custom Elements: `Element#insertAdjacentHTML` was not patched.");Re(d,Element.prototype,{X:Ee,append:Fe});Ue(d)};var We=window.customElements;if(!We||We.forcePolyfill||"function"!=typeof We.define||"function"!=typeof We.get){var Qe=new Zd;Pe();Se();Re(Qe,DocumentFragment.prototype,{X:me,append:ne});Te();Ve();document.__CE_hasRegistry=!0;var customElements=new P(Qe);Object.defineProperty(window,"customElements",{configurable:!0,enumerable:!0,value:customElements})};function Xe(){this.end=this.start=0;this.rules=this.parent=this.previous=null;this.cssText=this.parsedCssText="";this.atRule=!1;this.type=0;this.parsedSelector=this.selector=this.keyframesName=""}
function Ye(a){a=a.replace(Ze,"").replace($e,"");var b=af,c=a,d=new Xe;d.start=0;d.end=c.length;for(var e=d,f=0,h=c.length;f<h;f++)if("{"===c[f]){e.rules||(e.rules=[]);var g=e,k=g.rules[g.rules.length-1]||null;e=new Xe;e.start=f+1;e.parent=g;e.previous=k;g.rules.push(e)}else"}"===c[f]&&(e.end=f+1,e=e.parent||d);return b(d,a)}
function af(a,b){var c=b.substring(a.start,a.end-1);a.parsedCssText=a.cssText=c.trim();a.parent&&(c=b.substring(a.previous?a.previous.end:a.parent.start,a.start-1),c=bf(c),c=c.replace(hf," "),c=c.substring(c.lastIndexOf(";")+1),c=a.parsedSelector=a.selector=c.trim(),a.atRule=0===c.indexOf("@"),a.atRule?0===c.indexOf("@media")?a.type=jf:c.match(kf)&&(a.type=lf,a.keyframesName=a.selector.split(hf).pop()):a.type=0===c.indexOf("--")?mf:nf);if(c=a.rules)for(var d=0,e=c.length,f=void 0;d<e&&(f=c[d]);d++)af(f,
b);return a}function bf(a){return a.replace(/\\([0-9a-f]{1,6})\s/gi,function(a,c){a=c;for(c=6-a.length;c--;)a="0"+a;return"\\"+a})}
function of(a,b,c){c=void 0===c?"":c;var d="";if(a.cssText||a.rules){var e=a.rules,f;if(f=e)f=e[0],f=!(f&&f.selector&&0===f.selector.indexOf("--"));if(f){f=0;for(var h=e.length,g=void 0;f<h&&(g=e[f]);f++)d=of(g,b,d)}else b?b=a.cssText:(b=a.cssText,b=b.replace(pf,"").replace(qf,""),b=b.replace(rf,"").replace(sf,"")),(d=b.trim())&&(d="  "+d+"\n")}d&&(a.selector&&(c+=a.selector+" {\n"),c+=d,a.selector&&(c+="}\n\n"));return c}
var nf=1,lf=7,jf=4,mf=1E3,Ze=/\/\*[^*]*\*+([^/*][^*]*\*+)*\//gim,$e=/@import[^;]*;/gim,pf=/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?(?:[;\n]|$)/gim,qf=/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?{[^}]*?}(?:[;\n]|$)?/gim,rf=/@apply\s*\(?[^);]*\)?\s*(?:[;\n]|$)?/gim,sf=/[^;:]*?:[^;]*?var\([^;]*\)(?:[;\n]|$)?/gim,kf=/^@[^\s]*keyframes/,hf=/\s+/g;var R=!(window.ShadyDOM&&window.ShadyDOM.inUse),tf;function uf(a){tf=a&&a.shimcssproperties?!1:R||!(navigator.userAgent.match(/AppleWebKit\/601|Edge\/15/)||!window.CSS||!CSS.supports||!CSS.supports("box-shadow","0 0 0 var(--foo)"))}var vf;window.ShadyCSS&&void 0!==window.ShadyCSS.cssBuild&&(vf=window.ShadyCSS.cssBuild);window.ShadyCSS&&void 0!==window.ShadyCSS.nativeCss?tf=window.ShadyCSS.nativeCss:window.ShadyCSS?(uf(window.ShadyCSS),window.ShadyCSS=void 0):uf(window.WebComponents&&window.WebComponents.flags);
var S=tf,wf=vf;var xf=/(?:^|[;\s{]\s*)(--[\w-]*?)\s*:\s*(?:((?:'(?:\\'|.)*?'|"(?:\\"|.)*?"|\([^)]*?\)|[^};{])+)|\{([^}]*)\}(?:(?=[;\s}])|$))/gi,yf=/(?:^|\W+)@apply\s*\(?([^);\n]*)\)?/gi,zf=/(--[\w-]+)\s*([:,;)]|$)/gi,Af=/(animation\s*:)|(animation-name\s*:)/,Bf=/@media\s(.*)/,Cf=/\{[^}]*\}/g;var Df=new Set;function Ef(a,b){if(!a)return"";"string"===typeof a&&(a=Ye(a));b&&Ff(a,b);return of(a,S)}function Gf(a){!a.__cssRules&&a.textContent&&(a.__cssRules=Ye(a.textContent));return a.__cssRules||null}function Hf(a){return!!a.parent&&a.parent.type===lf}function Ff(a,b,c,d){if(a){var e=!1,f=a.type;if(d&&f===jf){var h=a.selector.match(Bf);h&&(window.matchMedia(h[1]).matches||(e=!0))}f===nf?b(a):c&&f===lf?c(a):f===mf&&(e=!0);if((a=a.rules)&&!e)for(e=0,f=a.length,h=void 0;e<f&&(h=a[e]);e++)Ff(h,b,c,d)}}
function If(a,b,c,d){var e=document.createElement("style");b&&e.setAttribute("scope",b);e.textContent=a;Jf(e,c,d);return e}var Kf=null;function Lf(a){a=document.createComment(" Shady DOM styles for "+a+" ");var b=document.head;b.insertBefore(a,(Kf?Kf.nextSibling:null)||b.firstChild);return Kf=a}function Jf(a,b,c){b=b||document.head;b.insertBefore(a,c&&c.nextSibling||b.firstChild);Kf?a.compareDocumentPosition(Kf)===Node.DOCUMENT_POSITION_PRECEDING&&(Kf=a):Kf=a}
function Mf(a,b){for(var c=0,d=a.length;b<d;b++)if("("===a[b])c++;else if(")"===a[b]&&0===--c)return b;return-1}function Nf(a,b){var c=a.indexOf("var(");if(-1===c)return b(a,"","","");var d=Mf(a,c+3),e=a.substring(c+4,d);c=a.substring(0,c);a=Nf(a.substring(d+1),b);d=e.indexOf(",");return-1===d?b(c,e.trim(),"",a):b(c,e.substring(0,d).trim(),e.substring(d+1).trim(),a)}function Of(a,b){R?a.setAttribute("class",b):window.ShadyDOM.nativeMethods.setAttribute.call(a,"class",b)}
function Pf(a){var b=a.localName,c="";b?-1<b.indexOf("-")||(c=b,b=a.getAttribute&&a.getAttribute("is")||""):(b=a.is,c=a.extends);return{is:b,O:c}}function Qf(a){for(var b=[],c="",d=0;0<=d&&d<a.length;d++)if("("===a[d]){var e=Mf(a,d);c+=a.slice(d,e+1);d=e}else","===a[d]?(b.push(c),c=""):c+=a[d];c&&b.push(c);return b}
function Rf(a){if(void 0!==wf)return wf;if(void 0===a.__cssBuild){var b=a.getAttribute("css-build");if(b)a.__cssBuild=b;else{a:{b="template"===a.localName?a.content.firstChild:a.firstChild;if(b instanceof Comment&&(b=b.textContent.trim().split(":"),"css-build"===b[0])){b=b[1];break a}b=""}if(""!==b){var c="template"===a.localName?a.content.firstChild:a.firstChild;c.parentNode.removeChild(c)}a.__cssBuild=b}}return a.__cssBuild||""}
function Sf(a){a=void 0===a?"":a;return""!==a&&S?R?"shadow"===a:"shady"===a:!1};function Tf(){}function Uf(a,b){Vf(U,a,function(a){Wf(a,b||"")})}function Vf(a,b,c){b.nodeType===Node.ELEMENT_NODE&&c(b);var d;"template"===b.localName?d=(b.content||b._content||b).childNodes:d=b.children||b.childNodes;if(d)for(b=0;b<d.length;b++)Vf(a,d[b],c)}
function Wf(a,b,c){if(b)if(a.classList)c?(a.classList.remove("style-scope"),a.classList.remove(b)):(a.classList.add("style-scope"),a.classList.add(b));else if(a.getAttribute){var d=a.getAttribute("class");c?d&&(b=d.replace("style-scope","").replace(b,""),Of(a,b)):Of(a,(d?d+" ":"")+"style-scope "+b)}}function Xf(a,b,c){Vf(U,a,function(a){Wf(a,b,!0);Wf(a,c)})}function Yf(a,b){Vf(U,a,function(a){Wf(a,b||"",!0)})}
function Zf(a,b,c,d,e){var f=U;e=void 0===e?"":e;""===e&&(R||"shady"===(void 0===d?"":d)?e=Ef(b,c):(a=Pf(a),e=$f(f,b,a.is,a.O,c)+"\n\n"));return e.trim()}function $f(a,b,c,d,e){var f=ag(c,d);c=c?"."+c:"";return Ef(b,function(b){b.c||(b.selector=b.m=bg(a,b,a.b,c,f),b.c=!0);e&&e(b,c,f)})}function ag(a,b){return b?"[is="+a+"]":a}
function bg(a,b,c,d,e){var f=Qf(b.selector);if(!Hf(b)){b=0;for(var h=f.length,g=void 0;b<h&&(g=f[b]);b++)f[b]=c.call(a,g,d,e)}return f.filter(function(a){return!!a}).join(",")}function cg(a){return a.replace(dg,function(a,c,d){-1<d.indexOf("+")?d=d.replace(/\+/g,"___"):-1<d.indexOf("___")&&(d=d.replace(/___/g,"+"));return":"+c+"("+d+")"})}
function eg(a){for(var b=[],c;c=a.match(fg);){var d=c.index,e=Mf(a,d);if(-1===e)throw Error(c.input+" selector missing ')'");c=a.slice(d,e+1);a=a.replace(c,"\ue000");b.push(c)}return{ha:a,matches:b}}function gg(a,b){var c=a.split("\ue000");return b.reduce(function(a,b,f){return a+b+c[f+1]},c[0])}
Tf.prototype.b=function(a,b,c){var d=!1;a=a.trim();var e=dg.test(a);e&&(a=a.replace(dg,function(a,b,c){return":"+b+"("+c.replace(/\s/g,"")+")"}),a=cg(a));var f=fg.test(a);if(f){var h=eg(a);a=h.ha;h=h.matches}a=a.replace(hg,":host $1");a=a.replace(ig,function(a,e,f){d||(a=jg(f,e,b,c),d=d||a.stop,e=a.Ga,f=a.value);return e+f});f&&(a=gg(a,h));e&&(a=cg(a));return a};
function jg(a,b,c,d){var e=a.indexOf("::slotted");0<=a.indexOf(":host")?a=kg(a,d):0!==e&&(a=c?lg(a,c):a);c=!1;0<=e&&(b="",c=!0);if(c){var f=!0;c&&(a=a.replace(mg,function(a,b){return" > "+b}))}a=a.replace(ng,function(a,b,c){return'[dir="'+c+'"] '+b+", "+b+'[dir="'+c+'"]'});return{value:a,Ga:b,stop:f}}
function lg(a,b){a=a.split(/(\[.+?\])/);for(var c=[],d=0;d<a.length;d++)if(1===d%2)c.push(a[d]);else{var e=a[d];if(""!==e||d!==a.length-1)e=e.split(":"),e[0]+=b,c.push(e.join(":"))}return c.join("")}function kg(a,b){var c=a.match(og);return(c=c&&c[2].trim()||"")?c[0].match(pg)?a.replace(og,function(a,c,f){return b+f}):c.split(pg)[0]===b?c:"should_not_match":a.replace(":host",b)}function qg(a){":root"===a.selector&&(a.selector="html")}
Tf.prototype.c=function(a){return a.match(":host")?"":a.match("::slotted")?this.b(a,":not(.style-scope)"):lg(a.trim(),":not(.style-scope)")};q.Object.defineProperties(Tf.prototype,{a:{configurable:!0,enumerable:!0,get:function(){return"style-scope"}}});
var dg=/:(nth[-\w]+)\(([^)]+)\)/,ig=/(^|[\s>+~]+)((?:\[.+?\]|[^\s>+~=[])+)/g,pg=/[[.:#*]/,hg=/^(::slotted)/,og=/(:host)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,mg=/(?:::slotted)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,ng=/(.*):dir\((?:(ltr|rtl))\)/,fg=/:(?:matches|any|-(?:webkit|moz)-any)/,U=new Tf;function rg(a,b,c,d,e){this.B=a||null;this.b=b||null;this.c=c||[];this.J=null;this.cssBuild=e||"";this.O=d||"";this.a=this.u=this.F=null}function V(a){return a?a.__styleInfo:null}function sg(a,b){return a.__styleInfo=b}rg.prototype.f=function(){return this.B};rg.prototype._getStyleRules=rg.prototype.f;function tg(a){var b=this.matches||this.matchesSelector||this.mozMatchesSelector||this.msMatchesSelector||this.oMatchesSelector||this.webkitMatchesSelector;return b&&b.call(this,a)}var ug=navigator.userAgent.match("Trident");function vg(){}function wg(a){var b={},c=[],d=0;Ff(a,function(a){xg(a);a.index=d++;a=a.l.cssText;for(var c;c=zf.exec(a);){var e=c[1];":"!==c[2]&&(b[e]=!0)}},function(a){c.push(a)});a.b=c;a=[];for(var e in b)a.push(e);return a}
function xg(a){if(!a.l){var b={},c={};yg(a,c)&&(b.A=c,a.rules=null);b.cssText=a.parsedCssText.replace(Cf,"").replace(xf,"");a.l=b}}function yg(a,b){var c=a.l;if(c){if(c.A)return Object.assign(b,c.A),!0}else{c=a.parsedCssText;for(var d;a=xf.exec(c);){d=(a[2]||a[3]).trim();if("inherit"!==d||"unset"!==d)b[a[1].trim()]=d;d=!0}return d}}
function zg(a,b,c){b&&(b=0<=b.indexOf(";")?Ag(a,b,c):Nf(b,function(b,e,f,h){if(!e)return b+h;(e=zg(a,c[e],c))&&"initial"!==e?"apply-shim-inherit"===e&&(e="inherit"):e=zg(a,c[f]||f,c)||f;return b+(e||"")+h}));return b&&b.trim()||""}
function Ag(a,b,c){b=b.split(";");for(var d=0,e,f;d<b.length;d++)if(e=b[d]){yf.lastIndex=0;if(f=yf.exec(e))e=zg(a,c[f[1]],c);else if(f=e.indexOf(":"),-1!==f){var h=e.substring(f);h=h.trim();h=zg(a,h,c)||h;e=e.substring(0,f)+h}b[d]=e&&e.lastIndexOf(";")===e.length-1?e.slice(0,-1):e||""}return b.join(";")}
function Bg(a,b){var c={},d=[];Ff(a,function(a){a.l||xg(a);var e=a.m||a.parsedSelector;b&&a.l.A&&e&&tg.call(b,e)&&(yg(a,c),a=a.index,e=parseInt(a/32,10),d[e]=(d[e]||0)|1<<a%32)},null,!0);return{A:c,key:d}}
function Cg(a,b,c,d){b.l||xg(b);if(b.l.A){var e=Pf(a);a=e.is;e=e.O;e=a?ag(a,e):"html";var f=b.parsedSelector,h=":host > *"===f||"html"===f,g=0===f.indexOf(":host")&&!h;"shady"===c&&(h=f===e+" > *."+e||-1!==f.indexOf("html"),g=!h&&0===f.indexOf(e));if(h||g)c=e,g&&(b.m||(b.m=bg(U,b,U.b,a?"."+a:"",e)),c=b.m||e),d({ha:c,Ma:g,nb:h})}}function Dg(a,b,c){var d={},e={};Ff(b,function(b){Cg(a,b,c,function(c){tg.call(a._element||a,c.ha)&&(c.Ma?yg(b,d):yg(b,e))})},null,!0);return{Ua:e,La:d}}
function Eg(a,b,c,d){var e=Pf(b),f=ag(e.is,e.O),h=new RegExp("(?:^|[^.#[:])"+(b.extends?"\\"+f.slice(0,-1)+"\\]":f)+"($|[.:[\\s>+~])"),g=V(b);e=g.B;g=g.cssBuild;var k=Fg(e,d);return Zf(b,e,function(b){var e="";b.l||xg(b);b.l.cssText&&(e=Ag(a,b.l.cssText,c));b.cssText=e;if(!R&&!Hf(b)&&b.cssText){var g=e=b.cssText;null==b.oa&&(b.oa=Af.test(e));if(b.oa)if(null==b.W){b.W=[];for(var l in k)g=k[l],g=g(e),e!==g&&(e=g,b.W.push(l))}else{for(l=0;l<b.W.length;++l)g=k[b.W[l]],e=g(e);g=e}b.cssText=g;b.m=b.m||
b.selector;e="."+d;l=Qf(b.m);g=0;for(var N=l.length,Y=void 0;g<N&&(Y=l[g]);g++)l[g]=Y.match(h)?Y.replace(f,e):e+" "+Y;b.selector=l.join(",")}},g)}function Fg(a,b){a=a.b;var c={};if(!R&&a)for(var d=0,e=a[d];d<a.length;e=a[++d]){var f=e,h=b;f.f=new RegExp("\\b"+f.keyframesName+"(?!\\B|-)","g");f.a=f.keyframesName+"-"+h;f.m=f.m||f.selector;f.selector=f.m.replace(f.keyframesName,f.a);c[e.keyframesName]=Gg(e)}return c}function Gg(a){return function(b){return b.replace(a.f,a.a)}}
function Hg(a,b){var c=Ig,d=Gf(a);a.textContent=Ef(d,function(a){var d=a.cssText=a.parsedCssText;a.l&&a.l.cssText&&(d=d.replace(pf,"").replace(qf,""),a.cssText=Ag(c,d,b))})}q.Object.defineProperties(vg.prototype,{a:{configurable:!0,enumerable:!0,get:function(){return"x-scope"}}});var Ig=new vg;var Jg={},Kg=window.customElements;if(Kg&&!R){var Lg=Kg.define;Kg.define=function(a,b,c){Jg[a]||(Jg[a]=Lf(a));Lg.call(Kg,a,b,c)}};function Mg(){this.cache={}}Mg.prototype.store=function(a,b,c,d){var e=this.cache[a]||[];e.push({A:b,styleElement:c,u:d});100<e.length&&e.shift();this.cache[a]=e};Mg.prototype.fetch=function(a,b,c){if(a=this.cache[a])for(var d=a.length-1;0<=d;d--){var e=a[d],f;a:{for(f=0;f<c.length;f++){var h=c[f];if(e.A[h]!==b[h]){f=!1;break a}}f=!0}if(f)return e}};function Ng(){}var Og=new RegExp(U.a+"\\s*([^\\s]*)");function Pg(a){return(a=(a.classList&&a.classList.value?a.classList.value:a.getAttribute("class")||"").match(Og))?a[1]:""}function Qg(a){var b=a.getRootNode();return b===a||b===a.ownerDocument?"":(a=b.host)?Pf(a).is:""}
function Rg(a){for(var b=0;b<a.length;b++){var c=a[b];if(c.target!==document.documentElement&&c.target!==document.head)for(var d=0;d<c.addedNodes.length;d++){var e=c.addedNodes[d];if(e.nodeType===Node.ELEMENT_NODE){var f=e.getRootNode(),h=Pg(e);if(h&&f===e.ownerDocument&&("style"!==e.localName&&"template"!==e.localName||""===Rf(e)))Yf(e,h);else if(f instanceof ShadowRoot)for(f=Qg(e),f!==h&&Xf(e,h,f),e=window.ShadyDOM.nativeMethods.querySelectorAll.call(e,":not(."+U.a+")"),h=0;h<e.length;h++){f=e[h];
var g=Qg(f);g&&Wf(f,g)}}}}}
if(!(R||window.ShadyDOM&&window.ShadyDOM.handlesDynamicScoping)){var Sg=new MutationObserver(Rg),Tg=function(a){Sg.observe(a,{childList:!0,subtree:!0})};if(window.customElements&&!window.customElements.polyfillWrapFlushCallback)Tg(document);else{var Ug=function(){Tg(document.body)};window.HTMLImports?window.HTMLImports.whenReady(Ug):requestAnimationFrame(function(){if("loading"===document.readyState){var a=function(){Ug();document.removeEventListener("readystatechange",a)};document.addEventListener("readystatechange",
a)}else Ug()})}Ng=function(){Rg(Sg.takeRecords())}}var Vg=Ng;var Wg={};var Xg=Promise.resolve();function Yg(a){if(a=Wg[a])a._applyShimCurrentVersion=a._applyShimCurrentVersion||0,a._applyShimValidatingVersion=a._applyShimValidatingVersion||0,a._applyShimNextVersion=(a._applyShimNextVersion||0)+1}function Zg(a){return a._applyShimCurrentVersion===a._applyShimNextVersion}function $g(a){a._applyShimValidatingVersion=a._applyShimNextVersion;a._validating||(a._validating=!0,Xg.then(function(){a._applyShimCurrentVersion=a._applyShimNextVersion;a._validating=!1}))};var ah=new Mg;function W(){this.o={};this.c=document.documentElement;var a=new Xe;a.rules=[];this.f=sg(this.c,new rg(a));this.i=!1;this.b=this.a=null}n=W.prototype;n.flush=function(){Vg()};n.Ja=function(a){return Gf(a)};n.Ya=function(a){return Ef(a)};n.prepareTemplate=function(a,b,c){this.prepareTemplateDom(a,b);this.prepareTemplateStyles(a,b,c)};
n.prepareTemplateStyles=function(a,b,c){if(!a._prepared){R||Jg[b]||(Jg[b]=Lf(b));a._prepared=!0;a.name=b;a.extends=c;Wg[b]=a;var d=Rf(a),e=Sf(d);c={is:b,extends:c};var f=[];for(var h=a.content.querySelectorAll("style"),g=0;g<h.length;g++){var k=h[g];if(k.hasAttribute("shady-unscoped")){if(!R){var l=k.textContent;Df.has(l)||(Df.add(l),l=k.cloneNode(!0),document.head.appendChild(l));k.parentNode.removeChild(k)}}else f.push(k.textContent),k.parentNode.removeChild(k)}f=f.join("").trim();bh(this);if(!e){if(h=
!d)h=yf.test(f)||xf.test(f),yf.lastIndex=0,xf.lastIndex=0;g=Ye(f);h&&S&&this.a&&this.a.transformRules(g,b);a._styleAst=g}h=[];S||(h=wg(a._styleAst));if(!h.length||S)g=R?a.content:null,b=Jg[b]||null,d=Zf(c,a._styleAst,null,d,e?f:""),d=d.length?If(d,c.is,g,b):null,a._style=d;a.a=h}};n.prepareTemplateDom=function(a,b){var c=Rf(a);R||"shady"===c||a._domPrepared||(a._domPrepared=!0,Uf(a.content,b))};
function ch(a){!a.b&&window.ShadyCSS&&window.ShadyCSS.CustomStyleInterface&&(a.b=window.ShadyCSS.CustomStyleInterface,a.b.transformCallback=function(b){a.sa(b)},a.b.validateCallback=function(){requestAnimationFrame(function(){(a.b.enqueued||a.i)&&a.flushCustomStyles()})})}function bh(a){!a.a&&window.ShadyCSS&&window.ShadyCSS.ApplyShim&&(a.a=window.ShadyCSS.ApplyShim,a.a.invalidCallback=Yg);ch(a)}
n.flushCustomStyles=function(){bh(this);if(this.b){var a=this.b.processStyles();if(this.b.enqueued&&!Sf(this.f.cssBuild)){if(S){if(!this.f.cssBuild)for(var b=0;b<a.length;b++){var c=this.b.getStyleForCustomStyle(a[b]);if(c&&S&&this.a){var d=Gf(c);bh(this);this.a.transformRules(d);c.textContent=Ef(d)}}}else{dh(this,this.c,this.f);for(b=0;b<a.length;b++)(c=this.b.getStyleForCustomStyle(a[b]))&&Hg(c,this.f.F);this.i&&this.styleDocument()}this.b.enqueued=!1}}};
n.styleElement=function(a,b){var c=V(a);if(!c){var d=Pf(a);c=d.is;d=d.O;var e=Jg[c]||null;c=Wg[c];if(c){var f=c._styleAst;var h=c.a;var g=Rf(c)}f=new rg(f,e,h,d,g);c&&sg(a,f);c=f}a!==this.c&&(this.i=!0);b&&(c.J=c.J||{},Object.assign(c.J,b));if(S){b=c;f=Pf(a).is;if(b.J){h=b.J;for(var k in h)null===k?a.style.removeProperty(k):a.style.setProperty(k,h[k])}if(!(!(k=Wg[f])&&a!==this.c||k&&""!==Rf(k))&&k&&k._style&&!Zg(k)){if(Zg(k)||k._applyShimValidatingVersion!==k._applyShimNextVersion)bh(this),this.a&&
this.a.transformRules(k._styleAst,f),k._style.textContent=Zf(a,b.B),$g(k);R&&(f=a.shadowRoot)&&(f=f.querySelector("style"))&&(f.textContent=Zf(a,b.B));b.B=k._styleAst}}else if(k=c,this.flush(),dh(this,a,k),k.c&&k.c.length){b=Pf(a).is;c=(f=ah.fetch(b,k.F,k.c))?f.styleElement:null;h=k.u;(g=f&&f.u)||(g=this.o[b]=(this.o[b]||0)+1,g=b+"-"+g);k.u=g;g=k.u;d=Ig;d=c?c.textContent||"":Eg(d,a,k.F,g);e=V(a);var l=e.a;l&&!R&&l!==c&&(l._useCount--,0>=l._useCount&&l.parentNode&&l.parentNode.removeChild(l));R?e.a?
(e.a.textContent=d,c=e.a):d&&(c=If(d,g,a.shadowRoot,e.b)):c?c.parentNode||(ug&&-1<d.indexOf("@media")&&(c.textContent=d),Jf(c,null,e.b)):d&&(c=If(d,g,null,e.b));c&&(c._useCount=c._useCount||0,e.a!=c&&c._useCount++,e.a=c);g=c;R||(c=k.u,e=d=a.getAttribute("class")||"",h&&(e=d.replace(new RegExp("\\s*x-scope\\s*"+h+"\\s*","g")," ")),e+=(e?" ":"")+"x-scope "+c,d!==e&&Of(a,e));f||ah.store(b,k.F,g,k.u)}};function eh(a,b){return(b=b.getRootNode().host)?V(b)?b:eh(a,b):a.c}
function dh(a,b,c){a=eh(a,b);var d=V(a);a=Object.create(d.F||null);var e=Dg(b,c.B,c.cssBuild);b=Bg(d.B,b).A;Object.assign(a,e.La,b,e.Ua);b=c.J;for(var f in b)if((e=b[f])||0===e)a[f]=e;f=Ig;b=Object.getOwnPropertyNames(a);for(e=0;e<b.length;e++)d=b[e],a[d]=zg(f,a[d],a);c.F=a}n.styleDocument=function(a){this.styleSubtree(this.c,a)};
n.styleSubtree=function(a,b){var c=a.shadowRoot;(c||a===this.c)&&this.styleElement(a,b);if(b=c&&(c.children||c.childNodes))for(a=0;a<b.length;a++)this.styleSubtree(b[a]);else if(a=a.children||a.childNodes)for(b=0;b<a.length;b++)this.styleSubtree(a[b])};
n.sa=function(a){var b=this,c=Rf(a);c!==this.f.cssBuild&&(this.f.cssBuild=c);if(!Sf(c)){var d=Gf(a);Ff(d,function(a){if(R)qg(a);else{var d=U;a.selector=a.parsedSelector;qg(a);a.selector=a.m=bg(d,a,d.c,void 0,void 0)}S&&""===c&&(bh(b),b.a&&b.a.transformRule(a))});S?a.textContent=Ef(d):this.f.B.rules.push(d)}};n.getComputedStyleValue=function(a,b){var c;S||(c=(V(a)||V(eh(this,a))).F[b]);return(c=c||window.getComputedStyle(a).getPropertyValue(b))?c.trim():""};
n.Xa=function(a,b){var c=a.getRootNode();b=b?b.split(/\s/):[];c=c.host&&c.host.localName;if(!c){var d=a.getAttribute("class");if(d){d=d.split(/\s/);for(var e=0;e<d.length;e++)if(d[e]===U.a){c=d[e+1];break}}}c&&b.push(U.a,c);S||(c=V(a))&&c.u&&b.push(Ig.a,c.u);Of(a,b.join(" "))};n.Fa=function(a){return V(a)};n.Wa=function(a,b){Wf(a,b)};n.Za=function(a,b){Wf(a,b,!0)};n.Va=function(a){return Qg(a)};n.Ha=function(a){return Pg(a)};W.prototype.flush=W.prototype.flush;W.prototype.prepareTemplate=W.prototype.prepareTemplate;
W.prototype.styleElement=W.prototype.styleElement;W.prototype.styleDocument=W.prototype.styleDocument;W.prototype.styleSubtree=W.prototype.styleSubtree;W.prototype.getComputedStyleValue=W.prototype.getComputedStyleValue;W.prototype.setElementClass=W.prototype.Xa;W.prototype._styleInfoForNode=W.prototype.Fa;W.prototype.transformCustomStyleForDocument=W.prototype.sa;W.prototype.getStyleAst=W.prototype.Ja;W.prototype.styleAstToString=W.prototype.Ya;W.prototype.flushCustomStyles=W.prototype.flushCustomStyles;
W.prototype.scopeNode=W.prototype.Wa;W.prototype.unscopeNode=W.prototype.Za;W.prototype.scopeForNode=W.prototype.Va;W.prototype.currentScopeForNode=W.prototype.Ha;Object.defineProperties(W.prototype,{nativeShadow:{get:function(){return R}},nativeCss:{get:function(){return S}}});var X=new W,fh,gh;window.ShadyCSS&&(fh=window.ShadyCSS.ApplyShim,gh=window.ShadyCSS.CustomStyleInterface);
window.ShadyCSS={ScopingShim:X,prepareTemplate:function(a,b,c){X.flushCustomStyles();X.prepareTemplate(a,b,c)},prepareTemplateDom:function(a,b){X.prepareTemplateDom(a,b)},prepareTemplateStyles:function(a,b,c){X.flushCustomStyles();X.prepareTemplateStyles(a,b,c)},styleSubtree:function(a,b){X.flushCustomStyles();X.styleSubtree(a,b)},styleElement:function(a){X.flushCustomStyles();X.styleElement(a)},styleDocument:function(a){X.flushCustomStyles();X.styleDocument(a)},flushCustomStyles:function(){X.flushCustomStyles()},
getComputedStyleValue:function(a,b){return X.getComputedStyleValue(a,b)},nativeCss:S,nativeShadow:R,cssBuild:wf};fh&&(window.ShadyCSS.ApplyShim=fh);gh&&(window.ShadyCSS.CustomStyleInterface=gh);var hh=window.customElements,ih=window.HTMLImports,jh=window.HTMLTemplateElement;window.WebComponents=window.WebComponents||{};if(hh&&hh.polyfillWrapFlushCallback){var kh,lh=function(){if(kh){jh.C&&jh.C(window.document);var a=kh;kh=null;a();return!0}},mh=ih.whenReady;hh.polyfillWrapFlushCallback(function(a){kh=a;mh(lh)});ih.whenReady=function(a){mh(function(){lh()?ih.whenReady(a):a()})}}
ih.whenReady(function(){requestAnimationFrame(function(){window.WebComponents.ready=!0;document.dispatchEvent(new CustomEvent("WebComponentsReady",{bubbles:!0}))})});var nh=document.createElement("style");nh.textContent="body {transition: opacity ease-in 0.2s; } \nbody[unresolved] {opacity: 0; display: block; overflow: hidden; position: relative; } \n";var oh=document.querySelector("head");oh.insertBefore(nh,oh.firstChild);}).call(this);

//# sourceMappingURL=webcomponents-lite.js.map
