/**
@license @nocompile
Copyright (c) 2018 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){/*

Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
'use strict';var n,aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},p="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function ba(){ba=function(){};p.Symbol||(p.Symbol=ca)}var ca=function(){var a=0;return function(b){return"jscomp_symbol_"+(b||"")+a++}}();
function da(){ba();var a=p.Symbol.iterator;a||(a=p.Symbol.iterator=p.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&aa(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ea(this)}});da=function(){}}function ea(a){var b=0;return fa(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function fa(a){da();a={next:a};a[p.Symbol.iterator]=function(){return this};return a}function ha(a){da();ba();da();var b=a[Symbol.iterator];return b?b.call(a):ea(a)}
function ia(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c}function ja(){this.ea=this.root=null;this.P=!1;this.w=this.M=this.X=this.assignedSlot=this.assignedNodes=this.D=null;this.childNodes=this.nextSibling=this.previousSibling=this.lastChild=this.firstChild=this.parentNode=this.H=void 0;this.ka=this.aa=!1;this.L={}}ja.prototype.toJSON=function(){return{}};function q(a){a.__shady||(a.__shady=new ja);return a.__shady}function r(a){return a&&a.__shady};var t=window.ShadyDOM||{};t.va=!(!Element.prototype.attachShadow||!Node.prototype.getRootNode);var ka=Object.getOwnPropertyDescriptor(Node.prototype,"firstChild");t.s=!!(ka&&ka.configurable&&ka.get);t.Y=t.force||!t.va;var na=navigator.userAgent.match("Trident"),oa=navigator.userAgent.match("Edge");void 0===t.ga&&(t.ga=t.s&&(na||oa));function u(a){return(a=r(a))&&void 0!==a.firstChild}function v(a){return"ShadyRoot"===a.pa}function pa(a){a=a.getRootNode();if(v(a))return a}
var qa=Element.prototype,ra=qa.matches||qa.matchesSelector||qa.mozMatchesSelector||qa.msMatchesSelector||qa.oMatchesSelector||qa.webkitMatchesSelector;function sa(a,b){if(a&&b)for(var c=Object.getOwnPropertyNames(b),d=0,e=void 0;d<c.length&&(e=c[d]);d++){var f=e,g=a,h=Object.getOwnPropertyDescriptor(b,f);h&&Object.defineProperty(g,f,h)}}function ta(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];for(d=0;d<c.length;d++)sa(a,c[d]);return a}
function ua(a,b){for(var c in b)a[c]=b[c]}var va=document.createTextNode(""),wa=0,xa=[];(new MutationObserver(function(){for(;xa.length;)try{xa.shift()()}catch(a){throw va.textContent=wa++,a;}})).observe(va,{characterData:!0});function ya(a){xa.push(a);va.textContent=wa++}var za=!!document.contains;function Aa(a,b){for(;b;){if(b==a)return!0;b=b.parentNode}return!1}
function Ba(a){for(var b=a.length-1;0<=b;b--){var c=a[b],d=c.getAttribute("id")||c.getAttribute("name");d&&"length"!==d&&isNaN(d)&&(a[d]=c)}a.item=function(b){return a[b]};a.namedItem=function(b){if("length"!==b&&isNaN(b)&&a[b])return a[b];for(var c=ha(a),d=c.next();!d.done;d=c.next())if(d=d.value,(d.getAttribute("id")||d.getAttribute("name"))==b)return d;return null};return a};var Ca=[],Da;function Ea(a){Da||(Da=!0,ya(Fa));Ca.push(a)}function Fa(){Da=!1;for(var a=!!Ca.length;Ca.length;)Ca.shift()();return a}Fa.list=Ca;function Ga(){this.a=!1;this.addedNodes=[];this.removedNodes=[];this.O=new Set}function Ha(a){a.a||(a.a=!0,ya(function(){a.flush()}))}Ga.prototype.flush=function(){if(this.a){this.a=!1;var a=this.takeRecords();a.length&&this.O.forEach(function(b){b(a)})}};Ga.prototype.takeRecords=function(){if(this.addedNodes.length||this.removedNodes.length){var a=[{addedNodes:this.addedNodes,removedNodes:this.removedNodes}];this.addedNodes=[];this.removedNodes=[];return a}return[]};
function Ia(a,b){var c=q(a);c.D||(c.D=new Ga);c.D.O.add(b);var d=c.D;return{oa:b,B:d,qa:a,takeRecords:function(){return d.takeRecords()}}}function Ja(a){var b=a&&a.B;b&&(b.O.delete(a.oa),b.O.size||(q(a.qa).D=null))}
function Ka(a,b){var c=b.getRootNode();return a.map(function(a){var b=c===a.target.getRootNode();if(b&&a.addedNodes){if(b=Array.from(a.addedNodes).filter(function(a){return c===a.getRootNode()}),b.length)return a=Object.create(a),Object.defineProperty(a,"addedNodes",{value:b,configurable:!0}),a}else if(b)return a}).filter(function(a){return a})};var La=Element.prototype.insertBefore,Ma=Element.prototype.replaceChild,Na=Element.prototype.removeChild,Oa=Element.prototype.setAttribute,Pa=Element.prototype.removeAttribute,Qa=Element.prototype.cloneNode,Ra=Document.prototype.importNode,Sa=Element.prototype.addEventListener,Ta=Element.prototype.removeEventListener,Va=Window.prototype.addEventListener,Wa=Window.prototype.removeEventListener,Xa=Element.prototype.dispatchEvent,Ya=Node.prototype.contains||HTMLElement.prototype.contains,Za=Document.prototype.getElementById,
$a=Element.prototype.querySelector,ab=DocumentFragment.prototype.querySelector,bb=Document.prototype.querySelector,cb=Element.prototype.querySelectorAll,db=DocumentFragment.prototype.querySelectorAll,eb=Document.prototype.querySelectorAll,x={};x.appendChild=Element.prototype.appendChild;x.insertBefore=La;x.replaceChild=Ma;x.removeChild=Na;x.setAttribute=Oa;x.removeAttribute=Pa;x.cloneNode=Qa;x.importNode=Ra;x.addEventListener=Sa;x.removeEventListener=Ta;x.Ha=Va;x.Ia=Wa;x.dispatchEvent=Xa;
x.contains=Ya;x.getElementById=Za;x.Oa=$a;x.Ra=ab;x.Ma=bb;x.querySelector=function(a){switch(this.nodeType){case Node.ELEMENT_NODE:return $a.call(this,a);case Node.DOCUMENT_NODE:return bb.call(this,a);default:return ab.call(this,a)}};x.Pa=cb;x.Sa=db;x.Na=eb;x.querySelectorAll=function(a){switch(this.nodeType){case Node.ELEMENT_NODE:return cb.call(this,a);case Node.DOCUMENT_NODE:return eb.call(this,a);default:return db.call(this,a)}};var fb=/[&\u00A0"]/g,gb=/[&\u00A0<>]/g;function hb(a){switch(a){case "&":return"&amp;";case "<":return"&lt;";case ">":return"&gt;";case '"':return"&quot;";case "\u00a0":return"&nbsp;"}}function ib(a){for(var b={},c=0;c<a.length;c++)b[a[c]]=!0;return b}var jb=ib("area base br col command embed hr img input keygen link meta param source track wbr".split(" ")),kb=ib("style script xmp iframe noembed noframes plaintext noscript".split(" "));
function lb(a,b){"template"===a.localName&&(a=a.content);for(var c="",d=b?b(a):a.childNodes,e=0,f=d.length,g=void 0;e<f&&(g=d[e]);e++){a:{var h=g;var k=a,l=b;switch(h.nodeType){case Node.ELEMENT_NODE:k=h.localName;for(var m="<"+k,w=h.attributes,la=0,ma;ma=w[la];la++)m+=" "+ma.name+'="'+ma.value.replace(fb,hb)+'"';m+=">";h=jb[k]?m:m+lb(h,l)+"</"+k+">";break a;case Node.TEXT_NODE:h=h.data;h=k&&kb[k.localName]?h:h.replace(gb,hb);break a;case Node.COMMENT_NODE:h="\x3c!--"+h.data+"--\x3e";break a;default:throw window.console.error(h),
Error("not implemented");}}c+=h}return c};var y=document.createTreeWalker(document,NodeFilter.SHOW_ALL,null,!1),z=document.createTreeWalker(document,NodeFilter.SHOW_ELEMENT,null,!1);function mb(a){var b=[];y.currentNode=a;for(a=y.firstChild();a;)b.push(a),a=y.nextSibling();return b}
var A={parentNode:function(a){y.currentNode=a;return y.parentNode()},firstChild:function(a){y.currentNode=a;return y.firstChild()},lastChild:function(a){y.currentNode=a;return y.lastChild()},previousSibling:function(a){y.currentNode=a;return y.previousSibling()},nextSibling:function(a){y.currentNode=a;return y.nextSibling()}};A.childNodes=mb;A.parentElement=function(a){z.currentNode=a;return z.parentNode()};A.firstElementChild=function(a){z.currentNode=a;return z.firstChild()};
A.lastElementChild=function(a){z.currentNode=a;return z.lastChild()};A.previousElementSibling=function(a){z.currentNode=a;return z.previousSibling()};A.nextElementSibling=function(a){z.currentNode=a;return z.nextSibling()};A.children=function(a){var b=[];z.currentNode=a;for(a=z.firstChild();a;)b.push(a),a=z.nextSibling();return Ba(b)};A.innerHTML=function(a){return lb(a,function(a){return mb(a)})};
A.textContent=function(a){switch(a.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:a=document.createTreeWalker(a,NodeFilter.SHOW_TEXT,null,!1);for(var b="",c;c=a.nextNode();)b+=c.nodeValue;return b;default:return a.nodeValue}};var nb=t.s,ob=[Node.prototype,Element.prototype,HTMLElement.prototype];function B(a){var b;a:{for(b=0;b<ob.length;b++){var c=ob[b];if(c.hasOwnProperty(a)){b=c;break a}}b=void 0}if(!b)throw Error("Could not find descriptor for "+a);return Object.getOwnPropertyDescriptor(b,a)}
var C=nb?{parentNode:B("parentNode"),firstChild:B("firstChild"),lastChild:B("lastChild"),previousSibling:B("previousSibling"),nextSibling:B("nextSibling"),childNodes:B("childNodes"),parentElement:B("parentElement"),previousElementSibling:B("previousElementSibling"),nextElementSibling:B("nextElementSibling"),innerHTML:B("innerHTML"),textContent:B("textContent"),firstElementChild:B("firstElementChild"),lastElementChild:B("lastElementChild"),children:B("children")}:{},pb=nb?{firstElementChild:Object.getOwnPropertyDescriptor(DocumentFragment.prototype,
"firstElementChild"),lastElementChild:Object.getOwnPropertyDescriptor(DocumentFragment.prototype,"lastElementChild"),children:Object.getOwnPropertyDescriptor(DocumentFragment.prototype,"children")}:{},qb=nb?{firstElementChild:Object.getOwnPropertyDescriptor(Document.prototype,"firstElementChild"),lastElementChild:Object.getOwnPropertyDescriptor(Document.prototype,"lastElementChild"),children:Object.getOwnPropertyDescriptor(Document.prototype,"children")}:{},rb={da:C,Qa:pb,La:qb,parentNode:function(a){return C.parentNode.get.call(a)},
firstChild:function(a){return C.firstChild.get.call(a)},lastChild:function(a){return C.lastChild.get.call(a)},previousSibling:function(a){return C.previousSibling.get.call(a)},nextSibling:function(a){return C.nextSibling.get.call(a)},childNodes:function(a){return Array.prototype.slice.call(C.childNodes.get.call(a))},parentElement:function(a){return C.parentElement.get.call(a)},previousElementSibling:function(a){return C.previousElementSibling.get.call(a)},nextElementSibling:function(a){return C.nextElementSibling.get.call(a)},
innerHTML:function(a){return C.innerHTML.get.call(a)},textContent:function(a){return C.textContent.get.call(a)},children:function(a){switch(a.nodeType){case Node.DOCUMENT_FRAGMENT_NODE:return pb.children.get.call(a);case Node.DOCUMENT_NODE:return qb.children.get.call(a);default:return C.children.get.call(a)}},firstElementChild:function(a){switch(a.nodeType){case Node.DOCUMENT_FRAGMENT_NODE:return pb.firstElementChild.get.call(a);case Node.DOCUMENT_NODE:return qb.firstElementChild.get.call(a);default:return C.firstElementChild.get.call(a)}},
lastElementChild:function(a){switch(a.nodeType){case Node.DOCUMENT_FRAGMENT_NODE:return pb.lastElementChild.get.call(a);case Node.DOCUMENT_NODE:return qb.lastElementChild.get.call(a);default:return C.lastElementChild.get.call(a)}}};var D=t.ga?rb:A;function sb(a){for(;a.firstChild;)a.removeChild(a.firstChild)}
var tb=t.s,ub=document.implementation.createHTMLDocument("inert"),vb=Object.getOwnPropertyDescriptor(Node.prototype,"isConnected"),wb=vb&&vb.get,xb=Object.getOwnPropertyDescriptor(Document.prototype,"activeElement"),yb={parentElement:{get:function(){var a=r(this);(a=a&&a.parentNode)&&a.nodeType!==Node.ELEMENT_NODE&&(a=null);return void 0!==a?a:D.parentElement(this)},configurable:!0},parentNode:{get:function(){var a=r(this);a=a&&a.parentNode;return void 0!==a?a:D.parentNode(this)},configurable:!0},
nextSibling:{get:function(){var a=r(this);a=a&&a.nextSibling;return void 0!==a?a:D.nextSibling(this)},configurable:!0},previousSibling:{get:function(){var a=r(this);a=a&&a.previousSibling;return void 0!==a?a:D.previousSibling(this)},configurable:!0},nextElementSibling:{get:function(){var a=r(this);if(a&&void 0!==a.nextSibling){for(a=this.nextSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.nextSibling;return a}return D.nextElementSibling(this)},configurable:!0},previousElementSibling:{get:function(){var a=
r(this);if(a&&void 0!==a.previousSibling){for(a=this.previousSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.previousSibling;return a}return D.previousElementSibling(this)},configurable:!0}},zb={className:{get:function(){return this.getAttribute("class")||""},set:function(a){this.setAttribute("class",a)},configurable:!0}},Ab={childNodes:{get:function(){if(u(this)){var a=r(this);if(!a.childNodes){a.childNodes=[];for(var b=this.firstChild;b;b=b.nextSibling)a.childNodes.push(b)}var c=a.childNodes}else c=
D.childNodes(this);c.item=function(a){return c[a]};return c},configurable:!0},childElementCount:{get:function(){return this.children.length},configurable:!0},firstChild:{get:function(){var a=r(this);a=a&&a.firstChild;return void 0!==a?a:D.firstChild(this)},configurable:!0},lastChild:{get:function(){var a=r(this);a=a&&a.lastChild;return void 0!==a?a:D.lastChild(this)},configurable:!0},textContent:{get:function(){if(u(this)){for(var a=[],b=0,c=this.childNodes,d;d=c[b];b++)d.nodeType!==Node.COMMENT_NODE&&
a.push(d.textContent);return a.join("")}return D.textContent(this)},set:function(a){if("undefined"===typeof a||null===a)a="";switch(this.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:if(!u(this)&&tb){var b=this.firstChild;(b!=this.lastChild||b&&b.nodeType!=Node.TEXT_NODE)&&sb(this);rb.da.textContent.set.call(this,a)}else sb(this),(0<a.length||this.nodeType===Node.ELEMENT_NODE)&&this.appendChild(document.createTextNode(a));break;default:this.nodeValue=a}},configurable:!0},firstElementChild:{get:function(){var a=
r(this);if(a&&void 0!==a.firstChild){for(a=this.firstChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.nextSibling;return a}return D.firstElementChild(this)},configurable:!0},lastElementChild:{get:function(){var a=r(this);if(a&&void 0!==a.lastChild){for(a=this.lastChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.previousSibling;return a}return D.lastElementChild(this)},configurable:!0},children:{get:function(){return u(this)?Ba(Array.prototype.filter.call(this.childNodes,function(a){return a.nodeType===Node.ELEMENT_NODE})):
D.children(this)},configurable:!0},innerHTML:{get:function(){return u(this)?lb("template"===this.localName?this.content:this):D.innerHTML(this)},set:function(a){var b="template"===this.localName?this.content:this;sb(b);var c=this.localName||"div";c=this.namespaceURI&&this.namespaceURI!==ub.namespaceURI?ub.createElementNS(this.namespaceURI,c):ub.createElement(c);tb?rb.da.innerHTML.set.call(c,a):c.innerHTML=a;for(a="template"===this.localName?c.content:c;a.firstChild;)b.appendChild(a.firstChild)},configurable:!0}},
Bb={shadowRoot:{get:function(){var a=r(this);return a&&a.ea||null},configurable:!0}},Cb={activeElement:{get:function(){var a=xb&&xb.get?xb.get.call(document):t.s?void 0:document.activeElement;if(a&&a.nodeType){var b=!!v(this);if(this===document||b&&this.host!==a&&x.contains.call(this.host,a)){for(b=pa(a);b&&b!==this;)a=b.host,b=pa(a);a=this===document?b?null:a:b===this?a:null}else a=null}else a=null;return a},set:function(){},configurable:!0}};
function E(a,b,c){for(var d in b){var e=Object.getOwnPropertyDescriptor(a,d);e&&e.configurable||!e&&c?Object.defineProperty(a,d,b[d]):c&&console.warn("Could not define",d,"on",a)}}function F(a){E(a,yb);E(a,zb);E(a,Ab);E(a,Cb)}
function Db(){var a=Eb.prototype;a.__proto__=DocumentFragment.prototype;E(a,yb,!0);E(a,Ab,!0);E(a,Cb,!0);Object.defineProperties(a,{nodeType:{value:Node.DOCUMENT_FRAGMENT_NODE,configurable:!0},nodeName:{value:"#document-fragment",configurable:!0},nodeValue:{value:null,configurable:!0}});["localName","namespaceURI","prefix"].forEach(function(b){Object.defineProperty(a,b,{value:void 0,configurable:!0})});["ownerDocument","baseURI","isConnected"].forEach(function(b){Object.defineProperty(a,b,{get:function(){return this.host[b]},
configurable:!0})})}var Fb=t.s?function(){}:function(a){var b=q(a);b.aa||(b.aa=!0,E(a,yb,!0),E(a,zb,!0))},Gb=t.s?function(){}:function(a){q(a).ka||(E(a,Ab,!0),E(a,Bb,!0))};var Hb=D.childNodes;function Ib(a,b,c){Gb(b);var d=q(b);void 0!==d.firstChild&&(d.childNodes=null);if(a.nodeType===Node.DOCUMENT_FRAGMENT_NODE){d=a.childNodes;for(var e=0;e<d.length;e++)Jb(d[e],b,c);a=q(a);b=void 0!==a.firstChild?null:void 0;a.firstChild=a.lastChild=b;a.childNodes=b}else Jb(a,b,c)}
function Jb(a,b,c){Fb(a);c=c||null;var d=q(a),e=q(b),f=c?q(c):null;d.previousSibling=c?f.previousSibling:b.lastChild;if(f=r(d.previousSibling))f.nextSibling=a;if(f=r(d.nextSibling=c))f.previousSibling=a;d.parentNode=b;c?c===e.firstChild&&(e.firstChild=a):(e.lastChild=a,e.firstChild||(e.firstChild=a));e.childNodes=null}
function Kb(a,b){var c=q(a);b=q(b);a===b.firstChild&&(b.firstChild=c.nextSibling);a===b.lastChild&&(b.lastChild=c.previousSibling);a=c.previousSibling;var d=c.nextSibling;a&&(q(a).nextSibling=d);d&&(q(d).previousSibling=a);c.parentNode=c.previousSibling=c.nextSibling=void 0;void 0!==b.childNodes&&(b.childNodes=null)}
function Lb(a,b){var c=q(a);if(void 0===c.firstChild)for(c.childNodes=null,b=b||Hb(a),c.firstChild=b[0]||null,c.lastChild=b[b.length-1]||null,Gb(a),c=0;c<b.length;c++){var d=b[c],e=q(d);e.parentNode=a;e.nextSibling=b[c+1]||null;e.previousSibling=b[c-1]||null;Fb(d)}};var Mb=D.parentNode,Nb=window.document,Ob=t.Ua;
function Pb(a,b,c){if(a.ownerDocument!==Nb&&b.ownerDocument!==Nb)return x.insertBefore.call(a,b,c);if(b===a)throw Error("Failed to execute 'appendChild' on 'Node': The new child element contains the parent.");if(c){var d=r(c);d=d&&d.parentNode;if(void 0!==d&&d!==a||void 0===d&&Mb(c)!==a)throw Error("Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.");}if(c===b)return b;var e=[],f=Qb,g=pa(a),h;g?h=g.host.localName:h=Rb(a);
if(b.parentNode){var k=Rb(b);Sb(b.parentNode,b,!!g||!(b.getRootNode()instanceof ShadowRoot));f=function(a,b){G()&&(Tb(a,k),Qb(a,b))}}d=!0;var l=(!Ob||void 0===b.__noInsertionPoint)&&!Ub(b,h);if(g)b.__noInsertionPoint&&!l||Vb(b,function(a){"slot"===a.localName&&e.push(a);l&&f(a,h)});else if(l){var m=Rb(b);Vb(b,function(a){var b=h;G()&&(Tb(a,m),Qb(a,b))})}e.length&&Wb(g,e);("slot"===a.localName||e.length)&&g&&H(g);u(a)&&(Ib(b,a,c),g=r(a),Xb(a)?(H(g.root),d=!1):g.root&&(d=!1));d?(d=v(a)?a.host:a,c?(c=
Yb(c),x.insertBefore.call(d,b,c)):x.appendChild.call(d,b)):b.ownerDocument!==a.ownerDocument&&a.ownerDocument.adoptNode(b);Zb(a,b);return b}
function Sb(a,b,c){c=void 0===c?!1:c;if(a.ownerDocument!==Nb)return x.removeChild.call(a,b);if(b.parentNode!==a)throw Error("The node to be removed is not a child of this node: "+b);var d=pa(b),e=r(a);if(u(a)&&(Kb(b,a),Xb(a))){H(e.root);var f=!0}if(G()&&!c&&d){var g=Rb(b);Vb(b,function(a){Tb(a,g)})}$b(b);if(d){var h=a&&"slot"===a.localName;h&&(f=!0);((c=ac(d,b))||h)&&H(d)}f||(f=v(a)?a.host:a,(!e.root&&"slot"!==b.localName||f===Mb(b))&&x.removeChild.call(f,b));Zb(a,null,b);return b}
function $b(a){var b=r(a);if(b&&void 0!==b.H){b=a.childNodes;for(var c=0,d=b.length,e=void 0;c<d&&(e=b[c]);c++)$b(e)}if(a=r(a))a.H=void 0}function Yb(a){var b=a;a&&"slot"===a.localName&&(b=(b=(b=r(a))&&b.w)&&b.length?b[0]:Yb(a.nextSibling));return b}function Xb(a){return(a=(a=r(a))&&a.root)&&bc(a)}
function cc(a,b){if("slot"===b)a=a.parentNode,Xb(a)&&H(r(a).root);else if("slot"===a.localName&&"name"===b&&(b=pa(a))){if(b.g){dc(b);var c=a.na,d=ec(a);if(d!==c){c=b.h[c];var e=c.indexOf(a);0<=e&&c.splice(e,1);c=b.h[d]||(b.h[d]=[]);c.push(a);1<c.length&&(b.h[d]=fc(c))}}H(b)}}function Zb(a,b,c){if(a=(a=r(a))&&a.D)b&&a.addedNodes.push(b),c&&a.removedNodes.push(c),Ha(a)}
function gc(a){if(a&&a.nodeType){var b=q(a),c=b.H;void 0===c&&(v(a)?(c=a,b.H=c):(c=(c=a.parentNode)?gc(c):a,x.contains.call(document.documentElement,a)&&(b.H=c)));return c}}function hc(a,b,c){var d=[];ic(a.childNodes,b,c,d);return d}function ic(a,b,c,d){for(var e=0,f=a.length,g=void 0;e<f&&(g=a[e]);e++){var h;if(h=g.nodeType===Node.ELEMENT_NODE){h=g;var k=b,l=c,m=d,w=k(h);w&&m.push(h);l&&l(w)?h=w:(ic(h.childNodes,k,l,m),h=void 0)}if(h)break}}var jc=null;
function G(){jc||(jc=window.ShadyCSS&&window.ShadyCSS.ScopingShim);return jc||null}function kc(a,b,c){if(a.ownerDocument!==Nb)x.setAttribute.call(a,b,c);else{var d=G();d&&"class"===b?d.setElementClass(a,c):(x.setAttribute.call(a,b,c),cc(a,b))}}function lc(a,b){if(a.ownerDocument!==document||"template"===a.localName)return x.importNode.call(document,a,b);var c=x.importNode.call(document,a,!1);if(b){a=a.childNodes;b=0;for(var d;b<a.length;b++)d=lc(a[b],!0),c.appendChild(d)}return c}
function Qb(a,b){var c=G();c&&c.scopeNode(a,b)}function Tb(a,b){var c=G();c&&c.unscopeNode(a,b)}function Ub(a,b){var c=G();if(!c)return!0;if(a.nodeType===Node.DOCUMENT_FRAGMENT_NODE){c=!0;for(var d=0;c&&d<a.childNodes.length;d++)c=c&&Ub(a.childNodes[d],b);return c}return a.nodeType!==Node.ELEMENT_NODE?!0:c.currentScopeForNode(a)===b}function Rb(a){if(a.nodeType!==Node.ELEMENT_NODE)return"";var b=G();return b?b.currentScopeForNode(a):""}
function Vb(a,b){if(a){a.nodeType===Node.ELEMENT_NODE&&b(a);for(var c=0,d;c<a.childNodes.length;c++)d=a.childNodes[c],d.nodeType===Node.ELEMENT_NODE&&Vb(d,b)}};var mc="__eventWrappers"+Date.now(),nc=function(){var a=Object.getOwnPropertyDescriptor(Event.prototype,"composed");return a?function(b){return a.get.call(b)}:null}(),oc={blur:!0,focus:!0,focusin:!0,focusout:!0,click:!0,dblclick:!0,mousedown:!0,mouseenter:!0,mouseleave:!0,mousemove:!0,mouseout:!0,mouseover:!0,mouseup:!0,wheel:!0,beforeinput:!0,input:!0,keydown:!0,keyup:!0,compositionstart:!0,compositionupdate:!0,compositionend:!0,touchstart:!0,touchend:!0,touchmove:!0,touchcancel:!0,pointerover:!0,
pointerenter:!0,pointerdown:!0,pointermove:!0,pointerup:!0,pointercancel:!0,pointerout:!0,pointerleave:!0,gotpointercapture:!0,lostpointercapture:!0,dragstart:!0,drag:!0,dragenter:!0,dragleave:!0,dragover:!0,drop:!0,dragend:!0,DOMActivate:!0,DOMFocusIn:!0,DOMFocusOut:!0,keypress:!0},pc={DOMAttrModified:!0,DOMAttributeNameChanged:!0,DOMCharacterDataModified:!0,DOMElementNameChanged:!0,DOMNodeInserted:!0,DOMNodeInsertedIntoDocument:!0,DOMNodeRemoved:!0,DOMNodeRemovedFromDocument:!0,DOMSubtreeModified:!0};
function qc(a,b){var c=[],d=a;for(a=a===window?window:a.getRootNode();d;)c.push(d),d=d.assignedSlot?d.assignedSlot:d.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&d.host&&(b||d!==a)?d.host:d.parentNode;c[c.length-1]===document&&c.push(window);return c}function rc(a,b){if(!v)return a;a=qc(a,!0);for(var c=0,d,e=void 0,f,g=void 0;c<b.length;c++)if(d=b[c],f=d===window?window:d.getRootNode(),f!==e&&(g=a.indexOf(f),e=f),!v(f)||-1<g)return d}
var sc={get composed(){void 0===this.K&&(nc?this.K="focusin"===this.type||"focusout"===this.type||nc(this):!1!==this.isTrusted&&(this.K=oc[this.type]));return this.K||!1},composedPath:function(){this.$||(this.$=qc(this.__target,this.composed));return this.$},get target(){return rc(this.currentTarget||this.__previousCurrentTarget,this.composedPath())},get relatedTarget(){if(!this.V)return null;this.ba||(this.ba=qc(this.V,!0));return rc(this.currentTarget||this.__previousCurrentTarget,this.ba)},stopPropagation:function(){Event.prototype.stopPropagation.call(this);
this.U=!0},stopImmediatePropagation:function(){Event.prototype.stopImmediatePropagation.call(this);this.U=this.ja=!0}};function tc(a){function b(b,d){b=new a(b,d);b.K=d&&!!d.composed;return b}ua(b,a);b.prototype=a.prototype;return b}var uc={focus:!0,blur:!0};function vc(a){return a.__target!==a.target||a.V!==a.relatedTarget}function wc(a,b,c){if(c=b.__handlers&&b.__handlers[a.type]&&b.__handlers[a.type][c])for(var d=0,e;(e=c[d])&&(!vc(a)||a.target!==a.relatedTarget)&&(e.call(b,a),!a.ja);d++);}
function xc(a){var b=a.composedPath();Object.defineProperty(a,"currentTarget",{get:function(){return d},configurable:!0});for(var c=b.length-1;0<=c;c--){var d=b[c];wc(a,d,"capture");if(a.U)return}Object.defineProperty(a,"eventPhase",{get:function(){return Event.AT_TARGET}});var e;for(c=0;c<b.length;c++){d=b[c];var f=r(d);f=f&&f.root;if(0===c||f&&f===e)if(wc(a,d,"bubble"),d!==window&&(e=d.getRootNode()),a.U)break}}
function yc(a,b,c,d,e,f){for(var g=0;g<a.length;g++){var h=a[g],k=h.type,l=h.capture,m=h.once,w=h.passive;if(b===h.node&&c===k&&d===l&&e===m&&f===w)return g}return-1}
function zc(a,b,c){if(b){var d=typeof b;if("function"===d||"object"===d)if("object"!==d||b.handleEvent&&"function"===typeof b.handleEvent){var e=this instanceof Window?x.Ha:x.addEventListener;if(pc[a])return e.call(this,a,b,c);if(c&&"object"===typeof c){var f=!!c.capture;var g=!!c.once;var h=!!c.passive}else f=!!c,h=g=!1;var k=c&&c.W||this,l=b[mc];if(l){if(-1<yc(l,k,a,f,g,h))return}else b[mc]=[];l=function(e){g&&this.removeEventListener(a,b,c);e.__target||Ac(e);if(k!==this){var f=Object.getOwnPropertyDescriptor(e,
"currentTarget");Object.defineProperty(e,"currentTarget",{get:function(){return k},configurable:!0})}e.__previousCurrentTarget=e.currentTarget;if(!v(k)||-1!=e.composedPath().indexOf(k))if(e.composed||-1<e.composedPath().indexOf(k))if(vc(e)&&e.target===e.relatedTarget)e.eventPhase===Event.BUBBLING_PHASE&&e.stopImmediatePropagation();else if(e.eventPhase===Event.CAPTURING_PHASE||e.bubbles||e.target===k||k instanceof Window){var h="function"===d?b.call(k,e):b.handleEvent&&b.handleEvent(e);k!==this&&
(f?(Object.defineProperty(e,"currentTarget",f),f=null):delete e.currentTarget);return h}};b[mc].push({node:k,type:a,capture:f,once:g,passive:h,Ja:l});uc[a]?(this.__handlers=this.__handlers||{},this.__handlers[a]=this.__handlers[a]||{capture:[],bubble:[]},this.__handlers[a][f?"capture":"bubble"].push(l)):e.call(this,a,l,c)}}}
function Bc(a,b,c){if(b){var d=this instanceof Window?x.Ia:x.removeEventListener;if(pc[a])return d.call(this,a,b,c);if(c&&"object"===typeof c){var e=!!c.capture;var f=!!c.once;var g=!!c.passive}else e=!!c,g=f=!1;var h=c&&c.W||this,k=void 0;var l=null;try{l=b[mc]}catch(m){}l&&(f=yc(l,h,a,e,f,g),-1<f&&(k=l.splice(f,1)[0].Ja,l.length||(b[mc]=void 0)));d.call(this,a,k||b,c);k&&uc[a]&&this.__handlers&&this.__handlers[a]&&(a=this.__handlers[a][e?"capture":"bubble"],k=a.indexOf(k),-1<k&&a.splice(k,1))}}
function Cc(){for(var a in uc)window.addEventListener(a,function(a){a.__target||(Ac(a),xc(a))},!0)}function Ac(a){a.__target=a.target;a.V=a.relatedTarget;if(t.s){var b=Object.getPrototypeOf(a);if(!b.hasOwnProperty("__patchProto")){var c=Object.create(b);c.Ka=b;sa(c,sc);b.__patchProto=c}a.__proto__=b.__patchProto}else sa(a,sc)}var Dc=tc(window.Event),Ec=tc(window.CustomEvent),Fc=tc(window.MouseEvent);
function Gc(){window.Event=Dc;window.CustomEvent=Ec;window.MouseEvent=Fc;Cc();if(!nc&&Object.getOwnPropertyDescriptor(Event.prototype,"isTrusted")){var a=function(){var a=new MouseEvent("click",{bubbles:!0,cancelable:!0,composed:!0});this.dispatchEvent(a)};Element.prototype.click?Element.prototype.click=a:HTMLElement.prototype.click&&(HTMLElement.prototype.click=a)}};function Hc(a,b){return{index:a,I:[],N:b}}
function Ic(a,b,c,d){var e=0,f=0,g=0,h=0,k=Math.min(b-e,d-f);if(0==e&&0==f)a:{for(g=0;g<k;g++)if(a[g]!==c[g])break a;g=k}if(b==a.length&&d==c.length){h=a.length;for(var l=c.length,m=0;m<k-g&&Jc(a[--h],c[--l]);)m++;h=m}e+=g;f+=g;b-=h;d-=h;if(0==b-e&&0==d-f)return[];if(e==b){for(b=Hc(e,0);f<d;)b.I.push(c[f++]);return[b]}if(f==d)return[Hc(e,b-e)];k=e;g=f;d=d-g+1;h=b-k+1;b=Array(d);for(l=0;l<d;l++)b[l]=Array(h),b[l][0]=l;for(l=0;l<h;l++)b[0][l]=l;for(l=1;l<d;l++)for(m=1;m<h;m++)if(a[k+m-1]===c[g+l-1])b[l][m]=
b[l-1][m-1];else{var w=b[l-1][m]+1,la=b[l][m-1]+1;b[l][m]=w<la?w:la}k=b.length-1;g=b[0].length-1;d=b[k][g];for(a=[];0<k||0<g;)0==k?(a.push(2),g--):0==g?(a.push(3),k--):(h=b[k-1][g-1],l=b[k-1][g],m=b[k][g-1],w=l<m?l<h?l:h:m<h?m:h,w==h?(h==d?a.push(0):(a.push(1),d=h),k--,g--):w==l?(a.push(3),k--,d=l):(a.push(2),g--,d=m));a.reverse();b=void 0;k=[];for(g=0;g<a.length;g++)switch(a[g]){case 0:b&&(k.push(b),b=void 0);e++;f++;break;case 1:b||(b=Hc(e,0));b.N++;e++;b.I.push(c[f]);f++;break;case 2:b||(b=Hc(e,
0));b.N++;e++;break;case 3:b||(b=Hc(e,0)),b.I.push(c[f]),f++}b&&k.push(b);return k}function Jc(a,b){return a===b};var Kc=D.parentNode,Lc=D.childNodes,Mc={},I=t.deferConnectionCallbacks&&"loading"===document.readyState,Nc;function Oc(a){var b=[];do b.unshift(a);while(a=a.parentNode);return b}
function Eb(a,b,c){if(a!==Mc)throw new TypeError("Illegal constructor");this.pa="ShadyRoot";this.host=b;this.c=c&&c.mode;a=Lc(b);Lb(b,a);c=q(b);c.root=this;c.ea="closed"!==this.c?this:null;c=q(this);c.firstChild=c.lastChild=c.parentNode=c.nextSibling=c.previousSibling=null;c.childNodes=[];this.b=this.G=!1;this.a=this.h=this.g=null;if(t.preferPerformance){c=0;for(var d=a.length;c<d;c++)x.removeChild.call(b,a[c])}else H(this)}function H(a){a.G||(a.G=!0,Ea(function(){return Pc(a)}))}
function Pc(a){for(var b;a;){a.G&&(b=a);a:{var c=a;a=c.host.getRootNode();if(v(a))for(var d=c.host.childNodes,e=0;e<d.length;e++)if(c=d[e],"slot"==c.localName)break a;a=void 0}}b&&b._renderRoot()}
Eb.prototype._renderRoot=function(){var a=I;I=!0;this.G=!1;if(this.g){dc(this);for(var b=0,c;b<this.g.length;b++){c=this.g[b];var d=r(c),e=d.assignedNodes;d.assignedNodes=[];d.w=[];if(d.X=e)for(d=0;d<e.length;d++){var f=r(e[d]);f.M=f.assignedSlot;f.assignedSlot===c&&(f.assignedSlot=null)}}for(b=this.host.firstChild;b;b=b.nextSibling)Qc(this,b);for(b=0;b<this.g.length;b++){c=this.g[b];e=r(c);if(!e.assignedNodes.length)for(d=c.firstChild;d;d=d.nextSibling)Qc(this,d,c);(d=(d=r(c.parentNode))&&d.root)&&
(bc(d)||d.G)&&d._renderRoot();Rc(this,e.w,e.assignedNodes);if(d=e.X){for(f=0;f<d.length;f++)r(d[f]).M=null;e.X=null;d.length>e.assignedNodes.length&&(e.P=!0)}e.P&&(e.P=!1,Sc(this,c))}c=this.g;b=[];for(e=0;e<c.length;e++)d=c[e].parentNode,(f=r(d))&&f.root||!(0>b.indexOf(d))||b.push(d);for(c=0;c<b.length;c++){f=b[c];e=f===this?this.host:f;d=[];f=f.childNodes;for(var g=0;g<f.length;g++){var h=f[g];if("slot"==h.localName){h=r(h).w;for(var k=0;k<h.length;k++)d.push(h[k])}else d.push(h)}f=Lc(e);g=Ic(d,
d.length,f,f.length);k=h=0;for(var l=void 0;h<g.length&&(l=g[h]);h++){for(var m=0,w=void 0;m<l.I.length&&(w=l.I[m]);m++)Kc(w)===e&&x.removeChild.call(e,w),f.splice(l.index+k,1);k-=l.N}k=0;for(l=void 0;k<g.length&&(l=g[k]);k++)for(h=f[l.index],m=l.index;m<l.index+l.N;m++)w=d[m],x.insertBefore.call(e,w,h),f.splice(m,0,w)}}if(!t.preferPerformance&&!this.b)for(b=this.host.childNodes,c=0,e=b.length;c<e;c++)d=b[c],f=r(d),Kc(d)!==this.host||"slot"!==d.localName&&f.assignedSlot||x.removeChild.call(this.host,
d);this.b=!0;I=a;Nc&&Nc()};function Qc(a,b,c){var d=q(b),e=d.M;d.M=null;c||(c=(a=a.h[b.slot||"__catchall"])&&a[0]);c?(q(c).assignedNodes.push(b),d.assignedSlot=c):d.assignedSlot=void 0;e!==d.assignedSlot&&d.assignedSlot&&(q(d.assignedSlot).P=!0)}function Rc(a,b,c){for(var d=0,e=void 0;d<c.length&&(e=c[d]);d++)if("slot"==e.localName){var f=r(e).assignedNodes;f&&f.length&&Rc(a,b,f)}else b.push(c[d])}
function Sc(a,b){x.dispatchEvent.call(b,new Event("slotchange"));b=r(b);b.assignedSlot&&Sc(a,b.assignedSlot)}function Wb(a,b){a.a=a.a||[];a.g=a.g||[];a.h=a.h||{};a.a.push.apply(a.a,b instanceof Array?b:ia(ha(b)))}function dc(a){if(a.a&&a.a.length){for(var b=a.a,c,d=0;d<b.length;d++){var e=b[d];Lb(e);Lb(e.parentNode);var f=ec(e);a.h[f]?(c=c||{},c[f]=!0,a.h[f].push(e)):a.h[f]=[e];a.g.push(e)}if(c)for(var g in c)a.h[g]=fc(a.h[g]);a.a=[]}}
function ec(a){var b=a.name||a.getAttribute("name")||"__catchall";return a.na=b}function fc(a){return a.sort(function(a,c){a=Oc(a);for(var b=Oc(c),e=0;e<a.length;e++){c=a[e];var f=b[e];if(c!==f)return a=Array.from(c.parentNode.childNodes),a.indexOf(c)-a.indexOf(f)}})}
function ac(a,b){if(a.g){dc(a);var c=a.h,d;for(d in c)for(var e=c[d],f=0;f<e.length;f++){var g=e[f];if(Aa(b,g)){e.splice(f,1);var h=a.g.indexOf(g);0<=h&&a.g.splice(h,1);f--;g=r(g);if(h=g.w)for(var k=0;k<h.length;k++){var l=h[k],m=Kc(l);m&&x.removeChild.call(m,l)}g.w=[];g.assignedNodes=[];h=!0}}return h}}function bc(a){dc(a);return!(!a.g||!a.g.length)}
if(window.customElements&&t.Y&&!t.preferPerformance){var Tc=new Map;Nc=function(){var a=Array.from(Tc);Tc.clear();a=ha(a);for(var b=a.next();!b.done;b=a.next()){b=ha(b.value);var c=b.next().value;b.next().value?c.la():c.ma()}};I&&document.addEventListener("readystatechange",function(){I=!1;Nc()},{once:!0});var Uc=function(a,b,c){var d=0,e="__isConnected"+d++;if(b||c)a.prototype.connectedCallback=a.prototype.la=function(){I?Tc.set(this,!0):this[e]||(this[e]=!0,b&&b.call(this))},a.prototype.disconnectedCallback=
a.prototype.ma=function(){I?this.isConnected||Tc.set(this,!1):this[e]&&(this[e]=!1,c&&c.call(this))};return a},Vc=window.customElements.define;Object.defineProperty(window.CustomElementRegistry.prototype,"define",{value:function(a,b){var c=b.prototype.connectedCallback,d=b.prototype.disconnectedCallback;Vc.call(window.customElements,a,Uc(b,c,d));b.prototype.connectedCallback=c;b.prototype.disconnectedCallback=d}})};function Wc(a){var b=a.getRootNode();v(b)&&Pc(b);return(a=r(a))&&a.assignedSlot||null}
var Xc={addEventListener:zc.bind(window),removeEventListener:Bc.bind(window)},Yc={addEventListener:zc,removeEventListener:Bc,appendChild:function(a){return Pb(this,a)},insertBefore:function(a,b){return Pb(this,a,b)},removeChild:function(a){return Sb(this,a)},replaceChild:function(a,b){Pb(this,a,b);Sb(this,b);return a},cloneNode:function(a){if("template"==this.localName)var b=x.cloneNode.call(this,a);else if(b=x.cloneNode.call(this,!1),a&&b.nodeType!==Node.ATTRIBUTE_NODE){a=this.childNodes;for(var c=
0,d;c<a.length;c++)d=a[c].cloneNode(!0),b.appendChild(d)}return b},getRootNode:function(){return gc(this)},contains:function(a){return Aa(this,a)},dispatchEvent:function(a){Fa();return x.dispatchEvent.call(this,a)}};
Object.defineProperties(Yc,{isConnected:{get:function(){if(wb&&wb.call(this))return!0;if(this.nodeType==Node.DOCUMENT_FRAGMENT_NODE)return!1;var a=this.ownerDocument;if(za){if(x.contains.call(a,this))return!0}else if(a.documentElement&&x.contains.call(a.documentElement,this))return!0;for(a=this;a&&!(a instanceof Document);)a=a.parentNode||(v(a)?a.host:void 0);return!!(a&&a instanceof Document)},configurable:!0}});
var Zc={get assignedSlot(){return Wc(this)}},$c={querySelector:function(a){return hc(this,function(b){return ra.call(b,a)},function(a){return!!a})[0]||null},querySelectorAll:function(a,b){if(b){b=Array.prototype.slice.call(x.querySelectorAll.call(this,a));var c=this.getRootNode();return b.filter(function(a){return a.getRootNode()==c})}return hc(this,function(b){return ra.call(b,a)})}},ad={},bd={assignedNodes:function(a){if("slot"===this.localName){var b=this.getRootNode();v(b)&&Pc(b);return(b=r(this))?
(a&&a.flatten?b.w:b.assignedNodes)||[]:[]}}},cd=ta({setAttribute:function(a,b){kc(this,a,b)},removeAttribute:function(a){x.removeAttribute.call(this,a);cc(this,a)},attachShadow:function(a){if(!this)throw"Must provide a host.";if(!a)throw"Not enough arguments.";return new Eb(Mc,this,a)},get slot(){return this.getAttribute("slot")},set slot(a){kc(this,"slot",a)},get assignedSlot(){return Wc(this)}},$c,bd);Object.defineProperties(cd,Bb);
var dd={importNode:function(a,b){return lc(a,b)},getElementById:function(a){return hc(this,function(b){return b.id==a},function(a){return!!a})[0]||null}};Object.defineProperties(dd,{_activeElement:Cb.activeElement});
for(var ed=HTMLElement.prototype.blur,fd={blur:function(){var a=r(this);(a=(a=a&&a.root)&&a.activeElement)?a.blur():ed.call(this)}},J={},gd=ha(Object.getOwnPropertyNames(Document.prototype)),hd=gd.next();!hd.done;J={m:J.m},hd=gd.next())J.m=hd.value,"on"===J.m.substring(0,2)&&Object.defineProperty(fd,J.m,{set:function(a){return function(b){var c=q(this),d=a.m.substring(2);c.L[a.m]&&this.removeEventListener(d,c.L[a.m]);this.addEventListener(d,b,{});c.L[a.m]=b}}(J),get:function(a){return function(){var b=
r(this);return b&&b.L[a.m]}}(J),configurable:!0});var id=ta({addEventListener:function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.W=this;this.host.addEventListener(a,b,c)},removeEventListener:function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.W=this;this.host.removeEventListener(a,b,c)},getElementById:function(a){return hc(this,function(b){return b.id==a},function(a){return!!a})[0]||null}},$c);t.preferPerformance||(ta(dd,$c),ta(ad,$c));
function K(a,b){for(var c=Object.getOwnPropertyNames(b),d=0;d<c.length;d++){var e=c[d],f=Object.getOwnPropertyDescriptor(b,e);f.value?a[e]=f.value:Object.defineProperty(a,e,f)}};if(t.Y){var ShadyDOM={inUse:t.Y,patch:function(a){Gb(a);Fb(a);return a},isShadyRoot:v,enqueue:Ea,flush:Fa,settings:t,filterMutations:Ka,observeChildren:Ia,unobserveChildren:Ja,nativeMethods:x,nativeTree:D,deferConnectionCallbacks:t.deferConnectionCallbacks,preferPerformance:t.preferPerformance,handlesDynamicScoping:!0};window.ShadyDOM=ShadyDOM;Gc();var jd=window.customElements&&window.customElements.nativeHTMLElement||HTMLElement;K(Eb.prototype,id);K(window.Node.prototype,Yc);K(window.Window.prototype,
Xc);K(window.Text.prototype,Zc);K(window.Element.prototype,cd);K(window.DocumentFragment.prototype,ad);K(window.Document.prototype,dd);window.HTMLSlotElement&&K(window.HTMLSlotElement.prototype,bd);K(jd.prototype,fd);t.s&&(F(window.Node.prototype),F(window.Text.prototype),F(window.DocumentFragment.prototype),F(window.Element.prototype),F(jd.prototype),F(window.Document.prototype),window.HTMLSlotElement&&F(window.HTMLSlotElement.prototype));Db();window.ShadowRoot=Eb};var kd=new Set("annotation-xml color-profile font-face font-face-src font-face-uri font-face-format font-face-name missing-glyph".split(" "));function ld(a){var b=kd.has(a);a=/^[a-z][.0-9_a-z]*-[\-.0-9_a-z]*$/.test(a);return!b&&a}function L(a){var b=a.isConnected;if(void 0!==b)return b;for(;a&&!(a.__CE_isImportDocument||a instanceof Document);)a=a.parentNode||(window.ShadowRoot&&a instanceof ShadowRoot?a.host:void 0);return!(!a||!(a.__CE_isImportDocument||a instanceof Document))}
function md(a,b){for(;b&&b!==a&&!b.nextSibling;)b=b.parentNode;return b&&b!==a?b.nextSibling:null}
function M(a,b,c){c=void 0===c?new Set:c;for(var d=a;d;){if(d.nodeType===Node.ELEMENT_NODE){var e=d;b(e);var f=e.localName;if("link"===f&&"import"===e.getAttribute("rel")){d=e.import;if(d instanceof Node&&!c.has(d))for(c.add(d),d=d.firstChild;d;d=d.nextSibling)M(d,b,c);d=md(a,e);continue}else if("template"===f){d=md(a,e);continue}if(e=e.__CE_shadowRoot)for(e=e.firstChild;e;e=e.nextSibling)M(e,b,c)}d=d.firstChild?d.firstChild:md(a,d)}}function N(a,b,c){a[b]=c};function nd(){this.a=new Map;this.l=new Map;this.f=[];this.c=!1}function od(a,b,c){a.a.set(b,c);a.l.set(c.constructorFunction,c)}function pd(a,b){a.c=!0;a.f.push(b)}function qd(a,b){a.c&&M(b,function(b){return a.b(b)})}nd.prototype.b=function(a){if(this.c&&!a.__CE_patched){a.__CE_patched=!0;for(var b=0;b<this.f.length;b++)this.f[b](a)}};function O(a,b){var c=[];M(b,function(a){return c.push(a)});for(b=0;b<c.length;b++){var d=c[b];1===d.__CE_state?a.connectedCallback(d):rd(a,d)}}
function P(a,b){var c=[];M(b,function(a){return c.push(a)});for(b=0;b<c.length;b++){var d=c[b];1===d.__CE_state&&a.disconnectedCallback(d)}}
function Q(a,b,c){c=void 0===c?{}:c;var d=c.Ga||new Set,e=c.T||function(b){return rd(a,b)},f=[];M(b,function(b){if("link"===b.localName&&"import"===b.getAttribute("rel")){var c=b.import;c instanceof Node&&(c.__CE_isImportDocument=!0,c.__CE_hasRegistry=!0);c&&"complete"===c.readyState?c.__CE_documentLoadHandled=!0:b.addEventListener("load",function(){var c=b.import;if(!c.__CE_documentLoadHandled){c.__CE_documentLoadHandled=!0;var f=new Set(d);f.delete(c);Q(a,c,{Ga:f,T:e})}})}else f.push(b)},d);if(a.c)for(b=
0;b<f.length;b++)a.b(f[b]);for(b=0;b<f.length;b++)e(f[b])}
function rd(a,b){if(void 0===b.__CE_state){var c=b.ownerDocument;if(c.defaultView||c.__CE_isImportDocument&&c.__CE_hasRegistry)if(c=a.a.get(b.localName)){c.constructionStack.push(b);var d=c.constructorFunction;try{try{if(new d!==b)throw Error("The custom element constructor did not produce the element being upgraded.");}finally{c.constructionStack.pop()}}catch(g){throw b.__CE_state=2,g;}b.__CE_state=1;b.__CE_definition=c;if(c.attributeChangedCallback)for(c=c.observedAttributes,d=0;d<c.length;d++){var e=
c[d],f=b.getAttribute(e);null!==f&&a.attributeChangedCallback(b,e,null,f,null)}L(b)&&a.connectedCallback(b)}}}nd.prototype.connectedCallback=function(a){var b=a.__CE_definition;b.connectedCallback&&b.connectedCallback.call(a)};nd.prototype.disconnectedCallback=function(a){var b=a.__CE_definition;b.disconnectedCallback&&b.disconnectedCallback.call(a)};
nd.prototype.attributeChangedCallback=function(a,b,c,d,e){var f=a.__CE_definition;f.attributeChangedCallback&&-1<f.observedAttributes.indexOf(b)&&f.attributeChangedCallback.call(a,b,c,d,e)};function sd(a){var b=document;this.b=a;this.a=b;this.B=void 0;Q(this.b,this.a);"loading"===this.a.readyState&&(this.B=new MutationObserver(this.c.bind(this)),this.B.observe(this.a,{childList:!0,subtree:!0}))}function td(a){a.B&&a.B.disconnect()}sd.prototype.c=function(a){var b=this.a.readyState;"interactive"!==b&&"complete"!==b||td(this);for(b=0;b<a.length;b++)for(var c=a[b].addedNodes,d=0;d<c.length;d++)Q(this.b,c[d])};function ud(){var a=this;this.b=this.a=void 0;this.c=new Promise(function(b){a.b=b;a.a&&b(a.a)})}function vd(a){if(a.a)throw Error("Already resolved.");a.a=void 0;a.b&&a.b(void 0)};function R(a){this.c=!1;this.a=a;this.C=new Map;this.f=function(a){return a()};this.b=!1;this.l=[];this.xa=new sd(a)}n=R.prototype;
n.ha=function(a,b){var c=this;if(!(b instanceof Function))throw new TypeError("Custom element constructors must be functions.");if(!ld(a))throw new SyntaxError("The element name '"+a+"' is not valid.");if(this.a.a.get(a))throw Error("A custom element with name '"+a+"' has already been defined.");if(this.c)throw Error("A custom element is already being defined.");this.c=!0;try{var d=function(a){var b=e[a];if(void 0!==b&&!(b instanceof Function))throw Error("The '"+a+"' callback must be a function.");
return b},e=b.prototype;if(!(e instanceof Object))throw new TypeError("The custom element constructor's prototype is not an object.");var f=d("connectedCallback");var g=d("disconnectedCallback");var h=d("adoptedCallback");var k=d("attributeChangedCallback");var l=b.observedAttributes||[]}catch(m){return}finally{this.c=!1}b={localName:a,constructorFunction:b,connectedCallback:f,disconnectedCallback:g,adoptedCallback:h,attributeChangedCallback:k,observedAttributes:l,constructionStack:[]};od(this.a,
a,b);this.l.push(b);this.b||(this.b=!0,this.f(function(){return wd(c)}))};n.T=function(a){Q(this.a,a)};
function wd(a){if(!1!==a.b){a.b=!1;for(var b=a.l,c=[],d=new Map,e=0;e<b.length;e++)d.set(b[e].localName,[]);Q(a.a,document,{T:function(b){if(void 0===b.__CE_state){var e=b.localName,f=d.get(e);f?f.push(b):a.a.a.get(e)&&c.push(b)}}});for(e=0;e<c.length;e++)rd(a.a,c[e]);for(;0<b.length;){var f=b.shift();e=f.localName;f=d.get(f.localName);for(var g=0;g<f.length;g++)rd(a.a,f[g]);(e=a.C.get(e))&&vd(e)}}}n.get=function(a){if(a=this.a.a.get(a))return a.constructorFunction};
n.ia=function(a){if(!ld(a))return Promise.reject(new SyntaxError("'"+a+"' is not a valid custom element name."));var b=this.C.get(a);if(b)return b.c;b=new ud;this.C.set(a,b);this.a.a.get(a)&&!this.l.some(function(b){return b.localName===a})&&vd(b);return b.c};n.za=function(a){td(this.xa);var b=this.f;this.f=function(c){return a(function(){return b(c)})}};window.CustomElementRegistry=R;R.prototype.define=R.prototype.ha;R.prototype.upgrade=R.prototype.T;R.prototype.get=R.prototype.get;
R.prototype.whenDefined=R.prototype.ia;R.prototype.polyfillWrapFlushCallback=R.prototype.za;var xd=window.Document.prototype.createElement,yd=window.Document.prototype.createElementNS,zd=window.Document.prototype.importNode,Ad=window.Document.prototype.prepend,Bd=window.Document.prototype.append,Cd=window.DocumentFragment.prototype.prepend,Dd=window.DocumentFragment.prototype.append,Ed=window.Node.prototype.cloneNode,Fd=window.Node.prototype.appendChild,Gd=window.Node.prototype.insertBefore,Hd=window.Node.prototype.removeChild,Id=window.Node.prototype.replaceChild,Jd=Object.getOwnPropertyDescriptor(window.Node.prototype,
"textContent"),Kd=window.Element.prototype.attachShadow,Ld=Object.getOwnPropertyDescriptor(window.Element.prototype,"innerHTML"),Md=window.Element.prototype.getAttribute,Nd=window.Element.prototype.setAttribute,Od=window.Element.prototype.removeAttribute,Pd=window.Element.prototype.getAttributeNS,Qd=window.Element.prototype.setAttributeNS,Rd=window.Element.prototype.removeAttributeNS,Sd=window.Element.prototype.insertAdjacentElement,Td=window.Element.prototype.insertAdjacentHTML,Ud=window.Element.prototype.prepend,
Vd=window.Element.prototype.append,Wd=window.Element.prototype.before,Xd=window.Element.prototype.after,Yd=window.Element.prototype.replaceWith,Zd=window.Element.prototype.remove,$d=window.HTMLElement,ae=Object.getOwnPropertyDescriptor(window.HTMLElement.prototype,"innerHTML"),be=window.HTMLElement.prototype.insertAdjacentElement,ce=window.HTMLElement.prototype.insertAdjacentHTML;var de=new function(){};function ee(){var a=fe;window.HTMLElement=function(){function b(){var b=this.constructor,d=a.l.get(b);if(!d)throw Error("The custom element being constructed was not registered with `customElements`.");var e=d.constructionStack;if(0===e.length)return e=xd.call(document,d.localName),Object.setPrototypeOf(e,b.prototype),e.__CE_state=1,e.__CE_definition=d,a.b(e),e;d=e.length-1;var f=e[d];if(f===de)throw Error("The HTMLElement constructor was either called reentrantly for this constructor or called multiple times.");
e[d]=de;Object.setPrototypeOf(f,b.prototype);a.b(f);return f}b.prototype=$d.prototype;Object.defineProperty(b.prototype,"constructor",{writable:!0,configurable:!0,enumerable:!1,value:b});return b}()};function ge(a,b,c){function d(b){return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e]=arguments[e];e=[];for(var f=[],l=0;l<d.length;l++){var m=d[l];m instanceof Element&&L(m)&&f.push(m);if(m instanceof DocumentFragment)for(m=m.firstChild;m;m=m.nextSibling)e.push(m);else e.push(m)}b.apply(this,d);for(d=0;d<f.length;d++)P(a,f[d]);if(L(this))for(d=0;d<e.length;d++)f=e[d],f instanceof Element&&O(a,f)}}void 0!==c.S&&(b.prepend=d(c.S));void 0!==c.append&&(b.append=d(c.append))};function he(){var a=fe;N(Document.prototype,"createElement",function(b){if(this.__CE_hasRegistry){var c=a.a.get(b);if(c)return new c.constructorFunction}b=xd.call(this,b);a.b(b);return b});N(Document.prototype,"importNode",function(b,c){b=zd.call(this,b,!!c);this.__CE_hasRegistry?Q(a,b):qd(a,b);return b});N(Document.prototype,"createElementNS",function(b,c){if(this.__CE_hasRegistry&&(null===b||"http://www.w3.org/1999/xhtml"===b)){var d=a.a.get(c);if(d)return new d.constructorFunction}b=yd.call(this,
b,c);a.b(b);return b});ge(a,Document.prototype,{S:Ad,append:Bd})};function ie(){function a(a,d){Object.defineProperty(a,"textContent",{enumerable:d.enumerable,configurable:!0,get:d.get,set:function(a){if(this.nodeType===Node.TEXT_NODE)d.set.call(this,a);else{var c=void 0;if(this.firstChild){var e=this.childNodes,h=e.length;if(0<h&&L(this)){c=Array(h);for(var k=0;k<h;k++)c[k]=e[k]}}d.set.call(this,a);if(c)for(a=0;a<c.length;a++)P(b,c[a])}}})}var b=fe;N(Node.prototype,"insertBefore",function(a,d){if(a instanceof DocumentFragment){var c=Array.prototype.slice.apply(a.childNodes);
a=Gd.call(this,a,d);if(L(this))for(d=0;d<c.length;d++)O(b,c[d]);return a}c=L(a);d=Gd.call(this,a,d);c&&P(b,a);L(this)&&O(b,a);return d});N(Node.prototype,"appendChild",function(a){if(a instanceof DocumentFragment){var c=Array.prototype.slice.apply(a.childNodes);a=Fd.call(this,a);if(L(this))for(var e=0;e<c.length;e++)O(b,c[e]);return a}c=L(a);e=Fd.call(this,a);c&&P(b,a);L(this)&&O(b,a);return e});N(Node.prototype,"cloneNode",function(a){a=Ed.call(this,!!a);this.ownerDocument.__CE_hasRegistry?Q(b,a):
qd(b,a);return a});N(Node.prototype,"removeChild",function(a){var c=L(a),e=Hd.call(this,a);c&&P(b,a);return e});N(Node.prototype,"replaceChild",function(a,d){if(a instanceof DocumentFragment){var c=Array.prototype.slice.apply(a.childNodes);a=Id.call(this,a,d);if(L(this))for(P(b,d),d=0;d<c.length;d++)O(b,c[d]);return a}c=L(a);var f=Id.call(this,a,d),g=L(this);g&&P(b,d);c&&P(b,a);g&&O(b,a);return f});Jd&&Jd.get?a(Node.prototype,Jd):pd(b,function(b){a(b,{enumerable:!0,configurable:!0,get:function(){for(var a=
[],b=0;b<this.childNodes.length;b++)a.push(this.childNodes[b].textContent);return a.join("")},set:function(a){for(;this.firstChild;)Hd.call(this,this.firstChild);Fd.call(this,document.createTextNode(a))}})})};function je(a){function b(b){return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e]=arguments[e];e=[];for(var h=[],k=0;k<d.length;k++){var l=d[k];l instanceof Element&&L(l)&&h.push(l);if(l instanceof DocumentFragment)for(l=l.firstChild;l;l=l.nextSibling)e.push(l);else e.push(l)}b.apply(this,d);for(d=0;d<h.length;d++)P(a,h[d]);if(L(this))for(d=0;d<e.length;d++)h=e[d],h instanceof Element&&O(a,h)}}var c=Element.prototype;void 0!==Wd&&(c.before=b(Wd));void 0!==Wd&&(c.after=b(Xd));void 0!==Yd&&
N(c,"replaceWith",function(b){for(var c=[],d=0;d<arguments.length;++d)c[d]=arguments[d];d=[];for(var g=[],h=0;h<c.length;h++){var k=c[h];k instanceof Element&&L(k)&&g.push(k);if(k instanceof DocumentFragment)for(k=k.firstChild;k;k=k.nextSibling)d.push(k);else d.push(k)}h=L(this);Yd.apply(this,c);for(c=0;c<g.length;c++)P(a,g[c]);if(h)for(P(a,this),c=0;c<d.length;c++)g=d[c],g instanceof Element&&O(a,g)});void 0!==Zd&&N(c,"remove",function(){var b=L(this);Zd.call(this);b&&P(a,this)})};function ke(){function a(a,b){Object.defineProperty(a,"innerHTML",{enumerable:b.enumerable,configurable:!0,get:b.get,set:function(a){var c=this,e=void 0;L(this)&&(e=[],M(this,function(a){a!==c&&e.push(a)}));b.set.call(this,a);if(e)for(var f=0;f<e.length;f++){var g=e[f];1===g.__CE_state&&d.disconnectedCallback(g)}this.ownerDocument.__CE_hasRegistry?Q(d,this):qd(d,this);return a}})}function b(a,b){N(a,"insertAdjacentElement",function(a,c){var e=L(c);a=b.call(this,a,c);e&&P(d,c);L(a)&&O(d,c);return a})}
function c(a,b){function c(a,b){for(var c=[];a!==b;a=a.nextSibling)c.push(a);for(b=0;b<c.length;b++)Q(d,c[b])}N(a,"insertAdjacentHTML",function(a,d){a=a.toLowerCase();if("beforebegin"===a){var e=this.previousSibling;b.call(this,a,d);c(e||this.parentNode.firstChild,this)}else if("afterbegin"===a)e=this.firstChild,b.call(this,a,d),c(this.firstChild,e);else if("beforeend"===a)e=this.lastChild,b.call(this,a,d),c(e||this.firstChild,null);else if("afterend"===a)e=this.nextSibling,b.call(this,a,d),c(this.nextSibling,
e);else throw new SyntaxError("The value provided ("+String(a)+") is not one of 'beforebegin', 'afterbegin', 'beforeend', or 'afterend'.");})}var d=fe;Kd&&N(Element.prototype,"attachShadow",function(a){return this.__CE_shadowRoot=a=Kd.call(this,a)});Ld&&Ld.get?a(Element.prototype,Ld):ae&&ae.get?a(HTMLElement.prototype,ae):pd(d,function(b){a(b,{enumerable:!0,configurable:!0,get:function(){return Ed.call(this,!0).innerHTML},set:function(a){var b="template"===this.localName,c=b?this.content:this,d=yd.call(document,
this.namespaceURI,this.localName);for(d.innerHTML=a;0<c.childNodes.length;)Hd.call(c,c.childNodes[0]);for(a=b?d.content:d;0<a.childNodes.length;)Fd.call(c,a.childNodes[0])}})});N(Element.prototype,"setAttribute",function(a,b){if(1!==this.__CE_state)return Nd.call(this,a,b);var c=Md.call(this,a);Nd.call(this,a,b);b=Md.call(this,a);d.attributeChangedCallback(this,a,c,b,null)});N(Element.prototype,"setAttributeNS",function(a,b,c){if(1!==this.__CE_state)return Qd.call(this,a,b,c);var e=Pd.call(this,a,
b);Qd.call(this,a,b,c);c=Pd.call(this,a,b);d.attributeChangedCallback(this,b,e,c,a)});N(Element.prototype,"removeAttribute",function(a){if(1!==this.__CE_state)return Od.call(this,a);var b=Md.call(this,a);Od.call(this,a);null!==b&&d.attributeChangedCallback(this,a,b,null,null)});N(Element.prototype,"removeAttributeNS",function(a,b){if(1!==this.__CE_state)return Rd.call(this,a,b);var c=Pd.call(this,a,b);Rd.call(this,a,b);var e=Pd.call(this,a,b);c!==e&&d.attributeChangedCallback(this,b,c,e,a)});be?b(HTMLElement.prototype,
be):Sd?b(Element.prototype,Sd):console.warn("Custom Elements: `Element#insertAdjacentElement` was not patched.");ce?c(HTMLElement.prototype,ce):Td?c(Element.prototype,Td):console.warn("Custom Elements: `Element#insertAdjacentHTML` was not patched.");ge(d,Element.prototype,{S:Ud,append:Vd});je(d)};/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
var le=window.customElements;if(!le||le.forcePolyfill||"function"!=typeof le.define||"function"!=typeof le.get){var fe=new nd;ee();he();ge(fe,DocumentFragment.prototype,{S:Cd,append:Dd});ie();ke();document.__CE_hasRegistry=!0;var customElements=new R(fe);Object.defineProperty(window,"customElements",{configurable:!0,enumerable:!0,value:customElements})};/*

Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
function me(){this.end=this.start=0;this.rules=this.parent=this.previous=null;this.cssText=this.parsedCssText="";this.atRule=!1;this.type=0;this.parsedSelector=this.selector=this.keyframesName=""}
function ne(a){a=a.replace(oe,"").replace(pe,"");var b=qe,c=a,d=new me;d.start=0;d.end=c.length;for(var e=d,f=0,g=c.length;f<g;f++)if("{"===c[f]){e.rules||(e.rules=[]);var h=e,k=h.rules[h.rules.length-1]||null;e=new me;e.start=f+1;e.parent=h;e.previous=k;h.rules.push(e)}else"}"===c[f]&&(e.end=f+1,e=e.parent||d);return b(d,a)}
function qe(a,b){var c=b.substring(a.start,a.end-1);a.parsedCssText=a.cssText=c.trim();a.parent&&(c=b.substring(a.previous?a.previous.end:a.parent.start,a.start-1),c=re(c),c=c.replace(se," "),c=c.substring(c.lastIndexOf(";")+1),c=a.parsedSelector=a.selector=c.trim(),a.atRule=0===c.indexOf("@"),a.atRule?0===c.indexOf("@media")?a.type=te:c.match(ue)&&(a.type=ve,a.keyframesName=a.selector.split(se).pop()):a.type=0===c.indexOf("--")?we:xe);if(c=a.rules)for(var d=0,e=c.length,f=void 0;d<e&&(f=c[d]);d++)qe(f,
b);return a}function re(a){return a.replace(/\\([0-9a-f]{1,6})\s/gi,function(a,c){a=c;for(c=6-a.length;c--;)a="0"+a;return"\\"+a})}
function ye(a,b,c){c=void 0===c?"":c;var d="";if(a.cssText||a.rules){var e=a.rules,f;if(f=e)f=e[0],f=!(f&&f.selector&&0===f.selector.indexOf("--"));if(f){f=0;for(var g=e.length,h=void 0;f<g&&(h=e[f]);f++)d=ye(h,b,d)}else b?b=a.cssText:(b=a.cssText,b=b.replace(ze,"").replace(Ae,""),b=b.replace(Be,"").replace(Ce,"")),(d=b.trim())&&(d="  "+d+"\n")}d&&(a.selector&&(c+=a.selector+" {\n"),c+=d,a.selector&&(c+="}\n\n"));return c}
var xe=1,ve=7,te=4,we=1E3,oe=/\/\*[^*]*\*+([^/*][^*]*\*+)*\//gim,pe=/@import[^;]*;/gim,ze=/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?(?:[;\n]|$)/gim,Ae=/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?{[^}]*?}(?:[;\n]|$)?/gim,Be=/@apply\s*\(?[^);]*\)?\s*(?:[;\n]|$)?/gim,Ce=/[^;:]*?:[^;]*?var\([^;]*\)(?:[;\n]|$)?/gim,ue=/^@[^\s]*keyframes/,se=/\s+/g;var S=!(window.ShadyDOM&&window.ShadyDOM.inUse),De;function Ee(a){De=a&&a.shimcssproperties?!1:S||!(navigator.userAgent.match(/AppleWebKit\/601|Edge\/15/)||!window.CSS||!CSS.supports||!CSS.supports("box-shadow","0 0 0 var(--foo)"))}var Fe;window.ShadyCSS&&void 0!==window.ShadyCSS.cssBuild&&(Fe=window.ShadyCSS.cssBuild);window.ShadyCSS&&void 0!==window.ShadyCSS.nativeCss?De=window.ShadyCSS.nativeCss:window.ShadyCSS?(Ee(window.ShadyCSS),window.ShadyCSS=void 0):Ee(window.WebComponents&&window.WebComponents.flags);
var T=De,Ge=Fe;var He=/(?:^|[;\s{]\s*)(--[\w-]*?)\s*:\s*(?:((?:'(?:\\'|.)*?'|"(?:\\"|.)*?"|\([^)]*?\)|[^};{])+)|\{([^}]*)\}(?:(?=[;\s}])|$))/gi,Ie=/(?:^|\W+)@apply\s*\(?([^);\n]*)\)?/gi,Je=/(--[\w-]+)\s*([:,;)]|$)/gi,Ke=/(animation\s*:)|(animation-name\s*:)/,Le=/@media\s(.*)/,Me=/\{[^}]*\}/g;var Ne=new Set;function Oe(a,b){if(!a)return"";"string"===typeof a&&(a=ne(a));b&&Pe(a,b);return ye(a,T)}function Qe(a){!a.__cssRules&&a.textContent&&(a.__cssRules=ne(a.textContent));return a.__cssRules||null}function Re(a){return!!a.parent&&a.parent.type===ve}function Pe(a,b,c,d){if(a){var e=!1,f=a.type;if(d&&f===te){var g=a.selector.match(Le);g&&(window.matchMedia(g[1]).matches||(e=!0))}f===xe?b(a):c&&f===ve?c(a):f===we&&(e=!0);if((a=a.rules)&&!e)for(e=0,f=a.length,g=void 0;e<f&&(g=a[e]);e++)Pe(g,b,c,d)}}
function Se(a,b,c,d){var e=document.createElement("style");b&&e.setAttribute("scope",b);e.textContent=a;Te(e,c,d);return e}var U=null;function Ue(a){a=document.createComment(" Shady DOM styles for "+a+" ");var b=document.head;b.insertBefore(a,(U?U.nextSibling:null)||b.firstChild);return U=a}function Te(a,b,c){b=b||document.head;b.insertBefore(a,c&&c.nextSibling||b.firstChild);U?a.compareDocumentPosition(U)===Node.DOCUMENT_POSITION_PRECEDING&&(U=a):U=a}
function Ve(a,b){for(var c=0,d=a.length;b<d;b++)if("("===a[b])c++;else if(")"===a[b]&&0===--c)return b;return-1}function We(a,b){var c=a.indexOf("var(");if(-1===c)return b(a,"","","");var d=Ve(a,c+3),e=a.substring(c+4,d);c=a.substring(0,c);a=We(a.substring(d+1),b);d=e.indexOf(",");return-1===d?b(c,e.trim(),"",a):b(c,e.substring(0,d).trim(),e.substring(d+1).trim(),a)}function Xe(a,b){S?a.setAttribute("class",b):window.ShadyDOM.nativeMethods.setAttribute.call(a,"class",b)}
function V(a){var b=a.localName,c="";b?-1<b.indexOf("-")||(c=b,b=a.getAttribute&&a.getAttribute("is")||""):(b=a.is,c=a.extends);return{is:b,J:c}}function Ye(a){for(var b=[],c="",d=0;0<=d&&d<a.length;d++)if("("===a[d]){var e=Ve(a,d);c+=a.slice(d,e+1);d=e}else","===a[d]?(b.push(c),c=""):c+=a[d];c&&b.push(c);return b}
function Ze(a){if(void 0!==Ge)return Ge;if(void 0===a.__cssBuild){var b=a.getAttribute("css-build");if(b)a.__cssBuild=b;else{a:{b="template"===a.localName?a.content.firstChild:a.firstChild;if(b instanceof Comment&&(b=b.textContent.trim().split(":"),"css-build"===b[0])){b=b[1];break a}b=""}if(""!==b){var c="template"===a.localName?a.content.firstChild:a.firstChild;c.parentNode.removeChild(c)}a.__cssBuild=b}}return a.__cssBuild||""}
function $e(a){a=void 0===a?"":a;return""!==a&&T?S?"shadow"===a:"shady"===a:!1};function af(){}function bf(a,b){cf(W,a,function(a){df(a,b||"")})}function cf(a,b,c){b.nodeType===Node.ELEMENT_NODE&&c(b);var d;"template"===b.localName?d=(b.content||b._content||b).childNodes:d=b.children||b.childNodes;if(d)for(b=0;b<d.length;b++)cf(a,d[b],c)}
function df(a,b,c){if(b)if(a.classList)c?(a.classList.remove("style-scope"),a.classList.remove(b)):(a.classList.add("style-scope"),a.classList.add(b));else if(a.getAttribute){var d=a.getAttribute("class");c?d&&(b=d.replace("style-scope","").replace(b,""),Xe(a,b)):Xe(a,(d?d+" ":"")+"style-scope "+b)}}function ef(a,b,c){cf(W,a,function(a){df(a,b,!0);df(a,c)})}function ff(a,b){cf(W,a,function(a){df(a,b||"",!0)})}
function gf(a,b,c,d,e){var f=W;e=void 0===e?"":e;""===e&&(S||"shady"===(void 0===d?"":d)?e=Oe(b,c):(a=V(a),e=hf(f,b,a.is,a.J,c)+"\n\n"));return e.trim()}function hf(a,b,c,d,e){var f=jf(c,d);c=c?"."+c:"";return Oe(b,function(b){b.c||(b.selector=b.j=kf(a,b,a.b,c,f),b.c=!0);e&&e(b,c,f)})}function jf(a,b){return b?"[is="+a+"]":a}
function kf(a,b,c,d,e){var f=Ye(b.selector);if(!Re(b)){b=0;for(var g=f.length,h=void 0;b<g&&(h=f[b]);b++)f[b]=c.call(a,h,d,e)}return f.filter(function(a){return!!a}).join(",")}function lf(a){return a.replace(mf,function(a,c,d){-1<d.indexOf("+")?d=d.replace(/\+/g,"___"):-1<d.indexOf("___")&&(d=d.replace(/___/g,"+"));return":"+c+"("+d+")"})}
function nf(a){for(var b=[],c;c=a.match(of);){var d=c.index,e=Ve(a,d);if(-1===e)throw Error(c.input+" selector missing ')'");c=a.slice(d,e+1);a=a.replace(c,"\ue000");b.push(c)}return{Z:a,matches:b}}function pf(a,b){var c=a.split("\ue000");return b.reduce(function(a,b,f){return a+b+c[f+1]},c[0])}
af.prototype.b=function(a,b,c){var d=!1;a=a.trim();var e=mf.test(a);e&&(a=a.replace(mf,function(a,b,c){return":"+b+"("+c.replace(/\s/g,"")+")"}),a=lf(a));var f=of.test(a);if(f){var g=nf(a);a=g.Z;g=g.matches}a=a.replace(qf,":host $1");a=a.replace(rf,function(a,e,f){d||(a=sf(f,e,b,c),d=d||a.stop,e=a.sa,f=a.value);return e+f});f&&(a=pf(a,g));e&&(a=lf(a));return a};
function sf(a,b,c,d){var e=a.indexOf("::slotted");0<=a.indexOf(":host")?a=tf(a,d):0!==e&&(a=c?uf(a,c):a);c=!1;0<=e&&(b="",c=!0);if(c){var f=!0;c&&(a=a.replace(vf,function(a,b){return" > "+b}))}a=a.replace(wf,function(a,b,c){return'[dir="'+c+'"] '+b+", "+b+'[dir="'+c+'"]'});return{value:a,sa:b,stop:f}}
function uf(a,b){a=a.split(/(\[.+?\])/);for(var c=[],d=0;d<a.length;d++)if(1===d%2)c.push(a[d]);else{var e=a[d];if(""!==e||d!==a.length-1)e=e.split(":"),e[0]+=b,c.push(e.join(":"))}return c.join("")}function tf(a,b){var c=a.match(xf);return(c=c&&c[2].trim()||"")?c[0].match(yf)?a.replace(xf,function(a,c,f){return b+f}):c.split(yf)[0]===b?c:"should_not_match":a.replace(":host",b)}function zf(a){":root"===a.selector&&(a.selector="html")}
af.prototype.c=function(a){return a.match(":host")?"":a.match("::slotted")?this.b(a,":not(.style-scope)"):uf(a.trim(),":not(.style-scope)")};p.Object.defineProperties(af.prototype,{a:{configurable:!0,enumerable:!0,get:function(){return"style-scope"}}});
var mf=/:(nth[-\w]+)\(([^)]+)\)/,rf=/(^|[\s>+~]+)((?:\[.+?\]|[^\s>+~=[])+)/g,yf=/[[.:#*]/,qf=/^(::slotted)/,xf=/(:host)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,vf=/(?:::slotted)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,wf=/(.*):dir\((?:(ltr|rtl))\)/,of=/:(?:matches|any|-(?:webkit|moz)-any)/,W=new af;function Af(a,b,c,d,e){this.v=a||null;this.b=b||null;this.c=c||[];this.F=null;this.cssBuild=e||"";this.J=d||"";this.a=this.o=this.A=null}function X(a){return a?a.__styleInfo:null}function Bf(a,b){return a.__styleInfo=b}Af.prototype.f=function(){return this.v};Af.prototype._getStyleRules=Af.prototype.f;function Cf(a){var b=this.matches||this.matchesSelector||this.mozMatchesSelector||this.msMatchesSelector||this.oMatchesSelector||this.webkitMatchesSelector;return b&&b.call(this,a)}var Df=navigator.userAgent.match("Trident");function Ef(){}function Ff(a){var b={},c=[],d=0;Pe(a,function(a){Gf(a);a.index=d++;a=a.i.cssText;for(var c;c=Je.exec(a);){var e=c[1];":"!==c[2]&&(b[e]=!0)}},function(a){c.push(a)});a.b=c;a=[];for(var e in b)a.push(e);return a}
function Gf(a){if(!a.i){var b={},c={};Hf(a,c)&&(b.u=c,a.rules=null);b.cssText=a.parsedCssText.replace(Me,"").replace(He,"");a.i=b}}function Hf(a,b){var c=a.i;if(c){if(c.u)return Object.assign(b,c.u),!0}else{c=a.parsedCssText;for(var d;a=He.exec(c);){d=(a[2]||a[3]).trim();if("inherit"!==d||"unset"!==d)b[a[1].trim()]=d;d=!0}return d}}
function If(a,b,c){b&&(b=0<=b.indexOf(";")?Jf(a,b,c):We(b,function(b,e,f,g){if(!e)return b+g;(e=If(a,c[e],c))&&"initial"!==e?"apply-shim-inherit"===e&&(e="inherit"):e=If(a,c[f]||f,c)||f;return b+(e||"")+g}));return b&&b.trim()||""}
function Jf(a,b,c){b=b.split(";");for(var d=0,e,f;d<b.length;d++)if(e=b[d]){Ie.lastIndex=0;if(f=Ie.exec(e))e=If(a,c[f[1]],c);else if(f=e.indexOf(":"),-1!==f){var g=e.substring(f);g=g.trim();g=If(a,g,c)||g;e=e.substring(0,f)+g}b[d]=e&&e.lastIndexOf(";")===e.length-1?e.slice(0,-1):e||""}return b.join(";")}
function Kf(a,b){var c={},d=[];Pe(a,function(a){a.i||Gf(a);var e=a.j||a.parsedSelector;b&&a.i.u&&e&&Cf.call(b,e)&&(Hf(a,c),a=a.index,e=parseInt(a/32,10),d[e]=(d[e]||0)|1<<a%32)},null,!0);return{u:c,key:d}}
function Lf(a,b,c,d){b.i||Gf(b);if(b.i.u){var e=V(a);a=e.is;e=e.J;e=a?jf(a,e):"html";var f=b.parsedSelector,g=":host > *"===f||"html"===f,h=0===f.indexOf(":host")&&!g;"shady"===c&&(g=f===e+" > *."+e||-1!==f.indexOf("html"),h=!g&&0===f.indexOf(e));if(g||h)c=e,h&&(b.j||(b.j=kf(W,b,W.b,a?"."+a:"",e)),c=b.j||e),d({Z:c,ya:h,Ta:g})}}function Mf(a,b,c){var d={},e={};Pe(b,function(b){Lf(a,b,c,function(c){Cf.call(a._element||a,c.Z)&&(c.ya?Hf(b,d):Hf(b,e))})},null,!0);return{Aa:e,wa:d}}
function Nf(a,b,c,d){var e=V(b),f=jf(e.is,e.J),g=new RegExp("(?:^|[^.#[:])"+(b.extends?"\\"+f.slice(0,-1)+"\\]":f)+"($|[.:[\\s>+~])"),h=X(b);e=h.v;h=h.cssBuild;var k=Of(e,d);return gf(b,e,function(b){var e="";b.i||Gf(b);b.i.cssText&&(e=Jf(a,b.i.cssText,c));b.cssText=e;if(!S&&!Re(b)&&b.cssText){var h=e=b.cssText;null==b.ca&&(b.ca=Ke.test(e));if(b.ca)if(null==b.R){b.R=[];for(var l in k)h=k[l],h=h(e),e!==h&&(e=h,b.R.push(l))}else{for(l=0;l<b.R.length;++l)h=k[b.R[l]],e=h(e);h=e}b.cssText=h;b.j=b.j||b.selector;
e="."+d;l=Ye(b.j);h=0;for(var ma=l.length,Ua=void 0;h<ma&&(Ua=l[h]);h++)l[h]=Ua.match(g)?Ua.replace(f,e):e+" "+Ua;b.selector=l.join(",")}},h)}function Of(a,b){a=a.b;var c={};if(!S&&a)for(var d=0,e=a[d];d<a.length;e=a[++d]){var f=e,g=b;f.f=new RegExp("\\b"+f.keyframesName+"(?!\\B|-)","g");f.a=f.keyframesName+"-"+g;f.j=f.j||f.selector;f.selector=f.j.replace(f.keyframesName,f.a);c[e.keyframesName]=Pf(e)}return c}function Pf(a){return function(b){return b.replace(a.f,a.a)}}
function Qf(a,b){var c=Rf,d=Qe(a);a.textContent=Oe(d,function(a){var d=a.cssText=a.parsedCssText;a.i&&a.i.cssText&&(d=d.replace(ze,"").replace(Ae,""),a.cssText=Jf(c,d,b))})}p.Object.defineProperties(Ef.prototype,{a:{configurable:!0,enumerable:!0,get:function(){return"x-scope"}}});var Rf=new Ef;var Sf={},Tf=window.customElements;if(Tf&&!S){var Uf=Tf.define;Tf.define=function(a,b,c){Sf[a]||(Sf[a]=Ue(a));Uf.call(Tf,a,b,c)}};function Vf(){this.cache={}}Vf.prototype.store=function(a,b,c,d){var e=this.cache[a]||[];e.push({u:b,styleElement:c,o:d});100<e.length&&e.shift();this.cache[a]=e};Vf.prototype.fetch=function(a,b,c){if(a=this.cache[a])for(var d=a.length-1;0<=d;d--){var e=a[d],f;a:{for(f=0;f<c.length;f++){var g=c[f];if(e.u[g]!==b[g]){f=!1;break a}}f=!0}if(f)return e}};function Wf(){}var Xf=new RegExp(W.a+"\\s*([^\\s]*)");function Yf(a){return(a=(a.classList&&a.classList.value?a.classList.value:a.getAttribute("class")||"").match(Xf))?a[1]:""}function Zf(a){var b=a.getRootNode();return b===a||b===a.ownerDocument?"":(a=b.host)?V(a).is:""}
function $f(a){for(var b=0;b<a.length;b++){var c=a[b];if(c.target!==document.documentElement&&c.target!==document.head)for(var d=0;d<c.addedNodes.length;d++){var e=c.addedNodes[d];if(e.nodeType===Node.ELEMENT_NODE){var f=e.getRootNode(),g=Yf(e);if(g&&f===e.ownerDocument&&("style"!==e.localName&&"template"!==e.localName||""===Ze(e)))ff(e,g);else if(f instanceof ShadowRoot)for(f=Zf(e),f!==g&&ef(e,g,f),e=window.ShadyDOM.nativeMethods.querySelectorAll.call(e,":not(."+W.a+")"),g=0;g<e.length;g++){f=e[g];
var h=Zf(f);h&&df(f,h)}}}}}
if(!(S||window.ShadyDOM&&window.ShadyDOM.handlesDynamicScoping)){var ag=new MutationObserver($f),bg=function(a){ag.observe(a,{childList:!0,subtree:!0})};if(window.customElements&&!window.customElements.polyfillWrapFlushCallback)bg(document);else{var cg=function(){bg(document.body)};window.HTMLImports?window.HTMLImports.whenReady(cg):requestAnimationFrame(function(){if("loading"===document.readyState){var a=function(){cg();document.removeEventListener("readystatechange",a)};document.addEventListener("readystatechange",
a)}else cg()})}Wf=function(){$f(ag.takeRecords())}}var dg=Wf;var eg={};var fg=Promise.resolve();function gg(a){if(a=eg[a])a._applyShimCurrentVersion=a._applyShimCurrentVersion||0,a._applyShimValidatingVersion=a._applyShimValidatingVersion||0,a._applyShimNextVersion=(a._applyShimNextVersion||0)+1}function hg(a){return a._applyShimCurrentVersion===a._applyShimNextVersion}function ig(a){a._applyShimValidatingVersion=a._applyShimNextVersion;a._validating||(a._validating=!0,fg.then(function(){a._applyShimCurrentVersion=a._applyShimNextVersion;a._validating=!1}))};var jg=new Vf;function Y(){this.C={};this.c=document.documentElement;var a=new me;a.rules=[];this.f=Bf(this.c,new Af(a));this.l=!1;this.b=this.a=null}n=Y.prototype;n.flush=function(){dg()};n.ua=function(a){return Qe(a)};n.Ea=function(a){return Oe(a)};n.prepareTemplate=function(a,b,c){this.prepareTemplateDom(a,b);this.prepareTemplateStyles(a,b,c)};
n.prepareTemplateStyles=function(a,b,c){if(!a._prepared){S||Sf[b]||(Sf[b]=Ue(b));a._prepared=!0;a.name=b;a.extends=c;eg[b]=a;var d=Ze(a),e=$e(d);c={is:b,extends:c};var f=[];for(var g=a.content.querySelectorAll("style"),h=0;h<g.length;h++){var k=g[h];if(k.hasAttribute("shady-unscoped")){if(!S){var l=k.textContent;Ne.has(l)||(Ne.add(l),l=k.cloneNode(!0),document.head.appendChild(l));k.parentNode.removeChild(k)}}else f.push(k.textContent),k.parentNode.removeChild(k)}f=f.join("").trim();kg(this);if(!e){if(g=
!d)g=Ie.test(f)||He.test(f),Ie.lastIndex=0,He.lastIndex=0;h=ne(f);g&&T&&this.a&&this.a.transformRules(h,b);a._styleAst=h}g=[];T||(g=Ff(a._styleAst));if(!g.length||T)h=S?a.content:null,b=Sf[b]||null,d=gf(c,a._styleAst,null,d,e?f:""),d=d.length?Se(d,c.is,h,b):null,a._style=d;a.a=g}};n.prepareTemplateDom=function(a,b){var c=Ze(a);S||"shady"===c||a._domPrepared||(a._domPrepared=!0,bf(a.content,b))};
function lg(a){!a.b&&window.ShadyCSS&&window.ShadyCSS.CustomStyleInterface&&(a.b=window.ShadyCSS.CustomStyleInterface,a.b.transformCallback=function(b){a.fa(b)},a.b.validateCallback=function(){requestAnimationFrame(function(){(a.b.enqueued||a.l)&&a.flushCustomStyles()})})}function kg(a){!a.a&&window.ShadyCSS&&window.ShadyCSS.ApplyShim&&(a.a=window.ShadyCSS.ApplyShim,a.a.invalidCallback=gg);lg(a)}
n.flushCustomStyles=function(){kg(this);if(this.b){var a=this.b.processStyles();if(this.b.enqueued&&!$e(this.f.cssBuild)){if(T){if(!this.f.cssBuild)for(var b=0;b<a.length;b++){var c=this.b.getStyleForCustomStyle(a[b]);if(c&&T&&this.a){var d=Qe(c);kg(this);this.a.transformRules(d);c.textContent=Oe(d)}}}else{mg(this,this.c,this.f);for(b=0;b<a.length;b++)(c=this.b.getStyleForCustomStyle(a[b]))&&Qf(c,this.f.A);this.l&&this.styleDocument()}this.b.enqueued=!1}}};
n.styleElement=function(a,b){var c=X(a);if(!c){var d=V(a);c=d.is;d=d.J;var e=Sf[c]||null;c=eg[c];if(c){var f=c._styleAst;var g=c.a;var h=Ze(c)}f=new Af(f,e,g,d,h);c&&Bf(a,f);c=f}a!==this.c&&(this.l=!0);b&&(c.F=c.F||{},Object.assign(c.F,b));if(T){b=c;f=V(a).is;if(b.F){g=b.F;for(var k in g)null===k?a.style.removeProperty(k):a.style.setProperty(k,g[k])}if(!(!(k=eg[f])&&a!==this.c||k&&""!==Ze(k))&&k&&k._style&&!hg(k)){if(hg(k)||k._applyShimValidatingVersion!==k._applyShimNextVersion)kg(this),this.a&&
this.a.transformRules(k._styleAst,f),k._style.textContent=gf(a,b.v),ig(k);S&&(f=a.shadowRoot)&&(f=f.querySelector("style"))&&(f.textContent=gf(a,b.v));b.v=k._styleAst}}else if(k=c,this.flush(),mg(this,a,k),k.c&&k.c.length){b=V(a).is;c=(f=jg.fetch(b,k.A,k.c))?f.styleElement:null;g=k.o;(h=f&&f.o)||(h=this.C[b]=(this.C[b]||0)+1,h=b+"-"+h);k.o=h;h=k.o;d=Rf;d=c?c.textContent||"":Nf(d,a,k.A,h);e=X(a);var l=e.a;l&&!S&&l!==c&&(l._useCount--,0>=l._useCount&&l.parentNode&&l.parentNode.removeChild(l));S?e.a?
(e.a.textContent=d,c=e.a):d&&(c=Se(d,h,a.shadowRoot,e.b)):c?c.parentNode||(Df&&-1<d.indexOf("@media")&&(c.textContent=d),Te(c,null,e.b)):d&&(c=Se(d,h,null,e.b));c&&(c._useCount=c._useCount||0,e.a!=c&&c._useCount++,e.a=c);h=c;S||(c=k.o,e=d=a.getAttribute("class")||"",g&&(e=d.replace(new RegExp("\\s*x-scope\\s*"+g+"\\s*","g")," ")),e+=(e?" ":"")+"x-scope "+c,d!==e&&Xe(a,e));f||jg.store(b,k.A,h,k.o)}};function ng(a,b){return(b=b.getRootNode().host)?X(b)?b:ng(a,b):a.c}
function mg(a,b,c){a=ng(a,b);var d=X(a);a=Object.create(d.A||null);var e=Mf(b,c.v,c.cssBuild);b=Kf(d.v,b).u;Object.assign(a,e.wa,b,e.Aa);b=c.F;for(var f in b)if((e=b[f])||0===e)a[f]=e;f=Rf;b=Object.getOwnPropertyNames(a);for(e=0;e<b.length;e++)d=b[e],a[d]=If(f,a[d],a);c.A=a}n.styleDocument=function(a){this.styleSubtree(this.c,a)};
n.styleSubtree=function(a,b){var c=a.shadowRoot;(c||a===this.c)&&this.styleElement(a,b);if(b=c&&(c.children||c.childNodes))for(a=0;a<b.length;a++)this.styleSubtree(b[a]);else if(a=a.children||a.childNodes)for(b=0;b<a.length;b++)this.styleSubtree(a[b])};
n.fa=function(a){var b=this,c=Ze(a);c!==this.f.cssBuild&&(this.f.cssBuild=c);if(!$e(c)){var d=Qe(a);Pe(d,function(a){if(S)zf(a);else{var d=W;a.selector=a.parsedSelector;zf(a);a.selector=a.j=kf(d,a,d.c,void 0,void 0)}T&&""===c&&(kg(b),b.a&&b.a.transformRule(a))});T?a.textContent=Oe(d):this.f.v.rules.push(d)}};n.getComputedStyleValue=function(a,b){var c;T||(c=(X(a)||X(ng(this,a))).A[b]);return(c=c||window.getComputedStyle(a).getPropertyValue(b))?c.trim():""};
n.Da=function(a,b){var c=a.getRootNode();b=b?b.split(/\s/):[];c=c.host&&c.host.localName;if(!c){var d=a.getAttribute("class");if(d){d=d.split(/\s/);for(var e=0;e<d.length;e++)if(d[e]===W.a){c=d[e+1];break}}}c&&b.push(W.a,c);T||(c=X(a))&&c.o&&b.push(Rf.a,c.o);Xe(a,b.join(" "))};n.ra=function(a){return X(a)};n.Ca=function(a,b){df(a,b)};n.Fa=function(a,b){df(a,b,!0)};n.Ba=function(a){return Zf(a)};n.ta=function(a){return Yf(a)};Y.prototype.flush=Y.prototype.flush;Y.prototype.prepareTemplate=Y.prototype.prepareTemplate;
Y.prototype.styleElement=Y.prototype.styleElement;Y.prototype.styleDocument=Y.prototype.styleDocument;Y.prototype.styleSubtree=Y.prototype.styleSubtree;Y.prototype.getComputedStyleValue=Y.prototype.getComputedStyleValue;Y.prototype.setElementClass=Y.prototype.Da;Y.prototype._styleInfoForNode=Y.prototype.ra;Y.prototype.transformCustomStyleForDocument=Y.prototype.fa;Y.prototype.getStyleAst=Y.prototype.ua;Y.prototype.styleAstToString=Y.prototype.Ea;Y.prototype.flushCustomStyles=Y.prototype.flushCustomStyles;
Y.prototype.scopeNode=Y.prototype.Ca;Y.prototype.unscopeNode=Y.prototype.Fa;Y.prototype.scopeForNode=Y.prototype.Ba;Y.prototype.currentScopeForNode=Y.prototype.ta;Object.defineProperties(Y.prototype,{nativeShadow:{get:function(){return S}},nativeCss:{get:function(){return T}}});var Z=new Y,og,pg;window.ShadyCSS&&(og=window.ShadyCSS.ApplyShim,pg=window.ShadyCSS.CustomStyleInterface);
window.ShadyCSS={ScopingShim:Z,prepareTemplate:function(a,b,c){Z.flushCustomStyles();Z.prepareTemplate(a,b,c)},prepareTemplateDom:function(a,b){Z.prepareTemplateDom(a,b)},prepareTemplateStyles:function(a,b,c){Z.flushCustomStyles();Z.prepareTemplateStyles(a,b,c)},styleSubtree:function(a,b){Z.flushCustomStyles();Z.styleSubtree(a,b)},styleElement:function(a){Z.flushCustomStyles();Z.styleElement(a)},styleDocument:function(a){Z.flushCustomStyles();Z.styleDocument(a)},flushCustomStyles:function(){Z.flushCustomStyles()},
getComputedStyleValue:function(a,b){return Z.getComputedStyleValue(a,b)},nativeCss:T,nativeShadow:S,cssBuild:Ge};og&&(window.ShadyCSS.ApplyShim=og);pg&&(window.ShadyCSS.CustomStyleInterface=pg);var qg=window.document;window.WebComponents=window.WebComponents||{};function rg(){requestAnimationFrame(function(){window.WebComponents.ready=!0;window.document.dispatchEvent(new CustomEvent("WebComponentsReady",{bubbles:!0}))})}function sg(){rg();qg.removeEventListener("readystatechange",sg)}"loading"!==qg.readyState?rg():qg.addEventListener("readystatechange",sg);}).call(this);

//# sourceMappingURL=webcomponents-sd-ce.js.map
