/**
@license @nocompile
Copyright (c) 2018 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
'use strict';var p,aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},q="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function ba(){ba=function(){};q.Symbol||(q.Symbol=da)}var da=function(){var a=0;return function(b){return"jscomp_symbol_"+(b||"")+a++}}();
function ea(){ba();var a=q.Symbol.iterator;a||(a=q.Symbol.iterator=q.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&aa(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return fa(this)}});ea=function(){}}function fa(a){var b=0;return ha(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function ha(a){ea();a={next:a};a[q.Symbol.iterator]=function(){return this};return a}function ia(a){ea();ba();ea();var b=a[Symbol.iterator];return b?b.call(a):fa(a)}
function ja(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c}
(function(a){function b(a,b){if("function"===typeof window.CustomEvent)return new CustomEvent(a,b);var c=document.createEvent("CustomEvent");c.initCustomEvent(a,!!b.bubbles,!!b.cancelable,b.detail);return c}function c(a){if(C)return a.ownerDocument!==document?a.ownerDocument:null;var b=a.__importDoc;if(!b&&a.parentNode){b=a.parentNode;if("function"===typeof b.closest)b=b.closest("link[rel=import]");else for(;!h(b)&&(b=b.parentNode););a.__importDoc=b}return b}function d(a){var b=m(document,"link[rel=import]:not([import-dependency])"),
c=b.length;c?n(b,function(b){return g(b,function(){0===--c&&a()})}):a()}function e(a){function b(){"loading"!==document.readyState&&document.body&&(document.removeEventListener("readystatechange",b),a())}document.addEventListener("readystatechange",b);b()}function f(a){e(function(){return d(function(){return a&&a()})})}function g(a,b){if(a.__loaded)b&&b();else if("script"===a.localName&&!a.src||"style"===a.localName&&!a.firstChild)a.__loaded=!0,b&&b();else{var c=function(d){a.removeEventListener(d.type,
c);a.__loaded=!0;b&&b()};a.addEventListener("load",c);Ia&&"style"===a.localName||a.addEventListener("error",c)}}function h(a){return a.nodeType===Node.ELEMENT_NODE&&"link"===a.localName&&"import"===a.rel}function k(){var a=this;this.a={};this.b=0;this.c=new MutationObserver(function(b){return a.Ea(b)});this.c.observe(document.head,{childList:!0,subtree:!0});this.loadImports(document)}function l(a){n(m(a,"template"),function(a){n(m(a.content,'script:not([type]),script[type="application/javascript"],script[type="text/javascript"],script[type="module"]'),
function(a){var b=document.createElement("script");n(a.attributes,function(a){return b.setAttribute(a.name,a.value)});b.textContent=a.textContent;a.parentNode.replaceChild(b,a)});l(a.content)})}function m(a,b){return a.childNodes.length?a.querySelectorAll(b):W}function n(a,b,c){var d=a?a.length:0,e=c?-1:1;for(c=c?d-1:0;c<d&&0<=c;c+=e)b(a[c],c)}var x=document.createElement("link"),C="import"in x,W=x.querySelectorAll("*"),Ja=null;!1==="currentScript"in document&&Object.defineProperty(document,"currentScript",
{get:function(){return Ja||("complete"!==document.readyState?document.scripts[document.scripts.length-1]:null)},configurable:!0});var Cd=/(url\()([^)]*)(\))/g,Dd=/(@import[\s]+(?!url\())([^;]*)(;)/g,Ed=/(<link[^>]*)(rel=['|"]?stylesheet['|"]?[^>]*>)/g,G={za:function(a,b){a.href&&a.setAttribute("href",G.R(a.getAttribute("href"),b));a.src&&a.setAttribute("src",G.R(a.getAttribute("src"),b));if("style"===a.localName){var c=G.ja(a.textContent,b,Cd);a.textContent=G.ja(c,b,Dd)}},ja:function(a,b,c){return a.replace(c,
function(a,c,d,e){a=d.replace(/["']/g,"");b&&(a=G.R(a,b));return c+"'"+a+"'"+e})},R:function(a,b){if(void 0===G.W){G.W=!1;try{var c=new URL("b","http://a");c.pathname="c%20d";G.W="http://a/c%20d"===c.href}catch(ef){}}if(G.W)return(new URL(a,b)).href;c=G.ra;c||(c=document.implementation.createHTMLDocument("temp"),G.ra=c,c.ba=c.createElement("base"),c.head.appendChild(c.ba),c.aa=c.createElement("a"));c.ba.href=b;c.aa.href=a;return c.aa.href||a}},Fb={async:!0,load:function(a,b,c){if(a)if(a.match(/^data:/)){a=
a.split(",");var d=a[1];d=-1<a[0].indexOf(";base64")?atob(d):decodeURIComponent(d);b(d)}else{var e=new XMLHttpRequest;e.open("GET",a,Fb.async);e.onload=function(){var a=e.responseURL||e.getResponseHeader("Location");a&&0===a.indexOf("/")&&(a=(location.origin||location.protocol+"//"+location.host)+a);var d=e.response||e.responseText;304===e.status||0===e.status||200<=e.status&&300>e.status?b(d,a):c(d)};e.send()}else c("error: href must be specified")}},Ia=/Trident/.test(navigator.userAgent)||/Edge\/\d./i.test(navigator.userAgent);
k.prototype.loadImports=function(a){var b=this;a=m(a,"link[rel=import]");n(a,function(a){return b.o(a)})};k.prototype.o=function(a){var b=this,c=a.href;if(void 0!==this.a[c]){var d=this.a[c];d&&d.__loaded&&(a.__import=d,this.j(a))}else this.b++,this.a[c]="pending",Fb.load(c,function(a,d){a=b.Fa(a,d||c);b.a[c]=a;b.b--;b.loadImports(a);b.B()},function(){b.a[c]=null;b.b--;b.B()})};k.prototype.Fa=function(a,b){if(!a)return document.createDocumentFragment();Ia&&(a=a.replace(Ed,function(a,b,c){return-1===
a.indexOf("type=")?b+" type=import-disable "+c:a}));var c=document.createElement("template");c.innerHTML=a;if(c.content)a=c.content,l(a);else for(a=document.createDocumentFragment();c.firstChild;)a.appendChild(c.firstChild);if(c=a.querySelector("base"))b=G.R(c.getAttribute("href"),b),c.removeAttribute("href");c=m(a,'link[rel=import],link[rel=stylesheet][href][type=import-disable],style:not([type]),link[rel=stylesheet][href]:not([type]),script:not([type]),script[type="application/javascript"],script[type="text/javascript"],script[type="module"]');
var d=0;n(c,function(a){g(a);G.za(a,b);a.setAttribute("import-dependency","");if("script"===a.localName&&!a.src&&a.textContent){if("module"===a.type)throw Error("Inline module scripts are not supported in HTML Imports.");a.setAttribute("src","data:text/javascript;charset=utf-8,"+encodeURIComponent(a.textContent+("\n//# sourceURL="+b+(d?"-"+d:"")+".js\n")));a.textContent="";d++}});return a};k.prototype.B=function(){var a=this;if(!this.b){this.c.disconnect();this.flatten(document);var b=!1,c=!1,d=function(){c&&
b&&(a.loadImports(document),a.b||(a.c.observe(document.head,{childList:!0,subtree:!0}),a.ga()))};this.Ha(function(){c=!0;d()});this.Ga(function(){b=!0;d()})}};k.prototype.flatten=function(a){var b=this;a=m(a,"link[rel=import]");n(a,function(a){var c=b.a[a.href];(a.__import=c)&&c.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&(b.a[a.href]=a,a.readyState="loading",a.__import=a,b.flatten(c),a.appendChild(c))})};k.prototype.Ga=function(a){function b(e){if(e<d){var f=c[e],h=document.createElement("script");f.removeAttribute("import-dependency");
n(f.attributes,function(a){return h.setAttribute(a.name,a.value)});Ja=h;f.parentNode.replaceChild(h,f);g(h,function(){Ja=null;b(e+1)})}else a()}var c=m(document,"script[import-dependency]"),d=c.length;b(0)};k.prototype.Ha=function(a){var b=m(document,"style[import-dependency],link[rel=stylesheet][import-dependency]"),d=b.length;if(d){var e=Ia&&!!document.querySelector("link[rel=stylesheet][href][type=import-disable]");n(b,function(b){g(b,function(){b.removeAttribute("import-dependency");0===--d&&
a()});if(e&&b.parentNode!==document.head){var f=document.createElement(b.localName);f.__appliedElement=b;f.setAttribute("type","import-placeholder");b.parentNode.insertBefore(f,b.nextSibling);for(f=c(b);f&&c(f);)f=c(f);f.parentNode!==document.head&&(f=null);document.head.insertBefore(b,f);b.removeAttribute("type")}})}else a()};k.prototype.ga=function(){var a=this,b=m(document,"link[rel=import]");n(b,function(b){return a.j(b)},!0)};k.prototype.j=function(a){a.__loaded||(a.__loaded=!0,a.import&&(a.import.readyState=
"complete"),a.dispatchEvent(b(a.import?"load":"error",{bubbles:!1,cancelable:!1,detail:void 0})))};k.prototype.Ea=function(a){var b=this;n(a,function(a){return n(a.addedNodes,function(a){a&&a.nodeType===Node.ELEMENT_NODE&&(h(a)?b.o(a):b.loadImports(a))})})};var Ka=null;if(C)x=m(document,"link[rel=import]"),n(x,function(a){a.import&&"loading"===a.import.readyState||(a.__loaded=!0)}),x=function(a){a=a.target;h(a)&&(a.__loaded=!0)},document.addEventListener("load",x,!0),document.addEventListener("error",
x,!0);else{var ca=Object.getOwnPropertyDescriptor(Node.prototype,"baseURI");Object.defineProperty((!ca||ca.configurable?Node:Element).prototype,"baseURI",{get:function(){var a=h(this)?this:c(this);return a?a.href:ca&&ca.get?ca.get.call(this):(document.querySelector("base")||window.location).href},configurable:!0,enumerable:!0});Object.defineProperty(HTMLLinkElement.prototype,"import",{get:function(){return this.__import||null},configurable:!0,enumerable:!0});e(function(){Ka=new k})}f(function(){return document.dispatchEvent(b("HTMLImportsLoaded",
{cancelable:!0,bubbles:!0,detail:void 0}))});a.useNative=C;a.whenReady=f;a.importForElement=c;a.loadImports=function(a){Ka&&Ka.loadImports(a)}})(window.HTMLImports=window.HTMLImports||{});/*

Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
function ka(){this.ia=this.root=null;this.O=!1;this.w=this.K=this.X=this.assignedSlot=this.assignedNodes=this.C=null;this.childNodes=this.nextSibling=this.previousSibling=this.lastChild=this.firstChild=this.parentNode=this.F=void 0;this.na=this.da=!1;this.J={}}ka.prototype.toJSON=function(){return{}};function r(a){a.U||(a.U=new ka);return a.U}function t(a){return a&&a.U};var u=window.ShadyDOM||{};u.Ba=!(!Element.prototype.attachShadow||!Node.prototype.getRootNode);var la=Object.getOwnPropertyDescriptor(Node.prototype,"firstChild");u.s=!!(la&&la.configurable&&la.get);u.Y=u.force||!u.Ba;var ma=navigator.userAgent.match("Trident"),na=navigator.userAgent.match("Edge");void 0===u.la&&(u.la=u.s&&(ma||na));function v(a){return(a=t(a))&&void 0!==a.firstChild}function w(a){return"ShadyRoot"===a.ta}function y(a){a=a.getRootNode();if(w(a))return a}
var z=Element.prototype,oa=z.matches||z.matchesSelector||z.mozMatchesSelector||z.msMatchesSelector||z.oMatchesSelector||z.webkitMatchesSelector;function pa(a,b){if(a&&b)for(var c=Object.getOwnPropertyNames(b),d=0,e;d<c.length&&(e=c[d]);d++){var f=Object.getOwnPropertyDescriptor(b,e);f&&Object.defineProperty(a,e,f)}}function qa(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];for(d=0;d<c.length;d++)pa(a,c[d]);return a}function ra(a,b){for(var c in b)a[c]=b[c]}
var sa=document.createTextNode(""),ta=0,ua=[];(new MutationObserver(function(){for(;ua.length;)try{ua.shift()()}catch(a){throw sa.textContent=ta++,a;}})).observe(sa,{characterData:!0});function va(a){ua.push(a);sa.textContent=ta++}var wa=!!document.contains;function xa(a,b){for(;b;){if(b==a)return!0;b=b.parentNode}return!1}
function ya(a){for(var b=a.length-1;0<=b;b--){var c=a[b],d=c.getAttribute("id")||c.getAttribute("name");d&&"length"!==d&&isNaN(d)&&(a[d]=c)}a.item=function(b){return a[b]};a.namedItem=function(b){if("length"!==b&&isNaN(b)&&a[b])return a[b];for(var c=ia(a),d=c.next();!d.done;d=c.next())if(d=d.value,(d.getAttribute("id")||d.getAttribute("name"))==b)return d;return null};return a};var za=[],Aa;function Ba(a){Aa||(Aa=!0,va(Ca));za.push(a)}function Ca(){Aa=!1;for(var a=!!za.length;za.length;)za.shift()();return a}Ca.list=za;function Da(){this.a=!1;this.addedNodes=[];this.removedNodes=[];this.N=new Set}function Ea(a){a.a||(a.a=!0,va(function(){Fa(a)}))}function Fa(a){if(a.a){a.a=!1;var b=a.takeRecords();b.length&&a.N.forEach(function(a){a(b)})}}Da.prototype.takeRecords=function(){if(this.addedNodes.length||this.removedNodes.length){var a=[{addedNodes:this.addedNodes,removedNodes:this.removedNodes}];this.addedNodes=[];this.removedNodes=[];return a}return[]};
function Ga(a,b){var c=r(a);c.C||(c.C=new Da);c.C.N.add(b);var d=c.C;return{sa:b,va:d,ua:a,takeRecords:function(){return d.takeRecords()}}}function Ha(a){var b=a&&a.va;b&&(b.N.delete(a.sa),b.N.size||(r(a.ua).C=null))}
function La(a,b){var c=b.getRootNode();return a.map(function(a){var b=c===a.target.getRootNode();if(b&&a.addedNodes){if(b=Array.from(a.addedNodes).filter(function(a){return c===a.getRootNode()}),b.length)return a=Object.create(a),Object.defineProperty(a,"addedNodes",{value:b,configurable:!0}),a}else if(b)return a}).filter(function(a){return a})};var A={},Ma=Element.prototype.insertBefore,Na=Element.prototype.replaceChild,Oa=Element.prototype.removeChild,Pa=Element.prototype.setAttribute,Qa=Element.prototype.removeAttribute,Ra=Element.prototype.cloneNode,Sa=Document.prototype.importNode,Ta=Element.prototype.addEventListener,Ua=Element.prototype.removeEventListener,Va=Window.prototype.addEventListener,Wa=Window.prototype.removeEventListener,Xa=Element.prototype.dispatchEvent,Ya=Node.prototype.contains||HTMLElement.prototype.contains,Za=Document.prototype.getElementById,
$a=Element.prototype.querySelector,ab=DocumentFragment.prototype.querySelector,bb=Document.prototype.querySelector,cb=Element.prototype.querySelectorAll,db=DocumentFragment.prototype.querySelectorAll,eb=Document.prototype.querySelectorAll;A.appendChild=Element.prototype.appendChild;A.insertBefore=Ma;A.replaceChild=Na;A.removeChild=Oa;A.setAttribute=Pa;A.removeAttribute=Qa;A.cloneNode=Ra;A.importNode=Sa;A.addEventListener=Ta;A.removeEventListener=Ua;A.Ma=Va;A.Na=Wa;A.dispatchEvent=Xa;A.contains=Ya;
A.getElementById=Za;A.Va=$a;A.Ya=ab;A.Ta=bb;A.querySelector=function(a){switch(this.nodeType){case Node.ELEMENT_NODE:return $a.call(this,a);case Node.DOCUMENT_NODE:return bb.call(this,a);default:return ab.call(this,a)}};A.Wa=cb;A.Za=db;A.Ua=eb;A.querySelectorAll=function(a){switch(this.nodeType){case Node.ELEMENT_NODE:return cb.call(this,a);case Node.DOCUMENT_NODE:return eb.call(this,a);default:return db.call(this,a)}};var fb=/[&\u00A0"]/g,gb=/[&\u00A0<>]/g;function hb(a){switch(a){case "&":return"&amp;";case "<":return"&lt;";case ">":return"&gt;";case '"':return"&quot;";case "\u00a0":return"&nbsp;"}}function ib(a){for(var b={},c=0;c<a.length;c++)b[a[c]]=!0;return b}var jb=ib("area base br col command embed hr img input keygen link meta param source track wbr".split(" ")),kb=ib("style script xmp iframe noembed noframes plaintext noscript".split(" "));
function lb(a,b){"template"===a.localName&&(a=a.content);for(var c="",d=b?b(a):a.childNodes,e=0,f=d.length,g;e<f&&(g=d[e]);e++){a:{var h=g;var k=a;var l=b;switch(h.nodeType){case Node.ELEMENT_NODE:for(var m=h.localName,n="<"+m,x=h.attributes,C=0;k=x[C];C++)n+=" "+k.name+'="'+k.value.replace(fb,hb)+'"';n+=">";h=jb[m]?n:n+lb(h,l)+"</"+m+">";break a;case Node.TEXT_NODE:h=h.data;h=k&&kb[k.localName]?h:h.replace(gb,hb);break a;case Node.COMMENT_NODE:h="\x3c!--"+h.data+"--\x3e";break a;default:throw window.console.error(h),
Error("not implemented");}}c+=h}return c};var B={},D=document.createTreeWalker(document,NodeFilter.SHOW_ALL,null,!1),E=document.createTreeWalker(document,NodeFilter.SHOW_ELEMENT,null,!1);function mb(a){var b=[];D.currentNode=a;for(a=D.firstChild();a;)b.push(a),a=D.nextSibling();return b}B.parentNode=function(a){D.currentNode=a;return D.parentNode()};B.firstChild=function(a){D.currentNode=a;return D.firstChild()};B.lastChild=function(a){D.currentNode=a;return D.lastChild()};B.previousSibling=function(a){D.currentNode=a;return D.previousSibling()};
B.nextSibling=function(a){D.currentNode=a;return D.nextSibling()};B.childNodes=mb;B.parentElement=function(a){E.currentNode=a;return E.parentNode()};B.firstElementChild=function(a){E.currentNode=a;return E.firstChild()};B.lastElementChild=function(a){E.currentNode=a;return E.lastChild()};B.previousElementSibling=function(a){E.currentNode=a;return E.previousSibling()};B.nextElementSibling=function(a){E.currentNode=a;return E.nextSibling()};
B.children=function(a){var b=[];E.currentNode=a;for(a=E.firstChild();a;)b.push(a),a=E.nextSibling();return ya(b)};B.innerHTML=function(a){return lb(a,function(a){return mb(a)})};B.textContent=function(a){switch(a.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:a=document.createTreeWalker(a,NodeFilter.SHOW_TEXT,null,!1);for(var b="",c;c=a.nextNode();)b+=c.nodeValue;return b;default:return a.nodeValue}};var F={},nb=u.s,ob=[Node.prototype,Element.prototype,HTMLElement.prototype];function H(a){var b;a:{for(b=0;b<ob.length;b++){var c=ob[b];if(c.hasOwnProperty(a)){b=c;break a}}b=void 0}if(!b)throw Error("Could not find descriptor for "+a);return Object.getOwnPropertyDescriptor(b,a)}
var I=nb?{parentNode:H("parentNode"),firstChild:H("firstChild"),lastChild:H("lastChild"),previousSibling:H("previousSibling"),nextSibling:H("nextSibling"),childNodes:H("childNodes"),parentElement:H("parentElement"),previousElementSibling:H("previousElementSibling"),nextElementSibling:H("nextElementSibling"),innerHTML:H("innerHTML"),textContent:H("textContent"),firstElementChild:H("firstElementChild"),lastElementChild:H("lastElementChild"),children:H("children")}:{},pb=nb?{firstElementChild:Object.getOwnPropertyDescriptor(DocumentFragment.prototype,
"firstElementChild"),lastElementChild:Object.getOwnPropertyDescriptor(DocumentFragment.prototype,"lastElementChild"),children:Object.getOwnPropertyDescriptor(DocumentFragment.prototype,"children")}:{},qb=nb?{firstElementChild:Object.getOwnPropertyDescriptor(Document.prototype,"firstElementChild"),lastElementChild:Object.getOwnPropertyDescriptor(Document.prototype,"lastElementChild"),children:Object.getOwnPropertyDescriptor(Document.prototype,"children")}:{};F.ha=I;F.Xa=pb;F.Sa=qb;F.parentNode=function(a){return I.parentNode.get.call(a)};
F.firstChild=function(a){return I.firstChild.get.call(a)};F.lastChild=function(a){return I.lastChild.get.call(a)};F.previousSibling=function(a){return I.previousSibling.get.call(a)};F.nextSibling=function(a){return I.nextSibling.get.call(a)};F.childNodes=function(a){return Array.prototype.slice.call(I.childNodes.get.call(a))};F.parentElement=function(a){return I.parentElement.get.call(a)};F.previousElementSibling=function(a){return I.previousElementSibling.get.call(a)};F.nextElementSibling=function(a){return I.nextElementSibling.get.call(a)};
F.innerHTML=function(a){return I.innerHTML.get.call(a)};F.textContent=function(a){return I.textContent.get.call(a)};F.children=function(a){switch(a.nodeType){case Node.DOCUMENT_FRAGMENT_NODE:return pb.children.get.call(a);case Node.DOCUMENT_NODE:return qb.children.get.call(a);default:return I.children.get.call(a)}};
F.firstElementChild=function(a){switch(a.nodeType){case Node.DOCUMENT_FRAGMENT_NODE:return pb.firstElementChild.get.call(a);case Node.DOCUMENT_NODE:return qb.firstElementChild.get.call(a);default:return I.firstElementChild.get.call(a)}};F.lastElementChild=function(a){switch(a.nodeType){case Node.DOCUMENT_FRAGMENT_NODE:return pb.lastElementChild.get.call(a);case Node.DOCUMENT_NODE:return qb.lastElementChild.get.call(a);default:return I.lastElementChild.get.call(a)}};var J=u.la?F:B;function rb(a){for(;a.firstChild;)a.removeChild(a.firstChild)}
var sb=u.s,tb=document.implementation.createHTMLDocument("inert"),ub=Object.getOwnPropertyDescriptor(Node.prototype,"isConnected"),vb=ub&&ub.get,wb=Object.getOwnPropertyDescriptor(Document.prototype,"activeElement"),xb={parentElement:{get:function(){var a=t(this);(a=a&&a.parentNode)&&a.nodeType!==Node.ELEMENT_NODE&&(a=null);return void 0!==a?a:J.parentElement(this)},configurable:!0},parentNode:{get:function(){var a=t(this);a=a&&a.parentNode;return void 0!==a?a:J.parentNode(this)},configurable:!0},
nextSibling:{get:function(){var a=t(this);a=a&&a.nextSibling;return void 0!==a?a:J.nextSibling(this)},configurable:!0},previousSibling:{get:function(){var a=t(this);a=a&&a.previousSibling;return void 0!==a?a:J.previousSibling(this)},configurable:!0},nextElementSibling:{get:function(){var a=t(this);if(a&&void 0!==a.nextSibling){for(a=this.nextSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.nextSibling;return a}return J.nextElementSibling(this)},configurable:!0},previousElementSibling:{get:function(){var a=
t(this);if(a&&void 0!==a.previousSibling){for(a=this.previousSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.previousSibling;return a}return J.previousElementSibling(this)},configurable:!0}},yb={className:{get:function(){return this.getAttribute("class")||""},set:function(a){this.setAttribute("class",a)},configurable:!0}},zb={childNodes:{get:function(){if(v(this)){var a=t(this);if(!a.childNodes){a.childNodes=[];for(var b=this.firstChild;b;b=b.nextSibling)a.childNodes.push(b)}var c=a.childNodes}else c=
J.childNodes(this);c.item=function(a){return c[a]};return c},configurable:!0},childElementCount:{get:function(){return this.children.length},configurable:!0},firstChild:{get:function(){var a=t(this);a=a&&a.firstChild;return void 0!==a?a:J.firstChild(this)},configurable:!0},lastChild:{get:function(){var a=t(this);a=a&&a.lastChild;return void 0!==a?a:J.lastChild(this)},configurable:!0},textContent:{get:function(){if(v(this)){for(var a=[],b=0,c=this.childNodes,d;d=c[b];b++)d.nodeType!==Node.COMMENT_NODE&&
a.push(d.textContent);return a.join("")}return J.textContent(this)},set:function(a){if("undefined"===typeof a||null===a)a="";switch(this.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:if(!v(this)&&sb){var b=this.firstChild;(b!=this.lastChild||b&&b.nodeType!=Node.TEXT_NODE)&&rb(this);F.ha.textContent.set.call(this,a)}else rb(this),(0<a.length||this.nodeType===Node.ELEMENT_NODE)&&this.appendChild(document.createTextNode(a));break;default:this.nodeValue=a}},configurable:!0},firstElementChild:{get:function(){var a=
t(this);if(a&&void 0!==a.firstChild){for(a=this.firstChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.nextSibling;return a}return J.firstElementChild(this)},configurable:!0},lastElementChild:{get:function(){var a=t(this);if(a&&void 0!==a.lastChild){for(a=this.lastChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.previousSibling;return a}return J.lastElementChild(this)},configurable:!0},children:{get:function(){return v(this)?ya(Array.prototype.filter.call(this.childNodes,function(a){return a.nodeType===Node.ELEMENT_NODE})):
J.children(this)},configurable:!0},innerHTML:{get:function(){return v(this)?lb("template"===this.localName?this.content:this):J.innerHTML(this)},set:function(a){var b="template"===this.localName?this.content:this;rb(b);var c=this.localName||"div";c=this.namespaceURI&&this.namespaceURI!==tb.namespaceURI?tb.createElementNS(this.namespaceURI,c):tb.createElement(c);sb?F.ha.innerHTML.set.call(c,a):c.innerHTML=a;for(a="template"===this.localName?c.content:c;a.firstChild;)b.appendChild(a.firstChild)},configurable:!0}},
Ab={shadowRoot:{get:function(){var a=t(this);return a&&a.ia||null},configurable:!0}},Bb={activeElement:{get:function(){var a=wb&&wb.get?wb.get.call(document):u.s?void 0:document.activeElement;if(a&&a.nodeType){var b=!!w(this);if(this===document||b&&this.host!==a&&A.contains.call(this.host,a)){for(b=y(a);b&&b!==this;)a=b.host,b=y(a);a=this===document?b?null:a:b===this?a:null}else a=null}else a=null;return a},set:function(){},configurable:!0}};
function K(a,b,c){for(var d in b){var e=Object.getOwnPropertyDescriptor(a,d);e&&e.configurable||!e&&c?Object.defineProperty(a,d,b[d]):c&&console.warn("Could not define",d,"on",a)}}function L(a){K(a,xb);K(a,yb);K(a,zb);K(a,Bb)}
function Cb(){var a=Db.prototype;a.__proto__=DocumentFragment.prototype;K(a,xb,!0);K(a,zb,!0);K(a,Bb,!0);Object.defineProperties(a,{nodeType:{value:Node.DOCUMENT_FRAGMENT_NODE,configurable:!0},nodeName:{value:"#document-fragment",configurable:!0},nodeValue:{value:null,configurable:!0}});["localName","namespaceURI","prefix"].forEach(function(b){Object.defineProperty(a,b,{value:void 0,configurable:!0})});["ownerDocument","baseURI","isConnected"].forEach(function(b){Object.defineProperty(a,b,{get:function(){return this.host[b]},
configurable:!0})})}var Eb=u.s?function(){}:function(a){var b=r(a);b.da||(b.da=!0,K(a,xb,!0),K(a,yb,!0))},Gb=u.s?function(){}:function(a){r(a).na||(K(a,zb,!0),K(a,Ab,!0))};var Hb=J.childNodes;function Ib(a,b,c){Eb(a);c=c||null;var d=r(a),e=r(b),f=c?r(c):null;d.previousSibling=c?f.previousSibling:b.lastChild;if(f=t(d.previousSibling))f.nextSibling=a;if(f=t(d.nextSibling=c))f.previousSibling=a;d.parentNode=b;c?c===e.firstChild&&(e.firstChild=a):(e.lastChild=a,e.firstChild||(e.firstChild=a));e.childNodes=null}
function Jb(a){var b=r(a);if(void 0===b.firstChild){b.childNodes=null;var c=Hb(a);b.firstChild=c[0]||null;b.lastChild=c[c.length-1]||null;Gb(a);for(b=0;b<c.length;b++){var d=c[b],e=r(d);e.parentNode=a;e.nextSibling=c[b+1]||null;e.previousSibling=c[b-1]||null;Eb(d)}}};var Kb=J.parentNode;
function Lb(a,b,c){if(b===a)throw Error("Failed to execute 'appendChild' on 'Node': The new child element contains the parent.");if(c){var d=t(c);d=d&&d.parentNode;if(void 0!==d&&d!==a||void 0===d&&Kb(c)!==a)throw Error("Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.");}if(c===b)return b;b.parentNode&&Mb(b.parentNode,b);var e,f;if(!b.__noInsertionPoint){if(f=e=y(a)){var g;"slot"===b.localName?g=[b]:b.querySelectorAll&&
(g=b.querySelectorAll("slot"));f=g&&g.length?g:void 0}f&&(g=e,d=f,g.a=g.a||[],g.f=g.f||[],g.g=g.g||{},g.a.push.apply(g.a,[].concat(d instanceof Array?d:ja(ia(d)))))}("slot"===a.localName||f)&&(e=e||y(a))&&M(e);if(v(a)){e=c;Gb(a);f=r(a);void 0!==f.firstChild&&(f.childNodes=null);if(b.nodeType===Node.DOCUMENT_FRAGMENT_NODE){f=b.childNodes;for(g=0;g<f.length;g++)Ib(f[g],a,e);e=r(b);f=void 0!==e.firstChild?null:void 0;e.firstChild=e.lastChild=f;e.childNodes=f}else Ib(b,a,e);e=t(a);if(Nb(a)){M(e.root);
var h=!0}else e.root&&(h=!0)}h||(h=w(a)?a.host:a,c?(c=Ob(c),A.insertBefore.call(h,b,c)):A.appendChild.call(h,b));Pb(a,b);return b}
function Mb(a,b){if(b.parentNode!==a)throw Error("The node to be removed is not a child of this node: "+b);var c=y(b),d=t(a);if(v(a)){var e=r(b),f=r(a);b===f.firstChild&&(f.firstChild=e.nextSibling);b===f.lastChild&&(f.lastChild=e.previousSibling);var g=e.previousSibling,h=e.nextSibling;g&&(r(g).nextSibling=h);h&&(r(h).previousSibling=g);e.parentNode=e.previousSibling=e.nextSibling=void 0;void 0!==f.childNodes&&(f.childNodes=null);if(Nb(a)){M(d.root);var k=!0}}Qb(b);if(c){(e=a&&"slot"===a.localName)&&
(k=!0);if(c.f){Rb(c);f=c.g;for(W in f)for(g=f[W],h=0;h<g.length;h++){var l=g[h];if(xa(b,l)){g.splice(h,1);var m=c.f.indexOf(l);0<=m&&c.f.splice(m,1);h--;m=t(l);if(l=m.w)for(var n=0;n<l.length;n++){var x=l[n],C=Sb(x);C&&A.removeChild.call(C,x)}m.w=[];m.assignedNodes=[];m=!0}}var W=m}else W=void 0;(W||e)&&M(c)}k||(k=w(a)?a.host:a,(!d.root&&"slot"!==b.localName||k===Kb(b))&&A.removeChild.call(k,b));Pb(a,null,b);return b}
function Qb(a){var b=t(a);if(b&&void 0!==b.F){b=a.childNodes;for(var c=0,d=b.length,e;c<d&&(e=b[c]);c++)Qb(e)}if(a=t(a))a.F=void 0}function Ob(a){var b=a;a&&"slot"===a.localName&&(b=(b=(b=t(a))&&b.w)&&b.length?b[0]:Ob(a.nextSibling));return b}function Nb(a){return(a=(a=t(a))&&a.root)&&Tb(a)}
function Ub(a,b){if("slot"===b)a=a.parentNode,Nb(a)&&M(t(a).root);else if("slot"===a.localName&&"name"===b&&(b=y(a))){if(b.f){var c=a.qa,d=Vb(a);if(d!==c){c=b.g[c];var e=c.indexOf(a);0<=e&&c.splice(e,1);c=b.g[d]||(b.g[d]=[]);c.push(a);1<c.length&&(b.g[d]=Wb(c))}}M(b)}}function Pb(a,b,c){if(a=(a=t(a))&&a.C)b&&a.addedNodes.push(b),c&&a.removedNodes.push(c),Ea(a)}
function Xb(a){if(a&&a.nodeType){var b=r(a),c=b.F;void 0===c&&(w(a)?(c=a,b.F=c):(c=(c=a.parentNode)?Xb(c):a,A.contains.call(document.documentElement,a)&&(b.F=c)));return c}}function Yb(a,b,c){var d=[];Zb(a.childNodes,b,c,d);return d}function Zb(a,b,c,d){for(var e=0,f=a.length,g;e<f&&(g=a[e]);e++){var h;if(h=g.nodeType===Node.ELEMENT_NODE){h=g;var k=b,l=c,m=d,n=k(h);n&&m.push(h);l&&l(n)?h=n:(Zb(h.childNodes,k,l,m),h=void 0)}if(h)break}}var $b=null;
function ac(a,b,c){$b||($b=window.ShadyCSS&&window.ShadyCSS.ScopingShim);$b&&"class"===b?$b.setElementClass(a,c):(A.setAttribute.call(a,b,c),Ub(a,b))}function bc(a,b){if(a.ownerDocument!==document||"template"===a.localName)return A.importNode.call(document,a,b);var c=A.importNode.call(document,a,!1);if(b){a=a.childNodes;b=0;for(var d;b<a.length;b++)d=bc(a[b],!0),c.appendChild(d)}return c};var cc="__eventWrappers"+Date.now(),dc=function(){var a=Object.getOwnPropertyDescriptor(Event.prototype,"composed");return a?function(b){return a.get.call(b)}:null}(),ec={blur:!0,focus:!0,focusin:!0,focusout:!0,click:!0,dblclick:!0,mousedown:!0,mouseenter:!0,mouseleave:!0,mousemove:!0,mouseout:!0,mouseover:!0,mouseup:!0,wheel:!0,beforeinput:!0,input:!0,keydown:!0,keyup:!0,compositionstart:!0,compositionupdate:!0,compositionend:!0,touchstart:!0,touchend:!0,touchmove:!0,touchcancel:!0,pointerover:!0,
pointerenter:!0,pointerdown:!0,pointermove:!0,pointerup:!0,pointercancel:!0,pointerout:!0,pointerleave:!0,gotpointercapture:!0,lostpointercapture:!0,dragstart:!0,drag:!0,dragenter:!0,dragleave:!0,dragover:!0,drop:!0,dragend:!0,DOMActivate:!0,DOMFocusIn:!0,DOMFocusOut:!0,keypress:!0},fc={DOMAttrModified:!0,DOMAttributeNameChanged:!0,DOMCharacterDataModified:!0,DOMElementNameChanged:!0,DOMNodeInserted:!0,DOMNodeInsertedIntoDocument:!0,DOMNodeRemoved:!0,DOMNodeRemovedFromDocument:!0,DOMSubtreeModified:!0};
function gc(a,b){var c=[],d=a;for(a=a===window?window:a.getRootNode();d;)c.push(d),d=d.assignedSlot?d.assignedSlot:d.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&d.host&&(b||d!==a)?d.host:d.parentNode;c[c.length-1]===document&&c.push(window);return c}function hc(a,b){if(!w)return a;a=gc(a,!0);for(var c=0,d,e,f,g;c<b.length;c++)if(d=b[c],f=d===window?window:d.getRootNode(),f!==e&&(g=a.indexOf(f),e=f),!w(f)||-1<g)return d}
var ic={get composed(){void 0===this.I&&(dc?this.I=dc(this):!1!==this.isTrusted&&(this.I=ec[this.type]));return this.I||!1},composedPath:function(){this.ca||(this.ca=gc(this.__target,this.composed));return this.ca},get target(){return hc(this.currentTarget,this.composedPath())},get relatedTarget(){if(!this.T)return null;this.ea||(this.ea=gc(this.T,!0));return hc(this.currentTarget,this.ea)},stopPropagation:function(){Event.prototype.stopPropagation.call(this);this.S=!0},stopImmediatePropagation:function(){Event.prototype.stopImmediatePropagation.call(this);
this.S=this.ma=!0}};function jc(a){function b(b,d){b=new a(b,d);b.I=d&&!!d.composed;return b}ra(b,a);b.prototype=a.prototype;return b}var kc={focus:!0,blur:!0};function lc(a){return a.__target!==a.target||a.T!==a.relatedTarget}function mc(a,b,c){if(c=b.__handlers&&b.__handlers[a.type]&&b.__handlers[a.type][c])for(var d=0,e;(e=c[d])&&(!lc(a)||a.target!==a.relatedTarget)&&(e.call(b,a),!a.ma);d++);}
function nc(a){var b=a.composedPath();Object.defineProperty(a,"currentTarget",{get:function(){return d},configurable:!0});for(var c=b.length-1;0<=c;c--){var d=b[c];mc(a,d,"capture");if(a.S)return}Object.defineProperty(a,"eventPhase",{get:function(){return Event.AT_TARGET}});var e;for(c=0;c<b.length;c++){d=b[c];var f=t(d);f=f&&f.root;if(0===c||f&&f===e)if(mc(a,d,"bubble"),d!==window&&(e=d.getRootNode()),a.S)break}}
function oc(a,b,c,d,e,f){for(var g=0;g<a.length;g++){var h=a[g],k=h.type,l=h.capture,m=h.once,n=h.passive;if(b===h.node&&c===k&&d===l&&e===m&&f===n)return g}return-1}
function pc(a,b,c){if(b){var d=typeof b;if("function"===d||"object"===d)if("object"!==d||b.handleEvent&&"function"===typeof b.handleEvent){var e=this instanceof Window?A.Ma:A.addEventListener;if(fc[a])return e.call(this,a,b,c);if(c&&"object"===typeof c){var f=!!c.capture;var g=!!c.once;var h=!!c.passive}else f=!!c,h=g=!1;var k=c&&c.V||this,l=b[cc];if(l){if(-1<oc(l,k,a,f,g,h))return}else b[cc]=[];l=function(e){g&&this.removeEventListener(a,b,c);e.__target||qc(e);if(k!==this){var f=Object.getOwnPropertyDescriptor(e,
"currentTarget");Object.defineProperty(e,"currentTarget",{get:function(){return k},configurable:!0})}if(!w(k)||-1!=e.composedPath().indexOf(k))if(e.composed||-1<e.composedPath().indexOf(k))if(lc(e)&&e.target===e.relatedTarget)e.eventPhase===Event.BUBBLING_PHASE&&e.stopImmediatePropagation();else if(e.eventPhase===Event.CAPTURING_PHASE||e.bubbles||e.target===k||k instanceof Window){var h="function"===d?b.call(k,e):b.handleEvent&&b.handleEvent(e);k!==this&&(f?(Object.defineProperty(e,"currentTarget",
f),f=null):delete e.currentTarget);return h}};b[cc].push({node:k,type:a,capture:f,once:g,passive:h,Oa:l});kc[a]?(this.__handlers=this.__handlers||{},this.__handlers[a]=this.__handlers[a]||{capture:[],bubble:[]},this.__handlers[a][f?"capture":"bubble"].push(l)):e.call(this,a,l,c)}}}
function rc(a,b,c){if(b){var d=this instanceof Window?A.Na:A.removeEventListener;if(fc[a])return d.call(this,a,b,c);if(c&&"object"===typeof c){var e=!!c.capture;var f=!!c.once;var g=!!c.passive}else e=!!c,g=f=!1;var h=c&&c.V||this,k=void 0;var l=null;try{l=b[cc]}catch(m){}l&&(f=oc(l,h,a,e,f,g),-1<f&&(k=l.splice(f,1)[0].Oa,l.length||(b[cc]=void 0)));d.call(this,a,k||b,c);k&&kc[a]&&this.__handlers&&this.__handlers[a]&&(a=this.__handlers[a][e?"capture":"bubble"],k=a.indexOf(k),-1<k&&a.splice(k,1))}}
function sc(){for(var a in kc)window.addEventListener(a,function(a){a.__target||(qc(a),nc(a))},!0)}function qc(a){a.__target=a.target;a.T=a.relatedTarget;if(u.s){var b=Object.getPrototypeOf(a);if(!b.hasOwnProperty("__patchProto")){var c=Object.create(b);c.Qa=b;pa(c,ic);b.__patchProto=c}a.__proto__=b.__patchProto}else pa(a,ic)}var tc=jc(window.Event),uc=jc(window.CustomEvent),vc=jc(window.MouseEvent);
function wc(){window.Event=tc;window.CustomEvent=uc;window.MouseEvent=vc;sc();if(!dc&&Object.getOwnPropertyDescriptor(Event.prototype,"isTrusted")){var a=function(){var a=new MouseEvent("click",{bubbles:!0,cancelable:!0,composed:!0});this.dispatchEvent(a)};Element.prototype.click?Element.prototype.click=a:HTMLElement.prototype.click&&(HTMLElement.prototype.click=a)}};function xc(a,b){return{index:a,G:[],M:b}}
function yc(a,b,c,d){var e=0,f=0,g=0,h=0,k=Math.min(b-e,d-f);if(0==e&&0==f)a:{for(g=0;g<k;g++)if(a[g]!==c[g])break a;g=k}if(b==a.length&&d==c.length){h=a.length;for(var l=c.length,m=0;m<k-g&&zc(a[--h],c[--l]);)m++;h=m}e+=g;f+=g;b-=h;d-=h;if(0==b-e&&0==d-f)return[];if(e==b){for(b=xc(e,0);f<d;)b.G.push(c[f++]);return[b]}if(f==d)return[xc(e,b-e)];k=e;g=f;d=d-g+1;h=b-k+1;b=Array(d);for(l=0;l<d;l++)b[l]=Array(h),b[l][0]=l;for(l=0;l<h;l++)b[0][l]=l;for(l=1;l<d;l++)for(m=1;m<h;m++)if(a[k+m-1]===c[g+l-1])b[l][m]=
b[l-1][m-1];else{var n=b[l-1][m]+1,x=b[l][m-1]+1;b[l][m]=n<x?n:x}k=b.length-1;g=b[0].length-1;d=b[k][g];for(a=[];0<k||0<g;)0==k?(a.push(2),g--):0==g?(a.push(3),k--):(h=b[k-1][g-1],l=b[k-1][g],m=b[k][g-1],n=l<m?l<h?l:h:m<h?m:h,n==h?(h==d?a.push(0):(a.push(1),d=h),k--,g--):n==l?(a.push(3),k--,d=l):(a.push(2),g--,d=m));a.reverse();b=void 0;k=[];for(g=0;g<a.length;g++)switch(a[g]){case 0:b&&(k.push(b),b=void 0);e++;f++;break;case 1:b||(b=xc(e,0));b.M++;e++;b.G.push(c[f]);f++;break;case 2:b||(b=xc(e,0));
b.M++;e++;break;case 3:b||(b=xc(e,0)),b.G.push(c[f]),f++}b&&k.push(b);return k}function zc(a,b){return a===b};var Sb=J.parentNode,Ac=J.childNodes,Bc={},N=u.deferConnectionCallbacks&&"loading"===document.readyState,Cc;function Dc(a){var b=[];do b.unshift(a);while(a=a.parentNode);return b}
function Db(a,b,c){if(a!==Bc)throw new TypeError("Illegal constructor");this.ta="ShadyRoot";this.host=b;this.c=c&&c.mode;Jb(b);a=r(b);a.root=this;a.ia="closed"!==this.c?this:null;a=r(this);a.firstChild=a.lastChild=a.parentNode=a.nextSibling=a.previousSibling=null;a.childNodes=[];this.b=this.L=!1;this.a=this.g=this.f=null;M(this)}function M(a){a.L||(a.L=!0,Ba(function(){return Ec(a)}))}
function Ec(a){for(var b;a;){a.L&&(b=a);a:{var c=a;a=c.host.getRootNode();if(w(a))for(var d=c.host.childNodes,e=0;e<d.length;e++)if(c=d[e],"slot"==c.localName)break a;a=void 0}}b&&b._renderRoot()}
Db.prototype._renderRoot=function(){var a=N;N=!0;this.L=!1;if(this.f){Rb(this);for(var b=0,c;b<this.f.length;b++){c=this.f[b];var d=t(c),e=d.assignedNodes;d.assignedNodes=[];d.w=[];if(d.X=e)for(d=0;d<e.length;d++){var f=t(e[d]);f.K=f.assignedSlot;f.assignedSlot===c&&(f.assignedSlot=null)}}for(c=this.host.firstChild;c;c=c.nextSibling)Fc(this,c);for(b=0;b<this.f.length;b++){c=this.f[b];e=t(c);if(!e.assignedNodes.length)for(d=c.firstChild;d;d=d.nextSibling)Fc(this,d,c);(d=(d=t(c.parentNode))&&d.root)&&
Tb(d)&&d._renderRoot();Gc(this,e.w,e.assignedNodes);if(d=e.X){for(f=0;f<d.length;f++)t(d[f]).K=null;e.X=null;d.length>e.assignedNodes.length&&(e.O=!0)}e.O&&(e.O=!1,Hc(this,c))}b=this.f;c=[];for(e=0;e<b.length;e++)d=b[e].parentNode,(f=t(d))&&f.root||!(0>c.indexOf(d))||c.push(d);for(b=0;b<c.length;b++){e=c[b];d=e===this?this.host:e;f=[];e=e.childNodes;for(var g=0;g<e.length;g++){var h=e[g];if("slot"==h.localName){h=t(h).w;for(var k=0;k<h.length;k++)f.push(h[k])}else f.push(h)}e=void 0;g=Ac(d);h=yc(f,
f.length,g,g.length);for(var l=k=0;k<h.length&&(e=h[k]);k++){for(var m=0,n;m<e.G.length&&(n=e.G[m]);m++)Sb(n)===d&&A.removeChild.call(d,n),g.splice(e.index+l,1);l-=e.M}for(l=0;l<h.length&&(e=h[l]);l++)for(k=g[e.index],m=e.index;m<e.index+e.M;m++)n=f[m],A.insertBefore.call(d,n,k),g.splice(m,0,n)}}if(!this.b)for(n=this.host.childNodes,c=0,b=n.length;c<b;c++)e=n[c],d=t(e),Sb(e)!==this.host||"slot"!==e.localName&&d.assignedSlot||A.removeChild.call(this.host,e);this.b=!0;N=a;Cc&&Cc()};
function Fc(a,b,c){var d=r(b),e=d.K;d.K=null;c||(c=(a=a.g[b.slot||"__catchall"])&&a[0]);c?(r(c).assignedNodes.push(b),d.assignedSlot=c):d.assignedSlot=void 0;e!==d.assignedSlot&&d.assignedSlot&&(r(d.assignedSlot).O=!0)}function Gc(a,b,c){for(var d=0,e;d<c.length&&(e=c[d]);d++)if("slot"==e.localName){var f=t(e).assignedNodes;f&&f.length&&Gc(a,b,f)}else b.push(c[d])}function Hc(a,b){A.dispatchEvent.call(b,new Event("slotchange"));b=t(b);b.assignedSlot&&Hc(a,b.assignedSlot)}
function Rb(a){if(a.a&&a.a.length){for(var b=a.a,c,d=0;d<b.length;d++){var e=b[d];Jb(e);Jb(e.parentNode);var f=Vb(e);a.g[f]?(c=c||{},c[f]=!0,a.g[f].push(e)):a.g[f]=[e];a.f.push(e)}if(c)for(var g in c)a.g[g]=Wb(a.g[g]);a.a=[]}}function Vb(a){var b=a.name||a.getAttribute("name")||"__catchall";return a.qa=b}function Wb(a){return a.sort(function(a,c){a=Dc(a);for(var b=Dc(c),e=0;e<a.length;e++){c=a[e];var f=b[e];if(c!==f)return a=Array.from(c.parentNode.childNodes),a.indexOf(c)-a.indexOf(f)}})}
function Tb(a){Rb(a);return!(!a.f||!a.f.length)}
if(window.customElements&&u.Y){var Ic=new Map;Cc=function(){var a=Array.from(Ic);Ic.clear();a=ia(a);for(var b=a.next();!b.done;b=a.next()){b=ia(b.value);var c=b.next().value;b.next().value?c.oa():c.pa()}};N&&document.addEventListener("readystatechange",function(){N=!1;Cc()},{once:!0});var Jc=function(a,b,c){var d=0,e="__isConnected"+d++;if(b||c)a.prototype.connectedCallback=a.prototype.oa=function(){N?Ic.set(this,!0):this[e]||(this[e]=!0,b&&b.call(this))},a.prototype.disconnectedCallback=a.prototype.pa=
function(){N?this.isConnected||Ic.set(this,!1):this[e]&&(this[e]=!1,c&&c.call(this))};return a},define=window.customElements.define;Object.defineProperty(window.CustomElementRegistry.prototype,"define",{value:function(a,b){var c=b.prototype.connectedCallback,d=b.prototype.disconnectedCallback;define.call(window.customElements,a,Jc(b,c,d));b.prototype.connectedCallback=c;b.prototype.disconnectedCallback=d}})};function Kc(a){var b=a.getRootNode();w(b)&&Ec(b);return(a=t(a))&&a.assignedSlot||null}
var Lc={addEventListener:pc.bind(window),removeEventListener:rc.bind(window)},Mc={addEventListener:pc,removeEventListener:rc,appendChild:function(a){return Lb(this,a)},insertBefore:function(a,b){return Lb(this,a,b)},removeChild:function(a){return Mb(this,a)},replaceChild:function(a,b){Lb(this,a,b);Mb(this,b);return a},cloneNode:function(a){if("template"==this.localName)var b=A.cloneNode.call(this,a);else if(b=A.cloneNode.call(this,!1),a&&b.nodeType!==Node.ATTRIBUTE_NODE){a=this.childNodes;for(var c=
0,d;c<a.length;c++)d=a[c].cloneNode(!0),b.appendChild(d)}return b},getRootNode:function(){return Xb(this)},contains:function(a){return xa(this,a)},dispatchEvent:function(a){Ca();return A.dispatchEvent.call(this,a)}};
Object.defineProperties(Mc,{isConnected:{get:function(){if(vb&&vb.call(this))return!0;if(this.nodeType==Node.DOCUMENT_FRAGMENT_NODE)return!1;var a=this.ownerDocument;if(wa){if(A.contains.call(a,this))return!0}else if(a.documentElement&&A.contains.call(a.documentElement,this))return!0;for(a=this;a&&!(a instanceof Document);)a=a.parentNode||(w(a)?a.host:void 0);return!!(a&&a instanceof Document)},configurable:!0}});
var Nc={get assignedSlot(){return Kc(this)}},Oc={querySelector:function(a){return Yb(this,function(b){return oa.call(b,a)},function(a){return!!a})[0]||null},querySelectorAll:function(a,b){if(b){b=Array.prototype.slice.call(A.querySelectorAll.call(this,a));var c=this.getRootNode();return b.filter(function(a){return a.getRootNode()==c})}return Yb(this,function(b){return oa.call(b,a)})}},Pc={assignedNodes:function(a){if("slot"===this.localName){var b=this.getRootNode();w(b)&&Ec(b);return(b=t(this))?
(a&&a.flatten?b.w:b.assignedNodes)||[]:[]}}},Qc=qa({setAttribute:function(a,b){ac(this,a,b)},removeAttribute:function(a){A.removeAttribute.call(this,a);Ub(this,a)},attachShadow:function(a){if(!this)throw"Must provide a host.";if(!a)throw"Not enough arguments.";return new Db(Bc,this,a)},get slot(){return this.getAttribute("slot")},set slot(a){ac(this,"slot",a)},get assignedSlot(){return Kc(this)}},Oc,Pc);Object.defineProperties(Qc,Ab);
var Rc=qa({importNode:function(a,b){return bc(a,b)},getElementById:function(a){return Yb(this,function(b){return b.id==a},function(a){return!!a})[0]||null}},Oc);Object.defineProperties(Rc,{_activeElement:Bb.activeElement});
for(var Sc=HTMLElement.prototype.blur,Tc={blur:function(){var a=t(this);(a=(a=a&&a.root)&&a.activeElement)?a.blur():Sc.call(this)}},O={},Uc=ia(Object.getOwnPropertyNames(Document.prototype)),Vc=Uc.next();!Vc.done;O={l:O.l},Vc=Uc.next())O.l=Vc.value,"on"===O.l.substring(0,2)&&Object.defineProperty(Tc,O.l,{set:function(a){return function(b){var c=r(this),d=a.l.substring(2);c.J[a.l]&&this.removeEventListener(d,c.J[a.l]);this.addEventListener(d,b,{});c.J[a.l]=b}}(O),get:function(a){return function(){var b=
t(this);return b&&b.J[a.l]}}(O),configurable:!0});var Wc={addEventListener:function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.V=this;this.host.addEventListener(a,b,c)},removeEventListener:function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.V=this;this.host.removeEventListener(a,b,c)},getElementById:function(a){return Yb(this,function(b){return b.id==a},function(a){return!!a})[0]||null}};
function P(a,b){for(var c=Object.getOwnPropertyNames(b),d=0;d<c.length;d++){var e=c[d],f=Object.getOwnPropertyDescriptor(b,e);f.value?a[e]=f.value:Object.defineProperty(a,e,f)}};if(u.Y){var ShadyDOM={inUse:u.Y,patch:function(a){Gb(a);Eb(a);return a},isShadyRoot:w,enqueue:Ba,flush:Ca,settings:u,filterMutations:La,observeChildren:Ga,unobserveChildren:Ha,nativeMethods:A,nativeTree:J,deferConnectionCallbacks:u.deferConnectionCallbacks};window.ShadyDOM=ShadyDOM;wc();var Xc=window.customElements&&window.customElements.nativeHTMLElement||HTMLElement;P(Db.prototype,Wc);P(window.Node.prototype,Mc);P(window.Window.prototype,Lc);P(window.Text.prototype,Nc);P(window.DocumentFragment.prototype,
Oc);P(window.Element.prototype,Qc);P(window.Document.prototype,Rc);window.HTMLSlotElement&&P(window.HTMLSlotElement.prototype,Pc);P(Xc.prototype,Tc);u.s&&(L(window.Node.prototype),L(window.Text.prototype),L(window.DocumentFragment.prototype),L(window.Element.prototype),L(Xc.prototype),L(window.Document.prototype),window.HTMLSlotElement&&L(window.HTMLSlotElement.prototype));Cb();window.ShadowRoot=Db};/*

Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
function Yc(){this.end=this.start=0;this.rules=this.parent=this.previous=null;this.cssText=this.parsedCssText="";this.atRule=!1;this.type=0;this.parsedSelector=this.selector=this.keyframesName=""}
function Zc(a){a=a.replace($c,"").replace(ad,"");var b=bd,c=a,d=new Yc;d.start=0;d.end=c.length;for(var e=d,f=0,g=c.length;f<g;f++)if("{"===c[f]){e.rules||(e.rules=[]);var h=e,k=h.rules[h.rules.length-1]||null;e=new Yc;e.start=f+1;e.parent=h;e.previous=k;h.rules.push(e)}else"}"===c[f]&&(e.end=f+1,e=e.parent||d);return b(d,a)}
function bd(a,b){var c=b.substring(a.start,a.end-1);a.parsedCssText=a.cssText=c.trim();a.parent&&(c=b.substring(a.previous?a.previous.end:a.parent.start,a.start-1),c=cd(c),c=c.replace(dd," "),c=c.substring(c.lastIndexOf(";")+1),c=a.parsedSelector=a.selector=c.trim(),a.atRule=0===c.indexOf("@"),a.atRule?0===c.indexOf("@media")?a.type=ed:c.match(fd)&&(a.type=gd,a.keyframesName=a.selector.split(dd).pop()):a.type=0===c.indexOf("--")?hd:id);if(c=a.rules)for(var d=0,e=c.length,f;d<e&&(f=c[d]);d++)bd(f,
b);return a}function cd(a){return a.replace(/\\([0-9a-f]{1,6})\s/gi,function(a,c){a=c;for(c=6-a.length;c--;)a="0"+a;return"\\"+a})}
function jd(a,b,c){c=void 0===c?"":c;var d="";if(a.cssText||a.rules){var e=a.rules,f;if(f=e)f=e[0],f=!(f&&f.selector&&0===f.selector.indexOf("--"));if(f){f=0;for(var g=e.length,h;f<g&&(h=e[f]);f++)d=jd(h,b,d)}else b?b=a.cssText:(b=a.cssText,b=b.replace(kd,"").replace(ld,""),b=b.replace(md,"").replace(nd,"")),(d=b.trim())&&(d="  "+d+"\n")}d&&(a.selector&&(c+=a.selector+" {\n"),c+=d,a.selector&&(c+="}\n\n"));return c}
var id=1,gd=7,ed=4,hd=1E3,$c=/\/\*[^*]*\*+([^/*][^*]*\*+)*\//gim,ad=/@import[^;]*;/gim,kd=/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?(?:[;\n]|$)/gim,ld=/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?{[^}]*?}(?:[;\n]|$)?/gim,md=/@apply\s*\(?[^);]*\)?\s*(?:[;\n]|$)?/gim,nd=/[^;:]*?:[^;]*?var\([^;]*\)(?:[;\n]|$)?/gim,fd=/^@[^\s]*keyframes/,dd=/\s+/g;var Q=!(window.ShadyDOM&&window.ShadyDOM.inUse),od;function pd(a){od=a&&a.shimcssproperties?!1:Q||!(navigator.userAgent.match(/AppleWebKit\/601|Edge\/15/)||!window.CSS||!CSS.supports||!CSS.supports("box-shadow","0 0 0 var(--foo)"))}window.ShadyCSS&&void 0!==window.ShadyCSS.nativeCss?od=window.ShadyCSS.nativeCss:window.ShadyCSS?(pd(window.ShadyCSS),window.ShadyCSS=void 0):pd(window.WebComponents&&window.WebComponents.flags);var R=od;var qd=/(?:^|[;\s{]\s*)(--[\w-]*?)\s*:\s*(?:((?:'(?:\\'|.)*?'|"(?:\\"|.)*?"|\([^)]*?\)|[^};{])+)|\{([^}]*)\}(?:(?=[;\s}])|$))/gi,rd=/(?:^|\W+)@apply\s*\(?([^);\n]*)\)?/gi,sd=/(--[\w-]+)\s*([:,;)]|$)/gi,td=/(animation\s*:)|(animation-name\s*:)/,ud=/@media\s(.*)/,vd=/\{[^}]*\}/g;var wd=new Set;function S(a,b){if(!a)return"";"string"===typeof a&&(a=Zc(a));b&&xd(a,b);return jd(a,R)}function yd(a){!a.__cssRules&&a.textContent&&(a.__cssRules=Zc(a.textContent));return a.__cssRules||null}function zd(a){return!!a.parent&&a.parent.type===gd}function xd(a,b,c,d){if(a){var e=!1,f=a.type;if(d&&f===ed){var g=a.selector.match(ud);g&&(window.matchMedia(g[1]).matches||(e=!0))}f===id?b(a):c&&f===gd?c(a):f===hd&&(e=!0);if((a=a.rules)&&!e){e=0;f=a.length;for(var h;e<f&&(h=a[e]);e++)xd(h,b,c,d)}}}
function Ad(a,b,c,d){var e=document.createElement("style");b&&e.setAttribute("scope",b);e.textContent=a;Bd(e,c,d);return e}var T=null;function Bd(a,b,c){b=b||document.head;b.insertBefore(a,c&&c.nextSibling||b.firstChild);T?a.compareDocumentPosition(T)===Node.DOCUMENT_POSITION_PRECEDING&&(T=a):T=a}
function Fd(a,b){var c=a.indexOf("var(");if(-1===c)return b(a,"","","");a:{var d=0;var e=c+3;for(var f=a.length;e<f;e++)if("("===a[e])d++;else if(")"===a[e]&&0===--d)break a;e=-1}d=a.substring(c+4,e);c=a.substring(0,c);a=Fd(a.substring(e+1),b);e=d.indexOf(",");return-1===e?b(c,d.trim(),"",a):b(c,d.substring(0,e).trim(),d.substring(e+1).trim(),a)}function Gd(a,b){Q?a.setAttribute("class",b):window.ShadyDOM.nativeMethods.setAttribute.call(a,"class",b)}
function U(a){var b=a.localName,c="";b?-1<b.indexOf("-")||(c=b,b=a.getAttribute&&a.getAttribute("is")||""):(b=a.is,c=a.extends);return{is:b,H:c}};function Hd(){}function Id(a,b,c){var d=V;a.__styleScoped?a.__styleScoped=null:Jd(d,a,b||"",c)}function Jd(a,b,c,d){b.nodeType===Node.ELEMENT_NODE&&Kd(b,c,d);if(b="template"===b.localName?(b.content||b.Ra||b).childNodes:b.children||b.childNodes)for(var e=0;e<b.length;e++)Jd(a,b[e],c,d)}
function Kd(a,b,c){if(b)if(a.classList)c?(a.classList.remove("style-scope"),a.classList.remove(b)):(a.classList.add("style-scope"),a.classList.add(b));else if(a.getAttribute){var d=a.getAttribute(Ld);c?d&&(b=d.replace("style-scope","").replace(b,""),Gd(a,b)):Gd(a,(d?d+" ":"")+"style-scope "+b)}}function Md(a,b,c){var d=V,e=a.__cssBuild;Q||"shady"===e?b=S(b,c):(a=U(a),b=Nd(d,b,a.is,a.H,c)+"\n\n");return b.trim()}
function Nd(a,b,c,d,e){var f=Od(c,d);c=c?Pd+c:"";return S(b,function(b){b.c||(b.selector=b.i=Qd(a,b,a.b,c,f),b.c=!0);e&&e(b,c,f)})}function Od(a,b){return b?"[is="+a+"]":a}function Qd(a,b,c,d,e){var f=b.selector.split(Rd);if(!zd(b)){b=0;for(var g=f.length,h;b<g&&(h=f[b]);b++)f[b]=c.call(a,h,d,e)}return f.join(Rd)}function Sd(a){return a.replace(Td,function(a,c,d){-1<d.indexOf("+")?d=d.replace(/\+/g,"___"):-1<d.indexOf("___")&&(d=d.replace(/___/g,"+"));return":"+c+"("+d+")"})}
Hd.prototype.b=function(a,b,c){var d=!1;a=a.trim();var e=Td.test(a);e&&(a=a.replace(Td,function(a,b,c){return":"+b+"("+c.replace(/\s/g,"")+")"}),a=Sd(a));a=a.replace(Ud,Vd+" $1");a=a.replace(Wd,function(a,e,h){d||(a=Xd(h,e,b,c),d=d||a.stop,e=a.ya,h=a.value);return e+h});e&&(a=Sd(a));return a};
function Xd(a,b,c,d){var e=a.indexOf(Yd);0<=a.indexOf(Vd)?a=Zd(a,d):0!==e&&(a=c?$d(a,c):a);c=!1;0<=e&&(b="",c=!0);if(c){var f=!0;c&&(a=a.replace(ae,function(a,b){return" > "+b}))}a=a.replace(be,function(a,b,c){return'[dir="'+c+'"] '+b+", "+b+'[dir="'+c+'"]'});return{value:a,ya:b,stop:f}}function $d(a,b){a=a.split(ce);a[0]+=b;return a.join(ce)}
function Zd(a,b){var c=a.match(de);return(c=c&&c[2].trim()||"")?c[0].match(ee)?a.replace(de,function(a,c,f){return b+f}):c.split(ee)[0]===b?c:fe:a.replace(Vd,b)}function ge(a){a.selector===he&&(a.selector="html")}Hd.prototype.c=function(a){return a.match(Yd)?this.b(a,ie):$d(a.trim(),ie)};q.Object.defineProperties(Hd.prototype,{a:{configurable:!0,enumerable:!0,get:function(){return"style-scope"}}});
var Td=/:(nth[-\w]+)\(([^)]+)\)/,ie=":not(.style-scope)",Rd=",",Wd=/(^|[\s>+~]+)((?:\[.+?\]|[^\s>+~=[])+)/g,ee=/[[.:#*]/,Vd=":host",he=":root",Yd="::slotted",Ud=new RegExp("^("+Yd+")"),de=/(:host)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,ae=/(?:::slotted)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,be=/(.*):dir\((?:(ltr|rtl))\)/,Pd=".",ce=":",Ld="class",fe="should_not_match",V=new Hd;function je(a,b,c,d){this.v=a||null;this.b=b||null;this.Z=c||[];this.D=null;this.H=d||"";this.a=this.m=this.A=null}function X(a){return a?a.__styleInfo:null}function ke(a,b){return a.__styleInfo=b}je.prototype.c=function(){return this.v};je.prototype._getStyleRules=je.prototype.c;function le(a){var b=this.matches||this.matchesSelector||this.mozMatchesSelector||this.msMatchesSelector||this.oMatchesSelector||this.webkitMatchesSelector;return b&&b.call(this,a)}var me=navigator.userAgent.match("Trident");function ne(){}function oe(a){var b={},c=[],d=0;xd(a,function(a){pe(a);a.index=d++;a=a.h.cssText;for(var c;c=sd.exec(a);){var e=c[1];":"!==c[2]&&(b[e]=!0)}},function(a){c.push(a)});a.b=c;a=[];for(var e in b)a.push(e);return a}
function pe(a){if(!a.h){var b={},c={};qe(a,c)&&(b.u=c,a.rules=null);b.cssText=a.parsedCssText.replace(vd,"").replace(qd,"");a.h=b}}function qe(a,b){var c=a.h;if(c){if(c.u)return Object.assign(b,c.u),!0}else{c=a.parsedCssText;for(var d;a=qd.exec(c);){d=(a[2]||a[3]).trim();if("inherit"!==d||"unset"!==d)b[a[1].trim()]=d;d=!0}return d}}
function re(a,b,c){b&&(b=0<=b.indexOf(";")?se(a,b,c):Fd(b,function(b,e,f,g){if(!e)return b+g;(e=re(a,c[e],c))&&"initial"!==e?"apply-shim-inherit"===e&&(e="inherit"):e=re(a,c[f]||f,c)||f;return b+(e||"")+g}));return b&&b.trim()||""}
function se(a,b,c){b=b.split(";");for(var d=0,e,f;d<b.length;d++)if(e=b[d]){rd.lastIndex=0;if(f=rd.exec(e))e=re(a,c[f[1]],c);else if(f=e.indexOf(":"),-1!==f){var g=e.substring(f);g=g.trim();g=re(a,g,c)||g;e=e.substring(0,f)+g}b[d]=e&&e.lastIndexOf(";")===e.length-1?e.slice(0,-1):e||""}return b.join(";")}
function te(a,b){var c={},d=[];xd(a,function(a){a.h||pe(a);var e=a.i||a.parsedSelector;b&&a.h.u&&e&&le.call(b,e)&&(qe(a,c),a=a.index,e=parseInt(a/32,10),d[e]=(d[e]||0)|1<<a%32)},null,!0);return{u:c,key:d}}
function ue(a,b,c,d){b.h||pe(b);if(b.h.u){var e=U(a);a=e.is;e=e.H;e=a?Od(a,e):"html";var f=b.parsedSelector,g=":host > *"===f||"html"===f,h=0===f.indexOf(":host")&&!g;"shady"===c&&(g=f===e+" > *."+e||-1!==f.indexOf("html"),h=!g&&0===f.indexOf(e));"shadow"===c&&(g=":host > *"===f||"html"===f,h=h&&!g);if(g||h)c=e,h&&(b.i||(b.i=Qd(V,b,V.b,a?Pd+a:"",e)),c=b.i||e),d({Ja:c,Da:h,$a:g})}}
function ve(a,b){var c={},d={},e=b&&b.__cssBuild;xd(b,function(b){ue(a,b,e,function(e){le.call(a.ga||a,e.Ja)&&(e.Da?qe(b,c):qe(b,d))})},null,!0);return{Ia:d,Ca:c}}
function we(a,b,c,d){var e=U(b),f=Od(e.is,e.H),g=new RegExp("(?:^|[^.#[:])"+(b.extends?"\\"+f.slice(0,-1)+"\\]":f)+"($|[.:[\\s>+~])");e=X(b).v;var h=xe(e,d);return Md(b,e,function(b){var e="";b.h||pe(b);b.h.cssText&&(e=se(a,b.h.cssText,c));b.cssText=e;if(!Q&&!zd(b)&&b.cssText){var k=e=b.cssText;null==b.fa&&(b.fa=td.test(e));if(b.fa)if(null==b.P){b.P=[];for(var n in h)k=h[n],k=k(e),e!==k&&(e=k,b.P.push(n))}else{for(n=0;n<b.P.length;++n)k=h[b.P[n]],e=k(e);k=e}b.cssText=k;b.i=b.i||b.selector;e="."+d;
n=b.i.split(",");k=0;for(var x=n.length,C;k<x&&(C=n[k]);k++)n[k]=C.match(g)?C.replace(f,e):e+" "+C;b.selector=n.join(",")}})}function xe(a,b){a=a.b;var c={};if(!Q&&a)for(var d=0,e=a[d];d<a.length;e=a[++d]){var f=e,g=b;f.j=new RegExp("\\b"+f.keyframesName+"(?!\\B|-)","g");f.a=f.keyframesName+"-"+g;f.i=f.i||f.selector;f.selector=f.i.replace(f.keyframesName,f.a);c[e.keyframesName]=ye(e)}return c}function ye(a){return function(b){return b.replace(a.j,a.a)}}
function ze(a,b){var c=Ae,d=yd(a);a.textContent=S(d,function(a){var d=a.cssText=a.parsedCssText;a.h&&a.h.cssText&&(d=d.replace(kd,"").replace(ld,""),a.cssText=se(c,d,b))})}q.Object.defineProperties(ne.prototype,{a:{configurable:!0,enumerable:!0,get:function(){return"x-scope"}}});var Ae=new ne;var Be={},Ce=window.customElements;if(Ce&&!Q){var De=Ce.define;Ce.define=function(a,b,c){var d=document.createComment(" Shady DOM styles for "+a+" "),e=document.head;e.insertBefore(d,(T?T.nextSibling:null)||e.firstChild);T=d;Be[a]=d;De.call(Ce,a,b,c)}};function Ee(){this.cache={}}Ee.prototype.store=function(a,b,c,d){var e=this.cache[a]||[];e.push({u:b,styleElement:c,m:d});100<e.length&&e.shift();this.cache[a]=e};Ee.prototype.fetch=function(a,b,c){if(a=this.cache[a])for(var d=a.length-1;0<=d;d--){var e=a[d],f;a:{for(f=0;f<c.length;f++){var g=c[f];if(e.u[g]!==b[g]){f=!1;break a}}f=!0}if(f)return e}};function Fe(){}
function Ge(a){for(var b=0;b<a.length;b++){var c=a[b];if(c.target!==document.documentElement&&c.target!==document.head)for(var d=0;d<c.addedNodes.length;d++){var e=c.addedNodes[d];if(e.nodeType===Node.ELEMENT_NODE){var f=e.getRootNode();var g=e;var h=[];g.classList?h=Array.from(g.classList):g instanceof window.SVGElement&&g.hasAttribute("class")&&(h=g.getAttribute("class").split(/\s+/));g=h;h=g.indexOf(V.a);if((g=-1<h?g[h+1]:"")&&f===e.ownerDocument)Id(e,g,!0);else if(f.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&
(f=f.host))if(f=U(f).is,g===f)for(e=window.ShadyDOM.nativeMethods.querySelectorAll.call(e,":not(."+V.a+")"),f=0;f<e.length;f++)Kd(e[f],g);else g&&Id(e,g,!0),Id(e,f)}}}}
if(!Q){var He=new MutationObserver(Ge),Ie=function(a){He.observe(a,{childList:!0,subtree:!0})};if(window.customElements&&!window.customElements.polyfillWrapFlushCallback)Ie(document);else{var Je=function(){Ie(document.body)};window.HTMLImports?window.HTMLImports.whenReady(Je):requestAnimationFrame(function(){if("loading"===document.readyState){var a=function(){Je();document.removeEventListener("readystatechange",a)};document.addEventListener("readystatechange",a)}else Je()})}Fe=function(){Ge(He.takeRecords())}}
var Ke=Fe;var Le={};var Me=Promise.resolve();function Ne(a){if(a=Le[a])a._applyShimCurrentVersion=a._applyShimCurrentVersion||0,a._applyShimValidatingVersion=a._applyShimValidatingVersion||0,a._applyShimNextVersion=(a._applyShimNextVersion||0)+1}function Oe(a){return a._applyShimCurrentVersion===a._applyShimNextVersion}function Pe(a){a._applyShimValidatingVersion=a._applyShimNextVersion;a.b||(a.b=!0,Me.then(function(){a._applyShimCurrentVersion=a._applyShimNextVersion;a.b=!1}))};var Qe=new Ee;function Y(){this.B={};this.c=document.documentElement;var a=new Yc;a.rules=[];this.j=ke(this.c,new je(a));this.o=!1;this.b=this.a=null}p=Y.prototype;p.$=function(){Ke()};p.Aa=function(a){return yd(a)};p.La=function(a){return S(a)};p.prepareTemplate=function(a,b,c){this.prepareTemplateDom(a,b);this.prepareTemplateStyles(a,b,c)};
p.prepareTemplateStyles=function(a,b,c){if(!a.o){a.o=!0;a.name=b;a.extends=c;Le[b]=a;var d=(d=a.content.querySelector("style"))?d.getAttribute("css-build")||"":"";var e=[];for(var f=a.content.querySelectorAll("style"),g=0;g<f.length;g++){var h=f[g];if(h.hasAttribute("shady-unscoped")){if(!Q){var k=h.textContent;wd.has(k)||(wd.add(k),k=h.cloneNode(!0),document.head.appendChild(k));h.parentNode.removeChild(h)}}else e.push(h.textContent),h.parentNode.removeChild(h)}e=e.join("").trim();c={is:b,extends:c,
Pa:d};Re(this);f=rd.test(e)||qd.test(e);rd.lastIndex=0;qd.lastIndex=0;e=Zc(e);f&&R&&this.a&&this.a.transformRules(e,b);a._styleAst=e;a.B=d;d=[];R||(d=oe(a._styleAst));if(!d.length||R)e=Q?a.content:null,b=Be[b],f=Md(c,a._styleAst),b=f.length?Ad(f,c.is,e,b):void 0,a.a=b;a.j=d}};p.prepareTemplateDom=function(a,b){Q||a.c||(a.c=!0,Id(a.content,b))};
function Se(a){!a.b&&window.ShadyCSS&&window.ShadyCSS.CustomStyleInterface&&(a.b=window.ShadyCSS.CustomStyleInterface,a.b.transformCallback=function(b){a.ka(b)},a.b.validateCallback=function(){requestAnimationFrame(function(){(a.b.enqueued||a.o)&&a.flushCustomStyles()})})}function Re(a){!a.a&&window.ShadyCSS&&window.ShadyCSS.ApplyShim&&(a.a=window.ShadyCSS.ApplyShim,a.a.invalidCallback=Ne);Se(a)}
p.flushCustomStyles=function(){Re(this);if(this.b){var a=this.b.processStyles();if(this.b.enqueued){if(R)for(var b=0;b<a.length;b++){var c=this.b.getStyleForCustomStyle(a[b]);if(c&&R&&this.a){var d=yd(c);Re(this);this.a.transformRules(d);c.textContent=S(d)}}else for(Te(this,this.c,this.j),b=0;b<a.length;b++)(c=this.b.getStyleForCustomStyle(a[b]))&&ze(c,this.j.A);this.b.enqueued=!1;this.o&&!R&&this.styleDocument()}}};
p.styleElement=function(a,b){var c=U(a).is,d=X(a);if(!d){var e=U(a);d=e.is;e=e.H;var f=Be[d];d=Le[d];if(d){var g=d._styleAst;var h=d.j}d=ke(a,new je(g,f,h,e))}a!==this.c&&(this.o=!0);b&&(d.D=d.D||{},Object.assign(d.D,b));if(R){if(d.D){b=d.D;for(var k in b)null===k?a.style.removeProperty(k):a.style.setProperty(k,b[k])}if(((k=Le[c])||a===this.c)&&k&&k.a&&!Oe(k)){if(Oe(k)||k._applyShimValidatingVersion!==k._applyShimNextVersion)Re(this),this.a&&this.a.transformRules(k._styleAst,c),k.a.textContent=Md(a,
d.v),Pe(k);Q&&(c=a.shadowRoot)&&(c.querySelector("style").textContent=Md(a,d.v));d.v=k._styleAst}}else if(this.$(),Te(this,a,d),d.Z&&d.Z.length){c=d;k=U(a).is;d=(b=Qe.fetch(k,c.A,c.Z))?b.styleElement:null;g=c.m;(h=b&&b.m)||(h=this.B[k]=(this.B[k]||0)+1,h=k+"-"+h);c.m=h;h=c.m;e=Ae;e=d?d.textContent||"":we(e,a,c.A,h);f=X(a);var l=f.a;l&&!Q&&l!==d&&(l._useCount--,0>=l._useCount&&l.parentNode&&l.parentNode.removeChild(l));Q?f.a?(f.a.textContent=e,d=f.a):e&&(d=Ad(e,h,a.shadowRoot,f.b)):d?d.parentNode||
(me&&-1<e.indexOf("@media")&&(d.textContent=e),Bd(d,null,f.b)):e&&(d=Ad(e,h,null,f.b));d&&(d._useCount=d._useCount||0,f.a!=d&&d._useCount++,f.a=d);h=d;Q||(d=c.m,f=e=a.getAttribute("class")||"",g&&(f=e.replace(new RegExp("\\s*x-scope\\s*"+g+"\\s*","g")," ")),f+=(f?" ":"")+"x-scope "+d,e!==f&&Gd(a,f));b||Qe.store(k,c.A,h,c.m)}};function Ue(a,b){return(b=b.getRootNode().host)?X(b)?b:Ue(a,b):a.c}
function Te(a,b,c){a=Ue(a,b);var d=X(a);a=Object.create(d.A||null);var e=ve(b,c.v);b=te(d.v,b).u;Object.assign(a,e.Ca,b,e.Ia);b=c.D;for(var f in b)if((e=b[f])||0===e)a[f]=e;f=Ae;b=Object.getOwnPropertyNames(a);for(e=0;e<b.length;e++)d=b[e],a[d]=re(f,a[d],a);c.A=a}p.styleDocument=function(a){this.styleSubtree(this.c,a)};
p.styleSubtree=function(a,b){var c=a.shadowRoot;(c||a===this.c)&&this.styleElement(a,b);if(b=c&&(c.children||c.childNodes))for(a=0;a<b.length;a++)this.styleSubtree(b[a]);else if(a=a.children||a.childNodes)for(b=0;b<a.length;b++)this.styleSubtree(a[b])};p.ka=function(a){var b=this,c=yd(a);xd(c,function(a){if(Q)ge(a);else{var c=V;a.selector=a.parsedSelector;ge(a);a.selector=a.i=Qd(c,a,c.c,void 0,void 0)}R&&(Re(b),b.a&&b.a.transformRule(a))});R?a.textContent=S(c):this.j.v.rules.push(c)};
p.getComputedStyleValue=function(a,b){var c;R||(c=(X(a)||X(Ue(this,a))).A[b]);return(c=c||window.getComputedStyle(a).getPropertyValue(b))?c.trim():""};p.Ka=function(a,b){var c=a.getRootNode();b=b?b.split(/\s/):[];c=c.host&&c.host.localName;if(!c){var d=a.getAttribute("class");if(d){d=d.split(/\s/);for(var e=0;e<d.length;e++)if(d[e]===V.a){c=d[e+1];break}}}c&&b.push(V.a,c);R||(c=X(a))&&c.m&&b.push(Ae.a,c.m);Gd(a,b.join(" "))};p.wa=function(a){return X(a)};Y.prototype.flush=Y.prototype.$;
Y.prototype.prepareTemplate=Y.prototype.prepareTemplate;Y.prototype.styleElement=Y.prototype.styleElement;Y.prototype.styleDocument=Y.prototype.styleDocument;Y.prototype.styleSubtree=Y.prototype.styleSubtree;Y.prototype.getComputedStyleValue=Y.prototype.getComputedStyleValue;Y.prototype.setElementClass=Y.prototype.Ka;Y.prototype._styleInfoForNode=Y.prototype.wa;Y.prototype.transformCustomStyleForDocument=Y.prototype.ka;Y.prototype.getStyleAst=Y.prototype.Aa;Y.prototype.styleAstToString=Y.prototype.La;
Y.prototype.flushCustomStyles=Y.prototype.flushCustomStyles;Object.defineProperties(Y.prototype,{nativeShadow:{get:function(){return Q}},nativeCss:{get:function(){return R}}});var Z=new Y,Ve,We;window.ShadyCSS&&(Ve=window.ShadyCSS.ApplyShim,We=window.ShadyCSS.CustomStyleInterface);
window.ShadyCSS={ScopingShim:Z,prepareTemplate:function(a,b,c){Z.flushCustomStyles();Z.prepareTemplate(a,b,c)},prepareTemplateDom:function(a,b){Z.prepareTemplateDom(a,b)},prepareTemplateStyles:function(a,b,c){Z.flushCustomStyles();Z.prepareTemplateStyles(a,b,c)},styleSubtree:function(a,b){Z.flushCustomStyles();Z.styleSubtree(a,b)},styleElement:function(a){Z.flushCustomStyles();Z.styleElement(a)},styleDocument:function(a){Z.flushCustomStyles();Z.styleDocument(a)},flushCustomStyles:function(){Z.flushCustomStyles()},
getComputedStyleValue:function(a,b){return Z.getComputedStyleValue(a,b)},nativeCss:R,nativeShadow:Q};Ve&&(window.ShadyCSS.ApplyShim=Ve);We&&(window.ShadyCSS.CustomStyleInterface=We);/*

 Copyright (c) 2014 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
var Xe=window.customElements,Ye=window.HTMLImports,Ze=window.HTMLTemplateElement;window.WebComponents=window.WebComponents||{};if(Xe&&Xe.polyfillWrapFlushCallback){var $e,af=function(){if($e){Ze.xa&&Ze.xa(window.document);var a=$e;$e=null;a();return!0}},bf=Ye.whenReady;Xe.polyfillWrapFlushCallback(function(a){$e=a;bf(af)});Ye.whenReady=function(a){bf(function(){af()?Ye.whenReady(a):a()})}}
Ye.whenReady(function(){requestAnimationFrame(function(){window.WebComponents.ready=!0;document.dispatchEvent(new CustomEvent("WebComponentsReady",{bubbles:!0}))})});var cf=document.createElement("style");cf.textContent="body {transition: opacity ease-in 0.2s; } \nbody[unresolved] {opacity: 0; display: block; overflow: hidden; position: relative; } \n";var df=document.querySelector("head");df.insertBefore(cf,df.firstChild);/*

Copyright (c) 2018 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
}).call(this);

//# sourceMappingURL=webcomponents-hi-sd.js.map
