/**
@license @nocompile
Copyright (c) 2018 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){/*

Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
'use strict';var m,aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},p="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function ba(){ba=function(){};p.Symbol||(p.Symbol=ea)}var ea=function(){var a=0;return function(b){return"jscomp_symbol_"+(b||"")+a++}}();
function fa(){ba();var a=p.Symbol.iterator;a||(a=p.Symbol.iterator=p.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&aa(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ha(this)}});fa=function(){}}function ha(a){var b=0;return ia(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function ia(a){fa();a={next:a};a[p.Symbol.iterator]=function(){return this};return a}function q(a){fa();ba();fa();var b=a[Symbol.iterator];return b?b.call(a):ha(a)}
function ja(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c}function ka(){this.ba=this.root=null;this.M=!1;this.v=this.J=this.S=this.assignedSlot=this.assignedNodes=this.A=null;this.childNodes=this.nextSibling=this.previousSibling=this.lastChild=this.firstChild=this.parentNode=this.D=void 0;this.fa=this.X=!1;this.I={}}ka.prototype.toJSON=function(){return{}};function r(a){a.__shady||(a.__shady=new ka);return a.__shady}function t(a){return a&&a.__shady};var v=window.ShadyDOM||{};v.ra=!(!Element.prototype.attachShadow||!Node.prototype.getRootNode);var la=Object.getOwnPropertyDescriptor(Node.prototype,"firstChild");v.o=!!(la&&la.configurable&&la.get);v.U=v.force||!v.ra;var ma=navigator.userAgent.match("Trident"),na=navigator.userAgent.match("Edge");void 0===v.da&&(v.da=v.o&&(ma||na));function w(a){return(a=t(a))&&void 0!==a.firstChild}function x(a){return"ShadyRoot"===a.ka}function oa(a){a=a.getRootNode();if(x(a))return a}
var y=Element.prototype,pa=y.matches||y.matchesSelector||y.mozMatchesSelector||y.msMatchesSelector||y.oMatchesSelector||y.webkitMatchesSelector;function qa(a,b){if(a&&b)for(var c=Object.getOwnPropertyNames(b),d=0,e=void 0;d<c.length&&(e=c[d]);d++){var f=e,g=a,h=Object.getOwnPropertyDescriptor(b,f);h&&Object.defineProperty(g,f,h)}}function ra(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];for(d=0;d<c.length;d++)qa(a,c[d]);return a}function sa(a,b){for(var c in b)a[c]=b[c]}
var ta=document.createTextNode(""),ua=0,va=[];(new MutationObserver(function(){for(;va.length;)try{va.shift()()}catch(a){throw ta.textContent=ua++,a;}})).observe(ta,{characterData:!0});function wa(a){va.push(a);ta.textContent=ua++}var xa=!!document.contains;function ya(a,b){for(;b;){if(b==a)return!0;b=b.parentNode}return!1}
function za(a){for(var b=a.length-1;0<=b;b--){var c=a[b],d=c.getAttribute("id")||c.getAttribute("name");d&&"length"!==d&&isNaN(d)&&(a[d]=c)}a.item=function(b){return a[b]};a.namedItem=function(b){if("length"!==b&&isNaN(b)&&a[b])return a[b];for(var c=q(a),d=c.next();!d.done;d=c.next())if(d=d.value,(d.getAttribute("id")||d.getAttribute("name"))==b)return d;return null};return a};var Aa=[],Ba;function Ca(a){Ba||(Ba=!0,wa(Da));Aa.push(a)}function Da(){Ba=!1;for(var a=!!Aa.length;Aa.length;)Aa.shift()();return a}Da.list=Aa;function Ea(){this.a=!1;this.addedNodes=[];this.removedNodes=[];this.L=new Set}function Fa(a){a.a||(a.a=!0,wa(function(){a.flush()}))}Ea.prototype.flush=function(){if(this.a){this.a=!1;var a=this.takeRecords();a.length&&this.L.forEach(function(b){b(a)})}};Ea.prototype.takeRecords=function(){if(this.addedNodes.length||this.removedNodes.length){var a=[{addedNodes:this.addedNodes,removedNodes:this.removedNodes}];this.addedNodes=[];this.removedNodes=[];return a}return[]};
function Ga(a,b){var c=r(a);c.A||(c.A=new Ea);c.A.L.add(b);var d=c.A;return{ja:b,ma:d,la:a,takeRecords:function(){return d.takeRecords()}}}function Ia(a){var b=a&&a.ma;b&&(b.L.delete(a.ja),b.L.size||(r(a.la).A=null))}
function Ja(a,b){var c=b.getRootNode();return a.map(function(a){var b=c===a.target.getRootNode();if(b&&a.addedNodes){if(b=Array.from(a.addedNodes).filter(function(a){return c===a.getRootNode()}),b.length)return a=Object.create(a),Object.defineProperty(a,"addedNodes",{value:b,configurable:!0}),a}else if(b)return a}).filter(function(a){return a})};var Ka=Element.prototype.insertBefore,La=Element.prototype.replaceChild,Ma=Element.prototype.removeChild,Na=Element.prototype.setAttribute,Oa=Element.prototype.removeAttribute,Pa=Element.prototype.cloneNode,Qa=Document.prototype.importNode,Ra=Element.prototype.addEventListener,Sa=Element.prototype.removeEventListener,Ta=Window.prototype.addEventListener,Ua=Window.prototype.removeEventListener,Va=Element.prototype.dispatchEvent,Wa=Node.prototype.contains||HTMLElement.prototype.contains,Xa=Document.prototype.getElementById,
Ya=Element.prototype.querySelector,Za=DocumentFragment.prototype.querySelector,$a=Document.prototype.querySelector,ab=Element.prototype.querySelectorAll,bb=DocumentFragment.prototype.querySelectorAll,cb=Document.prototype.querySelectorAll,z={};z.appendChild=Element.prototype.appendChild;z.insertBefore=Ka;z.replaceChild=La;z.removeChild=Ma;z.setAttribute=Na;z.removeAttribute=Oa;z.cloneNode=Pa;z.importNode=Qa;z.addEventListener=Ra;z.removeEventListener=Sa;z.Aa=Ta;z.Ba=Ua;z.dispatchEvent=Va;
z.contains=Wa;z.getElementById=Xa;z.Ha=Ya;z.Ka=Za;z.Fa=$a;z.querySelector=function(a){switch(this.nodeType){case Node.ELEMENT_NODE:return Ya.call(this,a);case Node.DOCUMENT_NODE:return $a.call(this,a);default:return Za.call(this,a)}};z.Ia=ab;z.La=bb;z.Ga=cb;z.querySelectorAll=function(a){switch(this.nodeType){case Node.ELEMENT_NODE:return ab.call(this,a);case Node.DOCUMENT_NODE:return cb.call(this,a);default:return bb.call(this,a)}};var db=/[&\u00A0"]/g,eb=/[&\u00A0<>]/g;function fb(a){switch(a){case "&":return"&amp;";case "<":return"&lt;";case ">":return"&gt;";case '"':return"&quot;";case "\u00a0":return"&nbsp;"}}function gb(a){for(var b={},c=0;c<a.length;c++)b[a[c]]=!0;return b}var hb=gb("area base br col command embed hr img input keygen link meta param source track wbr".split(" ")),ib=gb("style script xmp iframe noembed noframes plaintext noscript".split(" "));
function jb(a,b){"template"===a.localName&&(a=a.content);for(var c="",d=b?b(a):a.childNodes,e=0,f=d.length,g=void 0;e<f&&(g=d[e]);e++){a:{var h=g;var k=a,l=b;switch(h.nodeType){case Node.ELEMENT_NODE:k=h.localName;for(var n="<"+k,u=h.attributes,ca=0,da;da=u[ca];ca++)n+=" "+da.name+'="'+da.value.replace(db,fb)+'"';n+=">";h=hb[k]?n:n+jb(h,l)+"</"+k+">";break a;case Node.TEXT_NODE:h=h.data;h=k&&ib[k.localName]?h:h.replace(eb,fb);break a;case Node.COMMENT_NODE:h="\x3c!--"+h.data+"--\x3e";break a;default:throw window.console.error(h),
Error("not implemented");}}c+=h}return c};var A=document.createTreeWalker(document,NodeFilter.SHOW_ALL,null,!1),B=document.createTreeWalker(document,NodeFilter.SHOW_ELEMENT,null,!1);function kb(a){var b=[];A.currentNode=a;for(a=A.firstChild();a;)b.push(a),a=A.nextSibling();return b}
var C={parentNode:function(a){A.currentNode=a;return A.parentNode()},firstChild:function(a){A.currentNode=a;return A.firstChild()},lastChild:function(a){A.currentNode=a;return A.lastChild()},previousSibling:function(a){A.currentNode=a;return A.previousSibling()},nextSibling:function(a){A.currentNode=a;return A.nextSibling()}};C.childNodes=kb;C.parentElement=function(a){B.currentNode=a;return B.parentNode()};C.firstElementChild=function(a){B.currentNode=a;return B.firstChild()};
C.lastElementChild=function(a){B.currentNode=a;return B.lastChild()};C.previousElementSibling=function(a){B.currentNode=a;return B.previousSibling()};C.nextElementSibling=function(a){B.currentNode=a;return B.nextSibling()};C.children=function(a){var b=[];B.currentNode=a;for(a=B.firstChild();a;)b.push(a),a=B.nextSibling();return za(b)};C.innerHTML=function(a){return jb(a,function(a){return kb(a)})};
C.textContent=function(a){switch(a.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:a=document.createTreeWalker(a,NodeFilter.SHOW_TEXT,null,!1);for(var b="",c;c=a.nextNode();)b+=c.nodeValue;return b;default:return a.nodeValue}};var lb=v.o,mb=[Node.prototype,Element.prototype,HTMLElement.prototype];function D(a){var b;a:{for(b=0;b<mb.length;b++){var c=mb[b];if(c.hasOwnProperty(a)){b=c;break a}}b=void 0}if(!b)throw Error("Could not find descriptor for "+a);return Object.getOwnPropertyDescriptor(b,a)}
var E=lb?{parentNode:D("parentNode"),firstChild:D("firstChild"),lastChild:D("lastChild"),previousSibling:D("previousSibling"),nextSibling:D("nextSibling"),childNodes:D("childNodes"),parentElement:D("parentElement"),previousElementSibling:D("previousElementSibling"),nextElementSibling:D("nextElementSibling"),innerHTML:D("innerHTML"),textContent:D("textContent"),firstElementChild:D("firstElementChild"),lastElementChild:D("lastElementChild"),children:D("children")}:{},nb=lb?{firstElementChild:Object.getOwnPropertyDescriptor(DocumentFragment.prototype,
"firstElementChild"),lastElementChild:Object.getOwnPropertyDescriptor(DocumentFragment.prototype,"lastElementChild"),children:Object.getOwnPropertyDescriptor(DocumentFragment.prototype,"children")}:{},ob=lb?{firstElementChild:Object.getOwnPropertyDescriptor(Document.prototype,"firstElementChild"),lastElementChild:Object.getOwnPropertyDescriptor(Document.prototype,"lastElementChild"),children:Object.getOwnPropertyDescriptor(Document.prototype,"children")}:{},pb={aa:E,Ja:nb,Ea:ob,parentNode:function(a){return E.parentNode.get.call(a)},
firstChild:function(a){return E.firstChild.get.call(a)},lastChild:function(a){return E.lastChild.get.call(a)},previousSibling:function(a){return E.previousSibling.get.call(a)},nextSibling:function(a){return E.nextSibling.get.call(a)},childNodes:function(a){return Array.prototype.slice.call(E.childNodes.get.call(a))},parentElement:function(a){return E.parentElement.get.call(a)},previousElementSibling:function(a){return E.previousElementSibling.get.call(a)},nextElementSibling:function(a){return E.nextElementSibling.get.call(a)},
innerHTML:function(a){return E.innerHTML.get.call(a)},textContent:function(a){return E.textContent.get.call(a)},children:function(a){switch(a.nodeType){case Node.DOCUMENT_FRAGMENT_NODE:return nb.children.get.call(a);case Node.DOCUMENT_NODE:return ob.children.get.call(a);default:return E.children.get.call(a)}},firstElementChild:function(a){switch(a.nodeType){case Node.DOCUMENT_FRAGMENT_NODE:return nb.firstElementChild.get.call(a);case Node.DOCUMENT_NODE:return ob.firstElementChild.get.call(a);default:return E.firstElementChild.get.call(a)}},
lastElementChild:function(a){switch(a.nodeType){case Node.DOCUMENT_FRAGMENT_NODE:return nb.lastElementChild.get.call(a);case Node.DOCUMENT_NODE:return ob.lastElementChild.get.call(a);default:return E.lastElementChild.get.call(a)}}};var F=v.da?pb:C;function qb(a){for(;a.firstChild;)a.removeChild(a.firstChild)}
var rb=v.o,sb=document.implementation.createHTMLDocument("inert"),tb=Object.getOwnPropertyDescriptor(Node.prototype,"isConnected"),ub=tb&&tb.get,vb=Object.getOwnPropertyDescriptor(Document.prototype,"activeElement"),wb={parentElement:{get:function(){var a=t(this);(a=a&&a.parentNode)&&a.nodeType!==Node.ELEMENT_NODE&&(a=null);return void 0!==a?a:F.parentElement(this)},configurable:!0},parentNode:{get:function(){var a=t(this);a=a&&a.parentNode;return void 0!==a?a:F.parentNode(this)},configurable:!0},
nextSibling:{get:function(){var a=t(this);a=a&&a.nextSibling;return void 0!==a?a:F.nextSibling(this)},configurable:!0},previousSibling:{get:function(){var a=t(this);a=a&&a.previousSibling;return void 0!==a?a:F.previousSibling(this)},configurable:!0},nextElementSibling:{get:function(){var a=t(this);if(a&&void 0!==a.nextSibling){for(a=this.nextSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.nextSibling;return a}return F.nextElementSibling(this)},configurable:!0},previousElementSibling:{get:function(){var a=
t(this);if(a&&void 0!==a.previousSibling){for(a=this.previousSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.previousSibling;return a}return F.previousElementSibling(this)},configurable:!0}},xb={className:{get:function(){return this.getAttribute("class")||""},set:function(a){this.setAttribute("class",a)},configurable:!0}},yb={childNodes:{get:function(){if(w(this)){var a=t(this);if(!a.childNodes){a.childNodes=[];for(var b=this.firstChild;b;b=b.nextSibling)a.childNodes.push(b)}var c=a.childNodes}else c=
F.childNodes(this);c.item=function(a){return c[a]};return c},configurable:!0},childElementCount:{get:function(){return this.children.length},configurable:!0},firstChild:{get:function(){var a=t(this);a=a&&a.firstChild;return void 0!==a?a:F.firstChild(this)},configurable:!0},lastChild:{get:function(){var a=t(this);a=a&&a.lastChild;return void 0!==a?a:F.lastChild(this)},configurable:!0},textContent:{get:function(){if(w(this)){for(var a=[],b=0,c=this.childNodes,d;d=c[b];b++)d.nodeType!==Node.COMMENT_NODE&&
a.push(d.textContent);return a.join("")}return F.textContent(this)},set:function(a){if("undefined"===typeof a||null===a)a="";switch(this.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:if(!w(this)&&rb){var b=this.firstChild;(b!=this.lastChild||b&&b.nodeType!=Node.TEXT_NODE)&&qb(this);pb.aa.textContent.set.call(this,a)}else qb(this),(0<a.length||this.nodeType===Node.ELEMENT_NODE)&&this.appendChild(document.createTextNode(a));break;default:this.nodeValue=a}},configurable:!0},firstElementChild:{get:function(){var a=
t(this);if(a&&void 0!==a.firstChild){for(a=this.firstChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.nextSibling;return a}return F.firstElementChild(this)},configurable:!0},lastElementChild:{get:function(){var a=t(this);if(a&&void 0!==a.lastChild){for(a=this.lastChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.previousSibling;return a}return F.lastElementChild(this)},configurable:!0},children:{get:function(){return w(this)?za(Array.prototype.filter.call(this.childNodes,function(a){return a.nodeType===Node.ELEMENT_NODE})):
F.children(this)},configurable:!0},innerHTML:{get:function(){return w(this)?jb("template"===this.localName?this.content:this):F.innerHTML(this)},set:function(a){var b="template"===this.localName?this.content:this;qb(b);var c=this.localName||"div";c=this.namespaceURI&&this.namespaceURI!==sb.namespaceURI?sb.createElementNS(this.namespaceURI,c):sb.createElement(c);rb?pb.aa.innerHTML.set.call(c,a):c.innerHTML=a;for(a="template"===this.localName?c.content:c;a.firstChild;)b.appendChild(a.firstChild)},configurable:!0}},
zb={shadowRoot:{get:function(){var a=t(this);return a&&a.ba||null},configurable:!0}},Ab={activeElement:{get:function(){var a=vb&&vb.get?vb.get.call(document):v.o?void 0:document.activeElement;if(a&&a.nodeType){var b=!!x(this);if(this===document||b&&this.host!==a&&z.contains.call(this.host,a)){for(b=oa(a);b&&b!==this;)a=b.host,b=oa(a);a=this===document?b?null:a:b===this?a:null}else a=null}else a=null;return a},set:function(){},configurable:!0}};
function G(a,b,c){for(var d in b){var e=Object.getOwnPropertyDescriptor(a,d);e&&e.configurable||!e&&c?Object.defineProperty(a,d,b[d]):c&&console.warn("Could not define",d,"on",a)}}function H(a){G(a,wb);G(a,xb);G(a,yb);G(a,Ab)}
function Bb(){var a=Cb.prototype;a.__proto__=DocumentFragment.prototype;G(a,wb,!0);G(a,yb,!0);G(a,Ab,!0);Object.defineProperties(a,{nodeType:{value:Node.DOCUMENT_FRAGMENT_NODE,configurable:!0},nodeName:{value:"#document-fragment",configurable:!0},nodeValue:{value:null,configurable:!0}});["localName","namespaceURI","prefix"].forEach(function(b){Object.defineProperty(a,b,{value:void 0,configurable:!0})});["ownerDocument","baseURI","isConnected"].forEach(function(b){Object.defineProperty(a,b,{get:function(){return this.host[b]},
configurable:!0})})}var Db=v.o?function(){}:function(a){var b=r(a);b.X||(b.X=!0,G(a,wb,!0),G(a,xb,!0))},Eb=v.o?function(){}:function(a){r(a).fa||(G(a,yb,!0),G(a,zb,!0))};var Fb=F.childNodes;function Gb(a,b,c){Eb(b);var d=r(b);void 0!==d.firstChild&&(d.childNodes=null);if(a.nodeType===Node.DOCUMENT_FRAGMENT_NODE){d=a.childNodes;for(var e=0;e<d.length;e++)Hb(d[e],b,c);a=r(a);b=void 0!==a.firstChild?null:void 0;a.firstChild=a.lastChild=b;a.childNodes=b}else Hb(a,b,c)}
function Hb(a,b,c){Db(a);c=c||null;var d=r(a),e=r(b),f=c?r(c):null;d.previousSibling=c?f.previousSibling:b.lastChild;if(f=t(d.previousSibling))f.nextSibling=a;if(f=t(d.nextSibling=c))f.previousSibling=a;d.parentNode=b;c?c===e.firstChild&&(e.firstChild=a):(e.lastChild=a,e.firstChild||(e.firstChild=a));e.childNodes=null}
function Ib(a,b){var c=r(a);b=r(b);a===b.firstChild&&(b.firstChild=c.nextSibling);a===b.lastChild&&(b.lastChild=c.previousSibling);a=c.previousSibling;var d=c.nextSibling;a&&(r(a).nextSibling=d);d&&(r(d).previousSibling=a);c.parentNode=c.previousSibling=c.nextSibling=void 0;void 0!==b.childNodes&&(b.childNodes=null)}
function Jb(a,b){var c=r(a);if(void 0===c.firstChild)for(c.childNodes=null,b=b||Fb(a),c.firstChild=b[0]||null,c.lastChild=b[b.length-1]||null,Eb(a),c=0;c<b.length;c++){var d=b[c],e=r(d);e.parentNode=a;e.nextSibling=b[c+1]||null;e.previousSibling=b[c-1]||null;Db(d)}};var Kb=F.parentNode,Lb=window.document,Mb=v.Na;
function Nb(a,b,c){if(a.ownerDocument!==Lb&&b.ownerDocument!==Lb)return z.insertBefore.call(a,b,c);if(b===a)throw Error("Failed to execute 'appendChild' on 'Node': The new child element contains the parent.");if(c){var d=t(c);d=d&&d.parentNode;if(void 0!==d&&d!==a||void 0===d&&Kb(c)!==a)throw Error("Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.");}if(c===b)return b;var e=[],f=Ob,g=oa(a),h;g?h=g.host.localName:h=Pb(a);
if(b.parentNode){var k=Pb(b);Qb(b.parentNode,b,!!g||!(b.getRootNode()instanceof ShadowRoot));f=function(a,b){I()&&(Rb(a,k),Ob(a,b))}}d=!0;var l=(!Mb||void 0===b.__noInsertionPoint)&&!Sb(b,h);if(g)b.__noInsertionPoint&&!l||Tb(b,function(a){"slot"===a.localName&&e.push(a);l&&f(a,h)});else if(l){var n=Pb(b);Tb(b,function(a){var b=h;I()&&(Rb(a,n),Ob(a,b))})}e.length&&Ub(g,e);("slot"===a.localName||e.length)&&g&&J(g);w(a)&&(Gb(b,a,c),g=t(a),Vb(a)?(J(g.root),d=!1):g.root&&(d=!1));d?(d=x(a)?a.host:a,c?(c=
Wb(c),z.insertBefore.call(d,b,c)):z.appendChild.call(d,b)):b.ownerDocument!==a.ownerDocument&&a.ownerDocument.adoptNode(b);Xb(a,b);return b}
function Qb(a,b,c){c=void 0===c?!1:c;if(a.ownerDocument!==Lb)return z.removeChild.call(a,b);if(b.parentNode!==a)throw Error("The node to be removed is not a child of this node: "+b);var d=oa(b),e=t(a);if(w(a)&&(Ib(b,a),Vb(a))){J(e.root);var f=!0}if(I()&&!c&&d){var g=Pb(b);Tb(b,function(a){Rb(a,g)})}Yb(b);if(d){var h=a&&"slot"===a.localName;h&&(f=!0);((c=Zb(d,b))||h)&&J(d)}f||(f=x(a)?a.host:a,(!e.root&&"slot"!==b.localName||f===Kb(b))&&z.removeChild.call(f,b));Xb(a,null,b);return b}
function Yb(a){var b=t(a);if(b&&void 0!==b.D){b=a.childNodes;for(var c=0,d=b.length,e=void 0;c<d&&(e=b[c]);c++)Yb(e)}if(a=t(a))a.D=void 0}function Wb(a){var b=a;a&&"slot"===a.localName&&(b=(b=(b=t(a))&&b.v)&&b.length?b[0]:Wb(a.nextSibling));return b}function Vb(a){return(a=(a=t(a))&&a.root)&&$b(a)}
function ac(a,b){if("slot"===b)a=a.parentNode,Vb(a)&&J(t(a).root);else if("slot"===a.localName&&"name"===b&&(b=oa(a))){if(b.f){bc(b);var c=a.ia,d=cc(a);if(d!==c){c=b.g[c];var e=c.indexOf(a);0<=e&&c.splice(e,1);c=b.g[d]||(b.g[d]=[]);c.push(a);1<c.length&&(b.g[d]=dc(c))}}J(b)}}function Xb(a,b,c){if(a=(a=t(a))&&a.A)b&&a.addedNodes.push(b),c&&a.removedNodes.push(c),Fa(a)}
function ec(a){if(a&&a.nodeType){var b=r(a),c=b.D;void 0===c&&(x(a)?(c=a,b.D=c):(c=(c=a.parentNode)?ec(c):a,z.contains.call(document.documentElement,a)&&(b.D=c)));return c}}function fc(a,b,c){var d=[];gc(a.childNodes,b,c,d);return d}function gc(a,b,c,d){for(var e=0,f=a.length,g=void 0;e<f&&(g=a[e]);e++){var h;if(h=g.nodeType===Node.ELEMENT_NODE){h=g;var k=b,l=c,n=d,u=k(h);u&&n.push(h);l&&l(u)?h=u:(gc(h.childNodes,k,l,n),h=void 0)}if(h)break}}var hc=null;
function I(){hc||(hc=window.ShadyCSS&&window.ShadyCSS.ScopingShim);return hc||null}function ic(a,b,c){if(a.ownerDocument!==Lb)z.setAttribute.call(a,b,c);else{var d=I();d&&"class"===b?d.setElementClass(a,c):(z.setAttribute.call(a,b,c),ac(a,b))}}function jc(a,b){if(a.ownerDocument!==document||"template"===a.localName)return z.importNode.call(document,a,b);var c=z.importNode.call(document,a,!1);if(b){a=a.childNodes;b=0;for(var d;b<a.length;b++)d=jc(a[b],!0),c.appendChild(d)}return c}
function Ob(a,b){var c=I();c&&c.scopeNode(a,b)}function Rb(a,b){var c=I();c&&c.unscopeNode(a,b)}function Sb(a,b){var c=I();if(!c)return!0;if(a.nodeType===Node.DOCUMENT_FRAGMENT_NODE){c=!0;for(var d=0;c&&d<a.childNodes.length;d++)c=c&&Sb(a.childNodes[d],b);return c}return a.nodeType!==Node.ELEMENT_NODE?!0:c.currentScopeForNode(a)===b}function Pb(a){if(a.nodeType!==Node.ELEMENT_NODE)return"";var b=I();return b?b.currentScopeForNode(a):""}
function Tb(a,b){if(a){a.nodeType===Node.ELEMENT_NODE&&b(a);for(var c=0,d;c<a.childNodes.length;c++)d=a.childNodes[c],d.nodeType===Node.ELEMENT_NODE&&Tb(d,b)}};var kc="__eventWrappers"+Date.now(),lc=function(){var a=Object.getOwnPropertyDescriptor(Event.prototype,"composed");return a?function(b){return a.get.call(b)}:null}(),mc={blur:!0,focus:!0,focusin:!0,focusout:!0,click:!0,dblclick:!0,mousedown:!0,mouseenter:!0,mouseleave:!0,mousemove:!0,mouseout:!0,mouseover:!0,mouseup:!0,wheel:!0,beforeinput:!0,input:!0,keydown:!0,keyup:!0,compositionstart:!0,compositionupdate:!0,compositionend:!0,touchstart:!0,touchend:!0,touchmove:!0,touchcancel:!0,pointerover:!0,
pointerenter:!0,pointerdown:!0,pointermove:!0,pointerup:!0,pointercancel:!0,pointerout:!0,pointerleave:!0,gotpointercapture:!0,lostpointercapture:!0,dragstart:!0,drag:!0,dragenter:!0,dragleave:!0,dragover:!0,drop:!0,dragend:!0,DOMActivate:!0,DOMFocusIn:!0,DOMFocusOut:!0,keypress:!0},nc={DOMAttrModified:!0,DOMAttributeNameChanged:!0,DOMCharacterDataModified:!0,DOMElementNameChanged:!0,DOMNodeInserted:!0,DOMNodeInsertedIntoDocument:!0,DOMNodeRemoved:!0,DOMNodeRemovedFromDocument:!0,DOMSubtreeModified:!0};
function oc(a,b){var c=[],d=a;for(a=a===window?window:a.getRootNode();d;)c.push(d),d=d.assignedSlot?d.assignedSlot:d.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&d.host&&(b||d!==a)?d.host:d.parentNode;c[c.length-1]===document&&c.push(window);return c}function pc(a,b){if(!x)return a;a=oc(a,!0);for(var c=0,d,e=void 0,f,g=void 0;c<b.length;c++)if(d=b[c],f=d===window?window:d.getRootNode(),f!==e&&(g=a.indexOf(f),e=f),!x(f)||-1<g)return d}
var qc={get composed(){void 0===this.H&&(lc?this.H="focusin"===this.type||"focusout"===this.type||lc(this):!1!==this.isTrusted&&(this.H=mc[this.type]));return this.H||!1},composedPath:function(){this.W||(this.W=oc(this.__target,this.composed));return this.W},get target(){return pc(this.currentTarget||this.__previousCurrentTarget,this.composedPath())},get relatedTarget(){if(!this.P)return null;this.Y||(this.Y=oc(this.P,!0));return pc(this.currentTarget||this.__previousCurrentTarget,this.Y)},stopPropagation:function(){Event.prototype.stopPropagation.call(this);
this.O=!0},stopImmediatePropagation:function(){Event.prototype.stopImmediatePropagation.call(this);this.O=this.ea=!0}};function rc(a){function b(b,d){b=new a(b,d);b.H=d&&!!d.composed;return b}sa(b,a);b.prototype=a.prototype;return b}var sc={focus:!0,blur:!0};function tc(a){return a.__target!==a.target||a.P!==a.relatedTarget}function uc(a,b,c){if(c=b.__handlers&&b.__handlers[a.type]&&b.__handlers[a.type][c])for(var d=0,e;(e=c[d])&&(!tc(a)||a.target!==a.relatedTarget)&&(e.call(b,a),!a.ea);d++);}
function vc(a){var b=a.composedPath();Object.defineProperty(a,"currentTarget",{get:function(){return d},configurable:!0});for(var c=b.length-1;0<=c;c--){var d=b[c];uc(a,d,"capture");if(a.O)return}Object.defineProperty(a,"eventPhase",{get:function(){return Event.AT_TARGET}});var e;for(c=0;c<b.length;c++){d=b[c];var f=t(d);f=f&&f.root;if(0===c||f&&f===e)if(uc(a,d,"bubble"),d!==window&&(e=d.getRootNode()),a.O)break}}
function wc(a,b,c,d,e,f){for(var g=0;g<a.length;g++){var h=a[g],k=h.type,l=h.capture,n=h.once,u=h.passive;if(b===h.node&&c===k&&d===l&&e===n&&f===u)return g}return-1}
function xc(a,b,c){if(b){var d=typeof b;if("function"===d||"object"===d)if("object"!==d||b.handleEvent&&"function"===typeof b.handleEvent){var e=this instanceof Window?z.Aa:z.addEventListener;if(nc[a])return e.call(this,a,b,c);if(c&&"object"===typeof c){var f=!!c.capture;var g=!!c.once;var h=!!c.passive}else f=!!c,h=g=!1;var k=c&&c.R||this,l=b[kc];if(l){if(-1<wc(l,k,a,f,g,h))return}else b[kc]=[];l=function(e){g&&this.removeEventListener(a,b,c);e.__target||yc(e);if(k!==this){var f=Object.getOwnPropertyDescriptor(e,
"currentTarget");Object.defineProperty(e,"currentTarget",{get:function(){return k},configurable:!0})}e.__previousCurrentTarget=e.currentTarget;if(!x(k)||-1!=e.composedPath().indexOf(k))if(e.composed||-1<e.composedPath().indexOf(k))if(tc(e)&&e.target===e.relatedTarget)e.eventPhase===Event.BUBBLING_PHASE&&e.stopImmediatePropagation();else if(e.eventPhase===Event.CAPTURING_PHASE||e.bubbles||e.target===k||k instanceof Window){var h="function"===d?b.call(k,e):b.handleEvent&&b.handleEvent(e);k!==this&&
(f?(Object.defineProperty(e,"currentTarget",f),f=null):delete e.currentTarget);return h}};b[kc].push({node:k,type:a,capture:f,once:g,passive:h,Ca:l});sc[a]?(this.__handlers=this.__handlers||{},this.__handlers[a]=this.__handlers[a]||{capture:[],bubble:[]},this.__handlers[a][f?"capture":"bubble"].push(l)):e.call(this,a,l,c)}}}
function zc(a,b,c){if(b){var d=this instanceof Window?z.Ba:z.removeEventListener;if(nc[a])return d.call(this,a,b,c);if(c&&"object"===typeof c){var e=!!c.capture;var f=!!c.once;var g=!!c.passive}else e=!!c,g=f=!1;var h=c&&c.R||this,k=void 0;var l=null;try{l=b[kc]}catch(n){}l&&(f=wc(l,h,a,e,f,g),-1<f&&(k=l.splice(f,1)[0].Ca,l.length||(b[kc]=void 0)));d.call(this,a,k||b,c);k&&sc[a]&&this.__handlers&&this.__handlers[a]&&(a=this.__handlers[a][e?"capture":"bubble"],k=a.indexOf(k),-1<k&&a.splice(k,1))}}
function Ac(){for(var a in sc)window.addEventListener(a,function(a){a.__target||(yc(a),vc(a))},!0)}function yc(a){a.__target=a.target;a.P=a.relatedTarget;if(v.o){var b=Object.getPrototypeOf(a);if(!b.hasOwnProperty("__patchProto")){var c=Object.create(b);c.Da=b;qa(c,qc);b.__patchProto=c}a.__proto__=b.__patchProto}else qa(a,qc)}var Bc=rc(window.Event),Cc=rc(window.CustomEvent),Dc=rc(window.MouseEvent);
function Ec(){window.Event=Bc;window.CustomEvent=Cc;window.MouseEvent=Dc;Ac();if(!lc&&Object.getOwnPropertyDescriptor(Event.prototype,"isTrusted")){var a=function(){var a=new MouseEvent("click",{bubbles:!0,cancelable:!0,composed:!0});this.dispatchEvent(a)};Element.prototype.click?Element.prototype.click=a:HTMLElement.prototype.click&&(HTMLElement.prototype.click=a)}};function Fc(a,b){return{index:a,F:[],K:b}}
function Gc(a,b,c,d){var e=0,f=0,g=0,h=0,k=Math.min(b-e,d-f);if(0==e&&0==f)a:{for(g=0;g<k;g++)if(a[g]!==c[g])break a;g=k}if(b==a.length&&d==c.length){h=a.length;for(var l=c.length,n=0;n<k-g&&Hc(a[--h],c[--l]);)n++;h=n}e+=g;f+=g;b-=h;d-=h;if(0==b-e&&0==d-f)return[];if(e==b){for(b=Fc(e,0);f<d;)b.F.push(c[f++]);return[b]}if(f==d)return[Fc(e,b-e)];k=e;g=f;d=d-g+1;h=b-k+1;b=Array(d);for(l=0;l<d;l++)b[l]=Array(h),b[l][0]=l;for(l=0;l<h;l++)b[0][l]=l;for(l=1;l<d;l++)for(n=1;n<h;n++)if(a[k+n-1]===c[g+l-1])b[l][n]=
b[l-1][n-1];else{var u=b[l-1][n]+1,ca=b[l][n-1]+1;b[l][n]=u<ca?u:ca}k=b.length-1;g=b[0].length-1;d=b[k][g];for(a=[];0<k||0<g;)0==k?(a.push(2),g--):0==g?(a.push(3),k--):(h=b[k-1][g-1],l=b[k-1][g],n=b[k][g-1],u=l<n?l<h?l:h:n<h?n:h,u==h?(h==d?a.push(0):(a.push(1),d=h),k--,g--):u==l?(a.push(3),k--,d=l):(a.push(2),g--,d=n));a.reverse();b=void 0;k=[];for(g=0;g<a.length;g++)switch(a[g]){case 0:b&&(k.push(b),b=void 0);e++;f++;break;case 1:b||(b=Fc(e,0));b.K++;e++;b.F.push(c[f]);f++;break;case 2:b||(b=Fc(e,
0));b.K++;e++;break;case 3:b||(b=Fc(e,0)),b.F.push(c[f]),f++}b&&k.push(b);return k}function Hc(a,b){return a===b};var Ic=F.parentNode,Jc=F.childNodes,Kc={},K=v.deferConnectionCallbacks&&"loading"===document.readyState,Lc;function Mc(a){var b=[];do b.unshift(a);while(a=a.parentNode);return b}
function Cb(a,b,c){if(a!==Kc)throw new TypeError("Illegal constructor");this.ka="ShadyRoot";this.host=b;this.c=c&&c.mode;a=Jc(b);Jb(b,a);c=r(b);c.root=this;c.ba="closed"!==this.c?this:null;c=r(this);c.firstChild=c.lastChild=c.parentNode=c.nextSibling=c.previousSibling=null;c.childNodes=[];this.b=this.C=!1;this.a=this.g=this.f=null;if(v.preferPerformance){c=0;for(var d=a.length;c<d;c++)z.removeChild.call(b,a[c])}else J(this)}function J(a){a.C||(a.C=!0,Ca(function(){return Nc(a)}))}
function Nc(a){for(var b;a;){a.C&&(b=a);a:{var c=a;a=c.host.getRootNode();if(x(a))for(var d=c.host.childNodes,e=0;e<d.length;e++)if(c=d[e],"slot"==c.localName)break a;a=void 0}}b&&b._renderRoot()}
Cb.prototype._renderRoot=function(){var a=K;K=!0;this.C=!1;if(this.f){bc(this);for(var b=0,c;b<this.f.length;b++){c=this.f[b];var d=t(c),e=d.assignedNodes;d.assignedNodes=[];d.v=[];if(d.S=e)for(d=0;d<e.length;d++){var f=t(e[d]);f.J=f.assignedSlot;f.assignedSlot===c&&(f.assignedSlot=null)}}for(b=this.host.firstChild;b;b=b.nextSibling)Oc(this,b);for(b=0;b<this.f.length;b++){c=this.f[b];e=t(c);if(!e.assignedNodes.length)for(d=c.firstChild;d;d=d.nextSibling)Oc(this,d,c);(d=(d=t(c.parentNode))&&d.root)&&
($b(d)||d.C)&&d._renderRoot();Pc(this,e.v,e.assignedNodes);if(d=e.S){for(f=0;f<d.length;f++)t(d[f]).J=null;e.S=null;d.length>e.assignedNodes.length&&(e.M=!0)}e.M&&(e.M=!1,Qc(this,c))}c=this.f;b=[];for(e=0;e<c.length;e++)d=c[e].parentNode,(f=t(d))&&f.root||!(0>b.indexOf(d))||b.push(d);for(c=0;c<b.length;c++){f=b[c];e=f===this?this.host:f;d=[];f=f.childNodes;for(var g=0;g<f.length;g++){var h=f[g];if("slot"==h.localName){h=t(h).v;for(var k=0;k<h.length;k++)d.push(h[k])}else d.push(h)}f=Jc(e);g=Gc(d,
d.length,f,f.length);k=h=0;for(var l=void 0;h<g.length&&(l=g[h]);h++){for(var n=0,u=void 0;n<l.F.length&&(u=l.F[n]);n++)Ic(u)===e&&z.removeChild.call(e,u),f.splice(l.index+k,1);k-=l.K}k=0;for(l=void 0;k<g.length&&(l=g[k]);k++)for(h=f[l.index],n=l.index;n<l.index+l.K;n++)u=d[n],z.insertBefore.call(e,u,h),f.splice(n,0,u)}}if(!v.preferPerformance&&!this.b)for(b=this.host.childNodes,c=0,e=b.length;c<e;c++)d=b[c],f=t(d),Ic(d)!==this.host||"slot"!==d.localName&&f.assignedSlot||z.removeChild.call(this.host,
d);this.b=!0;K=a;Lc&&Lc()};function Oc(a,b,c){var d=r(b),e=d.J;d.J=null;c||(c=(a=a.g[b.slot||"__catchall"])&&a[0]);c?(r(c).assignedNodes.push(b),d.assignedSlot=c):d.assignedSlot=void 0;e!==d.assignedSlot&&d.assignedSlot&&(r(d.assignedSlot).M=!0)}function Pc(a,b,c){for(var d=0,e=void 0;d<c.length&&(e=c[d]);d++)if("slot"==e.localName){var f=t(e).assignedNodes;f&&f.length&&Pc(a,b,f)}else b.push(c[d])}
function Qc(a,b){z.dispatchEvent.call(b,new Event("slotchange"));b=t(b);b.assignedSlot&&Qc(a,b.assignedSlot)}function Ub(a,b){a.a=a.a||[];a.f=a.f||[];a.g=a.g||{};a.a.push.apply(a.a,b instanceof Array?b:ja(q(b)))}function bc(a){if(a.a&&a.a.length){for(var b=a.a,c,d=0;d<b.length;d++){var e=b[d];Jb(e);Jb(e.parentNode);var f=cc(e);a.g[f]?(c=c||{},c[f]=!0,a.g[f].push(e)):a.g[f]=[e];a.f.push(e)}if(c)for(var g in c)a.g[g]=dc(a.g[g]);a.a=[]}}
function cc(a){var b=a.name||a.getAttribute("name")||"__catchall";return a.ia=b}function dc(a){return a.sort(function(a,c){a=Mc(a);for(var b=Mc(c),e=0;e<a.length;e++){c=a[e];var f=b[e];if(c!==f)return a=Array.from(c.parentNode.childNodes),a.indexOf(c)-a.indexOf(f)}})}
function Zb(a,b){if(a.f){bc(a);var c=a.g,d;for(d in c)for(var e=c[d],f=0;f<e.length;f++){var g=e[f];if(ya(b,g)){e.splice(f,1);var h=a.f.indexOf(g);0<=h&&a.f.splice(h,1);f--;g=t(g);if(h=g.v)for(var k=0;k<h.length;k++){var l=h[k],n=Ic(l);n&&z.removeChild.call(n,l)}g.v=[];g.assignedNodes=[];h=!0}}return h}}function $b(a){bc(a);return!(!a.f||!a.f.length)}
if(window.customElements&&v.U&&!v.preferPerformance){var Rc=new Map;Lc=function(){var a=Array.from(Rc);Rc.clear();a=q(a);for(var b=a.next();!b.done;b=a.next()){b=q(b.value);var c=b.next().value;b.next().value?c.ga():c.ha()}};K&&document.addEventListener("readystatechange",function(){K=!1;Lc()},{once:!0});var Sc=function(a,b,c){var d=0,e="__isConnected"+d++;if(b||c)a.prototype.connectedCallback=a.prototype.ga=function(){K?Rc.set(this,!0):this[e]||(this[e]=!0,b&&b.call(this))},a.prototype.disconnectedCallback=
a.prototype.ha=function(){K?this.isConnected||Rc.set(this,!1):this[e]&&(this[e]=!1,c&&c.call(this))};return a},Tc=window.customElements.define;Object.defineProperty(window.CustomElementRegistry.prototype,"define",{value:function(a,b){var c=b.prototype.connectedCallback,d=b.prototype.disconnectedCallback;Tc.call(window.customElements,a,Sc(b,c,d));b.prototype.connectedCallback=c;b.prototype.disconnectedCallback=d}})};function Uc(a){var b=a.getRootNode();x(b)&&Nc(b);return(a=t(a))&&a.assignedSlot||null}
var Vc={addEventListener:xc.bind(window),removeEventListener:zc.bind(window)},Wc={addEventListener:xc,removeEventListener:zc,appendChild:function(a){return Nb(this,a)},insertBefore:function(a,b){return Nb(this,a,b)},removeChild:function(a){return Qb(this,a)},replaceChild:function(a,b){Nb(this,a,b);Qb(this,b);return a},cloneNode:function(a){if("template"==this.localName)var b=z.cloneNode.call(this,a);else if(b=z.cloneNode.call(this,!1),a&&b.nodeType!==Node.ATTRIBUTE_NODE){a=this.childNodes;for(var c=
0,d;c<a.length;c++)d=a[c].cloneNode(!0),b.appendChild(d)}return b},getRootNode:function(){return ec(this)},contains:function(a){return ya(this,a)},dispatchEvent:function(a){Da();return z.dispatchEvent.call(this,a)}};
Object.defineProperties(Wc,{isConnected:{get:function(){if(ub&&ub.call(this))return!0;if(this.nodeType==Node.DOCUMENT_FRAGMENT_NODE)return!1;var a=this.ownerDocument;if(xa){if(z.contains.call(a,this))return!0}else if(a.documentElement&&z.contains.call(a.documentElement,this))return!0;for(a=this;a&&!(a instanceof Document);)a=a.parentNode||(x(a)?a.host:void 0);return!!(a&&a instanceof Document)},configurable:!0}});
var Xc={get assignedSlot(){return Uc(this)}},Yc={querySelector:function(a){return fc(this,function(b){return pa.call(b,a)},function(a){return!!a})[0]||null},querySelectorAll:function(a,b){if(b){b=Array.prototype.slice.call(z.querySelectorAll.call(this,a));var c=this.getRootNode();return b.filter(function(a){return a.getRootNode()==c})}return fc(this,function(b){return pa.call(b,a)})}},Zc={},$c={assignedNodes:function(a){if("slot"===this.localName){var b=this.getRootNode();x(b)&&Nc(b);return(b=t(this))?
(a&&a.flatten?b.v:b.assignedNodes)||[]:[]}}},ad=ra({setAttribute:function(a,b){ic(this,a,b)},removeAttribute:function(a){z.removeAttribute.call(this,a);ac(this,a)},attachShadow:function(a){if(!this)throw"Must provide a host.";if(!a)throw"Not enough arguments.";return new Cb(Kc,this,a)},get slot(){return this.getAttribute("slot")},set slot(a){ic(this,"slot",a)},get assignedSlot(){return Uc(this)}},Yc,$c);Object.defineProperties(ad,zb);
var bd={importNode:function(a,b){return jc(a,b)},getElementById:function(a){return fc(this,function(b){return b.id==a},function(a){return!!a})[0]||null}};Object.defineProperties(bd,{_activeElement:Ab.activeElement});
for(var cd=HTMLElement.prototype.blur,dd={blur:function(){var a=t(this);(a=(a=a&&a.root)&&a.activeElement)?a.blur():cd.call(this)}},L={},ed=q(Object.getOwnPropertyNames(Document.prototype)),fd=ed.next();!fd.done;L={l:L.l},fd=ed.next())L.l=fd.value,"on"===L.l.substring(0,2)&&Object.defineProperty(dd,L.l,{set:function(a){return function(b){var c=r(this),d=a.l.substring(2);c.I[a.l]&&this.removeEventListener(d,c.I[a.l]);this.addEventListener(d,b,{});c.I[a.l]=b}}(L),get:function(a){return function(){var b=
t(this);return b&&b.I[a.l]}}(L),configurable:!0});var gd=ra({addEventListener:function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.R=this;this.host.addEventListener(a,b,c)},removeEventListener:function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.R=this;this.host.removeEventListener(a,b,c)},getElementById:function(a){return fc(this,function(b){return b.id==a},function(a){return!!a})[0]||null}},Yc);v.preferPerformance||(ra(bd,Yc),ra(Zc,Yc));
function M(a,b){for(var c=Object.getOwnPropertyNames(b),d=0;d<c.length;d++){var e=c[d],f=Object.getOwnPropertyDescriptor(b,e);f.value?a[e]=f.value:Object.defineProperty(a,e,f)}};if(v.U){var ShadyDOM={inUse:v.U,patch:function(a){Eb(a);Db(a);return a},isShadyRoot:x,enqueue:Ca,flush:Da,settings:v,filterMutations:Ja,observeChildren:Ga,unobserveChildren:Ia,nativeMethods:z,nativeTree:F,deferConnectionCallbacks:v.deferConnectionCallbacks,preferPerformance:v.preferPerformance,handlesDynamicScoping:!0};window.ShadyDOM=ShadyDOM;Ec();var hd=window.customElements&&window.customElements.nativeHTMLElement||HTMLElement;M(Cb.prototype,gd);M(window.Node.prototype,Wc);M(window.Window.prototype,
Vc);M(window.Text.prototype,Xc);M(window.Element.prototype,ad);M(window.DocumentFragment.prototype,Zc);M(window.Document.prototype,bd);window.HTMLSlotElement&&M(window.HTMLSlotElement.prototype,$c);M(hd.prototype,dd);v.o&&(H(window.Node.prototype),H(window.Text.prototype),H(window.DocumentFragment.prototype),H(window.Element.prototype),H(hd.prototype),H(window.Document.prototype),window.HTMLSlotElement&&H(window.HTMLSlotElement.prototype));Bb();window.ShadowRoot=Cb};/*

Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
function id(){this.end=this.start=0;this.rules=this.parent=this.previous=null;this.cssText=this.parsedCssText="";this.atRule=!1;this.type=0;this.parsedSelector=this.selector=this.keyframesName=""}
function jd(a){a=a.replace(kd,"").replace(ld,"");var b=md,c=a,d=new id;d.start=0;d.end=c.length;for(var e=d,f=0,g=c.length;f<g;f++)if("{"===c[f]){e.rules||(e.rules=[]);var h=e,k=h.rules[h.rules.length-1]||null;e=new id;e.start=f+1;e.parent=h;e.previous=k;h.rules.push(e)}else"}"===c[f]&&(e.end=f+1,e=e.parent||d);return b(d,a)}
function md(a,b){var c=b.substring(a.start,a.end-1);a.parsedCssText=a.cssText=c.trim();a.parent&&(c=b.substring(a.previous?a.previous.end:a.parent.start,a.start-1),c=nd(c),c=c.replace(od," "),c=c.substring(c.lastIndexOf(";")+1),c=a.parsedSelector=a.selector=c.trim(),a.atRule=0===c.indexOf("@"),a.atRule?0===c.indexOf("@media")?a.type=pd:c.match(qd)&&(a.type=rd,a.keyframesName=a.selector.split(od).pop()):a.type=0===c.indexOf("--")?sd:td);if(c=a.rules)for(var d=0,e=c.length,f=void 0;d<e&&(f=c[d]);d++)md(f,
b);return a}function nd(a){return a.replace(/\\([0-9a-f]{1,6})\s/gi,function(a,c){a=c;for(c=6-a.length;c--;)a="0"+a;return"\\"+a})}
function ud(a,b,c){c=void 0===c?"":c;var d="";if(a.cssText||a.rules){var e=a.rules,f;if(f=e)f=e[0],f=!(f&&f.selector&&0===f.selector.indexOf("--"));if(f){f=0;for(var g=e.length,h=void 0;f<g&&(h=e[f]);f++)d=ud(h,b,d)}else b?b=a.cssText:(b=a.cssText,b=b.replace(vd,"").replace(wd,""),b=b.replace(xd,"").replace(yd,"")),(d=b.trim())&&(d="  "+d+"\n")}d&&(a.selector&&(c+=a.selector+" {\n"),c+=d,a.selector&&(c+="}\n\n"));return c}
var td=1,rd=7,pd=4,sd=1E3,kd=/\/\*[^*]*\*+([^/*][^*]*\*+)*\//gim,ld=/@import[^;]*;/gim,vd=/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?(?:[;\n]|$)/gim,wd=/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?{[^}]*?}(?:[;\n]|$)?/gim,xd=/@apply\s*\(?[^);]*\)?\s*(?:[;\n]|$)?/gim,yd=/[^;:]*?:[^;]*?var\([^;]*\)(?:[;\n]|$)?/gim,qd=/^@[^\s]*keyframes/,od=/\s+/g;var N=!(window.ShadyDOM&&window.ShadyDOM.inUse),zd;function Ad(a){zd=a&&a.shimcssproperties?!1:N||!(navigator.userAgent.match(/AppleWebKit\/601|Edge\/15/)||!window.CSS||!CSS.supports||!CSS.supports("box-shadow","0 0 0 var(--foo)"))}var Bd;window.ShadyCSS&&void 0!==window.ShadyCSS.cssBuild&&(Bd=window.ShadyCSS.cssBuild);window.ShadyCSS&&void 0!==window.ShadyCSS.nativeCss?zd=window.ShadyCSS.nativeCss:window.ShadyCSS?(Ad(window.ShadyCSS),window.ShadyCSS=void 0):Ad(window.WebComponents&&window.WebComponents.flags);
var O=zd,Cd=Bd;var Dd=/(?:^|[;\s{]\s*)(--[\w-]*?)\s*:\s*(?:((?:'(?:\\'|.)*?'|"(?:\\"|.)*?"|\([^)]*?\)|[^};{])+)|\{([^}]*)\}(?:(?=[;\s}])|$))/gi,Ed=/(?:^|\W+)@apply\s*\(?([^);\n]*)\)?/gi,Fd=/(--[\w-]+)\s*([:,;)]|$)/gi,Gd=/(animation\s*:)|(animation-name\s*:)/,Hd=/@media\s(.*)/,Id=/\{[^}]*\}/g;var Jd=new Set;function P(a,b){if(!a)return"";"string"===typeof a&&(a=jd(a));b&&Q(a,b);return ud(a,O)}function Kd(a){!a.__cssRules&&a.textContent&&(a.__cssRules=jd(a.textContent));return a.__cssRules||null}function Ld(a){return!!a.parent&&a.parent.type===rd}function Q(a,b,c,d){if(a){var e=!1,f=a.type;if(d&&f===pd){var g=a.selector.match(Hd);g&&(window.matchMedia(g[1]).matches||(e=!0))}f===td?b(a):c&&f===rd?c(a):f===sd&&(e=!0);if((a=a.rules)&&!e)for(e=0,f=a.length,g=void 0;e<f&&(g=a[e]);e++)Q(g,b,c,d)}}
function Md(a,b,c,d){var e=document.createElement("style");b&&e.setAttribute("scope",b);e.textContent=a;Nd(e,c,d);return e}var R=null;function Od(a){a=document.createComment(" Shady DOM styles for "+a+" ");var b=document.head;b.insertBefore(a,(R?R.nextSibling:null)||b.firstChild);return R=a}function Nd(a,b,c){b=b||document.head;b.insertBefore(a,c&&c.nextSibling||b.firstChild);R?a.compareDocumentPosition(R)===Node.DOCUMENT_POSITION_PRECEDING&&(R=a):R=a}
function Pd(a,b){for(var c=0,d=a.length;b<d;b++)if("("===a[b])c++;else if(")"===a[b]&&0===--c)return b;return-1}function Qd(a,b){var c=a.indexOf("var(");if(-1===c)return b(a,"","","");var d=Pd(a,c+3),e=a.substring(c+4,d);c=a.substring(0,c);a=Qd(a.substring(d+1),b);d=e.indexOf(",");return-1===d?b(c,e.trim(),"",a):b(c,e.substring(0,d).trim(),e.substring(d+1).trim(),a)}function Rd(a,b){N?a.setAttribute("class",b):window.ShadyDOM.nativeMethods.setAttribute.call(a,"class",b)}
function S(a){var b=a.localName,c="";b?-1<b.indexOf("-")||(c=b,b=a.getAttribute&&a.getAttribute("is")||""):(b=a.is,c=a.extends);return{is:b,G:c}}function Sd(a){for(var b=[],c="",d=0;0<=d&&d<a.length;d++)if("("===a[d]){var e=Pd(a,d);c+=a.slice(d,e+1);d=e}else","===a[d]?(b.push(c),c=""):c+=a[d];c&&b.push(c);return b}
function T(a){if(void 0!==Cd)return Cd;if(void 0===a.__cssBuild){var b=a.getAttribute("css-build");if(b)a.__cssBuild=b;else{a:{b="template"===a.localName?a.content.firstChild:a.firstChild;if(b instanceof Comment&&(b=b.textContent.trim().split(":"),"css-build"===b[0])){b=b[1];break a}b=""}if(""!==b){var c="template"===a.localName?a.content.firstChild:a.firstChild;c.parentNode.removeChild(c)}a.__cssBuild=b}}return a.__cssBuild||""}
function Td(a){a=void 0===a?"":a;return""!==a&&O?N?"shadow"===a:"shady"===a:!1};function Ud(){}function Vd(a,b){Wd(U,a,function(a){V(a,b||"")})}function Wd(a,b,c){b.nodeType===Node.ELEMENT_NODE&&c(b);var d;"template"===b.localName?d=(b.content||b._content||b).childNodes:d=b.children||b.childNodes;if(d)for(b=0;b<d.length;b++)Wd(a,d[b],c)}
function V(a,b,c){if(b)if(a.classList)c?(a.classList.remove("style-scope"),a.classList.remove(b)):(a.classList.add("style-scope"),a.classList.add(b));else if(a.getAttribute){var d=a.getAttribute("class");c?d&&(b=d.replace("style-scope","").replace(b,""),Rd(a,b)):Rd(a,(d?d+" ":"")+"style-scope "+b)}}function Xd(a,b,c){Wd(U,a,function(a){V(a,b,!0);V(a,c)})}function Yd(a,b){Wd(U,a,function(a){V(a,b||"",!0)})}
function Zd(a,b,c,d,e){var f=U;e=void 0===e?"":e;""===e&&(N||"shady"===(void 0===d?"":d)?e=P(b,c):(a=S(a),e=$d(f,b,a.is,a.G,c)+"\n\n"));return e.trim()}function $d(a,b,c,d,e){var f=ae(c,d);c=c?"."+c:"";return P(b,function(b){b.c||(b.selector=b.j=be(a,b,a.b,c,f),b.c=!0);e&&e(b,c,f)})}function ae(a,b){return b?"[is="+a+"]":a}
function be(a,b,c,d,e){var f=Sd(b.selector);if(!Ld(b)){b=0;for(var g=f.length,h=void 0;b<g&&(h=f[b]);b++)f[b]=c.call(a,h,d,e)}return f.filter(function(a){return!!a}).join(",")}function ce(a){return a.replace(de,function(a,c,d){-1<d.indexOf("+")?d=d.replace(/\+/g,"___"):-1<d.indexOf("___")&&(d=d.replace(/___/g,"+"));return":"+c+"("+d+")"})}
function ee(a){for(var b=[],c;c=a.match(fe);){var d=c.index,e=Pd(a,d);if(-1===e)throw Error(c.input+" selector missing ')'");c=a.slice(d,e+1);a=a.replace(c,"\ue000");b.push(c)}return{V:a,matches:b}}function ge(a,b){var c=a.split("\ue000");return b.reduce(function(a,b,f){return a+b+c[f+1]},c[0])}
Ud.prototype.b=function(a,b,c){var d=!1;a=a.trim();var e=de.test(a);e&&(a=a.replace(de,function(a,b,c){return":"+b+"("+c.replace(/\s/g,"")+")"}),a=ce(a));var f=fe.test(a);if(f){var g=ee(a);a=g.V;g=g.matches}a=a.replace(he,":host $1");a=a.replace(ie,function(a,e,f){d||(a=je(f,e,b,c),d=d||a.stop,e=a.oa,f=a.value);return e+f});f&&(a=ge(a,g));e&&(a=ce(a));return a};
function je(a,b,c,d){var e=a.indexOf("::slotted");0<=a.indexOf(":host")?a=ke(a,d):0!==e&&(a=c?le(a,c):a);c=!1;0<=e&&(b="",c=!0);if(c){var f=!0;c&&(a=a.replace(me,function(a,b){return" > "+b}))}a=a.replace(ne,function(a,b,c){return'[dir="'+c+'"] '+b+", "+b+'[dir="'+c+'"]'});return{value:a,oa:b,stop:f}}
function le(a,b){a=a.split(/(\[.+?\])/);for(var c=[],d=0;d<a.length;d++)if(1===d%2)c.push(a[d]);else{var e=a[d];if(""!==e||d!==a.length-1)e=e.split(":"),e[0]+=b,c.push(e.join(":"))}return c.join("")}function ke(a,b){var c=a.match(oe);return(c=c&&c[2].trim()||"")?c[0].match(pe)?a.replace(oe,function(a,c,f){return b+f}):c.split(pe)[0]===b?c:"should_not_match":a.replace(":host",b)}function qe(a){":root"===a.selector&&(a.selector="html")}
Ud.prototype.c=function(a){return a.match(":host")?"":a.match("::slotted")?this.b(a,":not(.style-scope)"):le(a.trim(),":not(.style-scope)")};p.Object.defineProperties(Ud.prototype,{a:{configurable:!0,enumerable:!0,get:function(){return"style-scope"}}});
var de=/:(nth[-\w]+)\(([^)]+)\)/,ie=/(^|[\s>+~]+)((?:\[.+?\]|[^\s>+~=[])+)/g,pe=/[[.:#*]/,he=/^(::slotted)/,oe=/(:host)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,me=/(?:::slotted)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,ne=/(.*):dir\((?:(ltr|rtl))\)/,fe=/:(?:matches|any|-(?:webkit|moz)-any)/,U=new Ud;function re(a,b,c,d,e){this.u=a||null;this.b=b||null;this.c=c||[];this.B=null;this.cssBuild=e||"";this.G=d||"";this.a=this.m=this.w=null}function W(a){return a?a.__styleInfo:null}function se(a,b){return a.__styleInfo=b}re.prototype.i=function(){return this.u};re.prototype._getStyleRules=re.prototype.i;function te(a){var b=this.matches||this.matchesSelector||this.mozMatchesSelector||this.msMatchesSelector||this.oMatchesSelector||this.webkitMatchesSelector;return b&&b.call(this,a)}var ue=navigator.userAgent.match("Trident");function ve(){}function we(a){var b={},c=[],d=0;Q(a,function(a){xe(a);a.index=d++;a=a.h.cssText;for(var c;c=Fd.exec(a);){var e=c[1];":"!==c[2]&&(b[e]=!0)}},function(a){c.push(a)});a.b=c;a=[];for(var e in b)a.push(e);return a}
function xe(a){if(!a.h){var b={},c={};ye(a,c)&&(b.s=c,a.rules=null);b.cssText=a.parsedCssText.replace(Id,"").replace(Dd,"");a.h=b}}function ye(a,b){var c=a.h;if(c){if(c.s)return Object.assign(b,c.s),!0}else{c=a.parsedCssText;for(var d;a=Dd.exec(c);){d=(a[2]||a[3]).trim();if("inherit"!==d||"unset"!==d)b[a[1].trim()]=d;d=!0}return d}}
function ze(a,b,c){b&&(b=0<=b.indexOf(";")?Ae(a,b,c):Qd(b,function(b,e,f,g){if(!e)return b+g;(e=ze(a,c[e],c))&&"initial"!==e?"apply-shim-inherit"===e&&(e="inherit"):e=ze(a,c[f]||f,c)||f;return b+(e||"")+g}));return b&&b.trim()||""}
function Ae(a,b,c){b=b.split(";");for(var d=0,e,f;d<b.length;d++)if(e=b[d]){Ed.lastIndex=0;if(f=Ed.exec(e))e=ze(a,c[f[1]],c);else if(f=e.indexOf(":"),-1!==f){var g=e.substring(f);g=g.trim();g=ze(a,g,c)||g;e=e.substring(0,f)+g}b[d]=e&&e.lastIndexOf(";")===e.length-1?e.slice(0,-1):e||""}return b.join(";")}
function Be(a,b){var c={},d=[];Q(a,function(a){a.h||xe(a);var e=a.j||a.parsedSelector;b&&a.h.s&&e&&te.call(b,e)&&(ye(a,c),a=a.index,e=parseInt(a/32,10),d[e]=(d[e]||0)|1<<a%32)},null,!0);return{s:c,key:d}}
function Ce(a,b,c,d){b.h||xe(b);if(b.h.s){var e=S(a);a=e.is;e=e.G;e=a?ae(a,e):"html";var f=b.parsedSelector,g=":host > *"===f||"html"===f,h=0===f.indexOf(":host")&&!g;"shady"===c&&(g=f===e+" > *."+e||-1!==f.indexOf("html"),h=!g&&0===f.indexOf(e));if(g||h)c=e,h&&(b.j||(b.j=be(U,b,U.b,a?"."+a:"",e)),c=b.j||e),d({V:c,ta:h,Ma:g})}}function De(a,b,c){var d={},e={};Q(b,function(b){Ce(a,b,c,function(c){te.call(a._element||a,c.V)&&(c.ta?ye(b,d):ye(b,e))})},null,!0);return{ua:e,sa:d}}
function Ee(a,b,c,d){var e=S(b),f=ae(e.is,e.G),g=new RegExp("(?:^|[^.#[:])"+(b.extends?"\\"+f.slice(0,-1)+"\\]":f)+"($|[.:[\\s>+~])"),h=W(b);e=h.u;h=h.cssBuild;var k=Fe(e,d);return Zd(b,e,function(b){var e="";b.h||xe(b);b.h.cssText&&(e=Ae(a,b.h.cssText,c));b.cssText=e;if(!N&&!Ld(b)&&b.cssText){var h=e=b.cssText;null==b.$&&(b.$=Gd.test(e));if(b.$)if(null==b.N){b.N=[];for(var l in k)h=k[l],h=h(e),e!==h&&(e=h,b.N.push(l))}else{for(l=0;l<b.N.length;++l)h=k[b.N[l]],e=h(e);h=e}b.cssText=h;b.j=b.j||b.selector;
e="."+d;l=Sd(b.j);h=0;for(var da=l.length,Ha=void 0;h<da&&(Ha=l[h]);h++)l[h]=Ha.match(g)?Ha.replace(f,e):e+" "+Ha;b.selector=l.join(",")}},h)}function Fe(a,b){a=a.b;var c={};if(!N&&a)for(var d=0,e=a[d];d<a.length;e=a[++d]){var f=e,g=b;f.i=new RegExp("\\b"+f.keyframesName+"(?!\\B|-)","g");f.a=f.keyframesName+"-"+g;f.j=f.j||f.selector;f.selector=f.j.replace(f.keyframesName,f.a);c[e.keyframesName]=Ge(e)}return c}function Ge(a){return function(b){return b.replace(a.i,a.a)}}
function He(a,b){var c=Ie,d=Kd(a);a.textContent=P(d,function(a){var d=a.cssText=a.parsedCssText;a.h&&a.h.cssText&&(d=d.replace(vd,"").replace(wd,""),a.cssText=Ae(c,d,b))})}p.Object.defineProperties(ve.prototype,{a:{configurable:!0,enumerable:!0,get:function(){return"x-scope"}}});var Ie=new ve;var X={},Je=window.customElements;if(Je&&!N){var Ke=Je.define;Je.define=function(a,b,c){X[a]||(X[a]=Od(a));Ke.call(Je,a,b,c)}};function Le(){this.cache={}}Le.prototype.store=function(a,b,c,d){var e=this.cache[a]||[];e.push({s:b,styleElement:c,m:d});100<e.length&&e.shift();this.cache[a]=e};Le.prototype.fetch=function(a,b,c){if(a=this.cache[a])for(var d=a.length-1;0<=d;d--){var e=a[d],f;a:{for(f=0;f<c.length;f++){var g=c[f];if(e.s[g]!==b[g]){f=!1;break a}}f=!0}if(f)return e}};function Me(){}var Ne=new RegExp(U.a+"\\s*([^\\s]*)");function Oe(a){return(a=(a.classList&&a.classList.value?a.classList.value:a.getAttribute("class")||"").match(Ne))?a[1]:""}function Pe(a){var b=a.getRootNode();return b===a||b===a.ownerDocument?"":(a=b.host)?S(a).is:""}
function Qe(a){for(var b=0;b<a.length;b++){var c=a[b];if(c.target!==document.documentElement&&c.target!==document.head)for(var d=0;d<c.addedNodes.length;d++){var e=c.addedNodes[d];if(e.nodeType===Node.ELEMENT_NODE){var f=e.getRootNode(),g=Oe(e);if(g&&f===e.ownerDocument&&("style"!==e.localName&&"template"!==e.localName||""===T(e)))Yd(e,g);else if(f instanceof ShadowRoot)for(f=Pe(e),f!==g&&Xd(e,g,f),e=window.ShadyDOM.nativeMethods.querySelectorAll.call(e,":not(."+U.a+")"),g=0;g<e.length;g++){f=e[g];
var h=Pe(f);h&&V(f,h)}}}}}
if(!(N||window.ShadyDOM&&window.ShadyDOM.handlesDynamicScoping)){var Re=new MutationObserver(Qe),Se=function(a){Re.observe(a,{childList:!0,subtree:!0})};if(window.customElements&&!window.customElements.polyfillWrapFlushCallback)Se(document);else{var Te=function(){Se(document.body)};window.HTMLImports?window.HTMLImports.whenReady(Te):requestAnimationFrame(function(){if("loading"===document.readyState){var a=function(){Te();document.removeEventListener("readystatechange",a)};document.addEventListener("readystatechange",
a)}else Te()})}Me=function(){Qe(Re.takeRecords())}}var Ue=Me;var Ve={};var We=Promise.resolve();function Xe(a){if(a=Ve[a])a._applyShimCurrentVersion=a._applyShimCurrentVersion||0,a._applyShimValidatingVersion=a._applyShimValidatingVersion||0,a._applyShimNextVersion=(a._applyShimNextVersion||0)+1}function Ye(a){return a._applyShimCurrentVersion===a._applyShimNextVersion}function Ze(a){a._applyShimValidatingVersion=a._applyShimNextVersion;a._validating||(a._validating=!0,We.then(function(){a._applyShimCurrentVersion=a._applyShimNextVersion;a._validating=!1}))};var $e=new Le;function Y(){this.Z={};this.c=document.documentElement;var a=new id;a.rules=[];this.i=se(this.c,new re(a));this.T=!1;this.b=this.a=null}m=Y.prototype;m.flush=function(){Ue()};m.qa=function(a){return Kd(a)};m.ya=function(a){return P(a)};m.prepareTemplate=function(a,b,c){this.prepareTemplateDom(a,b);this.prepareTemplateStyles(a,b,c)};
m.prepareTemplateStyles=function(a,b,c){if(!a._prepared){N||X[b]||(X[b]=Od(b));a._prepared=!0;a.name=b;a.extends=c;Ve[b]=a;var d=T(a),e=Td(d);c={is:b,extends:c};var f=[];for(var g=a.content.querySelectorAll("style"),h=0;h<g.length;h++){var k=g[h];if(k.hasAttribute("shady-unscoped")){if(!N){var l=k.textContent;Jd.has(l)||(Jd.add(l),l=k.cloneNode(!0),document.head.appendChild(l));k.parentNode.removeChild(k)}}else f.push(k.textContent),k.parentNode.removeChild(k)}f=f.join("").trim();af(this);if(!e){if(g=
!d)g=Ed.test(f)||Dd.test(f),Ed.lastIndex=0,Dd.lastIndex=0;h=jd(f);g&&O&&this.a&&this.a.transformRules(h,b);a._styleAst=h}g=[];O||(g=we(a._styleAst));if(!g.length||O)h=N?a.content:null,b=X[b]||null,d=Zd(c,a._styleAst,null,d,e?f:""),d=d.length?Md(d,c.is,h,b):null,a._style=d;a.a=g}};m.prepareTemplateDom=function(a,b){var c=T(a);N||"shady"===c||a._domPrepared||(a._domPrepared=!0,Vd(a.content,b))};
function bf(a){!a.b&&window.ShadyCSS&&window.ShadyCSS.CustomStyleInterface&&(a.b=window.ShadyCSS.CustomStyleInterface,a.b.transformCallback=function(b){a.ca(b)},a.b.validateCallback=function(){requestAnimationFrame(function(){(a.b.enqueued||a.T)&&a.flushCustomStyles()})})}function af(a){!a.a&&window.ShadyCSS&&window.ShadyCSS.ApplyShim&&(a.a=window.ShadyCSS.ApplyShim,a.a.invalidCallback=Xe);bf(a)}
m.flushCustomStyles=function(){af(this);if(this.b){var a=this.b.processStyles();if(this.b.enqueued&&!Td(this.i.cssBuild)){if(O){if(!this.i.cssBuild)for(var b=0;b<a.length;b++){var c=this.b.getStyleForCustomStyle(a[b]);if(c&&O&&this.a){var d=Kd(c);af(this);this.a.transformRules(d);c.textContent=P(d)}}}else{cf(this,this.c,this.i);for(b=0;b<a.length;b++)(c=this.b.getStyleForCustomStyle(a[b]))&&He(c,this.i.w);this.T&&this.styleDocument()}this.b.enqueued=!1}}};
m.styleElement=function(a,b){var c=W(a);if(!c){var d=S(a);c=d.is;d=d.G;var e=X[c]||null;c=Ve[c];if(c){var f=c._styleAst;var g=c.a;var h=T(c)}f=new re(f,e,g,d,h);c&&se(a,f);c=f}a!==this.c&&(this.T=!0);b&&(c.B=c.B||{},Object.assign(c.B,b));if(O){b=c;f=S(a).is;if(b.B){g=b.B;for(var k in g)null===k?a.style.removeProperty(k):a.style.setProperty(k,g[k])}if(!(!(k=Ve[f])&&a!==this.c||k&&""!==T(k))&&k&&k._style&&!Ye(k)){if(Ye(k)||k._applyShimValidatingVersion!==k._applyShimNextVersion)af(this),this.a&&this.a.transformRules(k._styleAst,
f),k._style.textContent=Zd(a,b.u),Ze(k);N&&(f=a.shadowRoot)&&(f=f.querySelector("style"))&&(f.textContent=Zd(a,b.u));b.u=k._styleAst}}else if(k=c,this.flush(),cf(this,a,k),k.c&&k.c.length){b=S(a).is;c=(f=$e.fetch(b,k.w,k.c))?f.styleElement:null;g=k.m;(h=f&&f.m)||(h=this.Z[b]=(this.Z[b]||0)+1,h=b+"-"+h);k.m=h;h=k.m;d=Ie;d=c?c.textContent||"":Ee(d,a,k.w,h);e=W(a);var l=e.a;l&&!N&&l!==c&&(l._useCount--,0>=l._useCount&&l.parentNode&&l.parentNode.removeChild(l));N?e.a?(e.a.textContent=d,c=e.a):d&&(c=Md(d,
h,a.shadowRoot,e.b)):c?c.parentNode||(ue&&-1<d.indexOf("@media")&&(c.textContent=d),Nd(c,null,e.b)):d&&(c=Md(d,h,null,e.b));c&&(c._useCount=c._useCount||0,e.a!=c&&c._useCount++,e.a=c);h=c;N||(c=k.m,e=d=a.getAttribute("class")||"",g&&(e=d.replace(new RegExp("\\s*x-scope\\s*"+g+"\\s*","g")," ")),e+=(e?" ":"")+"x-scope "+c,d!==e&&Rd(a,e));f||$e.store(b,k.w,h,k.m)}};function df(a,b){return(b=b.getRootNode().host)?W(b)?b:df(a,b):a.c}
function cf(a,b,c){a=df(a,b);var d=W(a);a=Object.create(d.w||null);var e=De(b,c.u,c.cssBuild);b=Be(d.u,b).s;Object.assign(a,e.sa,b,e.ua);b=c.B;for(var f in b)if((e=b[f])||0===e)a[f]=e;f=Ie;b=Object.getOwnPropertyNames(a);for(e=0;e<b.length;e++)d=b[e],a[d]=ze(f,a[d],a);c.w=a}m.styleDocument=function(a){this.styleSubtree(this.c,a)};
m.styleSubtree=function(a,b){var c=a.shadowRoot;(c||a===this.c)&&this.styleElement(a,b);if(b=c&&(c.children||c.childNodes))for(a=0;a<b.length;a++)this.styleSubtree(b[a]);else if(a=a.children||a.childNodes)for(b=0;b<a.length;b++)this.styleSubtree(a[b])};
m.ca=function(a){var b=this,c=T(a);c!==this.i.cssBuild&&(this.i.cssBuild=c);if(!Td(c)){var d=Kd(a);Q(d,function(a){if(N)qe(a);else{var d=U;a.selector=a.parsedSelector;qe(a);a.selector=a.j=be(d,a,d.c,void 0,void 0)}O&&""===c&&(af(b),b.a&&b.a.transformRule(a))});O?a.textContent=P(d):this.i.u.rules.push(d)}};m.getComputedStyleValue=function(a,b){var c;O||(c=(W(a)||W(df(this,a))).w[b]);return(c=c||window.getComputedStyle(a).getPropertyValue(b))?c.trim():""};
m.xa=function(a,b){var c=a.getRootNode();b=b?b.split(/\s/):[];c=c.host&&c.host.localName;if(!c){var d=a.getAttribute("class");if(d){d=d.split(/\s/);for(var e=0;e<d.length;e++)if(d[e]===U.a){c=d[e+1];break}}}c&&b.push(U.a,c);O||(c=W(a))&&c.m&&b.push(Ie.a,c.m);Rd(a,b.join(" "))};m.na=function(a){return W(a)};m.wa=function(a,b){V(a,b)};m.za=function(a,b){V(a,b,!0)};m.va=function(a){return Pe(a)};m.pa=function(a){return Oe(a)};Y.prototype.flush=Y.prototype.flush;Y.prototype.prepareTemplate=Y.prototype.prepareTemplate;
Y.prototype.styleElement=Y.prototype.styleElement;Y.prototype.styleDocument=Y.prototype.styleDocument;Y.prototype.styleSubtree=Y.prototype.styleSubtree;Y.prototype.getComputedStyleValue=Y.prototype.getComputedStyleValue;Y.prototype.setElementClass=Y.prototype.xa;Y.prototype._styleInfoForNode=Y.prototype.na;Y.prototype.transformCustomStyleForDocument=Y.prototype.ca;Y.prototype.getStyleAst=Y.prototype.qa;Y.prototype.styleAstToString=Y.prototype.ya;Y.prototype.flushCustomStyles=Y.prototype.flushCustomStyles;
Y.prototype.scopeNode=Y.prototype.wa;Y.prototype.unscopeNode=Y.prototype.za;Y.prototype.scopeForNode=Y.prototype.va;Y.prototype.currentScopeForNode=Y.prototype.pa;Object.defineProperties(Y.prototype,{nativeShadow:{get:function(){return N}},nativeCss:{get:function(){return O}}});var Z=new Y,ef,ff;window.ShadyCSS&&(ef=window.ShadyCSS.ApplyShim,ff=window.ShadyCSS.CustomStyleInterface);
window.ShadyCSS={ScopingShim:Z,prepareTemplate:function(a,b,c){Z.flushCustomStyles();Z.prepareTemplate(a,b,c)},prepareTemplateDom:function(a,b){Z.prepareTemplateDom(a,b)},prepareTemplateStyles:function(a,b,c){Z.flushCustomStyles();Z.prepareTemplateStyles(a,b,c)},styleSubtree:function(a,b){Z.flushCustomStyles();Z.styleSubtree(a,b)},styleElement:function(a){Z.flushCustomStyles();Z.styleElement(a)},styleDocument:function(a){Z.flushCustomStyles();Z.styleDocument(a)},flushCustomStyles:function(){Z.flushCustomStyles()},
getComputedStyleValue:function(a,b){return Z.getComputedStyleValue(a,b)},nativeCss:O,nativeShadow:N,cssBuild:Cd};ef&&(window.ShadyCSS.ApplyShim=ef);ff&&(window.ShadyCSS.CustomStyleInterface=ff);var gf=window.document;window.WebComponents=window.WebComponents||{};function hf(){window.WebComponents.ready=!0;window.document.dispatchEvent(new CustomEvent("WebComponentsReady",{bubbles:!0}))}function jf(){hf();gf.removeEventListener("readystatechange",jf)}"loading"!==gf.readyState?hf():gf.addEventListener("readystatechange",jf);}).call(this);

//# sourceMappingURL=webcomponents-sd.js.map
