/**
@license @nocompile
Copyright (c) 2018 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){/*

Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
'use strict';var n,aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},q="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function ba(){ba=function(){};q.Symbol||(q.Symbol=ca)}var ca=function(){var a=0;return function(b){return"jscomp_symbol_"+(b||"")+a++}}();
function da(){ba();var a=q.Symbol.iterator;a||(a=q.Symbol.iterator=q.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&aa(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ea(this)}});da=function(){}}function ea(a){var b=0;return fa(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function fa(a){da();a={next:a};a[q.Symbol.iterator]=function(){return this};return a}function ha(a){da();ba();da();var b=a[Symbol.iterator];return b?b.call(a):ea(a)}
function ia(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c}function ja(){this.ma=this.root=null;this.R=!1;this.A=this.M=this.ba=this.assignedSlot=this.assignedNodes=this.D=null;this.childNodes=this.nextSibling=this.previousSibling=this.lastChild=this.firstChild=this.parentNode=this.G=void 0;this.qa=this.ia=!1;this.K={}}ja.prototype.toJSON=function(){return{}};function r(a){a.X||(a.X=new ja);return a.X}function t(a){return a&&a.X};var u=window.ShadyDOM||{};u.Ba=!(!Element.prototype.attachShadow||!Node.prototype.getRootNode);var ka=Object.getOwnPropertyDescriptor(Node.prototype,"firstChild");u.u=!!(ka&&ka.configurable&&ka.get);u.ea=u.force||!u.Ba;var la=navigator.userAgent.match("Trident"),ma=navigator.userAgent.match("Edge");void 0===u.oa&&(u.oa=u.u&&(la||ma));function v(a){return(a=t(a))&&void 0!==a.firstChild}function w(a){return"ShadyRoot"===a.wa}function na(a){a=a.getRootNode();if(w(a))return a}
var oa=Element.prototype,pa=oa.matches||oa.matchesSelector||oa.mozMatchesSelector||oa.msMatchesSelector||oa.oMatchesSelector||oa.webkitMatchesSelector;function qa(a,b){if(a&&b)for(var c=Object.getOwnPropertyNames(b),d=0,e;d<c.length&&(e=c[d]);d++){var f=Object.getOwnPropertyDescriptor(b,e);f&&Object.defineProperty(a,e,f)}}function ra(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];for(d=0;d<c.length;d++)qa(a,c[d]);return a}function sa(a,b){for(var c in b)a[c]=b[c]}
var ta=document.createTextNode(""),ua=0,wa=[];(new MutationObserver(function(){for(;wa.length;)try{wa.shift()()}catch(a){throw ta.textContent=ua++,a;}})).observe(ta,{characterData:!0});function xa(a){wa.push(a);ta.textContent=ua++}var ya=!!document.contains;function za(a,b){for(;b;){if(b==a)return!0;b=b.parentNode}return!1}
function Aa(a){for(var b=a.length-1;0<=b;b--){var c=a[b],d=c.getAttribute("id")||c.getAttribute("name");d&&"length"!==d&&isNaN(d)&&(a[d]=c)}a.item=function(b){return a[b]};a.namedItem=function(b){if("length"!==b&&isNaN(b)&&a[b])return a[b];for(var c=ha(a),d=c.next();!d.done;d=c.next())if(d=d.value,(d.getAttribute("id")||d.getAttribute("name"))==b)return d;return null};return a};var Ba=[],Ca;function Da(a){Ca||(Ca=!0,xa(Ea));Ba.push(a)}function Ea(){Ca=!1;for(var a=!!Ba.length;Ba.length;)Ba.shift()();return a}Ea.list=Ba;function Fa(){this.a=!1;this.addedNodes=[];this.removedNodes=[];this.P=new Set}function Ga(a){a.a||(a.a=!0,xa(function(){Ha(a)}))}function Ha(a){if(a.a){a.a=!1;var b=a.takeRecords();b.length&&a.P.forEach(function(a){a(b)})}}Fa.prototype.takeRecords=function(){if(this.addedNodes.length||this.removedNodes.length){var a=[{addedNodes:this.addedNodes,removedNodes:this.removedNodes}];this.addedNodes=[];this.removedNodes=[];return a}return[]};
function Ia(a,b){var c=r(a);c.D||(c.D=new Fa);c.D.P.add(b);var d=c.D;return{ua:b,C:d,xa:a,takeRecords:function(){return d.takeRecords()}}}function Ja(a){var b=a&&a.C;b&&(b.P.delete(a.ua),b.P.size||(r(a.xa).D=null))}
function Ka(a,b){var c=b.getRootNode();return a.map(function(a){var b=c===a.target.getRootNode();if(b&&a.addedNodes){if(b=Array.from(a.addedNodes).filter(function(a){return c===a.getRootNode()}),b.length)return a=Object.create(a),Object.defineProperty(a,"addedNodes",{value:b,configurable:!0}),a}else if(b)return a}).filter(function(a){return a})};var x={},La=Element.prototype.insertBefore,Ma=Element.prototype.replaceChild,Na=Element.prototype.removeChild,Oa=Element.prototype.setAttribute,Pa=Element.prototype.removeAttribute,Qa=Element.prototype.cloneNode,Ra=Document.prototype.importNode,Sa=Element.prototype.addEventListener,Ta=Element.prototype.removeEventListener,Ua=Window.prototype.addEventListener,Va=Window.prototype.removeEventListener,Wa=Element.prototype.dispatchEvent,Xa=Node.prototype.contains||HTMLElement.prototype.contains,Ya=Document.prototype.getElementById,
Za=Element.prototype.querySelector,$a=DocumentFragment.prototype.querySelector,ab=Document.prototype.querySelector,bb=Element.prototype.querySelectorAll,cb=DocumentFragment.prototype.querySelectorAll,db=Document.prototype.querySelectorAll;x.appendChild=Element.prototype.appendChild;x.insertBefore=La;x.replaceChild=Ma;x.removeChild=Na;x.setAttribute=Oa;x.removeAttribute=Pa;x.cloneNode=Qa;x.importNode=Ra;x.addEventListener=Sa;x.removeEventListener=Ta;x.Ka=Ua;x.La=Va;x.dispatchEvent=Wa;x.contains=Xa;
x.getElementById=Ya;x.Ua=Za;x.Xa=$a;x.Sa=ab;x.querySelector=function(a){switch(this.nodeType){case Node.ELEMENT_NODE:return Za.call(this,a);case Node.DOCUMENT_NODE:return ab.call(this,a);default:return $a.call(this,a)}};x.Va=bb;x.Ya=cb;x.Ta=db;x.querySelectorAll=function(a){switch(this.nodeType){case Node.ELEMENT_NODE:return bb.call(this,a);case Node.DOCUMENT_NODE:return db.call(this,a);default:return cb.call(this,a)}};var eb=/[&\u00A0"]/g,fb=/[&\u00A0<>]/g;function gb(a){switch(a){case "&":return"&amp;";case "<":return"&lt;";case ">":return"&gt;";case '"':return"&quot;";case "\u00a0":return"&nbsp;"}}function hb(a){for(var b={},c=0;c<a.length;c++)b[a[c]]=!0;return b}var ib=hb("area base br col command embed hr img input keygen link meta param source track wbr".split(" ")),jb=hb("style script xmp iframe noembed noframes plaintext noscript".split(" "));
function kb(a,b){"template"===a.localName&&(a=a.content);for(var c="",d=b?b(a):a.childNodes,e=0,f=d.length,g;e<f&&(g=d[e]);e++){a:{var h=g;var k=a;var l=b;switch(h.nodeType){case Node.ELEMENT_NODE:for(var m=h.localName,p="<"+m,O=h.attributes,M=0;k=O[M];M++)p+=" "+k.name+'="'+k.value.replace(eb,gb)+'"';p+=">";h=ib[m]?p:p+kb(h,l)+"</"+m+">";break a;case Node.TEXT_NODE:h=h.data;h=k&&jb[k.localName]?h:h.replace(fb,gb);break a;case Node.COMMENT_NODE:h="\x3c!--"+h.data+"--\x3e";break a;default:throw window.console.error(h),
Error("not implemented");}}c+=h}return c};var y={},z=document.createTreeWalker(document,NodeFilter.SHOW_ALL,null,!1),A=document.createTreeWalker(document,NodeFilter.SHOW_ELEMENT,null,!1);function lb(a){var b=[];z.currentNode=a;for(a=z.firstChild();a;)b.push(a),a=z.nextSibling();return b}y.parentNode=function(a){z.currentNode=a;return z.parentNode()};y.firstChild=function(a){z.currentNode=a;return z.firstChild()};y.lastChild=function(a){z.currentNode=a;return z.lastChild()};y.previousSibling=function(a){z.currentNode=a;return z.previousSibling()};
y.nextSibling=function(a){z.currentNode=a;return z.nextSibling()};y.childNodes=lb;y.parentElement=function(a){A.currentNode=a;return A.parentNode()};y.firstElementChild=function(a){A.currentNode=a;return A.firstChild()};y.lastElementChild=function(a){A.currentNode=a;return A.lastChild()};y.previousElementSibling=function(a){A.currentNode=a;return A.previousSibling()};y.nextElementSibling=function(a){A.currentNode=a;return A.nextSibling()};
y.children=function(a){var b=[];A.currentNode=a;for(a=A.firstChild();a;)b.push(a),a=A.nextSibling();return Aa(b)};y.innerHTML=function(a){return kb(a,function(a){return lb(a)})};y.textContent=function(a){switch(a.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:a=document.createTreeWalker(a,NodeFilter.SHOW_TEXT,null,!1);for(var b="",c;c=a.nextNode();)b+=c.nodeValue;return b;default:return a.nodeValue}};var B={},mb=u.u,nb=[Node.prototype,Element.prototype,HTMLElement.prototype];function C(a){var b;a:{for(b=0;b<nb.length;b++){var c=nb[b];if(c.hasOwnProperty(a)){b=c;break a}}b=void 0}if(!b)throw Error("Could not find descriptor for "+a);return Object.getOwnPropertyDescriptor(b,a)}
var D=mb?{parentNode:C("parentNode"),firstChild:C("firstChild"),lastChild:C("lastChild"),previousSibling:C("previousSibling"),nextSibling:C("nextSibling"),childNodes:C("childNodes"),parentElement:C("parentElement"),previousElementSibling:C("previousElementSibling"),nextElementSibling:C("nextElementSibling"),innerHTML:C("innerHTML"),textContent:C("textContent"),firstElementChild:C("firstElementChild"),lastElementChild:C("lastElementChild"),children:C("children")}:{},ob=mb?{firstElementChild:Object.getOwnPropertyDescriptor(DocumentFragment.prototype,
"firstElementChild"),lastElementChild:Object.getOwnPropertyDescriptor(DocumentFragment.prototype,"lastElementChild"),children:Object.getOwnPropertyDescriptor(DocumentFragment.prototype,"children")}:{},pb=mb?{firstElementChild:Object.getOwnPropertyDescriptor(Document.prototype,"firstElementChild"),lastElementChild:Object.getOwnPropertyDescriptor(Document.prototype,"lastElementChild"),children:Object.getOwnPropertyDescriptor(Document.prototype,"children")}:{};B.la=D;B.Wa=ob;B.Ra=pb;B.parentNode=function(a){return D.parentNode.get.call(a)};
B.firstChild=function(a){return D.firstChild.get.call(a)};B.lastChild=function(a){return D.lastChild.get.call(a)};B.previousSibling=function(a){return D.previousSibling.get.call(a)};B.nextSibling=function(a){return D.nextSibling.get.call(a)};B.childNodes=function(a){return Array.prototype.slice.call(D.childNodes.get.call(a))};B.parentElement=function(a){return D.parentElement.get.call(a)};B.previousElementSibling=function(a){return D.previousElementSibling.get.call(a)};B.nextElementSibling=function(a){return D.nextElementSibling.get.call(a)};
B.innerHTML=function(a){return D.innerHTML.get.call(a)};B.textContent=function(a){return D.textContent.get.call(a)};B.children=function(a){switch(a.nodeType){case Node.DOCUMENT_FRAGMENT_NODE:return ob.children.get.call(a);case Node.DOCUMENT_NODE:return pb.children.get.call(a);default:return D.children.get.call(a)}};
B.firstElementChild=function(a){switch(a.nodeType){case Node.DOCUMENT_FRAGMENT_NODE:return ob.firstElementChild.get.call(a);case Node.DOCUMENT_NODE:return pb.firstElementChild.get.call(a);default:return D.firstElementChild.get.call(a)}};B.lastElementChild=function(a){switch(a.nodeType){case Node.DOCUMENT_FRAGMENT_NODE:return ob.lastElementChild.get.call(a);case Node.DOCUMENT_NODE:return pb.lastElementChild.get.call(a);default:return D.lastElementChild.get.call(a)}};var E=u.oa?B:y;function qb(a){for(;a.firstChild;)a.removeChild(a.firstChild)}
var rb=u.u,sb=document.implementation.createHTMLDocument("inert"),tb=Object.getOwnPropertyDescriptor(Node.prototype,"isConnected"),ub=tb&&tb.get,vb=Object.getOwnPropertyDescriptor(Document.prototype,"activeElement"),wb={parentElement:{get:function(){var a=t(this);(a=a&&a.parentNode)&&a.nodeType!==Node.ELEMENT_NODE&&(a=null);return void 0!==a?a:E.parentElement(this)},configurable:!0},parentNode:{get:function(){var a=t(this);a=a&&a.parentNode;return void 0!==a?a:E.parentNode(this)},configurable:!0},
nextSibling:{get:function(){var a=t(this);a=a&&a.nextSibling;return void 0!==a?a:E.nextSibling(this)},configurable:!0},previousSibling:{get:function(){var a=t(this);a=a&&a.previousSibling;return void 0!==a?a:E.previousSibling(this)},configurable:!0},nextElementSibling:{get:function(){var a=t(this);if(a&&void 0!==a.nextSibling){for(a=this.nextSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.nextSibling;return a}return E.nextElementSibling(this)},configurable:!0},previousElementSibling:{get:function(){var a=
t(this);if(a&&void 0!==a.previousSibling){for(a=this.previousSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.previousSibling;return a}return E.previousElementSibling(this)},configurable:!0}},xb={className:{get:function(){return this.getAttribute("class")||""},set:function(a){this.setAttribute("class",a)},configurable:!0}},yb={childNodes:{get:function(){if(v(this)){var a=t(this);if(!a.childNodes){a.childNodes=[];for(var b=this.firstChild;b;b=b.nextSibling)a.childNodes.push(b)}var c=a.childNodes}else c=
E.childNodes(this);c.item=function(a){return c[a]};return c},configurable:!0},childElementCount:{get:function(){return this.children.length},configurable:!0},firstChild:{get:function(){var a=t(this);a=a&&a.firstChild;return void 0!==a?a:E.firstChild(this)},configurable:!0},lastChild:{get:function(){var a=t(this);a=a&&a.lastChild;return void 0!==a?a:E.lastChild(this)},configurable:!0},textContent:{get:function(){if(v(this)){for(var a=[],b=0,c=this.childNodes,d;d=c[b];b++)d.nodeType!==Node.COMMENT_NODE&&
a.push(d.textContent);return a.join("")}return E.textContent(this)},set:function(a){if("undefined"===typeof a||null===a)a="";switch(this.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:if(!v(this)&&rb){var b=this.firstChild;(b!=this.lastChild||b&&b.nodeType!=Node.TEXT_NODE)&&qb(this);B.la.textContent.set.call(this,a)}else qb(this),(0<a.length||this.nodeType===Node.ELEMENT_NODE)&&this.appendChild(document.createTextNode(a));break;default:this.nodeValue=a}},configurable:!0},firstElementChild:{get:function(){var a=
t(this);if(a&&void 0!==a.firstChild){for(a=this.firstChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.nextSibling;return a}return E.firstElementChild(this)},configurable:!0},lastElementChild:{get:function(){var a=t(this);if(a&&void 0!==a.lastChild){for(a=this.lastChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.previousSibling;return a}return E.lastElementChild(this)},configurable:!0},children:{get:function(){return v(this)?Aa(Array.prototype.filter.call(this.childNodes,function(a){return a.nodeType===Node.ELEMENT_NODE})):
E.children(this)},configurable:!0},innerHTML:{get:function(){return v(this)?kb("template"===this.localName?this.content:this):E.innerHTML(this)},set:function(a){var b="template"===this.localName?this.content:this;qb(b);var c=this.localName||"div";c=this.namespaceURI&&this.namespaceURI!==sb.namespaceURI?sb.createElementNS(this.namespaceURI,c):sb.createElement(c);rb?B.la.innerHTML.set.call(c,a):c.innerHTML=a;for(a="template"===this.localName?c.content:c;a.firstChild;)b.appendChild(a.firstChild)},configurable:!0}},
zb={shadowRoot:{get:function(){var a=t(this);return a&&a.ma||null},configurable:!0}},Ab={activeElement:{get:function(){var a=vb&&vb.get?vb.get.call(document):u.u?void 0:document.activeElement;if(a&&a.nodeType){var b=!!w(this);if(this===document||b&&this.host!==a&&x.contains.call(this.host,a)){for(b=na(a);b&&b!==this;)a=b.host,b=na(a);a=this===document?b?null:a:b===this?a:null}else a=null}else a=null;return a},set:function(){},configurable:!0}};
function F(a,b,c){for(var d in b){var e=Object.getOwnPropertyDescriptor(a,d);e&&e.configurable||!e&&c?Object.defineProperty(a,d,b[d]):c&&console.warn("Could not define",d,"on",a)}}function G(a){F(a,wb);F(a,xb);F(a,yb);F(a,Ab)}
function Bb(){var a=Cb.prototype;a.__proto__=DocumentFragment.prototype;F(a,wb,!0);F(a,yb,!0);F(a,Ab,!0);Object.defineProperties(a,{nodeType:{value:Node.DOCUMENT_FRAGMENT_NODE,configurable:!0},nodeName:{value:"#document-fragment",configurable:!0},nodeValue:{value:null,configurable:!0}});["localName","namespaceURI","prefix"].forEach(function(b){Object.defineProperty(a,b,{value:void 0,configurable:!0})});["ownerDocument","baseURI","isConnected"].forEach(function(b){Object.defineProperty(a,b,{get:function(){return this.host[b]},
configurable:!0})})}var Db=u.u?function(){}:function(a){var b=r(a);b.ia||(b.ia=!0,F(a,wb,!0),F(a,xb,!0))},Eb=u.u?function(){}:function(a){r(a).qa||(F(a,yb,!0),F(a,zb,!0))};var Fb=E.childNodes;function Gb(a,b,c){Db(a);c=c||null;var d=r(a),e=r(b),f=c?r(c):null;d.previousSibling=c?f.previousSibling:b.lastChild;if(f=t(d.previousSibling))f.nextSibling=a;if(f=t(d.nextSibling=c))f.previousSibling=a;d.parentNode=b;c?c===e.firstChild&&(e.firstChild=a):(e.lastChild=a,e.firstChild||(e.firstChild=a));e.childNodes=null}
function Hb(a){var b=r(a);if(void 0===b.firstChild){b.childNodes=null;var c=Fb(a);b.firstChild=c[0]||null;b.lastChild=c[c.length-1]||null;Eb(a);for(b=0;b<c.length;b++){var d=c[b],e=r(d);e.parentNode=a;e.nextSibling=c[b+1]||null;e.previousSibling=c[b-1]||null;Db(d)}}};var Ib=E.parentNode;
function Jb(a,b,c){if(b===a)throw Error("Failed to execute 'appendChild' on 'Node': The new child element contains the parent.");if(c){var d=t(c);d=d&&d.parentNode;if(void 0!==d&&d!==a||void 0===d&&Ib(c)!==a)throw Error("Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.");}if(c===b)return b;b.parentNode&&Kb(b.parentNode,b);var e,f;if(!b.__noInsertionPoint){if(f=e=na(a)){var g;"slot"===b.localName?g=[b]:b.querySelectorAll&&
(g=b.querySelectorAll("slot"));f=g&&g.length?g:void 0}f&&(g=e,d=f,g.a=g.a||[],g.f=g.f||[],g.g=g.g||{},g.a.push.apply(g.a,[].concat(d instanceof Array?d:ia(ha(d)))))}("slot"===a.localName||f)&&(e=e||na(a))&&H(e);if(v(a)){e=c;Eb(a);f=r(a);void 0!==f.firstChild&&(f.childNodes=null);if(b.nodeType===Node.DOCUMENT_FRAGMENT_NODE){f=b.childNodes;for(g=0;g<f.length;g++)Gb(f[g],a,e);e=r(b);f=void 0!==e.firstChild?null:void 0;e.firstChild=e.lastChild=f;e.childNodes=f}else Gb(b,a,e);e=t(a);if(Lb(a)){H(e.root);
var h=!0}else e.root&&(h=!0)}h||(h=w(a)?a.host:a,c?(c=Mb(c),x.insertBefore.call(h,b,c)):x.appendChild.call(h,b));Nb(a,b);return b}
function Kb(a,b){if(b.parentNode!==a)throw Error("The node to be removed is not a child of this node: "+b);var c=na(b),d=t(a);if(v(a)){var e=r(b),f=r(a);b===f.firstChild&&(f.firstChild=e.nextSibling);b===f.lastChild&&(f.lastChild=e.previousSibling);var g=e.previousSibling,h=e.nextSibling;g&&(r(g).nextSibling=h);h&&(r(h).previousSibling=g);e.parentNode=e.previousSibling=e.nextSibling=void 0;void 0!==f.childNodes&&(f.childNodes=null);if(Lb(a)){H(d.root);var k=!0}}Ob(b);if(c){(e=a&&"slot"===a.localName)&&
(k=!0);if(c.f){Pb(c);f=c.g;for(va in f)for(g=f[va],h=0;h<g.length;h++){var l=g[h];if(za(b,l)){g.splice(h,1);var m=c.f.indexOf(l);0<=m&&c.f.splice(m,1);h--;m=t(l);if(l=m.A)for(var p=0;p<l.length;p++){var O=l[p],M=Qb(O);M&&x.removeChild.call(M,O)}m.A=[];m.assignedNodes=[];m=!0}}var va=m}else va=void 0;(va||e)&&H(c)}k||(k=w(a)?a.host:a,(!d.root&&"slot"!==b.localName||k===Ib(b))&&x.removeChild.call(k,b));Nb(a,null,b);return b}
function Ob(a){var b=t(a);if(b&&void 0!==b.G){b=a.childNodes;for(var c=0,d=b.length,e;c<d&&(e=b[c]);c++)Ob(e)}if(a=t(a))a.G=void 0}function Mb(a){var b=a;a&&"slot"===a.localName&&(b=(b=(b=t(a))&&b.A)&&b.length?b[0]:Mb(a.nextSibling));return b}function Lb(a){return(a=(a=t(a))&&a.root)&&Rb(a)}
function Sb(a,b){if("slot"===b)a=a.parentNode,Lb(a)&&H(t(a).root);else if("slot"===a.localName&&"name"===b&&(b=na(a))){if(b.f){var c=a.ta,d=Tb(a);if(d!==c){c=b.g[c];var e=c.indexOf(a);0<=e&&c.splice(e,1);c=b.g[d]||(b.g[d]=[]);c.push(a);1<c.length&&(b.g[d]=Ub(c))}}H(b)}}function Nb(a,b,c){if(a=(a=t(a))&&a.D)b&&a.addedNodes.push(b),c&&a.removedNodes.push(c),Ga(a)}
function Vb(a){if(a&&a.nodeType){var b=r(a),c=b.G;void 0===c&&(w(a)?(c=a,b.G=c):(c=(c=a.parentNode)?Vb(c):a,x.contains.call(document.documentElement,a)&&(b.G=c)));return c}}function Wb(a,b,c){var d=[];Xb(a.childNodes,b,c,d);return d}function Xb(a,b,c,d){for(var e=0,f=a.length,g;e<f&&(g=a[e]);e++){var h;if(h=g.nodeType===Node.ELEMENT_NODE){h=g;var k=b,l=c,m=d,p=k(h);p&&m.push(h);l&&l(p)?h=p:(Xb(h.childNodes,k,l,m),h=void 0)}if(h)break}}var Yb=null;
function Zb(a,b,c){Yb||(Yb=window.ShadyCSS&&window.ShadyCSS.ScopingShim);Yb&&"class"===b?Yb.setElementClass(a,c):(x.setAttribute.call(a,b,c),Sb(a,b))}function $b(a,b){if(a.ownerDocument!==document||"template"===a.localName)return x.importNode.call(document,a,b);var c=x.importNode.call(document,a,!1);if(b){a=a.childNodes;b=0;for(var d;b<a.length;b++)d=$b(a[b],!0),c.appendChild(d)}return c};var ac="__eventWrappers"+Date.now(),bc=function(){var a=Object.getOwnPropertyDescriptor(Event.prototype,"composed");return a?function(b){return a.get.call(b)}:null}(),cc={blur:!0,focus:!0,focusin:!0,focusout:!0,click:!0,dblclick:!0,mousedown:!0,mouseenter:!0,mouseleave:!0,mousemove:!0,mouseout:!0,mouseover:!0,mouseup:!0,wheel:!0,beforeinput:!0,input:!0,keydown:!0,keyup:!0,compositionstart:!0,compositionupdate:!0,compositionend:!0,touchstart:!0,touchend:!0,touchmove:!0,touchcancel:!0,pointerover:!0,
pointerenter:!0,pointerdown:!0,pointermove:!0,pointerup:!0,pointercancel:!0,pointerout:!0,pointerleave:!0,gotpointercapture:!0,lostpointercapture:!0,dragstart:!0,drag:!0,dragenter:!0,dragleave:!0,dragover:!0,drop:!0,dragend:!0,DOMActivate:!0,DOMFocusIn:!0,DOMFocusOut:!0,keypress:!0},dc={DOMAttrModified:!0,DOMAttributeNameChanged:!0,DOMCharacterDataModified:!0,DOMElementNameChanged:!0,DOMNodeInserted:!0,DOMNodeInsertedIntoDocument:!0,DOMNodeRemoved:!0,DOMNodeRemovedFromDocument:!0,DOMSubtreeModified:!0};
function ec(a,b){var c=[],d=a;for(a=a===window?window:a.getRootNode();d;)c.push(d),d=d.assignedSlot?d.assignedSlot:d.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&d.host&&(b||d!==a)?d.host:d.parentNode;c[c.length-1]===document&&c.push(window);return c}function fc(a,b){if(!w)return a;a=ec(a,!0);for(var c=0,d,e,f,g;c<b.length;c++)if(d=b[c],f=d===window?window:d.getRootNode(),f!==e&&(g=a.indexOf(f),e=f),!w(f)||-1<g)return d}
var gc={get composed(){void 0===this.J&&(bc?this.J=bc(this):!1!==this.isTrusted&&(this.J=cc[this.type]));return this.J||!1},composedPath:function(){this.ha||(this.ha=ec(this.__target,this.composed));return this.ha},get target(){return fc(this.currentTarget,this.composedPath())},get relatedTarget(){if(!this.W)return null;this.ja||(this.ja=ec(this.W,!0));return fc(this.currentTarget,this.ja)},stopPropagation:function(){Event.prototype.stopPropagation.call(this);this.V=!0},stopImmediatePropagation:function(){Event.prototype.stopImmediatePropagation.call(this);
this.V=this.pa=!0}};function hc(a){function b(b,d){b=new a(b,d);b.J=d&&!!d.composed;return b}sa(b,a);b.prototype=a.prototype;return b}var ic={focus:!0,blur:!0};function jc(a){return a.__target!==a.target||a.W!==a.relatedTarget}function kc(a,b,c){if(c=b.__handlers&&b.__handlers[a.type]&&b.__handlers[a.type][c])for(var d=0,e;(e=c[d])&&(!jc(a)||a.target!==a.relatedTarget)&&(e.call(b,a),!a.pa);d++);}
function lc(a){var b=a.composedPath();Object.defineProperty(a,"currentTarget",{get:function(){return d},configurable:!0});for(var c=b.length-1;0<=c;c--){var d=b[c];kc(a,d,"capture");if(a.V)return}Object.defineProperty(a,"eventPhase",{get:function(){return Event.AT_TARGET}});var e;for(c=0;c<b.length;c++){d=b[c];var f=t(d);f=f&&f.root;if(0===c||f&&f===e)if(kc(a,d,"bubble"),d!==window&&(e=d.getRootNode()),a.V)break}}
function mc(a,b,c,d,e,f){for(var g=0;g<a.length;g++){var h=a[g],k=h.type,l=h.capture,m=h.once,p=h.passive;if(b===h.node&&c===k&&d===l&&e===m&&f===p)return g}return-1}
function nc(a,b,c){if(b){var d=typeof b;if("function"===d||"object"===d)if("object"!==d||b.handleEvent&&"function"===typeof b.handleEvent){var e=this instanceof Window?x.Ka:x.addEventListener;if(dc[a])return e.call(this,a,b,c);if(c&&"object"===typeof c){var f=!!c.capture;var g=!!c.once;var h=!!c.passive}else f=!!c,h=g=!1;var k=c&&c.Y||this,l=b[ac];if(l){if(-1<mc(l,k,a,f,g,h))return}else b[ac]=[];l=function(e){g&&this.removeEventListener(a,b,c);e.__target||oc(e);if(k!==this){var f=Object.getOwnPropertyDescriptor(e,
"currentTarget");Object.defineProperty(e,"currentTarget",{get:function(){return k},configurable:!0})}if(!w(k)||-1!=e.composedPath().indexOf(k))if(e.composed||-1<e.composedPath().indexOf(k))if(jc(e)&&e.target===e.relatedTarget)e.eventPhase===Event.BUBBLING_PHASE&&e.stopImmediatePropagation();else if(e.eventPhase===Event.CAPTURING_PHASE||e.bubbles||e.target===k||k instanceof Window){var h="function"===d?b.call(k,e):b.handleEvent&&b.handleEvent(e);k!==this&&(f?(Object.defineProperty(e,"currentTarget",
f),f=null):delete e.currentTarget);return h}};b[ac].push({node:k,type:a,capture:f,once:g,passive:h,Ma:l});ic[a]?(this.__handlers=this.__handlers||{},this.__handlers[a]=this.__handlers[a]||{capture:[],bubble:[]},this.__handlers[a][f?"capture":"bubble"].push(l)):e.call(this,a,l,c)}}}
function pc(a,b,c){if(b){var d=this instanceof Window?x.La:x.removeEventListener;if(dc[a])return d.call(this,a,b,c);if(c&&"object"===typeof c){var e=!!c.capture;var f=!!c.once;var g=!!c.passive}else e=!!c,g=f=!1;var h=c&&c.Y||this,k=void 0;var l=null;try{l=b[ac]}catch(m){}l&&(f=mc(l,h,a,e,f,g),-1<f&&(k=l.splice(f,1)[0].Ma,l.length||(b[ac]=void 0)));d.call(this,a,k||b,c);k&&ic[a]&&this.__handlers&&this.__handlers[a]&&(a=this.__handlers[a][e?"capture":"bubble"],k=a.indexOf(k),-1<k&&a.splice(k,1))}}
function qc(){for(var a in ic)window.addEventListener(a,function(a){a.__target||(oc(a),lc(a))},!0)}function oc(a){a.__target=a.target;a.W=a.relatedTarget;if(u.u){var b=Object.getPrototypeOf(a);if(!b.hasOwnProperty("__patchProto")){var c=Object.create(b);c.Oa=b;qa(c,gc);b.__patchProto=c}a.__proto__=b.__patchProto}else qa(a,gc)}var rc=hc(window.Event),sc=hc(window.CustomEvent),tc=hc(window.MouseEvent);
function uc(){window.Event=rc;window.CustomEvent=sc;window.MouseEvent=tc;qc();if(!bc&&Object.getOwnPropertyDescriptor(Event.prototype,"isTrusted")){var a=function(){var a=new MouseEvent("click",{bubbles:!0,cancelable:!0,composed:!0});this.dispatchEvent(a)};Element.prototype.click?Element.prototype.click=a:HTMLElement.prototype.click&&(HTMLElement.prototype.click=a)}};function vc(a,b){return{index:a,H:[],O:b}}
function wc(a,b,c,d){var e=0,f=0,g=0,h=0,k=Math.min(b-e,d-f);if(0==e&&0==f)a:{for(g=0;g<k;g++)if(a[g]!==c[g])break a;g=k}if(b==a.length&&d==c.length){h=a.length;for(var l=c.length,m=0;m<k-g&&xc(a[--h],c[--l]);)m++;h=m}e+=g;f+=g;b-=h;d-=h;if(0==b-e&&0==d-f)return[];if(e==b){for(b=vc(e,0);f<d;)b.H.push(c[f++]);return[b]}if(f==d)return[vc(e,b-e)];k=e;g=f;d=d-g+1;h=b-k+1;b=Array(d);for(l=0;l<d;l++)b[l]=Array(h),b[l][0]=l;for(l=0;l<h;l++)b[0][l]=l;for(l=1;l<d;l++)for(m=1;m<h;m++)if(a[k+m-1]===c[g+l-1])b[l][m]=
b[l-1][m-1];else{var p=b[l-1][m]+1,O=b[l][m-1]+1;b[l][m]=p<O?p:O}k=b.length-1;g=b[0].length-1;d=b[k][g];for(a=[];0<k||0<g;)0==k?(a.push(2),g--):0==g?(a.push(3),k--):(h=b[k-1][g-1],l=b[k-1][g],m=b[k][g-1],p=l<m?l<h?l:h:m<h?m:h,p==h?(h==d?a.push(0):(a.push(1),d=h),k--,g--):p==l?(a.push(3),k--,d=l):(a.push(2),g--,d=m));a.reverse();b=void 0;k=[];for(g=0;g<a.length;g++)switch(a[g]){case 0:b&&(k.push(b),b=void 0);e++;f++;break;case 1:b||(b=vc(e,0));b.O++;e++;b.H.push(c[f]);f++;break;case 2:b||(b=vc(e,0));
b.O++;e++;break;case 3:b||(b=vc(e,0)),b.H.push(c[f]),f++}b&&k.push(b);return k}function xc(a,b){return a===b};var Qb=E.parentNode,yc=E.childNodes,zc={},I=u.deferConnectionCallbacks&&"loading"===document.readyState,Ac;function Bc(a){var b=[];do b.unshift(a);while(a=a.parentNode);return b}
function Cb(a,b,c){if(a!==zc)throw new TypeError("Illegal constructor");this.wa="ShadyRoot";this.host=b;this.c=c&&c.mode;Hb(b);a=r(b);a.root=this;a.ma="closed"!==this.c?this:null;a=r(this);a.firstChild=a.lastChild=a.parentNode=a.nextSibling=a.previousSibling=null;a.childNodes=[];this.b=this.N=!1;this.a=this.g=this.f=null;H(this)}function H(a){a.N||(a.N=!0,Da(function(){return Cc(a)}))}
function Cc(a){for(var b;a;){a.N&&(b=a);a:{var c=a;a=c.host.getRootNode();if(w(a))for(var d=c.host.childNodes,e=0;e<d.length;e++)if(c=d[e],"slot"==c.localName)break a;a=void 0}}b&&b._renderRoot()}
Cb.prototype._renderRoot=function(){var a=I;I=!0;this.N=!1;if(this.f){Pb(this);for(var b=0,c;b<this.f.length;b++){c=this.f[b];var d=t(c),e=d.assignedNodes;d.assignedNodes=[];d.A=[];if(d.ba=e)for(d=0;d<e.length;d++){var f=t(e[d]);f.M=f.assignedSlot;f.assignedSlot===c&&(f.assignedSlot=null)}}for(c=this.host.firstChild;c;c=c.nextSibling)Dc(this,c);for(b=0;b<this.f.length;b++){c=this.f[b];e=t(c);if(!e.assignedNodes.length)for(d=c.firstChild;d;d=d.nextSibling)Dc(this,d,c);(d=(d=t(c.parentNode))&&d.root)&&
Rb(d)&&d._renderRoot();Ec(this,e.A,e.assignedNodes);if(d=e.ba){for(f=0;f<d.length;f++)t(d[f]).M=null;e.ba=null;d.length>e.assignedNodes.length&&(e.R=!0)}e.R&&(e.R=!1,Fc(this,c))}b=this.f;c=[];for(e=0;e<b.length;e++)d=b[e].parentNode,(f=t(d))&&f.root||!(0>c.indexOf(d))||c.push(d);for(b=0;b<c.length;b++){e=c[b];d=e===this?this.host:e;f=[];e=e.childNodes;for(var g=0;g<e.length;g++){var h=e[g];if("slot"==h.localName){h=t(h).A;for(var k=0;k<h.length;k++)f.push(h[k])}else f.push(h)}e=void 0;g=yc(d);h=wc(f,
f.length,g,g.length);for(var l=k=0;k<h.length&&(e=h[k]);k++){for(var m=0,p;m<e.H.length&&(p=e.H[m]);m++)Qb(p)===d&&x.removeChild.call(d,p),g.splice(e.index+l,1);l-=e.O}for(l=0;l<h.length&&(e=h[l]);l++)for(k=g[e.index],m=e.index;m<e.index+e.O;m++)p=f[m],x.insertBefore.call(d,p,k),g.splice(m,0,p)}}if(!this.b)for(p=this.host.childNodes,c=0,b=p.length;c<b;c++)e=p[c],d=t(e),Qb(e)!==this.host||"slot"!==e.localName&&d.assignedSlot||x.removeChild.call(this.host,e);this.b=!0;I=a;Ac&&Ac()};
function Dc(a,b,c){var d=r(b),e=d.M;d.M=null;c||(c=(a=a.g[b.slot||"__catchall"])&&a[0]);c?(r(c).assignedNodes.push(b),d.assignedSlot=c):d.assignedSlot=void 0;e!==d.assignedSlot&&d.assignedSlot&&(r(d.assignedSlot).R=!0)}function Ec(a,b,c){for(var d=0,e;d<c.length&&(e=c[d]);d++)if("slot"==e.localName){var f=t(e).assignedNodes;f&&f.length&&Ec(a,b,f)}else b.push(c[d])}function Fc(a,b){x.dispatchEvent.call(b,new Event("slotchange"));b=t(b);b.assignedSlot&&Fc(a,b.assignedSlot)}
function Pb(a){if(a.a&&a.a.length){for(var b=a.a,c,d=0;d<b.length;d++){var e=b[d];Hb(e);Hb(e.parentNode);var f=Tb(e);a.g[f]?(c=c||{},c[f]=!0,a.g[f].push(e)):a.g[f]=[e];a.f.push(e)}if(c)for(var g in c)a.g[g]=Ub(a.g[g]);a.a=[]}}function Tb(a){var b=a.name||a.getAttribute("name")||"__catchall";return a.ta=b}function Ub(a){return a.sort(function(a,c){a=Bc(a);for(var b=Bc(c),e=0;e<a.length;e++){c=a[e];var f=b[e];if(c!==f)return a=Array.from(c.parentNode.childNodes),a.indexOf(c)-a.indexOf(f)}})}
function Rb(a){Pb(a);return!(!a.f||!a.f.length)}
if(window.customElements&&u.ea){var Gc=new Map;Ac=function(){var a=Array.from(Gc);Gc.clear();a=ha(a);for(var b=a.next();!b.done;b=a.next()){b=ha(b.value);var c=b.next().value;b.next().value?c.ra():c.sa()}};I&&document.addEventListener("readystatechange",function(){I=!1;Ac()},{once:!0});var Hc=function(a,b,c){var d=0,e="__isConnected"+d++;if(b||c)a.prototype.connectedCallback=a.prototype.ra=function(){I?Gc.set(this,!0):this[e]||(this[e]=!0,b&&b.call(this))},a.prototype.disconnectedCallback=a.prototype.sa=
function(){I?this.isConnected||Gc.set(this,!1):this[e]&&(this[e]=!1,c&&c.call(this))};return a},define=window.customElements.define;Object.defineProperty(window.CustomElementRegistry.prototype,"define",{value:function(a,b){var c=b.prototype.connectedCallback,d=b.prototype.disconnectedCallback;define.call(window.customElements,a,Hc(b,c,d));b.prototype.connectedCallback=c;b.prototype.disconnectedCallback=d}})};function Ic(a){var b=a.getRootNode();w(b)&&Cc(b);return(a=t(a))&&a.assignedSlot||null}
var Jc={addEventListener:nc.bind(window),removeEventListener:pc.bind(window)},Kc={addEventListener:nc,removeEventListener:pc,appendChild:function(a){return Jb(this,a)},insertBefore:function(a,b){return Jb(this,a,b)},removeChild:function(a){return Kb(this,a)},replaceChild:function(a,b){Jb(this,a,b);Kb(this,b);return a},cloneNode:function(a){if("template"==this.localName)var b=x.cloneNode.call(this,a);else if(b=x.cloneNode.call(this,!1),a&&b.nodeType!==Node.ATTRIBUTE_NODE){a=this.childNodes;for(var c=
0,d;c<a.length;c++)d=a[c].cloneNode(!0),b.appendChild(d)}return b},getRootNode:function(){return Vb(this)},contains:function(a){return za(this,a)},dispatchEvent:function(a){Ea();return x.dispatchEvent.call(this,a)}};
Object.defineProperties(Kc,{isConnected:{get:function(){if(ub&&ub.call(this))return!0;if(this.nodeType==Node.DOCUMENT_FRAGMENT_NODE)return!1;var a=this.ownerDocument;if(ya){if(x.contains.call(a,this))return!0}else if(a.documentElement&&x.contains.call(a.documentElement,this))return!0;for(a=this;a&&!(a instanceof Document);)a=a.parentNode||(w(a)?a.host:void 0);return!!(a&&a instanceof Document)},configurable:!0}});
var Lc={get assignedSlot(){return Ic(this)}},Mc={querySelector:function(a){return Wb(this,function(b){return pa.call(b,a)},function(a){return!!a})[0]||null},querySelectorAll:function(a,b){if(b){b=Array.prototype.slice.call(x.querySelectorAll.call(this,a));var c=this.getRootNode();return b.filter(function(a){return a.getRootNode()==c})}return Wb(this,function(b){return pa.call(b,a)})}},Nc={assignedNodes:function(a){if("slot"===this.localName){var b=this.getRootNode();w(b)&&Cc(b);return(b=t(this))?
(a&&a.flatten?b.A:b.assignedNodes)||[]:[]}}},Oc=ra({setAttribute:function(a,b){Zb(this,a,b)},removeAttribute:function(a){x.removeAttribute.call(this,a);Sb(this,a)},attachShadow:function(a){if(!this)throw"Must provide a host.";if(!a)throw"Not enough arguments.";return new Cb(zc,this,a)},get slot(){return this.getAttribute("slot")},set slot(a){Zb(this,"slot",a)},get assignedSlot(){return Ic(this)}},Mc,Nc);Object.defineProperties(Oc,zb);
var Pc=ra({importNode:function(a,b){return $b(a,b)},getElementById:function(a){return Wb(this,function(b){return b.id==a},function(a){return!!a})[0]||null}},Mc);Object.defineProperties(Pc,{_activeElement:Ab.activeElement});
for(var Qc=HTMLElement.prototype.blur,Rc={blur:function(){var a=t(this);(a=(a=a&&a.root)&&a.activeElement)?a.blur():Qc.call(this)}},J={},Sc=ha(Object.getOwnPropertyNames(Document.prototype)),Tc=Sc.next();!Tc.done;J={m:J.m},Tc=Sc.next())J.m=Tc.value,"on"===J.m.substring(0,2)&&Object.defineProperty(Rc,J.m,{set:function(a){return function(b){var c=r(this),d=a.m.substring(2);c.K[a.m]&&this.removeEventListener(d,c.K[a.m]);this.addEventListener(d,b,{});c.K[a.m]=b}}(J),get:function(a){return function(){var b=
t(this);return b&&b.K[a.m]}}(J),configurable:!0});var Uc={addEventListener:function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.Y=this;this.host.addEventListener(a,b,c)},removeEventListener:function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.Y=this;this.host.removeEventListener(a,b,c)},getElementById:function(a){return Wb(this,function(b){return b.id==a},function(a){return!!a})[0]||null}};
function K(a,b){for(var c=Object.getOwnPropertyNames(b),d=0;d<c.length;d++){var e=c[d],f=Object.getOwnPropertyDescriptor(b,e);f.value?a[e]=f.value:Object.defineProperty(a,e,f)}};if(u.ea){var ShadyDOM={inUse:u.ea,patch:function(a){Eb(a);Db(a);return a},isShadyRoot:w,enqueue:Da,flush:Ea,settings:u,filterMutations:Ka,observeChildren:Ia,unobserveChildren:Ja,nativeMethods:x,nativeTree:E,deferConnectionCallbacks:u.deferConnectionCallbacks};window.ShadyDOM=ShadyDOM;uc();var Vc=window.customElements&&window.customElements.nativeHTMLElement||HTMLElement;K(Cb.prototype,Uc);K(window.Node.prototype,Kc);K(window.Window.prototype,Jc);K(window.Text.prototype,Lc);K(window.DocumentFragment.prototype,
Mc);K(window.Element.prototype,Oc);K(window.Document.prototype,Pc);window.HTMLSlotElement&&K(window.HTMLSlotElement.prototype,Nc);K(Vc.prototype,Rc);u.u&&(G(window.Node.prototype),G(window.Text.prototype),G(window.DocumentFragment.prototype),G(window.Element.prototype),G(Vc.prototype),G(window.Document.prototype),window.HTMLSlotElement&&G(window.HTMLSlotElement.prototype));Bb();window.ShadowRoot=Cb};var Wc=new Set("annotation-xml color-profile font-face font-face-src font-face-uri font-face-format font-face-name missing-glyph".split(" "));function Xc(a){var b=Wc.has(a);a=/^[a-z][.0-9_a-z]*-[\-.0-9_a-z]*$/.test(a);return!b&&a}function L(a){var b=a.isConnected;if(void 0!==b)return b;for(;a&&!(a.__CE_isImportDocument||a instanceof Document);)a=a.parentNode||(window.ShadowRoot&&a instanceof ShadowRoot?a.host:void 0);return!(!a||!(a.__CE_isImportDocument||a instanceof Document))}
function Yc(a,b){for(;b&&b!==a&&!b.nextSibling;)b=b.parentNode;return b&&b!==a?b.nextSibling:null}
function N(a,b,c){c=void 0===c?new Set:c;for(var d=a;d;){if(d.nodeType===Node.ELEMENT_NODE){var e=d;b(e);var f=e.localName;if("link"===f&&"import"===e.getAttribute("rel")){d=e.import;if(d instanceof Node&&!c.has(d))for(c.add(d),d=d.firstChild;d;d=d.nextSibling)N(d,b,c);d=Yc(a,e);continue}else if("template"===f){d=Yc(a,e);continue}if(e=e.__CE_shadowRoot)for(e=e.firstChild;e;e=e.nextSibling)N(e,b,c)}d=d.firstChild?d.firstChild:Yc(a,d)}}function P(a,b,c){a[b]=c};function Zc(){this.a=new Map;this.s=new Map;this.j=[];this.c=!1}function $c(a,b,c){a.a.set(b,c);a.s.set(c.constructor,c)}function ad(a,b){a.c=!0;a.j.push(b)}function bd(a,b){a.c&&N(b,function(b){return a.b(b)})}Zc.prototype.b=function(a){if(this.c&&!a.__CE_patched){a.__CE_patched=!0;for(var b=0;b<this.j.length;b++)this.j[b](a)}};function Q(a,b){var c=[];N(b,function(a){return c.push(a)});for(b=0;b<c.length;b++){var d=c[b];1===d.__CE_state?a.connectedCallback(d):cd(a,d)}}
function R(a,b){var c=[];N(b,function(a){return c.push(a)});for(b=0;b<c.length;b++){var d=c[b];1===d.__CE_state&&a.disconnectedCallback(d)}}
function S(a,b,c){c=void 0===c?{}:c;var d=c.Ja||new Set,e=c.U||function(b){return cd(a,b)},f=[];N(b,function(b){if("link"===b.localName&&"import"===b.getAttribute("rel")){var c=b.import;c instanceof Node&&(c.__CE_isImportDocument=!0,c.__CE_hasRegistry=!0);c&&"complete"===c.readyState?c.__CE_documentLoadHandled=!0:b.addEventListener("load",function(){var c=b.import;if(!c.__CE_documentLoadHandled){c.__CE_documentLoadHandled=!0;var f=new Set(d);f.delete(c);S(a,c,{Ja:f,U:e})}})}else f.push(b)},d);if(a.c)for(b=
0;b<f.length;b++)a.b(f[b]);for(b=0;b<f.length;b++)e(f[b])}
function cd(a,b){if(void 0===b.__CE_state){var c=b.ownerDocument;if(c.defaultView||c.__CE_isImportDocument&&c.__CE_hasRegistry)if(c=a.a.get(b.localName)){c.constructionStack.push(b);var d=c.constructor;try{try{if(new d!==b)throw Error("The custom element constructor did not produce the element being upgraded.");}finally{c.constructionStack.pop()}}catch(g){throw b.__CE_state=2,g;}b.__CE_state=1;b.__CE_definition=c;if(c.attributeChangedCallback)for(c=c.observedAttributes,d=0;d<c.length;d++){var e=c[d],
f=b.getAttribute(e);null!==f&&a.attributeChangedCallback(b,e,null,f,null)}L(b)&&a.connectedCallback(b)}}}Zc.prototype.connectedCallback=function(a){var b=a.__CE_definition;b.connectedCallback&&b.connectedCallback.call(a)};Zc.prototype.disconnectedCallback=function(a){var b=a.__CE_definition;b.disconnectedCallback&&b.disconnectedCallback.call(a)};
Zc.prototype.attributeChangedCallback=function(a,b,c,d,e){var f=a.__CE_definition;f.attributeChangedCallback&&-1<f.observedAttributes.indexOf(b)&&f.attributeChangedCallback.call(a,b,c,d,e)};function dd(a){var b=document;this.h=a;this.a=b;this.C=void 0;S(this.h,this.a);"loading"===this.a.readyState&&(this.C=new MutationObserver(this.b.bind(this)),this.C.observe(this.a,{childList:!0,subtree:!0}))}function ed(a){a.C&&a.C.disconnect()}dd.prototype.b=function(a){var b=this.a.readyState;"interactive"!==b&&"complete"!==b||ed(this);for(b=0;b<a.length;b++)for(var c=a[b].addedNodes,d=0;d<c.length;d++)S(this.h,c[d])};function fd(){var a=this;this.b=this.a=void 0;this.c=new Promise(function(b){a.b=b;a.a&&b(a.a)})}function gd(a){if(a.a)throw Error("Already resolved.");a.a=void 0;a.b&&a.b(void 0)};function T(a){this.Z=!1;this.h=a;this.ca=new Map;this.$=function(a){return a()};this.L=!1;this.aa=[];this.va=new dd(a)}n=T.prototype;
n.define=function(a,b){var c=this;if(!(b instanceof Function))throw new TypeError("Custom element constructors must be functions.");if(!Xc(a))throw new SyntaxError("The element name '"+a+"' is not valid.");if(this.h.a.get(a))throw Error("A custom element with name '"+a+"' has already been defined.");if(this.Z)throw Error("A custom element is already being defined.");this.Z=!0;try{var d=function(a){var b=e[a];if(void 0!==b&&!(b instanceof Function))throw Error("The '"+a+"' callback must be a function.");
return b},e=b.prototype;if(!(e instanceof Object))throw new TypeError("The custom element constructor's prototype is not an object.");var f=d("connectedCallback");var g=d("disconnectedCallback");var h=d("adoptedCallback");var k=d("attributeChangedCallback");var l=b.observedAttributes||[]}catch(m){return}finally{this.Z=!1}b={localName:a,constructor:b,connectedCallback:f,disconnectedCallback:g,adoptedCallback:h,attributeChangedCallback:k,observedAttributes:l,constructionStack:[]};$c(this.h,a,b);this.aa.push(b);
this.L||(this.L=!0,this.$(function(){return hd(c)}))};n.U=function(a){S(this.h,a)};function hd(a){if(!1!==a.L){a.L=!1;for(var b=a.aa,c=[],d=new Map,e=0;e<b.length;e++)d.set(b[e].localName,[]);S(a.h,document,{U:function(b){if(void 0===b.__CE_state){var e=b.localName,f=d.get(e);f?f.push(b):a.h.a.get(e)&&c.push(b)}}});for(e=0;e<c.length;e++)cd(a.h,c[e]);for(;0<b.length;){var f=b.shift();e=f.localName;f=d.get(f.localName);for(var g=0;g<f.length;g++)cd(a.h,f[g]);(e=a.ca.get(e))&&gd(e)}}}
n.get=function(a){if(a=this.h.a.get(a))return a.constructor};n.whenDefined=function(a){if(!Xc(a))return Promise.reject(new SyntaxError("'"+a+"' is not a valid custom element name."));var b=this.ca.get(a);if(b)return b.c;b=new fd;this.ca.set(a,b);this.h.a.get(a)&&!this.aa.some(function(b){return b.localName===a})&&gd(b);return b.c};n.Ea=function(a){ed(this.va);var b=this.$;this.$=function(c){return a(function(){return b(c)})}};window.CustomElementRegistry=T;T.prototype.define=T.prototype.define;
T.prototype.upgrade=T.prototype.U;T.prototype.get=T.prototype.get;T.prototype.whenDefined=T.prototype.whenDefined;T.prototype.polyfillWrapFlushCallback=T.prototype.Ea;var id=window.Document.prototype.createElement,jd=window.Document.prototype.createElementNS,kd=window.Document.prototype.importNode,ld=window.Document.prototype.prepend,md=window.Document.prototype.append,nd=window.DocumentFragment.prototype.prepend,od=window.DocumentFragment.prototype.append,pd=window.Node.prototype.cloneNode,qd=window.Node.prototype.appendChild,rd=window.Node.prototype.insertBefore,sd=window.Node.prototype.removeChild,td=window.Node.prototype.replaceChild,ud=Object.getOwnPropertyDescriptor(window.Node.prototype,
"textContent"),vd=window.Element.prototype.attachShadow,wd=Object.getOwnPropertyDescriptor(window.Element.prototype,"innerHTML"),xd=window.Element.prototype.getAttribute,yd=window.Element.prototype.setAttribute,zd=window.Element.prototype.removeAttribute,Ad=window.Element.prototype.getAttributeNS,Bd=window.Element.prototype.setAttributeNS,Cd=window.Element.prototype.removeAttributeNS,Dd=window.Element.prototype.insertAdjacentElement,Ed=window.Element.prototype.insertAdjacentHTML,Fd=window.Element.prototype.prepend,
Gd=window.Element.prototype.append,Hd=window.Element.prototype.before,Id=window.Element.prototype.after,Jd=window.Element.prototype.replaceWith,Kd=window.Element.prototype.remove,Ld=window.HTMLElement,Md=Object.getOwnPropertyDescriptor(window.HTMLElement.prototype,"innerHTML"),Nd=window.HTMLElement.prototype.insertAdjacentElement,Od=window.HTMLElement.prototype.insertAdjacentHTML;var Pd=new function(){};function Qd(){var a=Rd;window.HTMLElement=function(){function b(){var b=this.constructor,d=a.s.get(b);if(!d)throw Error("The custom element being constructed was not registered with `customElements`.");var e=d.constructionStack;if(0===e.length)return e=id.call(document,d.localName),Object.setPrototypeOf(e,b.prototype),e.__CE_state=1,e.__CE_definition=d,a.b(e),e;d=e.length-1;var f=e[d];if(f===Pd)throw Error("The HTMLElement constructor was either called reentrantly for this constructor or called multiple times.");
e[d]=Pd;Object.setPrototypeOf(f,b.prototype);a.b(f);return f}b.prototype=Ld.prototype;Object.defineProperty(b.prototype,"constructor",{writable:!0,configurable:!0,enumerable:!1,value:b});return b}()};function Sd(a,b,c){function d(b){return function(c){for(var e=[],d=0;d<arguments.length;++d)e[d-0]=arguments[d];d=[];for(var f=[],l=0;l<e.length;l++){var m=e[l];m instanceof Element&&L(m)&&f.push(m);if(m instanceof DocumentFragment)for(m=m.firstChild;m;m=m.nextSibling)d.push(m);else d.push(m)}b.apply(this,e);for(e=0;e<f.length;e++)R(a,f[e]);if(L(this))for(e=0;e<d.length;e++)f=d[e],f instanceof Element&&Q(a,f)}}void 0!==c.T&&(b.prepend=d(c.T));void 0!==c.append&&(b.append=d(c.append))};function Td(){var a=Rd;P(Document.prototype,"createElement",function(b){if(this.__CE_hasRegistry){var c=a.a.get(b);if(c)return new c.constructor}b=id.call(this,b);a.b(b);return b});P(Document.prototype,"importNode",function(b,c){b=kd.call(this,b,c);this.__CE_hasRegistry?S(a,b):bd(a,b);return b});P(Document.prototype,"createElementNS",function(b,c){if(this.__CE_hasRegistry&&(null===b||"http://www.w3.org/1999/xhtml"===b)){var d=a.a.get(c);if(d)return new d.constructor}b=jd.call(this,b,c);a.b(b);return b});
Sd(a,Document.prototype,{T:ld,append:md})};function Ud(){var a=Rd;function b(b,d){Object.defineProperty(b,"textContent",{enumerable:d.enumerable,configurable:!0,get:d.get,set:function(b){if(this.nodeType===Node.TEXT_NODE)d.set.call(this,b);else{var c=void 0;if(this.firstChild){var e=this.childNodes,h=e.length;if(0<h&&L(this)){c=Array(h);for(var k=0;k<h;k++)c[k]=e[k]}}d.set.call(this,b);if(c)for(b=0;b<c.length;b++)R(a,c[b])}}})}P(Node.prototype,"insertBefore",function(b,d){if(b instanceof DocumentFragment){var c=Array.prototype.slice.apply(b.childNodes);
b=rd.call(this,b,d);if(L(this))for(d=0;d<c.length;d++)Q(a,c[d]);return b}c=L(b);d=rd.call(this,b,d);c&&R(a,b);L(this)&&Q(a,b);return d});P(Node.prototype,"appendChild",function(b){if(b instanceof DocumentFragment){var c=Array.prototype.slice.apply(b.childNodes);b=qd.call(this,b);if(L(this))for(var e=0;e<c.length;e++)Q(a,c[e]);return b}c=L(b);e=qd.call(this,b);c&&R(a,b);L(this)&&Q(a,b);return e});P(Node.prototype,"cloneNode",function(b){b=pd.call(this,b);this.ownerDocument.__CE_hasRegistry?S(a,b):
bd(a,b);return b});P(Node.prototype,"removeChild",function(b){var c=L(b),e=sd.call(this,b);c&&R(a,b);return e});P(Node.prototype,"replaceChild",function(b,d){if(b instanceof DocumentFragment){var c=Array.prototype.slice.apply(b.childNodes);b=td.call(this,b,d);if(L(this))for(R(a,d),d=0;d<c.length;d++)Q(a,c[d]);return b}c=L(b);var f=td.call(this,b,d),g=L(this);g&&R(a,d);c&&R(a,b);g&&Q(a,b);return f});ud&&ud.get?b(Node.prototype,ud):ad(a,function(a){b(a,{enumerable:!0,configurable:!0,get:function(){for(var a=
[],b=0;b<this.childNodes.length;b++)a.push(this.childNodes[b].textContent);return a.join("")},set:function(a){for(;this.firstChild;)sd.call(this,this.firstChild);qd.call(this,document.createTextNode(a))}})})};function Vd(a){var b=Element.prototype;function c(b){return function(c){for(var e=[],d=0;d<arguments.length;++d)e[d-0]=arguments[d];d=[];for(var h=[],k=0;k<e.length;k++){var l=e[k];l instanceof Element&&L(l)&&h.push(l);if(l instanceof DocumentFragment)for(l=l.firstChild;l;l=l.nextSibling)d.push(l);else d.push(l)}b.apply(this,e);for(e=0;e<h.length;e++)R(a,h[e]);if(L(this))for(e=0;e<d.length;e++)h=d[e],h instanceof Element&&Q(a,h)}}void 0!==Hd&&(b.before=c(Hd));void 0!==Hd&&(b.after=c(Id));void 0!==
Jd&&P(b,"replaceWith",function(b){for(var c=[],d=0;d<arguments.length;++d)c[d-0]=arguments[d];d=[];for(var g=[],h=0;h<c.length;h++){var k=c[h];k instanceof Element&&L(k)&&g.push(k);if(k instanceof DocumentFragment)for(k=k.firstChild;k;k=k.nextSibling)d.push(k);else d.push(k)}h=L(this);Jd.apply(this,c);for(c=0;c<g.length;c++)R(a,g[c]);if(h)for(R(a,this),c=0;c<d.length;c++)g=d[c],g instanceof Element&&Q(a,g)});void 0!==Kd&&P(b,"remove",function(){var b=L(this);Kd.call(this);b&&R(a,this)})};function Wd(){var a=Rd;function b(b,c){Object.defineProperty(b,"innerHTML",{enumerable:c.enumerable,configurable:!0,get:c.get,set:function(b){var d=this,e=void 0;L(this)&&(e=[],N(this,function(a){a!==d&&e.push(a)}));c.set.call(this,b);if(e)for(var f=0;f<e.length;f++){var g=e[f];1===g.__CE_state&&a.disconnectedCallback(g)}this.ownerDocument.__CE_hasRegistry?S(a,this):bd(a,this);return b}})}function c(b,c){P(b,"insertAdjacentElement",function(b,d){var e=L(d);b=c.call(this,b,d);e&&R(a,d);L(b)&&Q(a,d);
return b})}function d(b,c){function d(b,c){for(var d=[];b!==c;b=b.nextSibling)d.push(b);for(c=0;c<d.length;c++)S(a,d[c])}P(b,"insertAdjacentHTML",function(a,b){a=a.toLowerCase();if("beforebegin"===a){var e=this.previousSibling;c.call(this,a,b);d(e||this.parentNode.firstChild,this)}else if("afterbegin"===a)e=this.firstChild,c.call(this,a,b),d(this.firstChild,e);else if("beforeend"===a)e=this.lastChild,c.call(this,a,b),d(e||this.firstChild,null);else if("afterend"===a)e=this.nextSibling,c.call(this,
a,b),d(this.nextSibling,e);else throw new SyntaxError("The value provided ("+String(a)+") is not one of 'beforebegin', 'afterbegin', 'beforeend', or 'afterend'.");})}vd&&P(Element.prototype,"attachShadow",function(a){return this.__CE_shadowRoot=a=vd.call(this,a)});wd&&wd.get?b(Element.prototype,wd):Md&&Md.get?b(HTMLElement.prototype,Md):ad(a,function(a){b(a,{enumerable:!0,configurable:!0,get:function(){return pd.call(this,!0).innerHTML},set:function(a){var b="template"===this.localName,c=b?this.content:
this,d=jd.call(document,this.namespaceURI,this.localName);for(d.innerHTML=a;0<c.childNodes.length;)sd.call(c,c.childNodes[0]);for(a=b?d.content:d;0<a.childNodes.length;)qd.call(c,a.childNodes[0])}})});P(Element.prototype,"setAttribute",function(b,c){if(1!==this.__CE_state)return yd.call(this,b,c);var d=xd.call(this,b);yd.call(this,b,c);c=xd.call(this,b);a.attributeChangedCallback(this,b,d,c,null)});P(Element.prototype,"setAttributeNS",function(b,c,d){if(1!==this.__CE_state)return Bd.call(this,b,c,
d);var e=Ad.call(this,b,c);Bd.call(this,b,c,d);d=Ad.call(this,b,c);a.attributeChangedCallback(this,c,e,d,b)});P(Element.prototype,"removeAttribute",function(b){if(1!==this.__CE_state)return zd.call(this,b);var c=xd.call(this,b);zd.call(this,b);null!==c&&a.attributeChangedCallback(this,b,c,null,null)});P(Element.prototype,"removeAttributeNS",function(b,c){if(1!==this.__CE_state)return Cd.call(this,b,c);var d=Ad.call(this,b,c);Cd.call(this,b,c);var e=Ad.call(this,b,c);d!==e&&a.attributeChangedCallback(this,
c,d,e,b)});Nd?c(HTMLElement.prototype,Nd):Dd?c(Element.prototype,Dd):console.warn("Custom Elements: `Element#insertAdjacentElement` was not patched.");Od?d(HTMLElement.prototype,Od):Ed?d(Element.prototype,Ed):console.warn("Custom Elements: `Element#insertAdjacentHTML` was not patched.");Sd(a,Element.prototype,{T:Fd,append:Gd});Vd(a)};/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
var Xd=window.customElements;if(!Xd||Xd.forcePolyfill||"function"!=typeof Xd.define||"function"!=typeof Xd.get){var Rd=new Zc;Qd();Td();Sd(Rd,DocumentFragment.prototype,{T:nd,append:od});Ud();Wd();document.__CE_hasRegistry=!0;var customElements=new T(Rd);Object.defineProperty(window,"customElements",{configurable:!0,enumerable:!0,value:customElements})};/*

Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
function Yd(){this.end=this.start=0;this.rules=this.parent=this.previous=null;this.cssText=this.parsedCssText="";this.atRule=!1;this.type=0;this.parsedSelector=this.selector=this.keyframesName=""}
function Zd(a){a=a.replace($d,"").replace(ae,"");var b=be,c=a,d=new Yd;d.start=0;d.end=c.length;for(var e=d,f=0,g=c.length;f<g;f++)if("{"===c[f]){e.rules||(e.rules=[]);var h=e,k=h.rules[h.rules.length-1]||null;e=new Yd;e.start=f+1;e.parent=h;e.previous=k;h.rules.push(e)}else"}"===c[f]&&(e.end=f+1,e=e.parent||d);return b(d,a)}
function be(a,b){var c=b.substring(a.start,a.end-1);a.parsedCssText=a.cssText=c.trim();a.parent&&(c=b.substring(a.previous?a.previous.end:a.parent.start,a.start-1),c=ce(c),c=c.replace(de," "),c=c.substring(c.lastIndexOf(";")+1),c=a.parsedSelector=a.selector=c.trim(),a.atRule=0===c.indexOf("@"),a.atRule?0===c.indexOf("@media")?a.type=ee:c.match(fe)&&(a.type=ge,a.keyframesName=a.selector.split(de).pop()):a.type=0===c.indexOf("--")?he:ie);if(c=a.rules)for(var d=0,e=c.length,f;d<e&&(f=c[d]);d++)be(f,
b);return a}function ce(a){return a.replace(/\\([0-9a-f]{1,6})\s/gi,function(a,c){a=c;for(c=6-a.length;c--;)a="0"+a;return"\\"+a})}
function je(a,b,c){c=void 0===c?"":c;var d="";if(a.cssText||a.rules){var e=a.rules,f;if(f=e)f=e[0],f=!(f&&f.selector&&0===f.selector.indexOf("--"));if(f){f=0;for(var g=e.length,h;f<g&&(h=e[f]);f++)d=je(h,b,d)}else b?b=a.cssText:(b=a.cssText,b=b.replace(ke,"").replace(le,""),b=b.replace(me,"").replace(ne,"")),(d=b.trim())&&(d="  "+d+"\n")}d&&(a.selector&&(c+=a.selector+" {\n"),c+=d,a.selector&&(c+="}\n\n"));return c}
var ie=1,ge=7,ee=4,he=1E3,$d=/\/\*[^*]*\*+([^/*][^*]*\*+)*\//gim,ae=/@import[^;]*;/gim,ke=/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?(?:[;\n]|$)/gim,le=/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?{[^}]*?}(?:[;\n]|$)?/gim,me=/@apply\s*\(?[^);]*\)?\s*(?:[;\n]|$)?/gim,ne=/[^;:]*?:[^;]*?var\([^;]*\)(?:[;\n]|$)?/gim,fe=/^@[^\s]*keyframes/,de=/\s+/g;var U=!(window.ShadyDOM&&window.ShadyDOM.inUse),oe;function pe(a){oe=a&&a.shimcssproperties?!1:U||!(navigator.userAgent.match(/AppleWebKit\/601|Edge\/15/)||!window.CSS||!CSS.supports||!CSS.supports("box-shadow","0 0 0 var(--foo)"))}window.ShadyCSS&&void 0!==window.ShadyCSS.nativeCss?oe=window.ShadyCSS.nativeCss:window.ShadyCSS?(pe(window.ShadyCSS),window.ShadyCSS=void 0):pe(window.WebComponents&&window.WebComponents.flags);var V=oe;var qe=/(?:^|[;\s{]\s*)(--[\w-]*?)\s*:\s*(?:((?:'(?:\\'|.)*?'|"(?:\\"|.)*?"|\([^)]*?\)|[^};{])+)|\{([^}]*)\}(?:(?=[;\s}])|$))/gi,re=/(?:^|\W+)@apply\s*\(?([^);\n]*)\)?/gi,se=/(--[\w-]+)\s*([:,;)]|$)/gi,te=/(animation\s*:)|(animation-name\s*:)/,ue=/@media\s(.*)/,ve=/\{[^}]*\}/g;var we=new Set;function xe(a,b){if(!a)return"";"string"===typeof a&&(a=Zd(a));b&&ye(a,b);return je(a,V)}function ze(a){!a.__cssRules&&a.textContent&&(a.__cssRules=Zd(a.textContent));return a.__cssRules||null}function Ae(a){return!!a.parent&&a.parent.type===ge}function ye(a,b,c,d){if(a){var e=!1,f=a.type;if(d&&f===ee){var g=a.selector.match(ue);g&&(window.matchMedia(g[1]).matches||(e=!0))}f===ie?b(a):c&&f===ge?c(a):f===he&&(e=!0);if((a=a.rules)&&!e){e=0;f=a.length;for(var h;e<f&&(h=a[e]);e++)ye(h,b,c,d)}}}
function Be(a,b,c,d){var e=document.createElement("style");b&&e.setAttribute("scope",b);e.textContent=a;Ce(e,c,d);return e}var De=null;function Ce(a,b,c){b=b||document.head;b.insertBefore(a,c&&c.nextSibling||b.firstChild);De?a.compareDocumentPosition(De)===Node.DOCUMENT_POSITION_PRECEDING&&(De=a):De=a}
function Ee(a,b){var c=a.indexOf("var(");if(-1===c)return b(a,"","","");a:{var d=0;var e=c+3;for(var f=a.length;e<f;e++)if("("===a[e])d++;else if(")"===a[e]&&0===--d)break a;e=-1}d=a.substring(c+4,e);c=a.substring(0,c);a=Ee(a.substring(e+1),b);e=d.indexOf(",");return-1===e?b(c,d.trim(),"",a):b(c,d.substring(0,e).trim(),d.substring(e+1).trim(),a)}function Fe(a,b){U?a.setAttribute("class",b):window.ShadyDOM.nativeMethods.setAttribute.call(a,"class",b)}
function Ge(a){var b=a.localName,c="";b?-1<b.indexOf("-")||(c=b,b=a.getAttribute&&a.getAttribute("is")||""):(b=a.is,c=a.extends);return{is:b,I:c}};function He(){}function Ie(a,b,c){var d=W;a.__styleScoped?a.__styleScoped=null:Je(d,a,b||"",c)}function Je(a,b,c,d){b.nodeType===Node.ELEMENT_NODE&&Ke(b,c,d);if(b="template"===b.localName?(b.content||b.Pa||b).childNodes:b.children||b.childNodes)for(var e=0;e<b.length;e++)Je(a,b[e],c,d)}
function Ke(a,b,c){if(b)if(a.classList)c?(a.classList.remove("style-scope"),a.classList.remove(b)):(a.classList.add("style-scope"),a.classList.add(b));else if(a.getAttribute){var d=a.getAttribute(Le);c?d&&(b=d.replace("style-scope","").replace(b,""),Fe(a,b)):Fe(a,(d?d+" ":"")+"style-scope "+b)}}function Me(a,b,c){var d=W,e=a.__cssBuild;U||"shady"===e?b=xe(b,c):(a=Ge(a),b=Ne(d,b,a.is,a.I,c)+"\n\n");return b.trim()}
function Ne(a,b,c,d,e){var f=Oe(c,d);c=c?Pe+c:"";return xe(b,function(b){b.c||(b.selector=b.l=Qe(a,b,a.b,c,f),b.c=!0);e&&e(b,c,f)})}function Oe(a,b){return b?"[is="+a+"]":a}function Qe(a,b,c,d,e){var f=b.selector.split(Re);if(!Ae(b)){b=0;for(var g=f.length,h;b<g&&(h=f[b]);b++)f[b]=c.call(a,h,d,e)}return f.join(Re)}function Se(a){return a.replace(Te,function(a,c,d){-1<d.indexOf("+")?d=d.replace(/\+/g,"___"):-1<d.indexOf("___")&&(d=d.replace(/___/g,"+"));return":"+c+"("+d+")"})}
He.prototype.b=function(a,b,c){var d=!1;a=a.trim();var e=Te.test(a);e&&(a=a.replace(Te,function(a,b,c){return":"+b+"("+c.replace(/\s/g,"")+")"}),a=Se(a));a=a.replace(Ue,Ve+" $1");a=a.replace(We,function(a,e,h){d||(a=Xe(h,e,b,c),d=d||a.stop,e=a.za,h=a.value);return e+h});e&&(a=Se(a));return a};
function Xe(a,b,c,d){var e=a.indexOf(Ye);0<=a.indexOf(Ve)?a=Ze(a,d):0!==e&&(a=c?$e(a,c):a);c=!1;0<=e&&(b="",c=!0);if(c){var f=!0;c&&(a=a.replace(af,function(a,b){return" > "+b}))}a=a.replace(bf,function(a,b,c){return'[dir="'+c+'"] '+b+", "+b+'[dir="'+c+'"]'});return{value:a,za:b,stop:f}}function $e(a,b){a=a.split(cf);a[0]+=b;return a.join(cf)}
function Ze(a,b){var c=a.match(df);return(c=c&&c[2].trim()||"")?c[0].match(ef)?a.replace(df,function(a,c,f){return b+f}):c.split(ef)[0]===b?c:ff:a.replace(Ve,b)}function gf(a){a.selector===hf&&(a.selector="html")}He.prototype.c=function(a){return a.match(Ye)?this.b(a,jf):$e(a.trim(),jf)};q.Object.defineProperties(He.prototype,{a:{configurable:!0,enumerable:!0,get:function(){return"style-scope"}}});
var Te=/:(nth[-\w]+)\(([^)]+)\)/,jf=":not(.style-scope)",Re=",",We=/(^|[\s>+~]+)((?:\[.+?\]|[^\s>+~=[])+)/g,ef=/[[.:#*]/,Ve=":host",hf=":root",Ye="::slotted",Ue=new RegExp("^("+Ye+")"),df=/(:host)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,af=/(?:::slotted)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,bf=/(.*):dir\((?:(ltr|rtl))\)/,Pe=".",cf=":",Le="class",ff="should_not_match",W=new He;function kf(a,b,c,d){this.w=a||null;this.b=b||null;this.fa=c||[];this.F=null;this.I=d||"";this.a=this.o=this.B=null}function X(a){return a?a.__styleInfo:null}function lf(a,b){return a.__styleInfo=b}kf.prototype.c=function(){return this.w};kf.prototype._getStyleRules=kf.prototype.c;function mf(a){var b=this.matches||this.matchesSelector||this.mozMatchesSelector||this.msMatchesSelector||this.oMatchesSelector||this.webkitMatchesSelector;return b&&b.call(this,a)}var nf=navigator.userAgent.match("Trident");function of(){}function pf(a){var b={},c=[],d=0;ye(a,function(a){qf(a);a.index=d++;a=a.i.cssText;for(var c;c=se.exec(a);){var e=c[1];":"!==c[2]&&(b[e]=!0)}},function(a){c.push(a)});a.b=c;a=[];for(var e in b)a.push(e);return a}
function qf(a){if(!a.i){var b={},c={};rf(a,c)&&(b.v=c,a.rules=null);b.cssText=a.parsedCssText.replace(ve,"").replace(qe,"");a.i=b}}function rf(a,b){var c=a.i;if(c){if(c.v)return Object.assign(b,c.v),!0}else{c=a.parsedCssText;for(var d;a=qe.exec(c);){d=(a[2]||a[3]).trim();if("inherit"!==d||"unset"!==d)b[a[1].trim()]=d;d=!0}return d}}
function sf(a,b,c){b&&(b=0<=b.indexOf(";")?tf(a,b,c):Ee(b,function(b,e,f,g){if(!e)return b+g;(e=sf(a,c[e],c))&&"initial"!==e?"apply-shim-inherit"===e&&(e="inherit"):e=sf(a,c[f]||f,c)||f;return b+(e||"")+g}));return b&&b.trim()||""}
function tf(a,b,c){b=b.split(";");for(var d=0,e,f;d<b.length;d++)if(e=b[d]){re.lastIndex=0;if(f=re.exec(e))e=sf(a,c[f[1]],c);else if(f=e.indexOf(":"),-1!==f){var g=e.substring(f);g=g.trim();g=sf(a,g,c)||g;e=e.substring(0,f)+g}b[d]=e&&e.lastIndexOf(";")===e.length-1?e.slice(0,-1):e||""}return b.join(";")}
function uf(a,b){var c={},d=[];ye(a,function(a){a.i||qf(a);var e=a.l||a.parsedSelector;b&&a.i.v&&e&&mf.call(b,e)&&(rf(a,c),a=a.index,e=parseInt(a/32,10),d[e]=(d[e]||0)|1<<a%32)},null,!0);return{v:c,key:d}}
function vf(a,b,c,d){b.i||qf(b);if(b.i.v){var e=Ge(a);a=e.is;e=e.I;e=a?Oe(a,e):"html";var f=b.parsedSelector,g=":host > *"===f||"html"===f,h=0===f.indexOf(":host")&&!g;"shady"===c&&(g=f===e+" > *."+e||-1!==f.indexOf("html"),h=!g&&0===f.indexOf(e));"shadow"===c&&(g=":host > *"===f||"html"===f,h=h&&!g);if(g||h)c=e,h&&(b.l||(b.l=Qe(W,b,W.b,a?Pe+a:"",e)),c=b.l||e),d({Ga:c,Da:h,Za:g})}}
function wf(a,b){var c={},d={},e=b&&b.__cssBuild;ye(b,function(b){vf(a,b,e,function(e){mf.call(a.Qa||a,e.Ga)&&(e.Da?rf(b,c):rf(b,d))})},null,!0);return{Fa:d,Ca:c}}
function xf(a,b,c,d){var e=Ge(b),f=Oe(e.is,e.I),g=new RegExp("(?:^|[^.#[:])"+(b.extends?"\\"+f.slice(0,-1)+"\\]":f)+"($|[.:[\\s>+~])");e=X(b).w;var h=yf(e,d);return Me(b,e,function(b){var e="";b.i||qf(b);b.i.cssText&&(e=tf(a,b.i.cssText,c));b.cssText=e;if(!U&&!Ae(b)&&b.cssText){var k=e=b.cssText;null==b.ka&&(b.ka=te.test(e));if(b.ka)if(null==b.S){b.S=[];for(var p in h)k=h[p],k=k(e),e!==k&&(e=k,b.S.push(p))}else{for(p=0;p<b.S.length;++p)k=h[b.S[p]],e=k(e);k=e}b.cssText=k;b.l=b.l||b.selector;e="."+
d;p=b.l.split(",");k=0;for(var O=p.length,M;k<O&&(M=p[k]);k++)p[k]=M.match(g)?M.replace(f,e):e+" "+M;b.selector=p.join(",")}})}function yf(a,b){a=a.b;var c={};if(!U&&a)for(var d=0,e=a[d];d<a.length;e=a[++d]){var f=e,g=b;f.j=new RegExp("\\b"+f.keyframesName+"(?!\\B|-)","g");f.a=f.keyframesName+"-"+g;f.l=f.l||f.selector;f.selector=f.l.replace(f.keyframesName,f.a);c[e.keyframesName]=zf(e)}return c}function zf(a){return function(b){return b.replace(a.j,a.a)}}
function Af(a,b){var c=Bf,d=ze(a);a.textContent=xe(d,function(a){var d=a.cssText=a.parsedCssText;a.i&&a.i.cssText&&(d=d.replace(ke,"").replace(le,""),a.cssText=tf(c,d,b))})}q.Object.defineProperties(of.prototype,{a:{configurable:!0,enumerable:!0,get:function(){return"x-scope"}}});var Bf=new of;var Cf={},Df=window.customElements;if(Df&&!U){var Ef=Df.define;Df.define=function(a,b,c){var d=document.createComment(" Shady DOM styles for "+a+" "),e=document.head;e.insertBefore(d,(De?De.nextSibling:null)||e.firstChild);De=d;Cf[a]=d;Ef.call(Df,a,b,c)}};function Ff(){this.cache={}}Ff.prototype.store=function(a,b,c,d){var e=this.cache[a]||[];e.push({v:b,styleElement:c,o:d});100<e.length&&e.shift();this.cache[a]=e};Ff.prototype.fetch=function(a,b,c){if(a=this.cache[a])for(var d=a.length-1;0<=d;d--){var e=a[d],f;a:{for(f=0;f<c.length;f++){var g=c[f];if(e.v[g]!==b[g]){f=!1;break a}}f=!0}if(f)return e}};function Gf(){}
function Hf(a){for(var b=0;b<a.length;b++){var c=a[b];if(c.target!==document.documentElement&&c.target!==document.head)for(var d=0;d<c.addedNodes.length;d++){var e=c.addedNodes[d];if(e.nodeType===Node.ELEMENT_NODE){var f=e.getRootNode();var g=e;var h=[];g.classList?h=Array.from(g.classList):g instanceof window.SVGElement&&g.hasAttribute("class")&&(h=g.getAttribute("class").split(/\s+/));g=h;h=g.indexOf(W.a);if((g=-1<h?g[h+1]:"")&&f===e.ownerDocument)Ie(e,g,!0);else if(f.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&
(f=f.host))if(f=Ge(f).is,g===f)for(e=window.ShadyDOM.nativeMethods.querySelectorAll.call(e,":not(."+W.a+")"),f=0;f<e.length;f++)Ke(e[f],g);else g&&Ie(e,g,!0),Ie(e,f)}}}}
if(!U){var If=new MutationObserver(Hf),Jf=function(a){If.observe(a,{childList:!0,subtree:!0})};if(window.customElements&&!window.customElements.polyfillWrapFlushCallback)Jf(document);else{var Kf=function(){Jf(document.body)};window.HTMLImports?window.HTMLImports.whenReady(Kf):requestAnimationFrame(function(){if("loading"===document.readyState){var a=function(){Kf();document.removeEventListener("readystatechange",a)};document.addEventListener("readystatechange",a)}else Kf()})}Gf=function(){Hf(If.takeRecords())}}
var Lf=Gf;var Mf={};var Nf=Promise.resolve();function Of(a){if(a=Mf[a])a._applyShimCurrentVersion=a._applyShimCurrentVersion||0,a._applyShimValidatingVersion=a._applyShimValidatingVersion||0,a._applyShimNextVersion=(a._applyShimNextVersion||0)+1}function Pf(a){return a._applyShimCurrentVersion===a._applyShimNextVersion}function Qf(a){a._applyShimValidatingVersion=a._applyShimNextVersion;a.b||(a.b=!0,Nf.then(function(){a._applyShimCurrentVersion=a._applyShimNextVersion;a.b=!1}))};var Rf=new Ff;function Y(){this.da={};this.c=document.documentElement;var a=new Yd;a.rules=[];this.j=lf(this.c,new kf(a));this.s=!1;this.b=this.a=null}n=Y.prototype;n.ga=function(){Lf()};n.Aa=function(a){return ze(a)};n.Ia=function(a){return xe(a)};n.prepareTemplate=function(a,b,c){this.prepareTemplateDom(a,b);this.prepareTemplateStyles(a,b,c)};
n.prepareTemplateStyles=function(a,b,c){if(!a.s){a.s=!0;a.name=b;a.extends=c;Mf[b]=a;var d=(d=a.content.querySelector("style"))?d.getAttribute("css-build")||"":"";var e=[];for(var f=a.content.querySelectorAll("style"),g=0;g<f.length;g++){var h=f[g];if(h.hasAttribute("shady-unscoped")){if(!U){var k=h.textContent;we.has(k)||(we.add(k),k=h.cloneNode(!0),document.head.appendChild(k));h.parentNode.removeChild(h)}}else e.push(h.textContent),h.parentNode.removeChild(h)}e=e.join("").trim();c={is:b,extends:c,
Na:d};Sf(this);f=re.test(e)||qe.test(e);re.lastIndex=0;qe.lastIndex=0;e=Zd(e);f&&V&&this.a&&this.a.transformRules(e,b);a._styleAst=e;a.da=d;d=[];V||(d=pf(a._styleAst));if(!d.length||V)e=U?a.content:null,b=Cf[b],f=Me(c,a._styleAst),b=f.length?Be(f,c.is,e,b):void 0,a.a=b;a.j=d}};n.prepareTemplateDom=function(a,b){U||a.c||(a.c=!0,Ie(a.content,b))};
function Tf(a){!a.b&&window.ShadyCSS&&window.ShadyCSS.CustomStyleInterface&&(a.b=window.ShadyCSS.CustomStyleInterface,a.b.transformCallback=function(b){a.na(b)},a.b.validateCallback=function(){requestAnimationFrame(function(){(a.b.enqueued||a.s)&&a.flushCustomStyles()})})}function Sf(a){!a.a&&window.ShadyCSS&&window.ShadyCSS.ApplyShim&&(a.a=window.ShadyCSS.ApplyShim,a.a.invalidCallback=Of);Tf(a)}
n.flushCustomStyles=function(){Sf(this);if(this.b){var a=this.b.processStyles();if(this.b.enqueued){if(V)for(var b=0;b<a.length;b++){var c=this.b.getStyleForCustomStyle(a[b]);if(c&&V&&this.a){var d=ze(c);Sf(this);this.a.transformRules(d);c.textContent=xe(d)}}else for(Uf(this,this.c,this.j),b=0;b<a.length;b++)(c=this.b.getStyleForCustomStyle(a[b]))&&Af(c,this.j.B);this.b.enqueued=!1;this.s&&!V&&this.styleDocument()}}};
n.styleElement=function(a,b){var c=Ge(a).is,d=X(a);if(!d){var e=Ge(a);d=e.is;e=e.I;var f=Cf[d];d=Mf[d];if(d){var g=d._styleAst;var h=d.j}d=lf(a,new kf(g,f,h,e))}a!==this.c&&(this.s=!0);b&&(d.F=d.F||{},Object.assign(d.F,b));if(V){if(d.F){b=d.F;for(var k in b)null===k?a.style.removeProperty(k):a.style.setProperty(k,b[k])}if(((k=Mf[c])||a===this.c)&&k&&k.a&&!Pf(k)){if(Pf(k)||k._applyShimValidatingVersion!==k._applyShimNextVersion)Sf(this),this.a&&this.a.transformRules(k._styleAst,c),k.a.textContent=
Me(a,d.w),Qf(k);U&&(c=a.shadowRoot)&&(c.querySelector("style").textContent=Me(a,d.w));d.w=k._styleAst}}else if(this.ga(),Uf(this,a,d),d.fa&&d.fa.length){c=d;k=Ge(a).is;d=(b=Rf.fetch(k,c.B,c.fa))?b.styleElement:null;g=c.o;(h=b&&b.o)||(h=this.da[k]=(this.da[k]||0)+1,h=k+"-"+h);c.o=h;h=c.o;e=Bf;e=d?d.textContent||"":xf(e,a,c.B,h);f=X(a);var l=f.a;l&&!U&&l!==d&&(l._useCount--,0>=l._useCount&&l.parentNode&&l.parentNode.removeChild(l));U?f.a?(f.a.textContent=e,d=f.a):e&&(d=Be(e,h,a.shadowRoot,f.b)):d?d.parentNode||
(nf&&-1<e.indexOf("@media")&&(d.textContent=e),Ce(d,null,f.b)):e&&(d=Be(e,h,null,f.b));d&&(d._useCount=d._useCount||0,f.a!=d&&d._useCount++,f.a=d);h=d;U||(d=c.o,f=e=a.getAttribute("class")||"",g&&(f=e.replace(new RegExp("\\s*x-scope\\s*"+g+"\\s*","g")," ")),f+=(f?" ":"")+"x-scope "+d,e!==f&&Fe(a,f));b||Rf.store(k,c.B,h,c.o)}};function Vf(a,b){return(b=b.getRootNode().host)?X(b)?b:Vf(a,b):a.c}
function Uf(a,b,c){a=Vf(a,b);var d=X(a);a=Object.create(d.B||null);var e=wf(b,c.w);b=uf(d.w,b).v;Object.assign(a,e.Ca,b,e.Fa);b=c.F;for(var f in b)if((e=b[f])||0===e)a[f]=e;f=Bf;b=Object.getOwnPropertyNames(a);for(e=0;e<b.length;e++)d=b[e],a[d]=sf(f,a[d],a);c.B=a}n.styleDocument=function(a){this.styleSubtree(this.c,a)};
n.styleSubtree=function(a,b){var c=a.shadowRoot;(c||a===this.c)&&this.styleElement(a,b);if(b=c&&(c.children||c.childNodes))for(a=0;a<b.length;a++)this.styleSubtree(b[a]);else if(a=a.children||a.childNodes)for(b=0;b<a.length;b++)this.styleSubtree(a[b])};n.na=function(a){var b=this,c=ze(a);ye(c,function(a){if(U)gf(a);else{var c=W;a.selector=a.parsedSelector;gf(a);a.selector=a.l=Qe(c,a,c.c,void 0,void 0)}V&&(Sf(b),b.a&&b.a.transformRule(a))});V?a.textContent=xe(c):this.j.w.rules.push(c)};
n.getComputedStyleValue=function(a,b){var c;V||(c=(X(a)||X(Vf(this,a))).B[b]);return(c=c||window.getComputedStyle(a).getPropertyValue(b))?c.trim():""};n.Ha=function(a,b){var c=a.getRootNode();b=b?b.split(/\s/):[];c=c.host&&c.host.localName;if(!c){var d=a.getAttribute("class");if(d){d=d.split(/\s/);for(var e=0;e<d.length;e++)if(d[e]===W.a){c=d[e+1];break}}}c&&b.push(W.a,c);V||(c=X(a))&&c.o&&b.push(Bf.a,c.o);Fe(a,b.join(" "))};n.ya=function(a){return X(a)};Y.prototype.flush=Y.prototype.ga;
Y.prototype.prepareTemplate=Y.prototype.prepareTemplate;Y.prototype.styleElement=Y.prototype.styleElement;Y.prototype.styleDocument=Y.prototype.styleDocument;Y.prototype.styleSubtree=Y.prototype.styleSubtree;Y.prototype.getComputedStyleValue=Y.prototype.getComputedStyleValue;Y.prototype.setElementClass=Y.prototype.Ha;Y.prototype._styleInfoForNode=Y.prototype.ya;Y.prototype.transformCustomStyleForDocument=Y.prototype.na;Y.prototype.getStyleAst=Y.prototype.Aa;Y.prototype.styleAstToString=Y.prototype.Ia;
Y.prototype.flushCustomStyles=Y.prototype.flushCustomStyles;Object.defineProperties(Y.prototype,{nativeShadow:{get:function(){return U}},nativeCss:{get:function(){return V}}});var Z=new Y,Wf,Xf;window.ShadyCSS&&(Wf=window.ShadyCSS.ApplyShim,Xf=window.ShadyCSS.CustomStyleInterface);
window.ShadyCSS={ScopingShim:Z,prepareTemplate:function(a,b,c){Z.flushCustomStyles();Z.prepareTemplate(a,b,c)},prepareTemplateDom:function(a,b){Z.prepareTemplateDom(a,b)},prepareTemplateStyles:function(a,b,c){Z.flushCustomStyles();Z.prepareTemplateStyles(a,b,c)},styleSubtree:function(a,b){Z.flushCustomStyles();Z.styleSubtree(a,b)},styleElement:function(a){Z.flushCustomStyles();Z.styleElement(a)},styleDocument:function(a){Z.flushCustomStyles();Z.styleDocument(a)},flushCustomStyles:function(){Z.flushCustomStyles()},
getComputedStyleValue:function(a,b){return Z.getComputedStyleValue(a,b)},nativeCss:V,nativeShadow:U};Wf&&(window.ShadyCSS.ApplyShim=Wf);Xf&&(window.ShadyCSS.CustomStyleInterface=Xf);var Yf=window.document;window.WebComponents=window.WebComponents||{};function Zf(){requestAnimationFrame(function(){window.WebComponents.ready=!0;window.document.dispatchEvent(new CustomEvent("WebComponentsReady",{bubbles:!0}))})}function $f(){Zf();Yf.removeEventListener("readystatechange",$f)}"loading"!==Yf.readyState?Zf():Yf.addEventListener("readystatechange",$f);}).call(this);

//# sourceMappingURL=webcomponents-sd-ce.js.map
