/**
@license @nocompile
Copyright (c) 2018 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){/*

Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
'use strict';var m,aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},q="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function ba(){ba=function(){};q.Symbol||(q.Symbol=ca)}var ca=function(){var a=0;return function(b){return"jscomp_symbol_"+(b||"")+a++}}();
function da(){ba();var a=q.Symbol.iterator;a||(a=q.Symbol.iterator=q.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&aa(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ea(this)}});da=function(){}}function ea(a){var b=0;return fa(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function fa(a){da();a={next:a};a[q.Symbol.iterator]=function(){return this};return a}function r(a){da();ba();da();var b=a[Symbol.iterator];return b?b.call(a):ea(a)}
function ha(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c}function ia(){this.da=this.root=null;this.N=!1;this.v=this.J=this.U=this.assignedSlot=this.assignedNodes=this.A=null;this.childNodes=this.nextSibling=this.previousSibling=this.lastChild=this.firstChild=this.parentNode=this.D=void 0;this.ha=this.$=!1;this.I={}}ia.prototype.toJSON=function(){return{}};function t(a){a.S||(a.S=new ia);return a.S}function u(a){return a&&a.S};var v=window.ShadyDOM||{};v.sa=!(!Element.prototype.attachShadow||!Node.prototype.getRootNode);var ja=Object.getOwnPropertyDescriptor(Node.prototype,"firstChild");v.m=!!(ja&&ja.configurable&&ja.get);v.W=v.force||!v.sa;var ka=navigator.userAgent.match("Trident"),la=navigator.userAgent.match("Edge");void 0===v.fa&&(v.fa=v.m&&(ka||la));function w(a){return(a=u(a))&&void 0!==a.firstChild}function x(a){return"ShadyRoot"===a.ma}function y(a){a=a.getRootNode();if(x(a))return a}
var z=Element.prototype,na=z.matches||z.matchesSelector||z.mozMatchesSelector||z.msMatchesSelector||z.oMatchesSelector||z.webkitMatchesSelector;function oa(a,b){if(a&&b)for(var c=Object.getOwnPropertyNames(b),e=0,d;e<c.length&&(d=c[e]);e++){var f=Object.getOwnPropertyDescriptor(b,d);f&&Object.defineProperty(a,d,f)}}function pa(a,b){for(var c=[],e=1;e<arguments.length;++e)c[e-1]=arguments[e];for(e=0;e<c.length;e++)oa(a,c[e]);return a}function qa(a,b){for(var c in b)a[c]=b[c]}
var ra=document.createTextNode(""),sa=0,ta=[];(new MutationObserver(function(){for(;ta.length;)try{ta.shift()()}catch(a){throw ra.textContent=sa++,a;}})).observe(ra,{characterData:!0});function ua(a){ta.push(a);ra.textContent=sa++}var va=!!document.contains;function wa(a,b){for(;b;){if(b==a)return!0;b=b.parentNode}return!1}
function xa(a){for(var b=a.length-1;0<=b;b--){var c=a[b],e=c.getAttribute("id")||c.getAttribute("name");e&&"length"!==e&&isNaN(e)&&(a[e]=c)}a.item=function(b){return a[b]};a.namedItem=function(b){if("length"!==b&&isNaN(b)&&a[b])return a[b];for(var c=r(a),e=c.next();!e.done;e=c.next())if(e=e.value,(e.getAttribute("id")||e.getAttribute("name"))==b)return e;return null};return a};var ya=[],za;function Aa(a){za||(za=!0,ua(Ba));ya.push(a)}function Ba(){za=!1;for(var a=!!ya.length;ya.length;)ya.shift()();return a}Ba.list=ya;function Ca(){this.a=!1;this.addedNodes=[];this.removedNodes=[];this.M=new Set}function Da(a){a.a||(a.a=!0,ua(function(){Ea(a)}))}function Ea(a){if(a.a){a.a=!1;var b=a.takeRecords();b.length&&a.M.forEach(function(a){a(b)})}}Ca.prototype.takeRecords=function(){if(this.addedNodes.length||this.removedNodes.length){var a=[{addedNodes:this.addedNodes,removedNodes:this.removedNodes}];this.addedNodes=[];this.removedNodes=[];return a}return[]};
function Fa(a,b){var c=t(a);c.A||(c.A=new Ca);c.A.M.add(b);var e=c.A;return{la:b,oa:e,na:a,takeRecords:function(){return e.takeRecords()}}}function Ga(a){var b=a&&a.oa;b&&(b.M.delete(a.la),b.M.size||(t(a.na).A=null))}
function Ha(a,b){var c=b.getRootNode();return a.map(function(a){var b=c===a.target.getRootNode();if(b&&a.addedNodes){if(b=Array.from(a.addedNodes).filter(function(a){return c===a.getRootNode()}),b.length)return a=Object.create(a),Object.defineProperty(a,"addedNodes",{value:b,configurable:!0}),a}else if(b)return a}).filter(function(a){return a})};var A={},Ia=Element.prototype.insertBefore,Ja=Element.prototype.replaceChild,Ka=Element.prototype.removeChild,La=Element.prototype.setAttribute,Ma=Element.prototype.removeAttribute,Na=Element.prototype.cloneNode,Oa=Document.prototype.importNode,Pa=Element.prototype.addEventListener,Qa=Element.prototype.removeEventListener,Ra=Window.prototype.addEventListener,Sa=Window.prototype.removeEventListener,Ta=Element.prototype.dispatchEvent,Ua=Node.prototype.contains||HTMLElement.prototype.contains,Va=Document.prototype.getElementById,
Wa=Element.prototype.querySelector,Xa=DocumentFragment.prototype.querySelector,Ya=Document.prototype.querySelector,Za=Element.prototype.querySelectorAll,$a=DocumentFragment.prototype.querySelectorAll,ab=Document.prototype.querySelectorAll;A.appendChild=Element.prototype.appendChild;A.insertBefore=Ia;A.replaceChild=Ja;A.removeChild=Ka;A.setAttribute=La;A.removeAttribute=Ma;A.cloneNode=Na;A.importNode=Oa;A.addEventListener=Pa;A.removeEventListener=Qa;A.za=Ra;A.Aa=Sa;A.dispatchEvent=Ta;A.contains=Ua;
A.getElementById=Va;A.Ia=Wa;A.La=Xa;A.Ga=Ya;A.querySelector=function(a){switch(this.nodeType){case Node.ELEMENT_NODE:return Wa.call(this,a);case Node.DOCUMENT_NODE:return Ya.call(this,a);default:return Xa.call(this,a)}};A.Ja=Za;A.Ma=$a;A.Ha=ab;A.querySelectorAll=function(a){switch(this.nodeType){case Node.ELEMENT_NODE:return Za.call(this,a);case Node.DOCUMENT_NODE:return ab.call(this,a);default:return $a.call(this,a)}};var bb=/[&\u00A0"]/g,cb=/[&\u00A0<>]/g;function db(a){switch(a){case "&":return"&amp;";case "<":return"&lt;";case ">":return"&gt;";case '"':return"&quot;";case "\u00a0":return"&nbsp;"}}function eb(a){for(var b={},c=0;c<a.length;c++)b[a[c]]=!0;return b}var fb=eb("area base br col command embed hr img input keygen link meta param source track wbr".split(" ")),gb=eb("style script xmp iframe noembed noframes plaintext noscript".split(" "));
function hb(a,b){"template"===a.localName&&(a=a.content);for(var c="",e=b?b(a):a.childNodes,d=0,f=e.length,g;d<f&&(g=e[d]);d++){a:{var h=g;var k=a;var l=b;switch(h.nodeType){case Node.ELEMENT_NODE:for(var n=h.localName,p="<"+n,J=h.attributes,I=0;k=J[I];I++)p+=" "+k.name+'="'+k.value.replace(bb,db)+'"';p+=">";h=fb[n]?p:p+hb(h,l)+"</"+n+">";break a;case Node.TEXT_NODE:h=h.data;h=k&&gb[k.localName]?h:h.replace(cb,db);break a;case Node.COMMENT_NODE:h="\x3c!--"+h.data+"--\x3e";break a;default:throw window.console.error(h),
Error("not implemented");}}c+=h}return c};var B={},C=document.createTreeWalker(document,NodeFilter.SHOW_ALL,null,!1),D=document.createTreeWalker(document,NodeFilter.SHOW_ELEMENT,null,!1);function ib(a){var b=[];C.currentNode=a;for(a=C.firstChild();a;)b.push(a),a=C.nextSibling();return b}B.parentNode=function(a){C.currentNode=a;return C.parentNode()};B.firstChild=function(a){C.currentNode=a;return C.firstChild()};B.lastChild=function(a){C.currentNode=a;return C.lastChild()};B.previousSibling=function(a){C.currentNode=a;return C.previousSibling()};
B.nextSibling=function(a){C.currentNode=a;return C.nextSibling()};B.childNodes=ib;B.parentElement=function(a){D.currentNode=a;return D.parentNode()};B.firstElementChild=function(a){D.currentNode=a;return D.firstChild()};B.lastElementChild=function(a){D.currentNode=a;return D.lastChild()};B.previousElementSibling=function(a){D.currentNode=a;return D.previousSibling()};B.nextElementSibling=function(a){D.currentNode=a;return D.nextSibling()};
B.children=function(a){var b=[];D.currentNode=a;for(a=D.firstChild();a;)b.push(a),a=D.nextSibling();return xa(b)};B.innerHTML=function(a){return hb(a,function(a){return ib(a)})};B.textContent=function(a){switch(a.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:a=document.createTreeWalker(a,NodeFilter.SHOW_TEXT,null,!1);for(var b="",c;c=a.nextNode();)b+=c.nodeValue;return b;default:return a.nodeValue}};var E={},jb=v.m,kb=[Node.prototype,Element.prototype,HTMLElement.prototype];function F(a){var b;a:{for(b=0;b<kb.length;b++){var c=kb[b];if(c.hasOwnProperty(a)){b=c;break a}}b=void 0}if(!b)throw Error("Could not find descriptor for "+a);return Object.getOwnPropertyDescriptor(b,a)}
var G=jb?{parentNode:F("parentNode"),firstChild:F("firstChild"),lastChild:F("lastChild"),previousSibling:F("previousSibling"),nextSibling:F("nextSibling"),childNodes:F("childNodes"),parentElement:F("parentElement"),previousElementSibling:F("previousElementSibling"),nextElementSibling:F("nextElementSibling"),innerHTML:F("innerHTML"),textContent:F("textContent"),firstElementChild:F("firstElementChild"),lastElementChild:F("lastElementChild"),children:F("children")}:{},lb=jb?{firstElementChild:Object.getOwnPropertyDescriptor(DocumentFragment.prototype,
"firstElementChild"),lastElementChild:Object.getOwnPropertyDescriptor(DocumentFragment.prototype,"lastElementChild"),children:Object.getOwnPropertyDescriptor(DocumentFragment.prototype,"children")}:{},mb=jb?{firstElementChild:Object.getOwnPropertyDescriptor(Document.prototype,"firstElementChild"),lastElementChild:Object.getOwnPropertyDescriptor(Document.prototype,"lastElementChild"),children:Object.getOwnPropertyDescriptor(Document.prototype,"children")}:{};E.ca=G;E.Ka=lb;E.Fa=mb;E.parentNode=function(a){return G.parentNode.get.call(a)};
E.firstChild=function(a){return G.firstChild.get.call(a)};E.lastChild=function(a){return G.lastChild.get.call(a)};E.previousSibling=function(a){return G.previousSibling.get.call(a)};E.nextSibling=function(a){return G.nextSibling.get.call(a)};E.childNodes=function(a){return Array.prototype.slice.call(G.childNodes.get.call(a))};E.parentElement=function(a){return G.parentElement.get.call(a)};E.previousElementSibling=function(a){return G.previousElementSibling.get.call(a)};E.nextElementSibling=function(a){return G.nextElementSibling.get.call(a)};
E.innerHTML=function(a){return G.innerHTML.get.call(a)};E.textContent=function(a){return G.textContent.get.call(a)};E.children=function(a){switch(a.nodeType){case Node.DOCUMENT_FRAGMENT_NODE:return lb.children.get.call(a);case Node.DOCUMENT_NODE:return mb.children.get.call(a);default:return G.children.get.call(a)}};
E.firstElementChild=function(a){switch(a.nodeType){case Node.DOCUMENT_FRAGMENT_NODE:return lb.firstElementChild.get.call(a);case Node.DOCUMENT_NODE:return mb.firstElementChild.get.call(a);default:return G.firstElementChild.get.call(a)}};E.lastElementChild=function(a){switch(a.nodeType){case Node.DOCUMENT_FRAGMENT_NODE:return lb.lastElementChild.get.call(a);case Node.DOCUMENT_NODE:return mb.lastElementChild.get.call(a);default:return G.lastElementChild.get.call(a)}};var H=v.fa?E:B;function nb(a){for(;a.firstChild;)a.removeChild(a.firstChild)}
var ob=v.m,pb=document.implementation.createHTMLDocument("inert"),qb=Object.getOwnPropertyDescriptor(Node.prototype,"isConnected"),rb=qb&&qb.get,sb=Object.getOwnPropertyDescriptor(Document.prototype,"activeElement"),tb={parentElement:{get:function(){var a=u(this);(a=a&&a.parentNode)&&a.nodeType!==Node.ELEMENT_NODE&&(a=null);return void 0!==a?a:H.parentElement(this)},configurable:!0},parentNode:{get:function(){var a=u(this);a=a&&a.parentNode;return void 0!==a?a:H.parentNode(this)},configurable:!0},
nextSibling:{get:function(){var a=u(this);a=a&&a.nextSibling;return void 0!==a?a:H.nextSibling(this)},configurable:!0},previousSibling:{get:function(){var a=u(this);a=a&&a.previousSibling;return void 0!==a?a:H.previousSibling(this)},configurable:!0},nextElementSibling:{get:function(){var a=u(this);if(a&&void 0!==a.nextSibling){for(a=this.nextSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.nextSibling;return a}return H.nextElementSibling(this)},configurable:!0},previousElementSibling:{get:function(){var a=
u(this);if(a&&void 0!==a.previousSibling){for(a=this.previousSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.previousSibling;return a}return H.previousElementSibling(this)},configurable:!0}},ub={className:{get:function(){return this.getAttribute("class")||""},set:function(a){this.setAttribute("class",a)},configurable:!0}},vb={childNodes:{get:function(){if(w(this)){var a=u(this);if(!a.childNodes){a.childNodes=[];for(var b=this.firstChild;b;b=b.nextSibling)a.childNodes.push(b)}var c=a.childNodes}else c=
H.childNodes(this);c.item=function(a){return c[a]};return c},configurable:!0},childElementCount:{get:function(){return this.children.length},configurable:!0},firstChild:{get:function(){var a=u(this);a=a&&a.firstChild;return void 0!==a?a:H.firstChild(this)},configurable:!0},lastChild:{get:function(){var a=u(this);a=a&&a.lastChild;return void 0!==a?a:H.lastChild(this)},configurable:!0},textContent:{get:function(){if(w(this)){for(var a=[],b=0,c=this.childNodes,e;e=c[b];b++)e.nodeType!==Node.COMMENT_NODE&&
a.push(e.textContent);return a.join("")}return H.textContent(this)},set:function(a){if("undefined"===typeof a||null===a)a="";switch(this.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:if(!w(this)&&ob){var b=this.firstChild;(b!=this.lastChild||b&&b.nodeType!=Node.TEXT_NODE)&&nb(this);E.ca.textContent.set.call(this,a)}else nb(this),(0<a.length||this.nodeType===Node.ELEMENT_NODE)&&this.appendChild(document.createTextNode(a));break;default:this.nodeValue=a}},configurable:!0},firstElementChild:{get:function(){var a=
u(this);if(a&&void 0!==a.firstChild){for(a=this.firstChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.nextSibling;return a}return H.firstElementChild(this)},configurable:!0},lastElementChild:{get:function(){var a=u(this);if(a&&void 0!==a.lastChild){for(a=this.lastChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.previousSibling;return a}return H.lastElementChild(this)},configurable:!0},children:{get:function(){return w(this)?xa(Array.prototype.filter.call(this.childNodes,function(a){return a.nodeType===Node.ELEMENT_NODE})):
H.children(this)},configurable:!0},innerHTML:{get:function(){return w(this)?hb("template"===this.localName?this.content:this):H.innerHTML(this)},set:function(a){var b="template"===this.localName?this.content:this;nb(b);var c=this.localName||"div";c=this.namespaceURI&&this.namespaceURI!==pb.namespaceURI?pb.createElementNS(this.namespaceURI,c):pb.createElement(c);ob?E.ca.innerHTML.set.call(c,a):c.innerHTML=a;for(a="template"===this.localName?c.content:c;a.firstChild;)b.appendChild(a.firstChild)},configurable:!0}},
wb={shadowRoot:{get:function(){var a=u(this);return a&&a.da||null},configurable:!0}},xb={activeElement:{get:function(){var a=sb&&sb.get?sb.get.call(document):v.m?void 0:document.activeElement;if(a&&a.nodeType){var b=!!x(this);if(this===document||b&&this.host!==a&&A.contains.call(this.host,a)){for(b=y(a);b&&b!==this;)a=b.host,b=y(a);a=this===document?b?null:a:b===this?a:null}else a=null}else a=null;return a},set:function(){},configurable:!0}};
function K(a,b,c){for(var e in b){var d=Object.getOwnPropertyDescriptor(a,e);d&&d.configurable||!d&&c?Object.defineProperty(a,e,b[e]):c&&console.warn("Could not define",e,"on",a)}}function L(a){K(a,tb);K(a,ub);K(a,vb);K(a,xb)}
function yb(){var a=zb.prototype;a.__proto__=DocumentFragment.prototype;K(a,tb,!0);K(a,vb,!0);K(a,xb,!0);Object.defineProperties(a,{nodeType:{value:Node.DOCUMENT_FRAGMENT_NODE,configurable:!0},nodeName:{value:"#document-fragment",configurable:!0},nodeValue:{value:null,configurable:!0}});["localName","namespaceURI","prefix"].forEach(function(b){Object.defineProperty(a,b,{value:void 0,configurable:!0})});["ownerDocument","baseURI","isConnected"].forEach(function(b){Object.defineProperty(a,b,{get:function(){return this.host[b]},
configurable:!0})})}var Ab=v.m?function(){}:function(a){var b=t(a);b.$||(b.$=!0,K(a,tb,!0),K(a,ub,!0))},Bb=v.m?function(){}:function(a){t(a).ha||(K(a,vb,!0),K(a,wb,!0))};var Cb=H.childNodes;function Db(a,b,c){Ab(a);c=c||null;var e=t(a),d=t(b),f=c?t(c):null;e.previousSibling=c?f.previousSibling:b.lastChild;if(f=u(e.previousSibling))f.nextSibling=a;if(f=u(e.nextSibling=c))f.previousSibling=a;e.parentNode=b;c?c===d.firstChild&&(d.firstChild=a):(d.lastChild=a,d.firstChild||(d.firstChild=a));d.childNodes=null}
function Eb(a){var b=t(a);if(void 0===b.firstChild){b.childNodes=null;var c=Cb(a);b.firstChild=c[0]||null;b.lastChild=c[c.length-1]||null;Bb(a);for(b=0;b<c.length;b++){var e=c[b],d=t(e);d.parentNode=a;d.nextSibling=c[b+1]||null;d.previousSibling=c[b-1]||null;Ab(e)}}};var Fb=H.parentNode;
function Gb(a,b,c){if(b===a)throw Error("Failed to execute 'appendChild' on 'Node': The new child element contains the parent.");if(c){var e=u(c);e=e&&e.parentNode;if(void 0!==e&&e!==a||void 0===e&&Fb(c)!==a)throw Error("Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.");}if(c===b)return b;b.parentNode&&Hb(b.parentNode,b);var d,f;if(!b.__noInsertionPoint){if(f=d=y(a)){var g;"slot"===b.localName?g=[b]:b.querySelectorAll&&
(g=b.querySelectorAll("slot"));f=g&&g.length?g:void 0}f&&(g=d,e=f,g.a=g.a||[],g.f=g.f||[],g.g=g.g||{},g.a.push.apply(g.a,[].concat(e instanceof Array?e:ha(r(e)))))}("slot"===a.localName||f)&&(d=d||y(a))&&M(d);if(w(a)){d=c;Bb(a);f=t(a);void 0!==f.firstChild&&(f.childNodes=null);if(b.nodeType===Node.DOCUMENT_FRAGMENT_NODE){f=b.childNodes;for(g=0;g<f.length;g++)Db(f[g],a,d);d=t(b);f=void 0!==d.firstChild?null:void 0;d.firstChild=d.lastChild=f;d.childNodes=f}else Db(b,a,d);d=u(a);if(Ib(a)){M(d.root);
var h=!0}else d.root&&(h=!0)}h||(h=x(a)?a.host:a,c?(c=Jb(c),A.insertBefore.call(h,b,c)):A.appendChild.call(h,b));Kb(a,b);return b}
function Hb(a,b){if(b.parentNode!==a)throw Error("The node to be removed is not a child of this node: "+b);var c=y(b),e=u(a);if(w(a)){var d=t(b),f=t(a);b===f.firstChild&&(f.firstChild=d.nextSibling);b===f.lastChild&&(f.lastChild=d.previousSibling);var g=d.previousSibling,h=d.nextSibling;g&&(t(g).nextSibling=h);h&&(t(h).previousSibling=g);d.parentNode=d.previousSibling=d.nextSibling=void 0;void 0!==f.childNodes&&(f.childNodes=null);if(Ib(a)){M(e.root);var k=!0}}Lb(b);if(c){(d=a&&"slot"===a.localName)&&
(k=!0);if(c.f){Mb(c);f=c.g;for(ma in f)for(g=f[ma],h=0;h<g.length;h++){var l=g[h];if(wa(b,l)){g.splice(h,1);var n=c.f.indexOf(l);0<=n&&c.f.splice(n,1);h--;n=u(l);if(l=n.v)for(var p=0;p<l.length;p++){var J=l[p],I=Nb(J);I&&A.removeChild.call(I,J)}n.v=[];n.assignedNodes=[];n=!0}}var ma=n}else ma=void 0;(ma||d)&&M(c)}k||(k=x(a)?a.host:a,(!e.root&&"slot"!==b.localName||k===Fb(b))&&A.removeChild.call(k,b));Kb(a,null,b);return b}
function Lb(a){var b=u(a);if(b&&void 0!==b.D){b=a.childNodes;for(var c=0,e=b.length,d;c<e&&(d=b[c]);c++)Lb(d)}if(a=u(a))a.D=void 0}function Jb(a){var b=a;a&&"slot"===a.localName&&(b=(b=(b=u(a))&&b.v)&&b.length?b[0]:Jb(a.nextSibling));return b}function Ib(a){return(a=(a=u(a))&&a.root)&&Ob(a)}
function Pb(a,b){if("slot"===b)a=a.parentNode,Ib(a)&&M(u(a).root);else if("slot"===a.localName&&"name"===b&&(b=y(a))){if(b.f){var c=a.ka,e=Qb(a);if(e!==c){c=b.g[c];var d=c.indexOf(a);0<=d&&c.splice(d,1);c=b.g[e]||(b.g[e]=[]);c.push(a);1<c.length&&(b.g[e]=Rb(c))}}M(b)}}function Kb(a,b,c){if(a=(a=u(a))&&a.A)b&&a.addedNodes.push(b),c&&a.removedNodes.push(c),Da(a)}
function Sb(a){if(a&&a.nodeType){var b=t(a),c=b.D;void 0===c&&(x(a)?(c=a,b.D=c):(c=(c=a.parentNode)?Sb(c):a,A.contains.call(document.documentElement,a)&&(b.D=c)));return c}}function Tb(a,b,c){var e=[];Ub(a.childNodes,b,c,e);return e}function Ub(a,b,c,e){for(var d=0,f=a.length,g;d<f&&(g=a[d]);d++){var h;if(h=g.nodeType===Node.ELEMENT_NODE){h=g;var k=b,l=c,n=e,p=k(h);p&&n.push(h);l&&l(p)?h=p:(Ub(h.childNodes,k,l,n),h=void 0)}if(h)break}}var Vb=null;
function Wb(a,b,c){Vb||(Vb=window.ShadyCSS&&window.ShadyCSS.ScopingShim);Vb&&"class"===b?Vb.setElementClass(a,c):(A.setAttribute.call(a,b,c),Pb(a,b))}function Xb(a,b){if(a.ownerDocument!==document||"template"===a.localName)return A.importNode.call(document,a,b);var c=A.importNode.call(document,a,!1);if(b){a=a.childNodes;b=0;for(var e;b<a.length;b++)e=Xb(a[b],!0),c.appendChild(e)}return c};var Yb="__eventWrappers"+Date.now(),Zb=function(){var a=Object.getOwnPropertyDescriptor(Event.prototype,"composed");return a?function(b){return a.get.call(b)}:null}(),$b={blur:!0,focus:!0,focusin:!0,focusout:!0,click:!0,dblclick:!0,mousedown:!0,mouseenter:!0,mouseleave:!0,mousemove:!0,mouseout:!0,mouseover:!0,mouseup:!0,wheel:!0,beforeinput:!0,input:!0,keydown:!0,keyup:!0,compositionstart:!0,compositionupdate:!0,compositionend:!0,touchstart:!0,touchend:!0,touchmove:!0,touchcancel:!0,pointerover:!0,
pointerenter:!0,pointerdown:!0,pointermove:!0,pointerup:!0,pointercancel:!0,pointerout:!0,pointerleave:!0,gotpointercapture:!0,lostpointercapture:!0,dragstart:!0,drag:!0,dragenter:!0,dragleave:!0,dragover:!0,drop:!0,dragend:!0,DOMActivate:!0,DOMFocusIn:!0,DOMFocusOut:!0,keypress:!0},ac={DOMAttrModified:!0,DOMAttributeNameChanged:!0,DOMCharacterDataModified:!0,DOMElementNameChanged:!0,DOMNodeInserted:!0,DOMNodeInsertedIntoDocument:!0,DOMNodeRemoved:!0,DOMNodeRemovedFromDocument:!0,DOMSubtreeModified:!0};
function bc(a,b){var c=[],e=a;for(a=a===window?window:a.getRootNode();e;)c.push(e),e=e.assignedSlot?e.assignedSlot:e.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&e.host&&(b||e!==a)?e.host:e.parentNode;c[c.length-1]===document&&c.push(window);return c}function cc(a,b){if(!x)return a;a=bc(a,!0);for(var c=0,e,d,f,g;c<b.length;c++)if(e=b[c],f=e===window?window:e.getRootNode(),f!==d&&(g=a.indexOf(f),d=f),!x(f)||-1<g)return e}
var dc={get composed(){void 0===this.H&&(Zb?this.H=Zb(this):!1!==this.isTrusted&&(this.H=$b[this.type]));return this.H||!1},composedPath:function(){this.Z||(this.Z=bc(this.__target,this.composed));return this.Z},get target(){return cc(this.currentTarget,this.composedPath())},get relatedTarget(){if(!this.R)return null;this.aa||(this.aa=bc(this.R,!0));return cc(this.currentTarget,this.aa)},stopPropagation:function(){Event.prototype.stopPropagation.call(this);this.P=!0},stopImmediatePropagation:function(){Event.prototype.stopImmediatePropagation.call(this);
this.P=this.ga=!0}};function ec(a){function b(b,e){b=new a(b,e);b.H=e&&!!e.composed;return b}qa(b,a);b.prototype=a.prototype;return b}var fc={focus:!0,blur:!0};function gc(a){return a.__target!==a.target||a.R!==a.relatedTarget}function hc(a,b,c){if(c=b.__handlers&&b.__handlers[a.type]&&b.__handlers[a.type][c])for(var e=0,d;(d=c[e])&&(!gc(a)||a.target!==a.relatedTarget)&&(d.call(b,a),!a.ga);e++);}
function ic(a){var b=a.composedPath();Object.defineProperty(a,"currentTarget",{get:function(){return e},configurable:!0});for(var c=b.length-1;0<=c;c--){var e=b[c];hc(a,e,"capture");if(a.P)return}Object.defineProperty(a,"eventPhase",{get:function(){return Event.AT_TARGET}});var d;for(c=0;c<b.length;c++){e=b[c];var f=u(e);f=f&&f.root;if(0===c||f&&f===d)if(hc(a,e,"bubble"),e!==window&&(d=e.getRootNode()),a.P)break}}
function jc(a,b,c,e,d,f){for(var g=0;g<a.length;g++){var h=a[g],k=h.type,l=h.capture,n=h.once,p=h.passive;if(b===h.node&&c===k&&e===l&&d===n&&f===p)return g}return-1}
function kc(a,b,c){if(b){var e=typeof b;if("function"===e||"object"===e)if("object"!==e||b.handleEvent&&"function"===typeof b.handleEvent){var d=this instanceof Window?A.za:A.addEventListener;if(ac[a])return d.call(this,a,b,c);if(c&&"object"===typeof c){var f=!!c.capture;var g=!!c.once;var h=!!c.passive}else f=!!c,h=g=!1;var k=c&&c.T||this,l=b[Yb];if(l){if(-1<jc(l,k,a,f,g,h))return}else b[Yb]=[];l=function(d){g&&this.removeEventListener(a,b,c);d.__target||lc(d);if(k!==this){var f=Object.getOwnPropertyDescriptor(d,
"currentTarget");Object.defineProperty(d,"currentTarget",{get:function(){return k},configurable:!0})}if(!x(k)||-1!=d.composedPath().indexOf(k))if(d.composed||-1<d.composedPath().indexOf(k))if(gc(d)&&d.target===d.relatedTarget)d.eventPhase===Event.BUBBLING_PHASE&&d.stopImmediatePropagation();else if(d.eventPhase===Event.CAPTURING_PHASE||d.bubbles||d.target===k||k instanceof Window){var h="function"===e?b.call(k,d):b.handleEvent&&b.handleEvent(d);k!==this&&(f?(Object.defineProperty(d,"currentTarget",
f),f=null):delete d.currentTarget);return h}};b[Yb].push({node:k,type:a,capture:f,once:g,passive:h,Ba:l});fc[a]?(this.__handlers=this.__handlers||{},this.__handlers[a]=this.__handlers[a]||{capture:[],bubble:[]},this.__handlers[a][f?"capture":"bubble"].push(l)):d.call(this,a,l,c)}}}
function mc(a,b,c){if(b){var e=this instanceof Window?A.Aa:A.removeEventListener;if(ac[a])return e.call(this,a,b,c);if(c&&"object"===typeof c){var d=!!c.capture;var f=!!c.once;var g=!!c.passive}else d=!!c,g=f=!1;var h=c&&c.T||this,k=void 0;var l=null;try{l=b[Yb]}catch(n){}l&&(f=jc(l,h,a,d,f,g),-1<f&&(k=l.splice(f,1)[0].Ba,l.length||(b[Yb]=void 0)));e.call(this,a,k||b,c);k&&fc[a]&&this.__handlers&&this.__handlers[a]&&(a=this.__handlers[a][d?"capture":"bubble"],k=a.indexOf(k),-1<k&&a.splice(k,1))}}
function nc(){for(var a in fc)window.addEventListener(a,function(a){a.__target||(lc(a),ic(a))},!0)}function lc(a){a.__target=a.target;a.R=a.relatedTarget;if(v.m){var b=Object.getPrototypeOf(a);if(!b.hasOwnProperty("__patchProto")){var c=Object.create(b);c.Da=b;oa(c,dc);b.__patchProto=c}a.__proto__=b.__patchProto}else oa(a,dc)}var oc=ec(window.Event),pc=ec(window.CustomEvent),qc=ec(window.MouseEvent);
function rc(){window.Event=oc;window.CustomEvent=pc;window.MouseEvent=qc;nc();if(!Zb&&Object.getOwnPropertyDescriptor(Event.prototype,"isTrusted")){var a=function(){var a=new MouseEvent("click",{bubbles:!0,cancelable:!0,composed:!0});this.dispatchEvent(a)};Element.prototype.click?Element.prototype.click=a:HTMLElement.prototype.click&&(HTMLElement.prototype.click=a)}};function sc(a,b){return{index:a,F:[],L:b}}
function tc(a,b,c,e){var d=0,f=0,g=0,h=0,k=Math.min(b-d,e-f);if(0==d&&0==f)a:{for(g=0;g<k;g++)if(a[g]!==c[g])break a;g=k}if(b==a.length&&e==c.length){h=a.length;for(var l=c.length,n=0;n<k-g&&uc(a[--h],c[--l]);)n++;h=n}d+=g;f+=g;b-=h;e-=h;if(0==b-d&&0==e-f)return[];if(d==b){for(b=sc(d,0);f<e;)b.F.push(c[f++]);return[b]}if(f==e)return[sc(d,b-d)];k=d;g=f;e=e-g+1;h=b-k+1;b=Array(e);for(l=0;l<e;l++)b[l]=Array(h),b[l][0]=l;for(l=0;l<h;l++)b[0][l]=l;for(l=1;l<e;l++)for(n=1;n<h;n++)if(a[k+n-1]===c[g+l-1])b[l][n]=
b[l-1][n-1];else{var p=b[l-1][n]+1,J=b[l][n-1]+1;b[l][n]=p<J?p:J}k=b.length-1;g=b[0].length-1;e=b[k][g];for(a=[];0<k||0<g;)0==k?(a.push(2),g--):0==g?(a.push(3),k--):(h=b[k-1][g-1],l=b[k-1][g],n=b[k][g-1],p=l<n?l<h?l:h:n<h?n:h,p==h?(h==e?a.push(0):(a.push(1),e=h),k--,g--):p==l?(a.push(3),k--,e=l):(a.push(2),g--,e=n));a.reverse();b=void 0;k=[];for(g=0;g<a.length;g++)switch(a[g]){case 0:b&&(k.push(b),b=void 0);d++;f++;break;case 1:b||(b=sc(d,0));b.L++;d++;b.F.push(c[f]);f++;break;case 2:b||(b=sc(d,0));
b.L++;d++;break;case 3:b||(b=sc(d,0)),b.F.push(c[f]),f++}b&&k.push(b);return k}function uc(a,b){return a===b};var Nb=H.parentNode,vc=H.childNodes,wc={},N=v.deferConnectionCallbacks&&"loading"===document.readyState,xc;function yc(a){var b=[];do b.unshift(a);while(a=a.parentNode);return b}
function zb(a,b,c){if(a!==wc)throw new TypeError("Illegal constructor");this.ma="ShadyRoot";this.host=b;this.c=c&&c.mode;Eb(b);a=t(b);a.root=this;a.da="closed"!==this.c?this:null;a=t(this);a.firstChild=a.lastChild=a.parentNode=a.nextSibling=a.previousSibling=null;a.childNodes=[];this.b=this.K=!1;this.a=this.g=this.f=null;M(this)}function M(a){a.K||(a.K=!0,Aa(function(){return zc(a)}))}
function zc(a){for(var b;a;){a.K&&(b=a);a:{var c=a;a=c.host.getRootNode();if(x(a))for(var e=c.host.childNodes,d=0;d<e.length;d++)if(c=e[d],"slot"==c.localName)break a;a=void 0}}b&&b._renderRoot()}
zb.prototype._renderRoot=function(){var a=N;N=!0;this.K=!1;if(this.f){Mb(this);for(var b=0,c;b<this.f.length;b++){c=this.f[b];var e=u(c),d=e.assignedNodes;e.assignedNodes=[];e.v=[];if(e.U=d)for(e=0;e<d.length;e++){var f=u(d[e]);f.J=f.assignedSlot;f.assignedSlot===c&&(f.assignedSlot=null)}}for(c=this.host.firstChild;c;c=c.nextSibling)Ac(this,c);for(b=0;b<this.f.length;b++){c=this.f[b];d=u(c);if(!d.assignedNodes.length)for(e=c.firstChild;e;e=e.nextSibling)Ac(this,e,c);(e=(e=u(c.parentNode))&&e.root)&&
Ob(e)&&e._renderRoot();Bc(this,d.v,d.assignedNodes);if(e=d.U){for(f=0;f<e.length;f++)u(e[f]).J=null;d.U=null;e.length>d.assignedNodes.length&&(d.N=!0)}d.N&&(d.N=!1,Cc(this,c))}b=this.f;c=[];for(d=0;d<b.length;d++)e=b[d].parentNode,(f=u(e))&&f.root||!(0>c.indexOf(e))||c.push(e);for(b=0;b<c.length;b++){d=c[b];e=d===this?this.host:d;f=[];d=d.childNodes;for(var g=0;g<d.length;g++){var h=d[g];if("slot"==h.localName){h=u(h).v;for(var k=0;k<h.length;k++)f.push(h[k])}else f.push(h)}d=void 0;g=vc(e);h=tc(f,
f.length,g,g.length);for(var l=k=0;k<h.length&&(d=h[k]);k++){for(var n=0,p;n<d.F.length&&(p=d.F[n]);n++)Nb(p)===e&&A.removeChild.call(e,p),g.splice(d.index+l,1);l-=d.L}for(l=0;l<h.length&&(d=h[l]);l++)for(k=g[d.index],n=d.index;n<d.index+d.L;n++)p=f[n],A.insertBefore.call(e,p,k),g.splice(n,0,p)}}if(!this.b)for(p=this.host.childNodes,c=0,b=p.length;c<b;c++)d=p[c],e=u(d),Nb(d)!==this.host||"slot"!==d.localName&&e.assignedSlot||A.removeChild.call(this.host,d);this.b=!0;N=a;xc&&xc()};
function Ac(a,b,c){var e=t(b),d=e.J;e.J=null;c||(c=(a=a.g[b.slot||"__catchall"])&&a[0]);c?(t(c).assignedNodes.push(b),e.assignedSlot=c):e.assignedSlot=void 0;d!==e.assignedSlot&&e.assignedSlot&&(t(e.assignedSlot).N=!0)}function Bc(a,b,c){for(var e=0,d;e<c.length&&(d=c[e]);e++)if("slot"==d.localName){var f=u(d).assignedNodes;f&&f.length&&Bc(a,b,f)}else b.push(c[e])}function Cc(a,b){A.dispatchEvent.call(b,new Event("slotchange"));b=u(b);b.assignedSlot&&Cc(a,b.assignedSlot)}
function Mb(a){if(a.a&&a.a.length){for(var b=a.a,c,e=0;e<b.length;e++){var d=b[e];Eb(d);Eb(d.parentNode);var f=Qb(d);a.g[f]?(c=c||{},c[f]=!0,a.g[f].push(d)):a.g[f]=[d];a.f.push(d)}if(c)for(var g in c)a.g[g]=Rb(a.g[g]);a.a=[]}}function Qb(a){var b=a.name||a.getAttribute("name")||"__catchall";return a.ka=b}function Rb(a){return a.sort(function(a,c){a=yc(a);for(var b=yc(c),d=0;d<a.length;d++){c=a[d];var f=b[d];if(c!==f)return a=Array.from(c.parentNode.childNodes),a.indexOf(c)-a.indexOf(f)}})}
function Ob(a){Mb(a);return!(!a.f||!a.f.length)}
if(window.customElements&&v.W){var Dc=new Map;xc=function(){var a=Array.from(Dc);Dc.clear();a=r(a);for(var b=a.next();!b.done;b=a.next()){b=r(b.value);var c=b.next().value;b.next().value?c.ia():c.ja()}};N&&document.addEventListener("readystatechange",function(){N=!1;xc()},{once:!0});var Ec=function(a,b,c){var e=0,d="__isConnected"+e++;if(b||c)a.prototype.connectedCallback=a.prototype.ia=function(){N?Dc.set(this,!0):this[d]||(this[d]=!0,b&&b.call(this))},a.prototype.disconnectedCallback=a.prototype.ja=
function(){N?this.isConnected||Dc.set(this,!1):this[d]&&(this[d]=!1,c&&c.call(this))};return a},define=window.customElements.define;Object.defineProperty(window.CustomElementRegistry.prototype,"define",{value:function(a,b){var c=b.prototype.connectedCallback,e=b.prototype.disconnectedCallback;define.call(window.customElements,a,Ec(b,c,e));b.prototype.connectedCallback=c;b.prototype.disconnectedCallback=e}})};function Fc(a){var b=a.getRootNode();x(b)&&zc(b);return(a=u(a))&&a.assignedSlot||null}
var Gc={addEventListener:kc.bind(window),removeEventListener:mc.bind(window)},Hc={addEventListener:kc,removeEventListener:mc,appendChild:function(a){return Gb(this,a)},insertBefore:function(a,b){return Gb(this,a,b)},removeChild:function(a){return Hb(this,a)},replaceChild:function(a,b){Gb(this,a,b);Hb(this,b);return a},cloneNode:function(a){if("template"==this.localName)var b=A.cloneNode.call(this,a);else if(b=A.cloneNode.call(this,!1),a&&b.nodeType!==Node.ATTRIBUTE_NODE){a=this.childNodes;for(var c=
0,e;c<a.length;c++)e=a[c].cloneNode(!0),b.appendChild(e)}return b},getRootNode:function(){return Sb(this)},contains:function(a){return wa(this,a)},dispatchEvent:function(a){Ba();return A.dispatchEvent.call(this,a)}};
Object.defineProperties(Hc,{isConnected:{get:function(){if(rb&&rb.call(this))return!0;if(this.nodeType==Node.DOCUMENT_FRAGMENT_NODE)return!1;var a=this.ownerDocument;if(va){if(A.contains.call(a,this))return!0}else if(a.documentElement&&A.contains.call(a.documentElement,this))return!0;for(a=this;a&&!(a instanceof Document);)a=a.parentNode||(x(a)?a.host:void 0);return!!(a&&a instanceof Document)},configurable:!0}});
var Ic={get assignedSlot(){return Fc(this)}},Jc={querySelector:function(a){return Tb(this,function(b){return na.call(b,a)},function(a){return!!a})[0]||null},querySelectorAll:function(a,b){if(b){b=Array.prototype.slice.call(A.querySelectorAll.call(this,a));var c=this.getRootNode();return b.filter(function(a){return a.getRootNode()==c})}return Tb(this,function(b){return na.call(b,a)})}},Kc={assignedNodes:function(a){if("slot"===this.localName){var b=this.getRootNode();x(b)&&zc(b);return(b=u(this))?
(a&&a.flatten?b.v:b.assignedNodes)||[]:[]}}},Lc=pa({setAttribute:function(a,b){Wb(this,a,b)},removeAttribute:function(a){A.removeAttribute.call(this,a);Pb(this,a)},attachShadow:function(a){if(!this)throw"Must provide a host.";if(!a)throw"Not enough arguments.";return new zb(wc,this,a)},get slot(){return this.getAttribute("slot")},set slot(a){Wb(this,"slot",a)},get assignedSlot(){return Fc(this)}},Jc,Kc);Object.defineProperties(Lc,wb);
var Mc=pa({importNode:function(a,b){return Xb(a,b)},getElementById:function(a){return Tb(this,function(b){return b.id==a},function(a){return!!a})[0]||null}},Jc);Object.defineProperties(Mc,{_activeElement:xb.activeElement});
for(var Nc=HTMLElement.prototype.blur,Oc={blur:function(){var a=u(this);(a=(a=a&&a.root)&&a.activeElement)?a.blur():Nc.call(this)}},O={},Pc=r(Object.getOwnPropertyNames(Document.prototype)),Qc=Pc.next();!Qc.done;O={j:O.j},Qc=Pc.next())O.j=Qc.value,"on"===O.j.substring(0,2)&&Object.defineProperty(Oc,O.j,{set:function(a){return function(b){var c=t(this),e=a.j.substring(2);c.I[a.j]&&this.removeEventListener(e,c.I[a.j]);this.addEventListener(e,b,{});c.I[a.j]=b}}(O),get:function(a){return function(){var b=
u(this);return b&&b.I[a.j]}}(O),configurable:!0});var Rc={addEventListener:function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.T=this;this.host.addEventListener(a,b,c)},removeEventListener:function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.T=this;this.host.removeEventListener(a,b,c)},getElementById:function(a){return Tb(this,function(b){return b.id==a},function(a){return!!a})[0]||null}};
function P(a,b){for(var c=Object.getOwnPropertyNames(b),e=0;e<c.length;e++){var d=c[e],f=Object.getOwnPropertyDescriptor(b,d);f.value?a[d]=f.value:Object.defineProperty(a,d,f)}};if(v.W){var ShadyDOM={inUse:v.W,patch:function(a){Bb(a);Ab(a);return a},isShadyRoot:x,enqueue:Aa,flush:Ba,settings:v,filterMutations:Ha,observeChildren:Fa,unobserveChildren:Ga,nativeMethods:A,nativeTree:H,deferConnectionCallbacks:v.deferConnectionCallbacks};window.ShadyDOM=ShadyDOM;rc();var Sc=window.customElements&&window.customElements.nativeHTMLElement||HTMLElement;P(zb.prototype,Rc);P(window.Node.prototype,Hc);P(window.Window.prototype,Gc);P(window.Text.prototype,Ic);P(window.DocumentFragment.prototype,
Jc);P(window.Element.prototype,Lc);P(window.Document.prototype,Mc);window.HTMLSlotElement&&P(window.HTMLSlotElement.prototype,Kc);P(Sc.prototype,Oc);v.m&&(L(window.Node.prototype),L(window.Text.prototype),L(window.DocumentFragment.prototype),L(window.Element.prototype),L(Sc.prototype),L(window.Document.prototype),window.HTMLSlotElement&&L(window.HTMLSlotElement.prototype));yb();window.ShadowRoot=zb};/*

Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
function Tc(){this.end=this.start=0;this.rules=this.parent=this.previous=null;this.cssText=this.parsedCssText="";this.atRule=!1;this.type=0;this.parsedSelector=this.selector=this.keyframesName=""}
function Uc(a){a=a.replace(Vc,"").replace(Wc,"");var b=Xc,c=a,e=new Tc;e.start=0;e.end=c.length;for(var d=e,f=0,g=c.length;f<g;f++)if("{"===c[f]){d.rules||(d.rules=[]);var h=d,k=h.rules[h.rules.length-1]||null;d=new Tc;d.start=f+1;d.parent=h;d.previous=k;h.rules.push(d)}else"}"===c[f]&&(d.end=f+1,d=d.parent||e);return b(e,a)}
function Xc(a,b){var c=b.substring(a.start,a.end-1);a.parsedCssText=a.cssText=c.trim();a.parent&&(c=b.substring(a.previous?a.previous.end:a.parent.start,a.start-1),c=Yc(c),c=c.replace(Zc," "),c=c.substring(c.lastIndexOf(";")+1),c=a.parsedSelector=a.selector=c.trim(),a.atRule=0===c.indexOf("@"),a.atRule?0===c.indexOf("@media")?a.type=$c:c.match(ad)&&(a.type=bd,a.keyframesName=a.selector.split(Zc).pop()):a.type=0===c.indexOf("--")?cd:dd);if(c=a.rules)for(var e=0,d=c.length,f;e<d&&(f=c[e]);e++)Xc(f,
b);return a}function Yc(a){return a.replace(/\\([0-9a-f]{1,6})\s/gi,function(a,c){a=c;for(c=6-a.length;c--;)a="0"+a;return"\\"+a})}
function ed(a,b,c){c=void 0===c?"":c;var e="";if(a.cssText||a.rules){var d=a.rules,f;if(f=d)f=d[0],f=!(f&&f.selector&&0===f.selector.indexOf("--"));if(f){f=0;for(var g=d.length,h;f<g&&(h=d[f]);f++)e=ed(h,b,e)}else b?b=a.cssText:(b=a.cssText,b=b.replace(fd,"").replace(gd,""),b=b.replace(hd,"").replace(id,"")),(e=b.trim())&&(e="  "+e+"\n")}e&&(a.selector&&(c+=a.selector+" {\n"),c+=e,a.selector&&(c+="}\n\n"));return c}
var dd=1,bd=7,$c=4,cd=1E3,Vc=/\/\*[^*]*\*+([^/*][^*]*\*+)*\//gim,Wc=/@import[^;]*;/gim,fd=/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?(?:[;\n]|$)/gim,gd=/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?{[^}]*?}(?:[;\n]|$)?/gim,hd=/@apply\s*\(?[^);]*\)?\s*(?:[;\n]|$)?/gim,id=/[^;:]*?:[^;]*?var\([^;]*\)(?:[;\n]|$)?/gim,ad=/^@[^\s]*keyframes/,Zc=/\s+/g;var Q=!(window.ShadyDOM&&window.ShadyDOM.inUse),jd;function kd(a){jd=a&&a.shimcssproperties?!1:Q||!(navigator.userAgent.match(/AppleWebKit\/601|Edge\/15/)||!window.CSS||!CSS.supports||!CSS.supports("box-shadow","0 0 0 var(--foo)"))}window.ShadyCSS&&void 0!==window.ShadyCSS.nativeCss?jd=window.ShadyCSS.nativeCss:window.ShadyCSS?(kd(window.ShadyCSS),window.ShadyCSS=void 0):kd(window.WebComponents&&window.WebComponents.flags);var R=jd;var ld=/(?:^|[;\s{]\s*)(--[\w-]*?)\s*:\s*(?:((?:'(?:\\'|.)*?'|"(?:\\"|.)*?"|\([^)]*?\)|[^};{])+)|\{([^}]*)\}(?:(?=[;\s}])|$))/gi,md=/(?:^|\W+)@apply\s*\(?([^);\n]*)\)?/gi,nd=/(--[\w-]+)\s*([:,;)]|$)/gi,od=/(animation\s*:)|(animation-name\s*:)/,pd=/@media\s(.*)/,qd=/\{[^}]*\}/g;var rd=new Set;function S(a,b){if(!a)return"";"string"===typeof a&&(a=Uc(a));b&&T(a,b);return ed(a,R)}function sd(a){!a.__cssRules&&a.textContent&&(a.__cssRules=Uc(a.textContent));return a.__cssRules||null}function td(a){return!!a.parent&&a.parent.type===bd}function T(a,b,c,e){if(a){var d=!1,f=a.type;if(e&&f===$c){var g=a.selector.match(pd);g&&(window.matchMedia(g[1]).matches||(d=!0))}f===dd?b(a):c&&f===bd?c(a):f===cd&&(d=!0);if((a=a.rules)&&!d){d=0;f=a.length;for(var h;d<f&&(h=a[d]);d++)T(h,b,c,e)}}}
function ud(a,b,c,e){var d=document.createElement("style");b&&d.setAttribute("scope",b);d.textContent=a;vd(d,c,e);return d}var U=null;function vd(a,b,c){b=b||document.head;b.insertBefore(a,c&&c.nextSibling||b.firstChild);U?a.compareDocumentPosition(U)===Node.DOCUMENT_POSITION_PRECEDING&&(U=a):U=a}
function wd(a,b){var c=a.indexOf("var(");if(-1===c)return b(a,"","","");a:{var e=0;var d=c+3;for(var f=a.length;d<f;d++)if("("===a[d])e++;else if(")"===a[d]&&0===--e)break a;d=-1}e=a.substring(c+4,d);c=a.substring(0,c);a=wd(a.substring(d+1),b);d=e.indexOf(",");return-1===d?b(c,e.trim(),"",a):b(c,e.substring(0,d).trim(),e.substring(d+1).trim(),a)}function xd(a,b){Q?a.setAttribute("class",b):window.ShadyDOM.nativeMethods.setAttribute.call(a,"class",b)}
function V(a){var b=a.localName,c="";b?-1<b.indexOf("-")||(c=b,b=a.getAttribute&&a.getAttribute("is")||""):(b=a.is,c=a.extends);return{is:b,G:c}};function yd(){}function zd(a,b,c){var e=W;a.__styleScoped?a.__styleScoped=null:Ad(e,a,b||"",c)}function Ad(a,b,c,e){b.nodeType===Node.ELEMENT_NODE&&Bd(b,c,e);if(b="template"===b.localName?(b.content||b.Ea||b).childNodes:b.children||b.childNodes)for(var d=0;d<b.length;d++)Ad(a,b[d],c,e)}
function Bd(a,b,c){if(b)if(a.classList)c?(a.classList.remove("style-scope"),a.classList.remove(b)):(a.classList.add("style-scope"),a.classList.add(b));else if(a.getAttribute){var e=a.getAttribute(Cd);c?e&&(b=e.replace("style-scope","").replace(b,""),xd(a,b)):xd(a,(e?e+" ":"")+"style-scope "+b)}}function Dd(a,b,c){var e=W,d=a.__cssBuild;Q||"shady"===d?b=S(b,c):(a=V(a),b=Ed(e,b,a.is,a.G,c)+"\n\n");return b.trim()}
function Ed(a,b,c,e,d){var f=Fd(c,e);c=c?Gd+c:"";return S(b,function(b){b.c||(b.selector=b.i=Hd(a,b,a.b,c,f),b.c=!0);d&&d(b,c,f)})}function Fd(a,b){return b?"[is="+a+"]":a}function Hd(a,b,c,e,d){var f=b.selector.split(Id);if(!td(b)){b=0;for(var g=f.length,h;b<g&&(h=f[b]);b++)f[b]=c.call(a,h,e,d)}return f.join(Id)}function Jd(a){return a.replace(Kd,function(a,c,e){-1<e.indexOf("+")?e=e.replace(/\+/g,"___"):-1<e.indexOf("___")&&(e=e.replace(/___/g,"+"));return":"+c+"("+e+")"})}
yd.prototype.b=function(a,b,c){var e=!1;a=a.trim();var d=Kd.test(a);d&&(a=a.replace(Kd,function(a,b,c){return":"+b+"("+c.replace(/\s/g,"")+")"}),a=Jd(a));a=a.replace(Ld,Md+" $1");a=a.replace(Nd,function(a,d,h){e||(a=Od(h,d,b,c),e=e||a.stop,d=a.qa,h=a.value);return d+h});d&&(a=Jd(a));return a};
function Od(a,b,c,e){var d=a.indexOf(Pd);0<=a.indexOf(Md)?a=Qd(a,e):0!==d&&(a=c?Rd(a,c):a);c=!1;0<=d&&(b="",c=!0);if(c){var f=!0;c&&(a=a.replace(Sd,function(a,b){return" > "+b}))}a=a.replace(Td,function(a,b,c){return'[dir="'+c+'"] '+b+", "+b+'[dir="'+c+'"]'});return{value:a,qa:b,stop:f}}function Rd(a,b){a=a.split(Ud);a[0]+=b;return a.join(Ud)}
function Qd(a,b){var c=a.match(Vd);return(c=c&&c[2].trim()||"")?c[0].match(Wd)?a.replace(Vd,function(a,c,f){return b+f}):c.split(Wd)[0]===b?c:Xd:a.replace(Md,b)}function Yd(a){a.selector===Zd&&(a.selector="html")}yd.prototype.c=function(a){return a.match(Pd)?this.b(a,$d):Rd(a.trim(),$d)};q.Object.defineProperties(yd.prototype,{a:{configurable:!0,enumerable:!0,get:function(){return"style-scope"}}});
var Kd=/:(nth[-\w]+)\(([^)]+)\)/,$d=":not(.style-scope)",Id=",",Nd=/(^|[\s>+~]+)((?:\[.+?\]|[^\s>+~=[])+)/g,Wd=/[[.:#*]/,Md=":host",Zd=":root",Pd="::slotted",Ld=new RegExp("^("+Pd+")"),Vd=/(:host)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,Sd=/(?:::slotted)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,Td=/(.*):dir\((?:(ltr|rtl))\)/,Gd=".",Ud=":",Cd="class",Xd="should_not_match",W=new yd;function ae(a,b,c,e){this.s=a||null;this.b=b||null;this.X=c||[];this.B=null;this.G=e||"";this.a=this.l=this.w=null}function X(a){return a?a.__styleInfo:null}function be(a,b){return a.__styleInfo=b}ae.prototype.c=function(){return this.s};ae.prototype._getStyleRules=ae.prototype.c;function ce(a){var b=this.matches||this.matchesSelector||this.mozMatchesSelector||this.msMatchesSelector||this.oMatchesSelector||this.webkitMatchesSelector;return b&&b.call(this,a)}var de=navigator.userAgent.match("Trident");function ee(){}function fe(a){var b={},c=[],e=0;T(a,function(a){ge(a);a.index=e++;a=a.h.cssText;for(var c;c=nd.exec(a);){var d=c[1];":"!==c[2]&&(b[d]=!0)}},function(a){c.push(a)});a.b=c;a=[];for(var d in b)a.push(d);return a}
function ge(a){if(!a.h){var b={},c={};he(a,c)&&(b.o=c,a.rules=null);b.cssText=a.parsedCssText.replace(qd,"").replace(ld,"");a.h=b}}function he(a,b){var c=a.h;if(c){if(c.o)return Object.assign(b,c.o),!0}else{c=a.parsedCssText;for(var e;a=ld.exec(c);){e=(a[2]||a[3]).trim();if("inherit"!==e||"unset"!==e)b[a[1].trim()]=e;e=!0}return e}}
function ie(a,b,c){b&&(b=0<=b.indexOf(";")?je(a,b,c):wd(b,function(b,d,f,g){if(!d)return b+g;(d=ie(a,c[d],c))&&"initial"!==d?"apply-shim-inherit"===d&&(d="inherit"):d=ie(a,c[f]||f,c)||f;return b+(d||"")+g}));return b&&b.trim()||""}
function je(a,b,c){b=b.split(";");for(var e=0,d,f;e<b.length;e++)if(d=b[e]){md.lastIndex=0;if(f=md.exec(d))d=ie(a,c[f[1]],c);else if(f=d.indexOf(":"),-1!==f){var g=d.substring(f);g=g.trim();g=ie(a,g,c)||g;d=d.substring(0,f)+g}b[e]=d&&d.lastIndexOf(";")===d.length-1?d.slice(0,-1):d||""}return b.join(";")}
function ke(a,b){var c={},e=[];T(a,function(a){a.h||ge(a);var d=a.i||a.parsedSelector;b&&a.h.o&&d&&ce.call(b,d)&&(he(a,c),a=a.index,d=parseInt(a/32,10),e[d]=(e[d]||0)|1<<a%32)},null,!0);return{o:c,key:e}}
function le(a,b,c,e){b.h||ge(b);if(b.h.o){var d=V(a);a=d.is;d=d.G;d=a?Fd(a,d):"html";var f=b.parsedSelector,g=":host > *"===f||"html"===f,h=0===f.indexOf(":host")&&!g;"shady"===c&&(g=f===d+" > *."+d||-1!==f.indexOf("html"),h=!g&&0===f.indexOf(d));"shadow"===c&&(g=":host > *"===f||"html"===f,h=h&&!g);if(g||h)c=d,h&&(b.i||(b.i=Hd(W,b,W.b,a?Gd+a:"",d)),c=b.i||d),e({wa:c,ua:h,Oa:g})}}
function me(a,b){var c={},e={},d=b&&b.__cssBuild;T(b,function(b){le(a,b,d,function(d){ce.call(a.Na||a,d.wa)&&(d.ua?he(b,c):he(b,e))})},null,!0);return{va:e,ta:c}}
function ne(a,b,c,e){var d=V(b),f=Fd(d.is,d.G),g=new RegExp("(?:^|[^.#[:])"+(b.extends?"\\"+f.slice(0,-1)+"\\]":f)+"($|[.:[\\s>+~])");d=X(b).s;var h=oe(d,e);return Dd(b,d,function(b){var d="";b.h||ge(b);b.h.cssText&&(d=je(a,b.h.cssText,c));b.cssText=d;if(!Q&&!td(b)&&b.cssText){var k=d=b.cssText;null==b.ba&&(b.ba=od.test(d));if(b.ba)if(null==b.O){b.O=[];for(var p in h)k=h[p],k=k(d),d!==k&&(d=k,b.O.push(p))}else{for(p=0;p<b.O.length;++p)k=h[b.O[p]],d=k(d);k=d}b.cssText=k;b.i=b.i||b.selector;d="."+e;
p=b.i.split(",");k=0;for(var J=p.length,I;k<J&&(I=p[k]);k++)p[k]=I.match(g)?I.replace(f,d):d+" "+I;b.selector=p.join(",")}})}function oe(a,b){a=a.b;var c={};if(!Q&&a)for(var e=0,d=a[e];e<a.length;d=a[++e]){var f=d,g=b;f.u=new RegExp("\\b"+f.keyframesName+"(?!\\B|-)","g");f.a=f.keyframesName+"-"+g;f.i=f.i||f.selector;f.selector=f.i.replace(f.keyframesName,f.a);c[d.keyframesName]=pe(d)}return c}function pe(a){return function(b){return b.replace(a.u,a.a)}}
function qe(a,b){var c=re,e=sd(a);a.textContent=S(e,function(a){var d=a.cssText=a.parsedCssText;a.h&&a.h.cssText&&(d=d.replace(fd,"").replace(gd,""),a.cssText=je(c,d,b))})}q.Object.defineProperties(ee.prototype,{a:{configurable:!0,enumerable:!0,get:function(){return"x-scope"}}});var re=new ee;var se={},te=window.customElements;if(te&&!Q){var ue=te.define;te.define=function(a,b,c){var e=document.createComment(" Shady DOM styles for "+a+" "),d=document.head;d.insertBefore(e,(U?U.nextSibling:null)||d.firstChild);U=e;se[a]=e;ue.call(te,a,b,c)}};function ve(){this.cache={}}ve.prototype.store=function(a,b,c,e){var d=this.cache[a]||[];d.push({o:b,styleElement:c,l:e});100<d.length&&d.shift();this.cache[a]=d};ve.prototype.fetch=function(a,b,c){if(a=this.cache[a])for(var e=a.length-1;0<=e;e--){var d=a[e],f;a:{for(f=0;f<c.length;f++){var g=c[f];if(d.o[g]!==b[g]){f=!1;break a}}f=!0}if(f)return d}};function we(){}
function xe(a){for(var b=0;b<a.length;b++){var c=a[b];if(c.target!==document.documentElement&&c.target!==document.head)for(var e=0;e<c.addedNodes.length;e++){var d=c.addedNodes[e];if(d.nodeType===Node.ELEMENT_NODE){var f=d.getRootNode();var g=d;var h=[];g.classList?h=Array.from(g.classList):g instanceof window.SVGElement&&g.hasAttribute("class")&&(h=g.getAttribute("class").split(/\s+/));g=h;h=g.indexOf(W.a);if((g=-1<h?g[h+1]:"")&&f===d.ownerDocument)zd(d,g,!0);else if(f.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&
(f=f.host))if(f=V(f).is,g===f)for(d=window.ShadyDOM.nativeMethods.querySelectorAll.call(d,":not(."+W.a+")"),f=0;f<d.length;f++)Bd(d[f],g);else g&&zd(d,g,!0),zd(d,f)}}}}
if(!Q){var ye=new MutationObserver(xe),ze=function(a){ye.observe(a,{childList:!0,subtree:!0})};if(window.customElements&&!window.customElements.polyfillWrapFlushCallback)ze(document);else{var Ae=function(){ze(document.body)};window.HTMLImports?window.HTMLImports.whenReady(Ae):requestAnimationFrame(function(){if("loading"===document.readyState){var a=function(){Ae();document.removeEventListener("readystatechange",a)};document.addEventListener("readystatechange",a)}else Ae()})}we=function(){xe(ye.takeRecords())}}
var Be=we;var Ce={};var De=Promise.resolve();function Ee(a){if(a=Ce[a])a._applyShimCurrentVersion=a._applyShimCurrentVersion||0,a._applyShimValidatingVersion=a._applyShimValidatingVersion||0,a._applyShimNextVersion=(a._applyShimNextVersion||0)+1}function Fe(a){return a._applyShimCurrentVersion===a._applyShimNextVersion}function Ge(a){a._applyShimValidatingVersion=a._applyShimNextVersion;a.b||(a.b=!0,De.then(function(){a._applyShimCurrentVersion=a._applyShimNextVersion;a.b=!1}))};var He=new ve;function Y(){this.V={};this.c=document.documentElement;var a=new Tc;a.rules=[];this.u=be(this.c,new ae(a));this.C=!1;this.b=this.a=null}m=Y.prototype;m.Y=function(){Be()};m.ra=function(a){return sd(a)};m.ya=function(a){return S(a)};m.prepareTemplate=function(a,b,c){this.prepareTemplateDom(a,b);this.prepareTemplateStyles(a,b,c)};
m.prepareTemplateStyles=function(a,b,c){if(!a.C){a.C=!0;a.name=b;a.extends=c;Ce[b]=a;var e=(e=a.content.querySelector("style"))?e.getAttribute("css-build")||"":"";var d=[];for(var f=a.content.querySelectorAll("style"),g=0;g<f.length;g++){var h=f[g];if(h.hasAttribute("shady-unscoped")){if(!Q){var k=h.textContent;rd.has(k)||(rd.add(k),k=h.cloneNode(!0),document.head.appendChild(k));h.parentNode.removeChild(h)}}else d.push(h.textContent),h.parentNode.removeChild(h)}d=d.join("").trim();c={is:b,extends:c,
Ca:e};Ie(this);f=md.test(d)||ld.test(d);md.lastIndex=0;ld.lastIndex=0;d=Uc(d);f&&R&&this.a&&this.a.transformRules(d,b);a._styleAst=d;a.V=e;e=[];R||(e=fe(a._styleAst));if(!e.length||R)d=Q?a.content:null,b=se[b],f=Dd(c,a._styleAst),b=f.length?ud(f,c.is,d,b):void 0,a.a=b;a.u=e}};m.prepareTemplateDom=function(a,b){Q||a.c||(a.c=!0,zd(a.content,b))};
function Je(a){!a.b&&window.ShadyCSS&&window.ShadyCSS.CustomStyleInterface&&(a.b=window.ShadyCSS.CustomStyleInterface,a.b.transformCallback=function(b){a.ea(b)},a.b.validateCallback=function(){requestAnimationFrame(function(){(a.b.enqueued||a.C)&&a.flushCustomStyles()})})}function Ie(a){!a.a&&window.ShadyCSS&&window.ShadyCSS.ApplyShim&&(a.a=window.ShadyCSS.ApplyShim,a.a.invalidCallback=Ee);Je(a)}
m.flushCustomStyles=function(){Ie(this);if(this.b){var a=this.b.processStyles();if(this.b.enqueued){if(R)for(var b=0;b<a.length;b++){var c=this.b.getStyleForCustomStyle(a[b]);if(c&&R&&this.a){var e=sd(c);Ie(this);this.a.transformRules(e);c.textContent=S(e)}}else for(Ke(this,this.c,this.u),b=0;b<a.length;b++)(c=this.b.getStyleForCustomStyle(a[b]))&&qe(c,this.u.w);this.b.enqueued=!1;this.C&&!R&&this.styleDocument()}}};
m.styleElement=function(a,b){var c=V(a).is,e=X(a);if(!e){var d=V(a);e=d.is;d=d.G;var f=se[e];e=Ce[e];if(e){var g=e._styleAst;var h=e.u}e=be(a,new ae(g,f,h,d))}a!==this.c&&(this.C=!0);b&&(e.B=e.B||{},Object.assign(e.B,b));if(R){if(e.B){b=e.B;for(var k in b)null===k?a.style.removeProperty(k):a.style.setProperty(k,b[k])}if(((k=Ce[c])||a===this.c)&&k&&k.a&&!Fe(k)){if(Fe(k)||k._applyShimValidatingVersion!==k._applyShimNextVersion)Ie(this),this.a&&this.a.transformRules(k._styleAst,c),k.a.textContent=Dd(a,
e.s),Ge(k);Q&&(c=a.shadowRoot)&&(c.querySelector("style").textContent=Dd(a,e.s));e.s=k._styleAst}}else if(this.Y(),Ke(this,a,e),e.X&&e.X.length){c=e;k=V(a).is;e=(b=He.fetch(k,c.w,c.X))?b.styleElement:null;g=c.l;(h=b&&b.l)||(h=this.V[k]=(this.V[k]||0)+1,h=k+"-"+h);c.l=h;h=c.l;d=re;d=e?e.textContent||"":ne(d,a,c.w,h);f=X(a);var l=f.a;l&&!Q&&l!==e&&(l._useCount--,0>=l._useCount&&l.parentNode&&l.parentNode.removeChild(l));Q?f.a?(f.a.textContent=d,e=f.a):d&&(e=ud(d,h,a.shadowRoot,f.b)):e?e.parentNode||
(de&&-1<d.indexOf("@media")&&(e.textContent=d),vd(e,null,f.b)):d&&(e=ud(d,h,null,f.b));e&&(e._useCount=e._useCount||0,f.a!=e&&e._useCount++,f.a=e);h=e;Q||(e=c.l,f=d=a.getAttribute("class")||"",g&&(f=d.replace(new RegExp("\\s*x-scope\\s*"+g+"\\s*","g")," ")),f+=(f?" ":"")+"x-scope "+e,d!==f&&xd(a,f));b||He.store(k,c.w,h,c.l)}};function Le(a,b){return(b=b.getRootNode().host)?X(b)?b:Le(a,b):a.c}
function Ke(a,b,c){a=Le(a,b);var e=X(a);a=Object.create(e.w||null);var d=me(b,c.s);b=ke(e.s,b).o;Object.assign(a,d.ta,b,d.va);b=c.B;for(var f in b)if((d=b[f])||0===d)a[f]=d;f=re;b=Object.getOwnPropertyNames(a);for(d=0;d<b.length;d++)e=b[d],a[e]=ie(f,a[e],a);c.w=a}m.styleDocument=function(a){this.styleSubtree(this.c,a)};
m.styleSubtree=function(a,b){var c=a.shadowRoot;(c||a===this.c)&&this.styleElement(a,b);if(b=c&&(c.children||c.childNodes))for(a=0;a<b.length;a++)this.styleSubtree(b[a]);else if(a=a.children||a.childNodes)for(b=0;b<a.length;b++)this.styleSubtree(a[b])};m.ea=function(a){var b=this,c=sd(a);T(c,function(a){if(Q)Yd(a);else{var c=W;a.selector=a.parsedSelector;Yd(a);a.selector=a.i=Hd(c,a,c.c,void 0,void 0)}R&&(Ie(b),b.a&&b.a.transformRule(a))});R?a.textContent=S(c):this.u.s.rules.push(c)};
m.getComputedStyleValue=function(a,b){var c;R||(c=(X(a)||X(Le(this,a))).w[b]);return(c=c||window.getComputedStyle(a).getPropertyValue(b))?c.trim():""};m.xa=function(a,b){var c=a.getRootNode();b=b?b.split(/\s/):[];c=c.host&&c.host.localName;if(!c){var e=a.getAttribute("class");if(e){e=e.split(/\s/);for(var d=0;d<e.length;d++)if(e[d]===W.a){c=e[d+1];break}}}c&&b.push(W.a,c);R||(c=X(a))&&c.l&&b.push(re.a,c.l);xd(a,b.join(" "))};m.pa=function(a){return X(a)};Y.prototype.flush=Y.prototype.Y;
Y.prototype.prepareTemplate=Y.prototype.prepareTemplate;Y.prototype.styleElement=Y.prototype.styleElement;Y.prototype.styleDocument=Y.prototype.styleDocument;Y.prototype.styleSubtree=Y.prototype.styleSubtree;Y.prototype.getComputedStyleValue=Y.prototype.getComputedStyleValue;Y.prototype.setElementClass=Y.prototype.xa;Y.prototype._styleInfoForNode=Y.prototype.pa;Y.prototype.transformCustomStyleForDocument=Y.prototype.ea;Y.prototype.getStyleAst=Y.prototype.ra;Y.prototype.styleAstToString=Y.prototype.ya;
Y.prototype.flushCustomStyles=Y.prototype.flushCustomStyles;Object.defineProperties(Y.prototype,{nativeShadow:{get:function(){return Q}},nativeCss:{get:function(){return R}}});var Z=new Y,Me,Ne;window.ShadyCSS&&(Me=window.ShadyCSS.ApplyShim,Ne=window.ShadyCSS.CustomStyleInterface);
window.ShadyCSS={ScopingShim:Z,prepareTemplate:function(a,b,c){Z.flushCustomStyles();Z.prepareTemplate(a,b,c)},prepareTemplateDom:function(a,b){Z.prepareTemplateDom(a,b)},prepareTemplateStyles:function(a,b,c){Z.flushCustomStyles();Z.prepareTemplateStyles(a,b,c)},styleSubtree:function(a,b){Z.flushCustomStyles();Z.styleSubtree(a,b)},styleElement:function(a){Z.flushCustomStyles();Z.styleElement(a)},styleDocument:function(a){Z.flushCustomStyles();Z.styleDocument(a)},flushCustomStyles:function(){Z.flushCustomStyles()},
getComputedStyleValue:function(a,b){return Z.getComputedStyleValue(a,b)},nativeCss:R,nativeShadow:Q};Me&&(window.ShadyCSS.ApplyShim=Me);Ne&&(window.ShadyCSS.CustomStyleInterface=Ne);var Oe=window.document;window.WebComponents=window.WebComponents||{};function Pe(){window.WebComponents.ready=!0;window.document.dispatchEvent(new CustomEvent("WebComponentsReady",{bubbles:!0}))}function Qe(){Pe();Oe.removeEventListener("readystatechange",Qe)}"loading"!==Oe.readyState?Pe():Oe.addEventListener("readystatechange",Qe);}).call(this);

//# sourceMappingURL=webcomponents-sd.js.map
